
CREATE INDEX ix_dienst_dienstbundel ON autaut.dienst USING btree (dienstbundel);              -- "autaut"."dienst"."ix_dienst_dienstbundel";
CREATE INDEX ix_dienstbundel_levsautorisatie ON autaut.dienstbundel USING btree (levsautorisatie);              -- "autaut"."dienstbundel"."ix_dienstbundel_levsautorisatie";
CREATE INDEX uc_his_dienst_dienst_tsreg ON autaut.his_dienst USING btree (dienst, tsreg);              -- "autaut"."his_dienst"."uc_his_dienst_dienst_tsreg";
CREATE INDEX uc_his_dienstattendering_dienst_tsreg ON autaut.his_dienstattendering USING btree (dienst, tsreg);              -- "autaut"."his_dienstattendering"."uc_his_dienstattendering_dienst_tsreg";
CREATE INDEX uc_his_dienstbundel_dienstbundel_tsreg ON autaut.his_dienstbundel USING btree (dienstbundel, tsreg);              -- "autaut"."his_dienstbundel"."uc_his_dienstbundel_dienstbundel_tsreg";
CREATE INDEX uc_his_dienstbundelgroep_dienstbundelgroep_tsreg ON autaut.his_dienstbundelgroep USING btree (dienstbundelgroep, tsreg);              -- "autaut"."his_dienstbundelgroep"."uc_his_dienstbundelgroep_dienstbundelgroep_tsreg";
CREATE INDEX uc_his_dienstbundelgroepattr_dienstbundelgroepattr_tsreg ON autaut.his_dienstbundelgroepattr USING btree (dienstbundelgroepattr, tsreg);              -- "autaut"."his_dienstbundelgroepattr"."uc_his_dienstbundelgroepattr_dienstbundelgroepattr_tsreg";
CREATE INDEX uc_his_dienstbundello3rubriek_dienstbundello3rubriek_tsreg ON autaut.his_dienstbundello3rubriek USING btree (dienstbundello3rubriek, tsreg);              -- "autaut"."his_dienstbundello3rubriek"."uc_his_dienstbundello3rubriek_dienstbundello3rubriek_tsreg";
CREATE INDEX uc_his_dienstselectie_dienst_tsreg ON autaut.his_dienstselectie USING btree (dienst, tsreg);              -- "autaut"."his_dienstselectie"."uc_his_dienstselectie_dienst_tsreg";
CREATE INDEX uc_his_levsautorisatie_levsautorisatie_tsreg ON autaut.his_levsautorisatie USING btree (levsautorisatie, tsreg);              -- "autaut"."his_levsautorisatie"."uc_his_levsautorisatie_levsautorisatie_tsreg";
CREATE INDEX ix_his_partijfiatuitz_partijbijhvoorstel ON autaut.his_partijfiatuitz USING btree (partijbijhvoorstel);              -- "autaut"."his_partijfiatuitz"."ix_his_partijfiatuitz_partijbijhvoorstel";
CREATE INDEX uc_his_partijfiatuitz_partijfiatuitz_tsreg ON autaut.his_partijfiatuitz USING btree (partijfiatuitz, tsreg);              -- "autaut"."his_partijfiatuitz"."uc_his_partijfiatuitz_partijfiatuitz_tsreg";
CREATE INDEX ix_his_persafnemerindicatie_tsreg_tsverval ON autaut.his_persafnemerindicatie USING btree (tsreg, tsverval);              -- "autaut"."his_persafnemerindicatie"."ix_his_persafnemerindicatie_tsreg_tsverval";
CREATE INDEX uc_his_toegangbijhautorisatie_toegangbijhautorisatie_tsreg ON autaut.his_toegangbijhautorisatie USING btree (toegangbijhautorisatie, tsreg);              -- "autaut"."his_toegangbijhautorisatie"."uc_his_toegangbijhautorisatie_toegangbijhautorisatie_tsreg";
CREATE INDEX uc_his_toeganglevsautorisatie_toeganglevsautorisatie_tsreg ON autaut.his_toeganglevsautorisatie USING btree (toeganglevsautorisatie, tsreg);              -- "autaut"."his_toeganglevsautorisatie"."uc_his_toeganglevsautorisatie_toeganglevsautorisatie_tsreg";
CREATE INDEX ix_partijfiatuitz_partij ON autaut.partijfiatuitz USING btree (partij);              -- "autaut"."partijfiatuitz"."ix_partijfiatuitz_partij";
CREATE INDEX ix_partijfiatuitz_partijbijhvoorstel ON autaut.partijfiatuitz USING btree (partijbijhvoorstel);              -- "autaut"."partijfiatuitz"."ix_partijfiatuitz_partijbijhvoorstel";
CREATE INDEX ix_persafnemerindicatie_afnemer ON autaut.persafnemerindicatie USING btree (afnemer);              -- "autaut"."persafnemerindicatie"."ix_persafnemerindicatie_afnemer";
CREATE INDEX ix_persafnemerindicatie_levsautorisatie ON autaut.persafnemerindicatie USING btree (levsautorisatie);              -- "autaut"."persafnemerindicatie"."ix_persafnemerindicatie_levsautorisatie";
CREATE INDEX ix_toegangbijhautorisatie_geautoriseerde ON autaut.toegangbijhautorisatie USING btree (geautoriseerde);              -- "autaut"."toegangbijhautorisatie"."ix_toegangbijhautorisatie_geautoriseerde";
CREATE INDEX ix_toegangbijhautorisatie_ondertekenaar ON autaut.toegangbijhautorisatie USING btree (ondertekenaar);              -- "autaut"."toegangbijhautorisatie"."ix_toegangbijhautorisatie_ondertekenaar";
CREATE INDEX ix_toegangbijhautorisatie_transporteur ON autaut.toegangbijhautorisatie USING btree (transporteur);              -- "autaut"."toegangbijhautorisatie"."ix_toegangbijhautorisatie_transporteur";
CREATE INDEX ix_toeganglevsautorisatie_geautoriseerde ON autaut.toeganglevsautorisatie USING btree (geautoriseerde);              -- "autaut"."toeganglevsautorisatie"."ix_toeganglevsautorisatie_geautoriseerde";
CREATE INDEX ix_toeganglevsautorisatie_levsautorisatie ON autaut.toeganglevsautorisatie USING btree (levsautorisatie);              -- "autaut"."toeganglevsautorisatie"."ix_toeganglevsautorisatie_levsautorisatie";
CREATE INDEX ix_toeganglevsautorisatie_ondertekenaar ON autaut.toeganglevsautorisatie USING btree (ondertekenaar);              -- "autaut"."toeganglevsautorisatie"."ix_toeganglevsautorisatie_ondertekenaar";
CREATE INDEX ix_toeganglevsautorisatie_transporteur ON autaut.toeganglevsautorisatie USING btree (transporteur);              -- "autaut"."toeganglevsautorisatie"."ix_toeganglevsautorisatie_transporteur";
CREATE INDEX ix_ber_admhnd ON ber.ber USING btree (admhnd);              -- "ber"."ber"."ix_ber_admhnd";
CREATE INDEX ix_ber_antwoordop ON ber.ber USING btree (antwoordop);              -- "ber"."ber"."ix_ber_antwoordop";
CREATE INDEX ix_ber_dienst ON ber.ber USING btree (dienst);              -- "ber"."ber"."ix_ber_dienst";
CREATE INDEX ix_ber_levsautorisatie ON ber.ber USING btree (levsautorisatie);              -- "ber"."ber"."ix_ber_levsautorisatie";
CREATE INDEX ix_ber_ontvangendepartij ON ber.ber USING btree (ontvangendepartij);              -- "ber"."ber"."ix_ber_ontvangendepartij";
CREATE INDEX ix_ber_referentienr ON ber.ber USING btree (referentienr);              -- "ber"."ber"."ix_ber_referentienr";
CREATE INDEX ix_ber_referentienru ON ber.ber USING btree (upper((referentienr)::text));              -- "ber"."ber"."ix_ber_referentienru";
CREATE INDEX ix_ber_tsontv ON ber.ber USING btree (tsontv);              -- "ber"."ber"."ix_ber_tsontv";
CREATE INDEX ix_ber_tsverzending ON ber.ber USING btree (tsverzending);              -- "ber"."ber"."ix_ber_tsverzending";
CREATE INDEX ix_ber_zendendepartij ON ber.ber USING btree (zendendepartij);              -- "ber"."ber"."ix_ber_zendendepartij";
CREATE INDEX ix_berpers_ber ON ber.berpers USING btree (ber);              -- "ber"."berpers"."ix_berpers_ber";
CREATE INDEX ix_berpers_pers ON ber.berpers USING btree (pers);              -- "ber"."berpers"."ix_berpers_pers";
CREATE INDEX uc_his_regelsituatie_regelsituatie_tsreg ON brm.his_regelsituatie USING btree (regelsituatie, tsreg);              -- "brm"."his_regelsituatie"."uc_his_regelsituatie_regelsituatie_tsreg";
CREATE INDEX ix_stapelrelatie_relatie ON ist.stapelrelatie USING btree (relatie);              -- "ist"."stapelrelatie"."ix_stapelrelatie_relatie";
CREATE INDEX ix_stapelvoorkomen_admhnd ON ist.stapelvoorkomen USING btree (admhnd);              -- "ist"."stapelvoorkomen"."ix_stapelvoorkomen_admhnd";
CREATE INDEX ix_stapelvoorkomen_partij ON ist.stapelvoorkomen USING btree (partij);              -- "ist"."stapelvoorkomen"."ix_stapelvoorkomen_partij";
CREATE INDEX ix_actie_admhnd ON kern.actie USING btree (admhnd);              -- "kern"."actie"."ix_actie_admhnd";
CREATE INDEX ix_actiebron_doc ON kern.actiebron USING btree (doc);              -- "kern"."actiebron"."ix_actiebron_doc";
CREATE INDEX ix_admhnd_tslev ON kern.admhnd USING btree (tslev);              -- "kern"."admhnd"."ix_admhnd_tslev";
CREATE INDEX ix_admhnd_tsreg ON kern.admhnd USING btree (tsreg);              -- "kern"."admhnd"."ix_admhnd_tsreg";
CREATE INDEX ix_admhndgedeblokkeerdemelding_admhnd ON kern.admhndgedeblokkeerdemelding USING btree (admhnd);              -- "kern"."admhndgedeblokkeerdemelding"."ix_admhndgedeblokkeerdemelding_admhnd";
CREATE INDEX ix_admhndgedeblokkeerdemelding_gedeblokkeerdemelding ON kern.admhndgedeblokkeerdemelding USING btree (gedeblokkeerdemelding);              -- "kern"."admhndgedeblokkeerdemelding"."ix_admhndgedeblokkeerdemelding_gedeblokkeerdemelding";
CREATE INDEX ix_betr_pers ON kern.betr USING btree (pers);              -- "kern"."betr"."ix_betr_pers";
CREATE INDEX ix_betr_relatie ON kern.betr USING btree (relatie);              -- "kern"."betr"."ix_betr_relatie";
CREATE INDEX ix_gegeveninonderzoek_onderzoek ON kern.gegeveninonderzoek USING btree (onderzoek);              -- "kern"."gegeveninonderzoek"."ix_gegeveninonderzoek_onderzoek";
CREATE INDEX ix_gegeveninterugmelding_terugmelding ON kern.gegeveninterugmelding USING btree (terugmelding);              -- "kern"."gegeveninterugmelding"."ix_gegeveninterugmelding_terugmelding";
CREATE INDEX uc_his_doc_doc_tsreg ON kern.his_doc USING btree (doc, tsreg);              -- "kern"."his_doc"."uc_his_doc_doc_tsreg";
CREATE INDEX uc_his_onderzoek_onderzoek_tsreg ON kern.his_onderzoek USING btree (onderzoek, tsreg);              -- "kern"."his_onderzoek"."uc_his_onderzoek_onderzoek_tsreg";
CREATE INDEX ix_his_onderzoekafgeleidadminis_admhnd ON kern.his_onderzoekafgeleidadminis USING btree (admhnd);              -- "kern"."his_onderzoekafgeleidadminis"."ix_his_onderzoekafgeleidadminis_admhnd";
CREATE INDEX uc_his_onderzoekafgeleidadminis_onderzoek_tsreg ON kern.his_onderzoekafgeleidadminis USING btree (onderzoek, tsreg);              -- "kern"."his_onderzoekafgeleidadminis"."uc_his_onderzoekafgeleidadminis_onderzoek_tsreg";
CREATE INDEX uc_his_ouderouderlijkgezag_betr_tsreg_dataanvgel ON kern.his_ouderouderlijkgezag USING btree (betr, tsreg, dataanvgel);              -- "kern"."his_ouderouderlijkgezag"."uc_his_ouderouderlijkgezag_betr_tsreg_dataanvgel";
CREATE INDEX uc_his_ouderouderschap_betr_tsreg_dataanvgel ON kern.his_ouderouderschap USING btree (betr, tsreg, dataanvgel);              -- "kern"."his_ouderouderschap"."uc_his_ouderouderschap_betr_tsreg_dataanvgel";
CREATE INDEX uc_his_partij_partij_tsreg ON kern.his_partij USING btree (partij, tsreg);              -- "kern"."his_partij"."uc_his_partij_partij_tsreg";
CREATE INDEX uc_his_partijbijhouding_partij_tsreg ON kern.his_partijbijhouding USING btree (partij, tsreg);              -- "kern"."his_partijbijhouding"."uc_his_partijbijhouding_partij_tsreg";
CREATE INDEX uc_his_partijonderzoek_partijonderzoek_tsreg ON kern.his_partijonderzoek USING btree (partijonderzoek, tsreg);              -- "kern"."his_partijonderzoek"."uc_his_partijonderzoek_partijonderzoek_tsreg";
CREATE INDEX uc_his_partijrol_partijrol_tsreg ON kern.his_partijrol USING btree (partijrol, tsreg);              -- "kern"."his_partijrol"."uc_his_partijrol_partijrol_tsreg";
CREATE INDEX uc_his_persadres_persadres_tsreg_dataanvgel ON kern.his_persadres USING btree (persadres, tsreg, dataanvgel);              -- "kern"."his_persadres"."uc_his_persadres_persadres_tsreg_dataanvgel";
CREATE INDEX ix_his_persafgeleidadministrati_admhnd ON kern.his_persafgeleidadministrati USING btree (admhnd);              -- "kern"."his_persafgeleidadministrati"."ix_his_persafgeleidadministrati_admhnd";
CREATE INDEX uc_his_persafgeleidadministrati_pers_tsreg ON kern.his_persafgeleidadministrati USING btree (pers, tsreg);              -- "kern"."his_persafgeleidadministrati"."uc_his_persafgeleidadministrati_pers_tsreg";
CREATE INDEX uc_his_persbijhouding_pers_tsreg_dataanvgel ON kern.his_persbijhouding USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_persbijhouding"."uc_his_persbijhouding_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_persdeelneuverkiezingen_pers_tsreg ON kern.his_persdeelneuverkiezingen USING btree (pers, tsreg);              -- "kern"."his_persdeelneuverkiezingen"."uc_his_persdeelneuverkiezingen_pers_tsreg";
CREATE INDEX uc_his_persgeboorte_pers_tsreg ON kern.his_persgeboorte USING btree (pers, tsreg);              -- "kern"."his_persgeboorte"."uc_his_persgeboorte_pers_tsreg";
CREATE INDEX uc_his_persgeslachtsaand_pers_tsreg_dataanvgel ON kern.his_persgeslachtsaand USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_persgeslachtsaand"."uc_his_persgeslachtsaand_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_persgeslnaamcomp_persgeslnaamcomp_tsreg_dataanvgel ON kern.his_persgeslnaamcomp USING btree (persgeslnaamcomp, tsreg, dataanvgel);              -- "kern"."his_persgeslnaamcomp"."uc_his_persgeslnaamcomp_persgeslnaamcomp_tsreg_dataanvgel";
CREATE INDEX ix_his_persids_anr ON kern.his_persids USING btree (anr);              -- "kern"."his_persids"."ix_his_persids_anr";
CREATE INDEX ix_his_persids_bsn ON kern.his_persids USING btree (bsn);              -- "kern"."his_persids"."ix_his_persids_bsn";
CREATE INDEX uc_his_persids_pers_tsreg_dataanvgel ON kern.his_persids USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_persids"."uc_his_persids_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_persindicatie_persindicatie_tsreg_dataanvgel ON kern.his_persindicatie USING btree (persindicatie, tsreg, dataanvgel);              -- "kern"."his_persindicatie"."uc_his_persindicatie_persindicatie_tsreg_dataanvgel";
CREATE INDEX uc_his_persinschr_pers_tsreg ON kern.his_persinschr USING btree (pers, tsreg);              -- "kern"."his_persinschr"."uc_his_persinschr_pers_tsreg";
CREATE INDEX uc_his_persmigratie_pers_tsreg_dataanvgel ON kern.his_persmigratie USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_persmigratie"."uc_his_persmigratie_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_persnaamgebruik_pers_tsreg ON kern.his_persnaamgebruik USING btree (pers, tsreg);              -- "kern"."his_persnaamgebruik"."uc_his_persnaamgebruik_pers_tsreg";
CREATE INDEX uc_his_persnation_persnation_tsreg_dataanvgel ON kern.his_persnation USING btree (persnation, tsreg, dataanvgel);              -- "kern"."his_persnation"."uc_his_persnation_persnation_tsreg_dataanvgel";
CREATE INDEX uc_his_persnrverwijzing_pers_tsreg_dataanvgel ON kern.his_persnrverwijzing USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_persnrverwijzing"."uc_his_persnrverwijzing_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_personderzoek_personderzoek_tsreg ON kern.his_personderzoek USING btree (personderzoek, tsreg);              -- "kern"."his_personderzoek"."uc_his_personderzoek_personderzoek_tsreg";
CREATE INDEX uc_his_persoverlijden_pers_tsreg ON kern.his_persoverlijden USING btree (pers, tsreg);              -- "kern"."his_persoverlijden"."uc_his_persoverlijden_pers_tsreg";
CREATE INDEX uc_his_perspk_pers_tsreg ON kern.his_perspk USING btree (pers, tsreg);              -- "kern"."his_perspk"."uc_his_perspk_pers_tsreg";
CREATE INDEX uc_his_persreisdoc_persreisdoc_tsreg ON kern.his_persreisdoc USING btree (persreisdoc, tsreg);              -- "kern"."his_persreisdoc"."uc_his_persreisdoc_persreisdoc_tsreg";
CREATE INDEX ix_his_perssamengesteldenaam_geslnaamstamu ON kern.his_perssamengesteldenaam USING btree (upper((geslnaamstam)::text));              -- "kern"."his_perssamengesteldenaam"."ix_his_perssamengesteldenaam_geslnaamstamu";
CREATE INDEX uc_his_perssamengesteldenaam_pers_tsreg_dataanvgel ON kern.his_perssamengesteldenaam USING btree (pers, tsreg, dataanvgel);              -- "kern"."his_perssamengesteldenaam"."uc_his_perssamengesteldenaam_pers_tsreg_dataanvgel";
CREATE INDEX uc_his_persuitslkiesr_pers_tsreg ON kern.his_persuitslkiesr USING btree (pers, tsreg);              -- "kern"."his_persuitslkiesr"."uc_his_persuitslkiesr_pers_tsreg";
CREATE INDEX uc_his_persverblijfsr_pers_tsreg ON kern.his_persverblijfsr USING btree (pers, tsreg);              -- "kern"."his_persverblijfsr"."uc_his_persverblijfsr_pers_tsreg";
CREATE INDEX uc_his_persverificatie_persverificatie_tsreg ON kern.his_persverificatie USING btree (persverificatie, tsreg);              -- "kern"."his_persverificatie"."uc_his_persverificatie_persverificatie_tsreg";
CREATE INDEX uc_his_persverstrbeperking_persverstrbeperking_tsreg ON kern.his_persverstrbeperking USING btree (persverstrbeperking, tsreg);              -- "kern"."his_persverstrbeperking"."uc_his_persverstrbeperking_persverstrbeperking_tsreg";
CREATE INDEX uc_his_persvoornaam_persvoornaam_tsreg_dataanvgel ON kern.his_persvoornaam USING btree (persvoornaam, tsreg, dataanvgel);              -- "kern"."his_persvoornaam"."uc_his_persvoornaam_persvoornaam_tsreg_dataanvgel";
CREATE INDEX uc_his_relatie_relatie_tsreg ON kern.his_relatie USING btree (relatie, tsreg);              -- "kern"."his_relatie"."uc_his_relatie_relatie_tsreg";
CREATE INDEX ix_his_terugmelding_onderzoek ON kern.his_terugmelding USING btree (onderzoek);              -- "kern"."his_terugmelding"."ix_his_terugmelding_onderzoek";
CREATE INDEX uc_his_terugmelding_terugmelding_tsreg ON kern.his_terugmelding USING btree (terugmelding, tsreg);              -- "kern"."his_terugmelding"."uc_his_terugmelding_terugmelding_tsreg";
CREATE INDEX uc_his_terugmeldingcontactpers_terugmelding_tsreg ON kern.his_terugmeldingcontactpers USING btree (terugmelding, tsreg);              -- "kern"."his_terugmeldingcontactpers"."uc_his_terugmeldingcontactpers_terugmelding_tsreg";
CREATE INDEX ix_onderzoek_admhnd ON kern.onderzoek USING btree (admhnd);              -- "kern"."onderzoek"."ix_onderzoek_admhnd";
CREATE INDEX ix_partij_oin ON kern.partij USING btree (oin);              -- "kern"."partij"."ix_partij_oin";
CREATE INDEX ix_pers_admhnd ON kern.pers USING btree (admhnd);              -- "kern"."pers"."ix_pers_admhnd";
CREATE INDEX ix_pers_anr ON kern.pers USING btree (anr);              -- "kern"."pers"."ix_pers_anr";
CREATE INDEX ix_pers_bsn ON kern.pers USING btree (bsn);              -- "kern"."pers"."ix_pers_bsn";
CREATE INDEX ix_pers_geslnaamstamu ON kern.pers USING btree (upper((geslnaamstam)::text));              -- "kern"."pers"."ix_pers_geslnaamstamu";
CREATE INDEX ix_persadres_gem_nor_huisnr_huisletter_huisnrtoevoeging_srtu ON kern.persadres USING btree (gem, upper((nor)::text), huisnr, upper((huisletter)::text), upper((huisnrtoevoeging)::text), srt);              -- "kern"."persadres"."ix_persadres_gem_nor_huisnr_huisletter_huisnrtoevoeging_srtu";
CREATE INDEX ix_persadres_identcodenraand ON kern.persadres USING btree (identcodenraand);              -- "kern"."persadres"."ix_persadres_identcodenraand";
CREATE INDEX ix_persadres_pers ON kern.persadres USING btree (pers);              -- "kern"."persadres"."ix_persadres_pers";
CREATE INDEX ix_persadres_postcode_huisnr_huisletter_huisnrtoevoeging_srtu ON kern.persadres USING btree (upper((postcode)::text), huisnr, upper((huisletter)::text), upper((huisnrtoevoeging)::text), srt);              -- "kern"."persadres"."ix_persadres_postcode_huisnr_huisletter_huisnrtoevoeging_srtu";
CREATE INDEX ix_perscache_pers ON kern.perscache USING btree (pers);              -- "kern"."perscache"."ix_perscache_pers";
CREATE INDEX ix_personderzoek_pers ON kern.personderzoek USING btree (pers);              -- "kern"."personderzoek"."ix_personderzoek_pers";
CREATE INDEX ix_persreisdoc_pers ON kern.persreisdoc USING btree (pers);              -- "kern"."persreisdoc"."ix_persreisdoc_pers";
CREATE INDEX ix_persverificatie_geverifieerde ON kern.persverificatie USING btree (geverifieerde);              -- "kern"."persverificatie"."ix_persverificatie_geverifieerde";
CREATE INDEX ix_regelverantwoording_actie ON kern.regelverantwoording USING btree (actie);              -- "kern"."regelverantwoording"."ix_regelverantwoording_actie";
CREATE INDEX ix_terugmelding_onderzoek ON kern.terugmelding USING btree (onderzoek);              -- "kern"."terugmelding"."ix_terugmelding_onderzoek";
CREATE INDEX ix_terugmelding_pers ON kern.terugmelding USING btree (pers);              -- "kern"."terugmelding"."ix_terugmelding_pers";
CREATE INDEX ix_levsaantek_admhnd ON prot.levsaantek USING btree (admhnd);              -- "prot"."levsaantek"."ix_levsaantek_admhnd";
CREATE INDEX ix_levsaantek_dienst ON prot.levsaantek USING btree (dienst);              -- "prot"."levsaantek"."ix_levsaantek_dienst";
CREATE INDEX ix_levsaantek_toeganglevsautorisatie ON prot.levsaantek USING btree (toeganglevsautorisatie);              -- "prot"."levsaantek"."ix_levsaantek_toeganglevsautorisatie";
CREATE INDEX ix_levsaantekpers_pers ON prot.levsaantekpers USING btree (pers);              -- "prot"."levsaantekpers"."ix_levsaantekpers_pers";
CREATE INDEX ix_lo3ber_anr ON verconv.lo3ber USING btree (anr);              -- "verconv"."lo3ber"."ix_lo3ber_anr";
CREATE INDEX ix_lo3ber_pers ON verconv.lo3ber USING btree (pers);              -- "verconv"."lo3ber"."ix_lo3ber_pers";


