Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (1,0, $$Onbekend$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (2,9, $$Art. 9 van de Vreemdelingenwet$$,0,19941001);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (3,10, $$Art. 10 van de Vreemdelingenwet$$,0,19941001);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (4,11, $$Vergunning art. 9 Vw, zonder beperking, dan wel gerechtigd krachtens art. 10 Vw$$,19670101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (5,12, $$Vergunning art. 9 Vw, met beperking, die elke vorm arbeid in loondienst toestaat$$,19670101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (6,13, $$Vergunning art. 9 Vw, met beperking, die arbeid in loondienst niet toestaat$$,19670101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (7,14, $$Voorwaardelijke vergunning art. 9a Vw$$,19940101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (8,15, $$Benelux of EG richtl nrs 68/360/EEG, 73/148/EEG 75/34/EEG, verord nr 1251/70/EEG$$,19520723,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (9,16, $$EG-richtlijnen nrs. 90/364/EEG, 90/365/EEG en 90/366/EEG$$,19520723,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (10,17, $$Verzoek tot toelating als vluchteling, uitzetting blijft achterwege$$,19540421,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (11,18, $$Gemeld bij VD, geen verzoek toelating als vluchteling, geen uitzetting$$,19460101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (12,19, $$Vergunning art. 9 Vw, met andere beperking dan hierboven$$,19670101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (13,20, $$Ander verdrag dan hierboven$$,19460101,20010401);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (14,21, $$Vw 2000 art. 8, onder a, vergunning regulier bepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (15,22, $$Vw 2000 art. 8, onder a, vergunning regulier bepaalde tijd, arbeid mits TWV$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (16,23, $$Vw 2000 art. 8, onder a, vergunning regulier bepaalde tijd, arbeid specifiek$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (17,24, $$Vw 2000 art. 8, onder a, vergunning regulier bepaalde tijd, geen arbeid$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (18,25, $$Vw 2000 art. 8, onder b, vergunning regulier onbepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (19,26, $$Vw 2000 art. 8, onder c, vergunning asiel bepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (20,27, $$Vw 2000 art. 8, onder d, vergunning asiel onbepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (21,28, $$Vw 2000 art. 8, onder e, gemeenschapsonderdaan econ. actief, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (22,29, $$Vw 2000 art. 8, onder e, gemeenschapsonderdaan econ. niet-actief, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (23,30, $$Vw 2000 art. 8, onder e, toetsing aan het gemeenschapsrecht, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (24,31, $$Vw 2000 art. 8, onder f en h, in procedure voor vergunning art. 14 Vw 2000$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (25,32, $$Vw 2000 art. 8, onder f en h, in procedure voor vergunning art. 28 Vw 2000$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (26,33, $$Vw 2000 art. 8, onder g en h, in procedure voortgezet verblijf, tijdige aanvr.$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (27,34, $$Vw 2000 art. 8, onder g en h, in procedure voortgezet verblijf, ontijdige aanvr.$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (28,35, $$Vw 2000 art. 8, onder l, Associatiebesluit 1/80 EEG/Turkije, arbeid specifiek$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (29,36, $$Vw 2000 art. 8, onder e, gemeenschapsonderdaan econ. actief, arbeid specifiek$$,20040501,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (30,37, $$Vw 2000 art. 8, onder e, gemeenschapsonderdaan econ. niet-actief, arbeid spec.$$,20040501,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (31,38, $$Vw 2000 art. 8, onder e, toetsing aan het gemeenschapsrecht, arbeid specifiek$$,20040501,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (32,39, $$Vw 2000 art. 8, onder m, in afwachting indiening asielaanvraag, geen arbeid$$,20100701,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (33,40, $$Vw 2000 art. 8, onder e, gemeenschapsonderdaan duurzaam verblijf, arbeid vrij$$,20100701,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (34,41, $$Rechtmatig verblijf Vw 2000 art. 8, onder e, is beëindigd$$,20100701,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (35,42, $$Rechtmatig verblijf op grond van voorlopige maatregel EHRM, geen arbeid$$,20100701,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (36,43, $$Rechtmatig verblijf op aanwijzing Minister van Justitie, geen arbeid$$,20100701,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (37,91, $$Vw 2000 art. 115, lid 4, vergunning onbepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (38,92, $$Vw 2000 art. 115, lid 6, vergunning asiel bepaalde tijd, arbeid vrij$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (39,93, $$Vw 2000 art. 115, lid 2, verg. regulier bepaalde tijd, arbeid nader te bepalen$$,0,null);
Insert into Kern.verblijfstitel (id, code, oms, dataanvgel, dateindegel) values (40,98, $$geen verblijfstitel (meer)$$,0,null);
