/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hismultirealiteitregel generated by hbm2java
 */
@Entity
@Table(name = "hismultirealiteitregel", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = {
        "multirealiteitregel", "dataanvgel", "dattijdreg" }))
public class Hismultirealiteitregel implements java.io.Serializable {

    private long                   id;
    private Srtmultirealiteitregel srtmultirealiteitregel;
    private Brpactie               brpactieByBrpactiebegin;
    private Pers                   persByPers;
    private Betr                   betr;
    private Pers                   persByMultirealiteitpers;
    private Multirealiteitregel    multirealiteitregel;
    private Relatie                relatie;
    private Pers                   persByGeldigvoor;
    private Brpactie               brpactieByBrpactiebeingeld;
    private Brpactie               brpactieByBrpactieeinde;
    private Integer                dataanvgel;
    private Integer                dateindegel;
    private Date                   dattijdreg;
    private Date                   dattijdverval;

    public Hismultirealiteitregel() {
    }

    public Hismultirealiteitregel(long id, Srtmultirealiteitregel srtmultirealiteitregel, Pers persByGeldigvoor) {
        this.id = id;
        this.srtmultirealiteitregel = srtmultirealiteitregel;
        this.persByGeldigvoor = persByGeldigvoor;
    }

    public Hismultirealiteitregel(long id, Srtmultirealiteitregel srtmultirealiteitregel,
            Brpactie brpactieByBrpactiebegin, Pers persByPers, Betr betr, Pers persByMultirealiteitpers,
            Multirealiteitregel multirealiteitregel, Relatie relatie, Pers persByGeldigvoor,
            Brpactie brpactieByBrpactiebeingeld, Brpactie brpactieByBrpactieeinde, Integer dataanvgel,
            Integer dateindegel, Date dattijdreg, Date dattijdverval)
    {
        this.id = id;
        this.srtmultirealiteitregel = srtmultirealiteitregel;
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
        this.persByPers = persByPers;
        this.betr = betr;
        this.persByMultirealiteitpers = persByMultirealiteitpers;
        this.multirealiteitregel = multirealiteitregel;
        this.relatie = relatie;
        this.persByGeldigvoor = persByGeldigvoor;
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "srt", nullable = false)
    public Srtmultirealiteitregel getSrtmultirealiteitregel() {
        return this.srtmultirealiteitregel;
    }

    public void setSrtmultirealiteitregel(Srtmultirealiteitregel srtmultirealiteitregel) {
        this.srtmultirealiteitregel = srtmultirealiteitregel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebegin")
    public Brpactie getBrpactieByBrpactiebegin() {
        return this.brpactieByBrpactiebegin;
    }

    public void setBrpactieByBrpactiebegin(Brpactie brpactieByBrpactiebegin) {
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pers")
    public Pers getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(Pers persByPers) {
        this.persByPers = persByPers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "betr")
    public Betr getBetr() {
        return this.betr;
    }

    public void setBetr(Betr betr) {
        this.betr = betr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "multirealiteitpers")
    public Pers getPersByMultirealiteitpers() {
        return this.persByMultirealiteitpers;
    }

    public void setPersByMultirealiteitpers(Pers persByMultirealiteitpers) {
        this.persByMultirealiteitpers = persByMultirealiteitpers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "multirealiteitregel")
    public Multirealiteitregel getMultirealiteitregel() {
        return this.multirealiteitregel;
    }

    public void setMultirealiteitregel(Multirealiteitregel multirealiteitregel) {
        this.multirealiteitregel = multirealiteitregel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "relatie")
    public Relatie getRelatie() {
        return this.relatie;
    }

    public void setRelatie(Relatie relatie) {
        this.relatie = relatie;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geldigvoor", nullable = false)
    public Pers getPersByGeldigvoor() {
        return this.persByGeldigvoor;
    }

    public void setPersByGeldigvoor(Pers persByGeldigvoor) {
        this.persByGeldigvoor = persByGeldigvoor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebeingeld")
    public Brpactie getBrpactieByBrpactiebeingeld() {
        return this.brpactieByBrpactiebeingeld;
    }

    public void setBrpactieByBrpactiebeingeld(Brpactie brpactieByBrpactiebeingeld) {
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactieeinde")
    public Brpactie getBrpactieByBrpactieeinde() {
        return this.brpactieByBrpactieeinde;
    }

    public void setBrpactieByBrpactieeinde(Brpactie brpactieByBrpactieeinde) {
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

}
