/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;


/**
 * Pers generated by hbm2java
 */
@Entity
@Table(name = "pers", schema = "kern")
public class Pers implements java.io.Serializable {

    private long                              id;
    private Predikaat                         predikaatByPredikaataanschr;
    private Gem                               gemByGempk;
    private Land                              landByLandvanwaaringeschreven;
    private Plaats                            plaatsByWplgeboorte;
    private Pers                              persByVolgendepers;
    private Verblijfsr                        verblijfsr;
    private Predikaat                         predikaatByPredikaat;
    private Plaats                            plaatsByWploverlijden;
    private Pers                              persByVorigepers;
    private Gem                               gemByGemgeboorte;
    private Verantwoordelijke                 verantwoordelijke;
    private Gem                               gemByBijhgem;
    private Geslachtsaand                     geslachtsaand;
    private Srtpers                           srtpers;
    private Land                              landByLandoverlijden;
    private Wijzegebruikgeslnaam              wijzegebruikgeslnaam;
    private Land                              landByLandgeboorte;
    private Gem                               gemByGemoverlijden;
    private Rdnopschorting                    rdnopschorting;
    private Adellijketitel                    adellijketitel;
    private Integer                           bsn;
    private Long                              anr;
    private String                            voornamen;
    private String                            voorvoegsel;
    private String                            scheidingsteken;
    private String                            geslnaam;
    private String                            indnreeksalsgeslnaam;
    private String                            indafgeleid;
    private String                            indaanschrmetadellijketitel;
    private String                            indaanschrafgeleid;
    private String                            voornamenaanschr;
    private String                            voorvoegselaanschr;
    private String                            scheidingstekenaanschr;
    private String                            geslnaamaanschr;
    private int                               datgeboorte;
    private String                            blgeboorteplaats;
    private String                            blregiogeboorte;
    private String                            omsgeboorteloc;
    private int                               datoverlijden;
    private String                            blplaatsoverlijden;
    private String                            blregiooverlijden;
    private String                            omslocoverlijden;
    private int                               dataanvverblijfsr;
    private Integer                           datvoorzeindeverblijfsr;
    private Integer                           dataanvaaneenslverblijfsr;
    private String                            induitslnlkiesr;
    private Integer                           dateindeuitslnlkiesr;
    private String                            inddeelneuverkiezingen;
    private Integer                           dataanlaanpdeelneuverkiezi;
    private Integer                           dateindeuitsleukiesr;
    private int                               datinschringem;
    private String                            indonverwdocaanw;
    private String                            indpkvollediggeconv;
    private int                               datvestiginginnederland;
    private int                               datinschr;
    private long                              versienr;
    private Date                              tijdstiplaatstewijz;
    private String                            indgegevensinonderzoek;
    private Integer                           dataanvgel;
    private Date                              dattijdreg;
    private Set<Persgeslnaamcomp>             persgeslnaamcomps                            = new HashSet<Persgeslnaamcomp>(0);
    private Set<Multirealiteitregel>          multirealiteitregelsForMultirealiteitpers    = new HashSet<Multirealiteitregel>(0);
    private Set<Hispersoverlijden>            hispersoverlijdens                           = new HashSet<Hispersoverlijden>(0);
    private Set<Persvoornaam>                 persvoornaams                                = new HashSet<Persvoornaam>(0);
    private Set<Hispersverblijfsr>            hispersverblijfsrs                           = new HashSet<Hispersverblijfsr>(0);
    private Set<Multirealiteitregel>          multirealiteitregelsForPers                  = new HashSet<Multirealiteitregel>(0);
    private Set<Hispersids>                   hispersidses                                 = new HashSet<Hispersids>(0);
    private Set<Pers>                         persesForVorigepers                          = new HashSet<Pers>(0);
    private Set<Pers>                         persesForVolgendepers                        = new HashSet<Pers>(0);
    private Set<Hisperssamengesteldenaam>     hisperssamengesteldenaams                    = new HashSet<Hisperssamengesteldenaam>(0);
    private Set<Hispersimmigratie>            hispersimmigraties                           = new HashSet<Hispersimmigratie>(0);
    private Set<Hispersaanschr>               hispersaanschrs                              = new HashSet<Hispersaanschr>(0);
    private Set<Hispersuitslnlkiesr>          hispersuitslnlkiesrs                         = new HashSet<Hispersuitslnlkiesr>(0);
    private Set<Hispersinschr>                hispersinschrsForVorigepers                  = new HashSet<Hispersinschr>(0);
    private Set<Hismultirealiteitregel>       hismultirealiteitregelsForGeldigvoor         = new HashSet<Hismultirealiteitregel>(0);
    private Set<Hispersinschr>                hispersinschrsForVolgendepers                = new HashSet<Hispersinschr>(0);
    private Set<Hismultirealiteitregel>       hismultirealiteitregelsForPers               = new HashSet<Hismultirealiteitregel>(0);
    private Set<Persreisdoc>                  persreisdocs                                 = new HashSet<Persreisdoc>(0);
    private Set<Hismultirealiteitregel>       hismultirealiteitregelsForMultirealiteitpers = new HashSet<Hismultirealiteitregel>(0);
    private Set<Hispersgeboorte>              hispersgeboortes                             = new HashSet<Hispersgeboorte>(0);
    private Set<Hispersopschorting>           hispersopschortings                          = new HashSet<Hispersopschorting>(0);
    private Set<Persindicatie>                persindicaties                               = new HashSet<Persindicatie>(0);
    private Set<Hisperseuverkiezingen>        hisperseuverkiezingens                       = new HashSet<Hisperseuverkiezingen>(0);
    private Set<Persnation>                   persnations                                  = new HashSet<Persnation>(0);
    private Set<Hispersbijhgem>               hispersbijhgems                              = new HashSet<Hispersbijhgem>(0);
    private Set<Hispersinschr>                hispersinschrsForPers                        = new HashSet<Hispersinschr>(0);
    private Set<Betr>                         betrs                                        = new HashSet<Betr>(0);
    private Set<Hispersgeslachtsaand>         hispersgeslachtsaands                        = new HashSet<Hispersgeslachtsaand>(0);
    private Set<Persverificatie>              persverificaties                             = new HashSet<Persverificatie>(0);
    private Set<Hispersbijhverantwoordelijkh> hispersbijhverantwoordelijkhs                = new HashSet<Hispersbijhverantwoordelijkh>(0);
    private Set<Persadres>                    persadreses                                  = new HashSet<Persadres>(0);
    private Set<Multirealiteitregel>          multirealiteitregelsForGeldigvoor            = new HashSet<Multirealiteitregel>(0);
    private Set<Hisperspk>                    hisperspks                                   = new HashSet<Hisperspk>(0);

    public Pers() {
    }

    public Pers(long id, Verblijfsr verblijfsr, Verantwoordelijke verantwoordelijke, Gem gemByBijhgem,
            Geslachtsaand geslachtsaand, Srtpers srtpers, Land landByLandoverlijden, Land landByLandgeboorte,
            Rdnopschorting rdnopschorting, String geslnaam, String indafgeleid, String indaanschrafgeleid,
            String geslnaamaanschr, int datgeboorte, int datoverlijden, int dataanvverblijfsr, int datinschringem,
            int datvestiginginnederland, int datinschr, long versienr, Date tijdstiplaatstewijz,
            String indgegevensinonderzoek)
    {
        this.id = id;
        this.verblijfsr = verblijfsr;
        this.verantwoordelijke = verantwoordelijke;
        this.gemByBijhgem = gemByBijhgem;
        this.geslachtsaand = geslachtsaand;
        this.srtpers = srtpers;
        this.landByLandoverlijden = landByLandoverlijden;
        this.landByLandgeboorte = landByLandgeboorte;
        this.rdnopschorting = rdnopschorting;
        this.geslnaam = geslnaam;
        this.indafgeleid = indafgeleid;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.geslnaamaanschr = geslnaamaanschr;
        this.datgeboorte = datgeboorte;
        this.datoverlijden = datoverlijden;
        this.dataanvverblijfsr = dataanvverblijfsr;
        this.datinschringem = datinschringem;
        this.datvestiginginnederland = datvestiginginnederland;
        this.datinschr = datinschr;
        this.versienr = versienr;
        this.tijdstiplaatstewijz = tijdstiplaatstewijz;
        this.indgegevensinonderzoek = indgegevensinonderzoek;
    }

    public Pers(long id, Predikaat predikaatByPredikaataanschr, Gem gemByGempk, Land landByLandvanwaaringeschreven,
            Plaats plaatsByWplgeboorte, Pers persByVolgendepers, Verblijfsr verblijfsr, Predikaat predikaatByPredikaat,
            Plaats plaatsByWploverlijden, Pers persByVorigepers, Gem gemByGemgeboorte,
            Verantwoordelijke verantwoordelijke, Gem gemByBijhgem, Geslachtsaand geslachtsaand, Srtpers srtpers,
            Land landByLandoverlijden, Wijzegebruikgeslnaam wijzegebruikgeslnaam, Land landByLandgeboorte,
            Gem gemByGemoverlijden, Rdnopschorting rdnopschorting, Adellijketitel adellijketitel, Integer bsn,
            Long anr, String voornamen, String voorvoegsel, String scheidingsteken, String geslnaam,
            String indnreeksalsgeslnaam, String indafgeleid, String indaanschrmetadellijketitel,
            String indaanschrafgeleid, String voornamenaanschr, String voorvoegselaanschr,
            String scheidingstekenaanschr, String geslnaamaanschr, int datgeboorte, String blgeboorteplaats,
            String blregiogeboorte, String omsgeboorteloc, int datoverlijden, String blplaatsoverlijden,
            String blregiooverlijden, String omslocoverlijden, int dataanvverblijfsr, Integer datvoorzeindeverblijfsr,
            Integer dataanvaaneenslverblijfsr, String induitslnlkiesr, Integer dateindeuitslnlkiesr,
            String inddeelneuverkiezingen, Integer dataanlaanpdeelneuverkiezi, Integer dateindeuitsleukiesr,
            int datinschringem, String indonverwdocaanw, String indpkvollediggeconv, int datvestiginginnederland,
            int datinschr, long versienr, Date tijdstiplaatstewijz, String indgegevensinonderzoek, Integer dataanvgel,
            Date dattijdreg, Set<Persgeslnaamcomp> persgeslnaamcomps,
            Set<Multirealiteitregel> multirealiteitregelsForMultirealiteitpers,
            Set<Hispersoverlijden> hispersoverlijdens, Set<Persvoornaam> persvoornaams,
            Set<Hispersverblijfsr> hispersverblijfsrs, Set<Multirealiteitregel> multirealiteitregelsForPers,
            Set<Hispersids> hispersidses, Set<Pers> persesForVorigepers, Set<Pers> persesForVolgendepers,
            Set<Hisperssamengesteldenaam> hisperssamengesteldenaams, Set<Hispersimmigratie> hispersimmigraties,
            Set<Hispersaanschr> hispersaanschrs, Set<Hispersuitslnlkiesr> hispersuitslnlkiesrs,
            Set<Hispersinschr> hispersinschrsForVorigepers,
            Set<Hismultirealiteitregel> hismultirealiteitregelsForGeldigvoor,
            Set<Hispersinschr> hispersinschrsForVolgendepers,
            Set<Hismultirealiteitregel> hismultirealiteitregelsForPers, Set<Persreisdoc> persreisdocs,
            Set<Hismultirealiteitregel> hismultirealiteitregelsForMultirealiteitpers,
            Set<Hispersgeboorte> hispersgeboortes, Set<Hispersopschorting> hispersopschortings,
            Set<Persindicatie> persindicaties, Set<Hisperseuverkiezingen> hisperseuverkiezingens,
            Set<Persnation> persnations, Set<Hispersbijhgem> hispersbijhgems, Set<Hispersinschr> hispersinschrsForPers,
            Set<Betr> betrs, Set<Hispersgeslachtsaand> hispersgeslachtsaands, Set<Persverificatie> persverificaties,
            Set<Hispersbijhverantwoordelijkh> hispersbijhverantwoordelijkhs, Set<Persadres> persadreses,
            Set<Multirealiteitregel> multirealiteitregelsForGeldigvoor, Set<Hisperspk> hisperspks)
    {
        this.id = id;
        this.predikaatByPredikaataanschr = predikaatByPredikaataanschr;
        this.gemByGempk = gemByGempk;
        this.landByLandvanwaaringeschreven = landByLandvanwaaringeschreven;
        this.plaatsByWplgeboorte = plaatsByWplgeboorte;
        this.persByVolgendepers = persByVolgendepers;
        this.verblijfsr = verblijfsr;
        this.predikaatByPredikaat = predikaatByPredikaat;
        this.plaatsByWploverlijden = plaatsByWploverlijden;
        this.persByVorigepers = persByVorigepers;
        this.gemByGemgeboorte = gemByGemgeboorte;
        this.verantwoordelijke = verantwoordelijke;
        this.gemByBijhgem = gemByBijhgem;
        this.geslachtsaand = geslachtsaand;
        this.srtpers = srtpers;
        this.landByLandoverlijden = landByLandoverlijden;
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
        this.landByLandgeboorte = landByLandgeboorte;
        this.gemByGemoverlijden = gemByGemoverlijden;
        this.rdnopschorting = rdnopschorting;
        this.adellijketitel = adellijketitel;
        this.bsn = bsn;
        this.anr = anr;
        this.voornamen = voornamen;
        this.voorvoegsel = voorvoegsel;
        this.scheidingsteken = scheidingsteken;
        this.geslnaam = geslnaam;
        this.indnreeksalsgeslnaam = indnreeksalsgeslnaam;
        this.indafgeleid = indafgeleid;
        this.indaanschrmetadellijketitel = indaanschrmetadellijketitel;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.voornamenaanschr = voornamenaanschr;
        this.voorvoegselaanschr = voorvoegselaanschr;
        this.scheidingstekenaanschr = scheidingstekenaanschr;
        this.geslnaamaanschr = geslnaamaanschr;
        this.datgeboorte = datgeboorte;
        this.blgeboorteplaats = blgeboorteplaats;
        this.blregiogeboorte = blregiogeboorte;
        this.omsgeboorteloc = omsgeboorteloc;
        this.datoverlijden = datoverlijden;
        this.blplaatsoverlijden = blplaatsoverlijden;
        this.blregiooverlijden = blregiooverlijden;
        this.omslocoverlijden = omslocoverlijden;
        this.dataanvverblijfsr = dataanvverblijfsr;
        this.datvoorzeindeverblijfsr = datvoorzeindeverblijfsr;
        this.dataanvaaneenslverblijfsr = dataanvaaneenslverblijfsr;
        this.induitslnlkiesr = induitslnlkiesr;
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
        this.inddeelneuverkiezingen = inddeelneuverkiezingen;
        this.dataanlaanpdeelneuverkiezi = dataanlaanpdeelneuverkiezi;
        this.dateindeuitsleukiesr = dateindeuitsleukiesr;
        this.datinschringem = datinschringem;
        this.indonverwdocaanw = indonverwdocaanw;
        this.indpkvollediggeconv = indpkvollediggeconv;
        this.datvestiginginnederland = datvestiginginnederland;
        this.datinschr = datinschr;
        this.versienr = versienr;
        this.tijdstiplaatstewijz = tijdstiplaatstewijz;
        this.indgegevensinonderzoek = indgegevensinonderzoek;
        this.dataanvgel = dataanvgel;
        this.dattijdreg = dattijdreg;
        this.persgeslnaamcomps = persgeslnaamcomps;
        this.multirealiteitregelsForMultirealiteitpers = multirealiteitregelsForMultirealiteitpers;
        this.hispersoverlijdens = hispersoverlijdens;
        this.persvoornaams = persvoornaams;
        this.hispersverblijfsrs = hispersverblijfsrs;
        this.multirealiteitregelsForPers = multirealiteitregelsForPers;
        this.hispersidses = hispersidses;
        this.persesForVorigepers = persesForVorigepers;
        this.persesForVolgendepers = persesForVolgendepers;
        this.hisperssamengesteldenaams = hisperssamengesteldenaams;
        this.hispersimmigraties = hispersimmigraties;
        this.hispersaanschrs = hispersaanschrs;
        this.hispersuitslnlkiesrs = hispersuitslnlkiesrs;
        this.hispersinschrsForVorigepers = hispersinschrsForVorigepers;
        this.hismultirealiteitregelsForGeldigvoor = hismultirealiteitregelsForGeldigvoor;
        this.hispersinschrsForVolgendepers = hispersinschrsForVolgendepers;
        this.hismultirealiteitregelsForPers = hismultirealiteitregelsForPers;
        this.persreisdocs = persreisdocs;
        this.hismultirealiteitregelsForMultirealiteitpers = hismultirealiteitregelsForMultirealiteitpers;
        this.hispersgeboortes = hispersgeboortes;
        this.hispersopschortings = hispersopschortings;
        this.persindicaties = persindicaties;
        this.hisperseuverkiezingens = hisperseuverkiezingens;
        this.persnations = persnations;
        this.hispersbijhgems = hispersbijhgems;
        this.hispersinschrsForPers = hispersinschrsForPers;
        this.betrs = betrs;
        this.hispersgeslachtsaands = hispersgeslachtsaands;
        this.persverificaties = persverificaties;
        this.hispersbijhverantwoordelijkhs = hispersbijhverantwoordelijkhs;
        this.persadreses = persadreses;
        this.multirealiteitregelsForGeldigvoor = multirealiteitregelsForGeldigvoor;
        this.hisperspks = hisperspks;
    }
    
    @SequenceGenerator(name="Pers_Gen", sequenceName="kern.seq_pers")
    @Id @GeneratedValue(generator="Pers_Gen", strategy=GenerationType.SEQUENCE)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predikaataanschr")
    public Predikaat getPredikaatByPredikaataanschr() {
        return this.predikaatByPredikaataanschr;
    }

    public void setPredikaatByPredikaataanschr(Predikaat predikaatByPredikaataanschr) {
        this.predikaatByPredikaataanschr = predikaatByPredikaataanschr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gempk")
    public Gem getGemByGempk() {
        return this.gemByGempk;
    }

    public void setGemByGempk(Gem gemByGempk) {
        this.gemByGempk = gemByGempk;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "landvanwaaringeschreven")
    public Land getLandByLandvanwaaringeschreven() {
        return this.landByLandvanwaaringeschreven;
    }

    public void setLandByLandvanwaaringeschreven(Land landByLandvanwaaringeschreven) {
        this.landByLandvanwaaringeschreven = landByLandvanwaaringeschreven;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wplgeboorte")
    public Plaats getPlaatsByWplgeboorte() {
        return this.plaatsByWplgeboorte;
    }

    public void setPlaatsByWplgeboorte(Plaats plaatsByWplgeboorte) {
        this.plaatsByWplgeboorte = plaatsByWplgeboorte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "volgendepers")
    public Pers getPersByVolgendepers() {
        return this.persByVolgendepers;
    }

    public void setPersByVolgendepers(Pers persByVolgendepers) {
        this.persByVolgendepers = persByVolgendepers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "verblijfsr", nullable = false)
    public Verblijfsr getVerblijfsr() {
        return this.verblijfsr;
    }

    public void setVerblijfsr(Verblijfsr verblijfsr) {
        this.verblijfsr = verblijfsr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predikaat")
    public Predikaat getPredikaatByPredikaat() {
        return this.predikaatByPredikaat;
    }

    public void setPredikaatByPredikaat(Predikaat predikaatByPredikaat) {
        this.predikaatByPredikaat = predikaatByPredikaat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wploverlijden")
    public Plaats getPlaatsByWploverlijden() {
        return this.plaatsByWploverlijden;
    }

    public void setPlaatsByWploverlijden(Plaats plaatsByWploverlijden) {
        this.plaatsByWploverlijden = plaatsByWploverlijden;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vorigepers")
    public Pers getPersByVorigepers() {
        return this.persByVorigepers;
    }

    public void setPersByVorigepers(Pers persByVorigepers) {
        this.persByVorigepers = persByVorigepers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gemgeboorte")
    public Gem getGemByGemgeboorte() {
        return this.gemByGemgeboorte;
    }

    public void setGemByGemgeboorte(Gem gemByGemgeboorte) {
        this.gemByGemgeboorte = gemByGemgeboorte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "verantwoordelijke", nullable = false)
    public Verantwoordelijke getVerantwoordelijke() {
        return this.verantwoordelijke;
    }

    public void setVerantwoordelijke(Verantwoordelijke verantwoordelijke) {
        this.verantwoordelijke = verantwoordelijke;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bijhgem", nullable = false)
    public Gem getGemByBijhgem() {
        return this.gemByBijhgem;
    }

    public void setGemByBijhgem(Gem gemByBijhgem) {
        this.gemByBijhgem = gemByBijhgem;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geslachtsaand", nullable = false)
    public Geslachtsaand getGeslachtsaand() {
        return this.geslachtsaand;
    }

    public void setGeslachtsaand(Geslachtsaand geslachtsaand) {
        this.geslachtsaand = geslachtsaand;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "srt", nullable = false)
    public Srtpers getSrtpers() {
        return this.srtpers;
    }

    public void setSrtpers(Srtpers srtpers) {
        this.srtpers = srtpers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "landoverlijden", nullable = false)
    public Land getLandByLandoverlijden() {
        return this.landByLandoverlijden;
    }

    public void setLandByLandoverlijden(Land landByLandoverlijden) {
        this.landByLandoverlijden = landByLandoverlijden;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gebrgeslnaamegp")
    public Wijzegebruikgeslnaam getWijzegebruikgeslnaam() {
        return this.wijzegebruikgeslnaam;
    }

    public void setWijzegebruikgeslnaam(Wijzegebruikgeslnaam wijzegebruikgeslnaam) {
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "landgeboorte", nullable = false)
    public Land getLandByLandgeboorte() {
        return this.landByLandgeboorte;
    }

    public void setLandByLandgeboorte(Land landByLandgeboorte) {
        this.landByLandgeboorte = landByLandgeboorte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gemoverlijden")
    public Gem getGemByGemoverlijden() {
        return this.gemByGemoverlijden;
    }

    public void setGemByGemoverlijden(Gem gemByGemoverlijden) {
        this.gemByGemoverlijden = gemByGemoverlijden;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rdnopschortingbijhouding", nullable = false)
    public Rdnopschorting getRdnopschorting() {
        return this.rdnopschorting;
    }

    public void setRdnopschorting(Rdnopschorting rdnopschorting) {
        this.rdnopschorting = rdnopschorting;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "adellijketitel")
    public Adellijketitel getAdellijketitel() {
        return this.adellijketitel;
    }

    public void setAdellijketitel(Adellijketitel adellijketitel) {
        this.adellijketitel = adellijketitel;
    }

    @Column(name = "bsn", precision = 9, scale = 0)
    @Min(value=100000000, message="{pers.valid.bsn}")
    @Max(value=999999999, message="{pers.valid.bsn}")
    @NotNull(message="{pers.valid.bsn}")
    public Integer getBsn() {
        return this.bsn;
    }

    public void setBsn(Integer bsn) {
        this.bsn = bsn;
    }

    @Column(name = "anr", precision = 10, scale = 0)
    @Min(value=1000000000L, message="{pers.valid.anr}")
    @Max(value=9999999999L, message="{pers.valid.anr}")
    @NotNull(message="{pers.valid.anr}")
    public Long getAnr() {
        return this.anr;
    }

    public void setAnr(Long anr) {
        this.anr = anr;
    }

    @Column(name = "voornamen", length = 200)
    public String getVoornamen() {
        return this.voornamen;
    }

    public void setVoornamen(String voornamen) {
        this.voornamen = voornamen;
    }

    @Column(name = "voorvoegsel", length = 10)
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }

    public void setVoorvoegsel(String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }

    @Column(name = "scheidingsteken", length = 1)
    public String getScheidingsteken() {
        return this.scheidingsteken;
    }

    public void setScheidingsteken(String scheidingsteken) {
        this.scheidingsteken = scheidingsteken;
    }

    @Column(name = "geslnaam", nullable = false, length = 200)
    public String getGeslnaam() {
        return this.geslnaam;
    }

    public void setGeslnaam(String geslnaam) {
        this.geslnaam = geslnaam;
    }

    @Column(name = "indnreeksalsgeslnaam", length = 1)
    public String getIndnreeksalsgeslnaam() {
        return this.indnreeksalsgeslnaam;
    }

    public void setIndnreeksalsgeslnaam(String indnreeksalsgeslnaam) {
        this.indnreeksalsgeslnaam = indnreeksalsgeslnaam;
    }

    @Column(name = "indafgeleid", nullable = false, length = 1)
    public String getIndafgeleid() {
        return this.indafgeleid;
    }

    public void setIndafgeleid(String indafgeleid) {
        this.indafgeleid = indafgeleid;
    }

    @Column(name = "indaanschrmetadellijketitel", length = 1)
    public String getIndaanschrmetadellijketitel() {
        return this.indaanschrmetadellijketitel;
    }

    public void setIndaanschrmetadellijketitel(String indaanschrmetadellijketitel) {
        this.indaanschrmetadellijketitel = indaanschrmetadellijketitel;
    }

    @Column(name = "indaanschrafgeleid", nullable = false, length = 1)
    public String getIndaanschrafgeleid() {
        return this.indaanschrafgeleid;
    }

    public void setIndaanschrafgeleid(String indaanschrafgeleid) {
        this.indaanschrafgeleid = indaanschrafgeleid;
    }

    @Column(name = "voornamenaanschr", length = 200)
    public String getVoornamenaanschr() {
        return this.voornamenaanschr;
    }

    public void setVoornamenaanschr(String voornamenaanschr) {
        this.voornamenaanschr = voornamenaanschr;
    }

    @Column(name = "voorvoegselaanschr", length = 10)
    public String getVoorvoegselaanschr() {
        return this.voorvoegselaanschr;
    }

    public void setVoorvoegselaanschr(String voorvoegselaanschr) {
        this.voorvoegselaanschr = voorvoegselaanschr;
    }

    @Column(name = "scheidingstekenaanschr", length = 1)
    public String getScheidingstekenaanschr() {
        return this.scheidingstekenaanschr;
    }

    public void setScheidingstekenaanschr(String scheidingstekenaanschr) {
        this.scheidingstekenaanschr = scheidingstekenaanschr;
    }

    @Column(name = "geslnaamaanschr", nullable = false, length = 200)
    public String getGeslnaamaanschr() {
        return this.geslnaamaanschr;
    }

    public void setGeslnaamaanschr(String geslnaamaanschr) {
        this.geslnaamaanschr = geslnaamaanschr;
    }

    @Column(name = "datgeboorte", nullable = false, precision = 8, scale = 0)
    public int getDatgeboorte() {
        return this.datgeboorte;
    }

    public void setDatgeboorte(int datgeboorte) {
        this.datgeboorte = datgeboorte;
    }

    @Column(name = "blgeboorteplaats", length = 40)
    public String getBlgeboorteplaats() {
        return this.blgeboorteplaats;
    }

    public void setBlgeboorteplaats(String blgeboorteplaats) {
        this.blgeboorteplaats = blgeboorteplaats;
    }

    @Column(name = "blregiogeboorte", length = 35)
    public String getBlregiogeboorte() {
        return this.blregiogeboorte;
    }

    public void setBlregiogeboorte(String blregiogeboorte) {
        this.blregiogeboorte = blregiogeboorte;
    }

    @Column(name = "omsgeboorteloc", length = 40)
    public String getOmsgeboorteloc() {
        return this.omsgeboorteloc;
    }

    public void setOmsgeboorteloc(String omsgeboorteloc) {
        this.omsgeboorteloc = omsgeboorteloc;
    }

    @Column(name = "datoverlijden", nullable = false, precision = 8, scale = 0)
    public int getDatoverlijden() {
        return this.datoverlijden;
    }

    public void setDatoverlijden(int datoverlijden) {
        this.datoverlijden = datoverlijden;
    }

    @Column(name = "blplaatsoverlijden", length = 40)
    public String getBlplaatsoverlijden() {
        return this.blplaatsoverlijden;
    }

    public void setBlplaatsoverlijden(String blplaatsoverlijden) {
        this.blplaatsoverlijden = blplaatsoverlijden;
    }

    @Column(name = "blregiooverlijden", length = 35)
    public String getBlregiooverlijden() {
        return this.blregiooverlijden;
    }

    public void setBlregiooverlijden(String blregiooverlijden) {
        this.blregiooverlijden = blregiooverlijden;
    }

    @Column(name = "omslocoverlijden", length = 40)
    public String getOmslocoverlijden() {
        return this.omslocoverlijden;
    }

    public void setOmslocoverlijden(String omslocoverlijden) {
        this.omslocoverlijden = omslocoverlijden;
    }

    @Column(name = "dataanvverblijfsr", nullable = false, precision = 8, scale = 0)
    public int getDataanvverblijfsr() {
        return this.dataanvverblijfsr;
    }

    public void setDataanvverblijfsr(int dataanvverblijfsr) {
        this.dataanvverblijfsr = dataanvverblijfsr;
    }

    @Column(name = "datvoorzeindeverblijfsr", precision = 8, scale = 0)
    public Integer getDatvoorzeindeverblijfsr() {
        return this.datvoorzeindeverblijfsr;
    }

    public void setDatvoorzeindeverblijfsr(Integer datvoorzeindeverblijfsr) {
        this.datvoorzeindeverblijfsr = datvoorzeindeverblijfsr;
    }

    @Column(name = "dataanvaaneenslverblijfsr", precision = 8, scale = 0)
    public Integer getDataanvaaneenslverblijfsr() {
        return this.dataanvaaneenslverblijfsr;
    }

    public void setDataanvaaneenslverblijfsr(Integer dataanvaaneenslverblijfsr) {
        this.dataanvaaneenslverblijfsr = dataanvaaneenslverblijfsr;
    }

    @Column(name = "induitslnlkiesr", length = 1)
    public String getInduitslnlkiesr() {
        return this.induitslnlkiesr;
    }

    public void setInduitslnlkiesr(String induitslnlkiesr) {
        this.induitslnlkiesr = induitslnlkiesr;
    }

    @Column(name = "dateindeuitslnlkiesr", precision = 8, scale = 0)
    public Integer getDateindeuitslnlkiesr() {
        return this.dateindeuitslnlkiesr;
    }

    public void setDateindeuitslnlkiesr(Integer dateindeuitslnlkiesr) {
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
    }

    @Column(name = "inddeelneuverkiezingen", length = 1)
    public String getInddeelneuverkiezingen() {
        return this.inddeelneuverkiezingen;
    }

    public void setInddeelneuverkiezingen(String inddeelneuverkiezingen) {
        this.inddeelneuverkiezingen = inddeelneuverkiezingen;
    }

    @Column(name = "dataanlaanpdeelneuverkiezi", precision = 8, scale = 0)
    public Integer getDataanlaanpdeelneuverkiezi() {
        return this.dataanlaanpdeelneuverkiezi;
    }

    public void setDataanlaanpdeelneuverkiezi(Integer dataanlaanpdeelneuverkiezi) {
        this.dataanlaanpdeelneuverkiezi = dataanlaanpdeelneuverkiezi;
    }

    @Column(name = "dateindeuitsleukiesr", precision = 8, scale = 0)
    public Integer getDateindeuitsleukiesr() {
        return this.dateindeuitsleukiesr;
    }

    public void setDateindeuitsleukiesr(Integer dateindeuitsleukiesr) {
        this.dateindeuitsleukiesr = dateindeuitsleukiesr;
    }

    @Column(name = "datinschringem", nullable = false, precision = 8, scale = 0)
    public int getDatinschringem() {
        return this.datinschringem;
    }

    public void setDatinschringem(int datinschringem) {
        this.datinschringem = datinschringem;
    }

    @Column(name = "indonverwdocaanw", length = 1)
    public String getIndonverwdocaanw() {
        return this.indonverwdocaanw;
    }

    public void setIndonverwdocaanw(String indonverwdocaanw) {
        this.indonverwdocaanw = indonverwdocaanw;
    }

    @Column(name = "indpkvollediggeconv", length = 1)
    public String getIndpkvollediggeconv() {
        return this.indpkvollediggeconv;
    }

    public void setIndpkvollediggeconv(String indpkvollediggeconv) {
        this.indpkvollediggeconv = indpkvollediggeconv;
    }

    @Column(name = "datvestiginginnederland", nullable = false, precision = 8, scale = 0)
    public int getDatvestiginginnederland() {
        return this.datvestiginginnederland;
    }

    public void setDatvestiginginnederland(int datvestiginginnederland) {
        this.datvestiginginnederland = datvestiginginnederland;
    }

    @Column(name = "datinschr", nullable = false, precision = 8, scale = 0)
    public int getDatinschr() {
        return this.datinschr;
    }

    public void setDatinschr(int datinschr) {
        this.datinschr = datinschr;
    }

    @Column(name = "versienr", nullable = false)
    public long getVersienr() {
        return this.versienr;
    }

    public void setVersienr(long versienr) {
        this.versienr = versienr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tijdstiplaatstewijz", nullable = false, length = 29)
    public Date getTijdstiplaatstewijz() {
        return this.tijdstiplaatstewijz;
    }

    public void setTijdstiplaatstewijz(Date tijdstiplaatstewijz) {
        this.tijdstiplaatstewijz = tijdstiplaatstewijz;
    }

    @Column(name = "indgegevensinonderzoek", nullable = false, length = 1)
    public String getIndgegevensinonderzoek() {
        return this.indgegevensinonderzoek;
    }

    public void setIndgegevensinonderzoek(String indgegevensinonderzoek) {
        this.indgegevensinonderzoek = indgegevensinonderzoek;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persgeslnaamcomp> getPersgeslnaamcomps() {
        return this.persgeslnaamcomps;
    }

    public void setPersgeslnaamcomps(Set<Persgeslnaamcomp> persgeslnaamcomps) {
        this.persgeslnaamcomps = persgeslnaamcomps;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByMultirealiteitpers")
    public Set<Multirealiteitregel> getMultirealiteitregelsForMultirealiteitpers() {
        return this.multirealiteitregelsForMultirealiteitpers;
    }

    public void setMultirealiteitregelsForMultirealiteitpers(
            Set<Multirealiteitregel> multirealiteitregelsForMultirealiteitpers)
    {
        this.multirealiteitregelsForMultirealiteitpers = multirealiteitregelsForMultirealiteitpers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersoverlijden> getHispersoverlijdens() {
        return this.hispersoverlijdens;
    }

    public void setHispersoverlijdens(Set<Hispersoverlijden> hispersoverlijdens) {
        this.hispersoverlijdens = hispersoverlijdens;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persvoornaam> getPersvoornaams() {
        return this.persvoornaams;
    }

    public void setPersvoornaams(Set<Persvoornaam> persvoornaams) {
        this.persvoornaams = persvoornaams;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersverblijfsr> getHispersverblijfsrs() {
        return this.hispersverblijfsrs;
    }

    public void setHispersverblijfsrs(Set<Hispersverblijfsr> hispersverblijfsrs) {
        this.hispersverblijfsrs = hispersverblijfsrs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByPers")
    public Set<Multirealiteitregel> getMultirealiteitregelsForPers() {
        return this.multirealiteitregelsForPers;
    }

    public void setMultirealiteitregelsForPers(Set<Multirealiteitregel> multirealiteitregelsForPers) {
        this.multirealiteitregelsForPers = multirealiteitregelsForPers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersids> getHispersidses() {
        return this.hispersidses;
    }

    public void setHispersidses(Set<Hispersids> hispersidses) {
        this.hispersidses = hispersidses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByVorigepers")
    public Set<Pers> getPersesForVorigepers() {
        return this.persesForVorigepers;
    }

    public void setPersesForVorigepers(Set<Pers> persesForVorigepers) {
        this.persesForVorigepers = persesForVorigepers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByVolgendepers")
    public Set<Pers> getPersesForVolgendepers() {
        return this.persesForVolgendepers;
    }

    public void setPersesForVolgendepers(Set<Pers> persesForVolgendepers) {
        this.persesForVolgendepers = persesForVolgendepers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hisperssamengesteldenaam> getHisperssamengesteldenaams() {
        return this.hisperssamengesteldenaams;
    }

    public void setHisperssamengesteldenaams(Set<Hisperssamengesteldenaam> hisperssamengesteldenaams) {
        this.hisperssamengesteldenaams = hisperssamengesteldenaams;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersimmigratie> getHispersimmigraties() {
        return this.hispersimmigraties;
    }

    public void setHispersimmigraties(Set<Hispersimmigratie> hispersimmigraties) {
        this.hispersimmigraties = hispersimmigraties;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersaanschr> getHispersaanschrs() {
        return this.hispersaanschrs;
    }

    public void setHispersaanschrs(Set<Hispersaanschr> hispersaanschrs) {
        this.hispersaanschrs = hispersaanschrs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersuitslnlkiesr> getHispersuitslnlkiesrs() {
        return this.hispersuitslnlkiesrs;
    }

    public void setHispersuitslnlkiesrs(Set<Hispersuitslnlkiesr> hispersuitslnlkiesrs) {
        this.hispersuitslnlkiesrs = hispersuitslnlkiesrs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByVorigepers")
    public Set<Hispersinschr> getHispersinschrsForVorigepers() {
        return this.hispersinschrsForVorigepers;
    }

    public void setHispersinschrsForVorigepers(Set<Hispersinschr> hispersinschrsForVorigepers) {
        this.hispersinschrsForVorigepers = hispersinschrsForVorigepers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByGeldigvoor")
    public Set<Hismultirealiteitregel> getHismultirealiteitregelsForGeldigvoor() {
        return this.hismultirealiteitregelsForGeldigvoor;
    }

    public void
            setHismultirealiteitregelsForGeldigvoor(Set<Hismultirealiteitregel> hismultirealiteitregelsForGeldigvoor)
    {
        this.hismultirealiteitregelsForGeldigvoor = hismultirealiteitregelsForGeldigvoor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByVolgendepers")
    public Set<Hispersinschr> getHispersinschrsForVolgendepers() {
        return this.hispersinschrsForVolgendepers;
    }

    public void setHispersinschrsForVolgendepers(Set<Hispersinschr> hispersinschrsForVolgendepers) {
        this.hispersinschrsForVolgendepers = hispersinschrsForVolgendepers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByPers")
    public Set<Hismultirealiteitregel> getHismultirealiteitregelsForPers() {
        return this.hismultirealiteitregelsForPers;
    }

    public void setHismultirealiteitregelsForPers(Set<Hismultirealiteitregel> hismultirealiteitregelsForPers) {
        this.hismultirealiteitregelsForPers = hismultirealiteitregelsForPers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persreisdoc> getPersreisdocs() {
        return this.persreisdocs;
    }

    public void setPersreisdocs(Set<Persreisdoc> persreisdocs) {
        this.persreisdocs = persreisdocs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByMultirealiteitpers")
    public Set<Hismultirealiteitregel> getHismultirealiteitregelsForMultirealiteitpers() {
        return this.hismultirealiteitregelsForMultirealiteitpers;
    }

    public void setHismultirealiteitregelsForMultirealiteitpers(
            Set<Hismultirealiteitregel> hismultirealiteitregelsForMultirealiteitpers)
    {
        this.hismultirealiteitregelsForMultirealiteitpers = hismultirealiteitregelsForMultirealiteitpers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersgeboorte> getHispersgeboortes() {
        return this.hispersgeboortes;
    }

    public void setHispersgeboortes(Set<Hispersgeboorte> hispersgeboortes) {
        this.hispersgeboortes = hispersgeboortes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersopschorting> getHispersopschortings() {
        return this.hispersopschortings;
    }

    public void setHispersopschortings(Set<Hispersopschorting> hispersopschortings) {
        this.hispersopschortings = hispersopschortings;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persindicatie> getPersindicaties() {
        return this.persindicaties;
    }

    public void setPersindicaties(Set<Persindicatie> persindicaties) {
        this.persindicaties = persindicaties;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hisperseuverkiezingen> getHisperseuverkiezingens() {
        return this.hisperseuverkiezingens;
    }

    public void setHisperseuverkiezingens(Set<Hisperseuverkiezingen> hisperseuverkiezingens) {
        this.hisperseuverkiezingens = hisperseuverkiezingens;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persnation> getPersnations() {
        return this.persnations;
    }

    public void setPersnations(Set<Persnation> persnations) {
        this.persnations = persnations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersbijhgem> getHispersbijhgems() {
        return this.hispersbijhgems;
    }

    public void setHispersbijhgems(Set<Hispersbijhgem> hispersbijhgems) {
        this.hispersbijhgems = hispersbijhgems;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByPers")
    public Set<Hispersinschr> getHispersinschrsForPers() {
        return this.hispersinschrsForPers;
    }

    public void setHispersinschrsForPers(Set<Hispersinschr> hispersinschrsForPers) {
        this.hispersinschrsForPers = hispersinschrsForPers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Betr> getBetrs() {
        return this.betrs;
    }

    public void setBetrs(Set<Betr> betrs) {
        this.betrs = betrs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersgeslachtsaand> getHispersgeslachtsaands() {
        return this.hispersgeslachtsaands;
    }

    public void setHispersgeslachtsaands(Set<Hispersgeslachtsaand> hispersgeslachtsaands) {
        this.hispersgeslachtsaands = hispersgeslachtsaands;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Persverificatie> getPersverificaties() {
        return this.persverificaties;
    }

    public void setPersverificaties(Set<Persverificatie> persverificaties) {
        this.persverificaties = persverificaties;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hispersbijhverantwoordelijkh> getHispersbijhverantwoordelijkhs() {
        return this.hispersbijhverantwoordelijkhs;
    }

    public void setHispersbijhverantwoordelijkhs(Set<Hispersbijhverantwoordelijkh> hispersbijhverantwoordelijkhs) {
        this.hispersbijhverantwoordelijkhs = hispersbijhverantwoordelijkhs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers",  cascade = { CascadeType.ALL })
    public Set<Persadres> getPersadreses() {
        return this.persadreses;
    }

    public void setPersadreses(Set<Persadres> persadreses) {
        this.persadreses = persadreses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persByGeldigvoor")
    public Set<Multirealiteitregel> getMultirealiteitregelsForGeldigvoor() {
        return this.multirealiteitregelsForGeldigvoor;
    }

    public void setMultirealiteitregelsForGeldigvoor(Set<Multirealiteitregel> multirealiteitregelsForGeldigvoor) {
        this.multirealiteitregelsForGeldigvoor = multirealiteitregelsForGeldigvoor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pers")
    public Set<Hisperspk> getHisperspks() {
        return this.hisperspks;
    }

    public void setHisperspks(Set<Hisperspk> hisperspks) {
        this.hisperspks = hisperspks;
    }

}
