/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Rdnverknlnation generated by hbm2java
 */
@Entity
@Table(name = "rdnverknlnation", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = "naam"))
public class Rdnverknlnation implements java.io.Serializable {

    private int                id;
    private String             naam;
    private Integer            dataanvgel;
    private Integer            dateindegel;
    private Set<Persnation>    persnations    = new HashSet<Persnation>(0);
    private Set<Hispersnation> hispersnations = new HashSet<Hispersnation>(0);

    public Rdnverknlnation() {
    }

    public Rdnverknlnation(int id, String naam) {
        this.id = id;
        this.naam = naam;
    }

    public Rdnverknlnation(int id, String naam, Integer dataanvgel, Integer dateindegel, Set<Persnation> persnations,
            Set<Hispersnation> hispersnations)
    {
        this.id = id;
        this.naam = naam;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.persnations = persnations;
        this.hispersnations = hispersnations;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "naam", unique = true, nullable = false, length = 40)
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rdnverknlnation")
    public Set<Persnation> getPersnations() {
        return this.persnations;
    }

    public void setPersnations(Set<Persnation> persnations) {
        this.persnations = persnations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rdnverknlnation")
    public Set<Hispersnation> getHispersnations() {
        return this.hispersnations;
    }

    public void setHispersnations(Set<Hispersnation> hispersnations) {
        this.hispersnations = hispersnations;
    }

}
