--------------------------------------------------------------------------------
-- PostgreSQL SQL-DDL bestand voor Basisregistratie Personen (BRP)            --
-- PostgreSQL - Kern Rechten                                                  --
--------------------------------------------------------------------------------
-- 
-- Gegenereerd door BRP Meta Register Release 44.
-- Gegenereerd op: dinsdag 24 nov 2015 13:59:27
-- 
--------------------------------------------------------------------------------

-- Rollen aanmaken:
CREATE OR REPLACE FUNCTION CREATE_ROLE_IF_NOT_EXISTS(rolename TEXT) RETURNS VOID AS
$$
BEGIN
   IF NOT EXISTS (SELECT * FROM pg_roles WHERE lower(rolname) = lower(rolename)) THEN
      EXECUTE 'CREATE ROLE ' || rolename;
      RAISE NOTICE 'Role % created.', rolename;
   ELSE
      RAISE NOTICE 'Role % already exists.', rolename;
   END IF;
END;
$$ LANGUAGE plpgsql;
SELECT CREATE_ROLE_IF_NOT_EXISTS('BRP_Bijhouding');
SELECT CREATE_ROLE_IF_NOT_EXISTS('BRP_Lezen');
SELECT CREATE_ROLE_IF_NOT_EXISTS('BRP_ActiveMQ');
DROP FUNCTION CREATE_ROLE_IF_NOT_EXISTS(rolename TEXT);

-- Rechten toekennen
GRANT USAGE ON SCHEMA AutAut TO BRP_Lezen;
GRANT USAGE ON SCHEMA AutAut TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA BRM TO BRP_Lezen;
GRANT USAGE ON SCHEMA BRM TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA Conv TO BRP_Lezen;
GRANT USAGE ON SCHEMA Conv TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA IST TO BRP_Lezen;
GRANT USAGE ON SCHEMA IST TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA Kern TO BRP_Lezen;
GRANT USAGE ON SCHEMA Kern TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA MigBlok TO BRP_Lezen;
GRANT USAGE ON SCHEMA MigBlok TO BRP_Bijhouding;
GRANT USAGE ON SCHEMA VerConv TO BRP_Lezen;
GRANT USAGE ON SCHEMA VerConv TO BRP_Bijhouding;

GRANT SELECT ON AutAut.BijhautorisatieSrtAdmHnd TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.BijhautorisatieSrtAdmHnd TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_BijhautorisatieSrtAdmHnd TO BRP_Bijhouding;
GRANT SELECT ON AutAut.Dienst TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.Dienst TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_Dienst TO BRP_Bijhouding;
GRANT SELECT ON AutAut.Dienstbundel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.Dienstbundel TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_Dienstbundel TO BRP_Bijhouding;
GRANT SELECT ON AutAut.DienstbundelGroep TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.DienstbundelGroep TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_DienstbundelGroep TO BRP_Bijhouding;
GRANT SELECT ON AutAut.DienstbundelGroepAttr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.DienstbundelGroepAttr TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_DienstbundelGroepAttr TO BRP_Bijhouding;
GRANT SELECT ON AutAut.DienstbundelLO3Rubriek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.DienstbundelLO3Rubriek TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_DienstbundelLO3Rubriek TO BRP_Bijhouding;
GRANT SELECT ON AutAut.EffectAfnemerindicaties TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.EffectAfnemerindicaties TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_EffectAfnemerindicaties TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_Dienst TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_Dienst TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_Dienst TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_DienstAttendering TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_DienstAttendering TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_DienstAttendering TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_DienstSelectie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_DienstSelectie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_DienstSelectie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_Dienstbundel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_Dienstbundel TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_Dienstbundel TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_DienstbundelGroep TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_DienstbundelGroep TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_DienstbundelGroep TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_DienstbundelGroepAttr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_DienstbundelGroepAttr TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_DienstbundelGroepAttr TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_DienstbundelLO3Rubriek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_DienstbundelLO3Rubriek TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_DienstbundelLO3Rubriek TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_Levsautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_Levsautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_Levsautorisatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_PartijFiatuitz TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_PartijFiatuitz TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_PartijFiatuitz TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_PersAfnemerindicatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_ToegangBijhautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_ToegangBijhautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_ToegangBijhautorisatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_ToegangLevsautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.His_ToegangLevsautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_ToegangLevsautorisatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.Levsautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.Levsautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_Levsautorisatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.PartijFiatuitz TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.PartijFiatuitz TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_PartijFiatuitz TO BRP_Bijhouding;
GRANT SELECT ON AutAut.PersAfnemerindicatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.PersAfnemerindicatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.Protocolleringsniveau TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.Protocolleringsniveau TO BRP_Bijhouding;
GRANT SELECT ON AutAut.SrtDienst TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.SrtDienst TO BRP_Bijhouding;
GRANT SELECT ON AutAut.ToegangBijhautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.ToegangBijhautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_ToegangBijhautorisatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.ToegangLevsautorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON AutAut.ToegangLevsautorisatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_ToegangLevsautorisatie TO BRP_Bijhouding;
GRANT SELECT ON BRM.His_Regelsituatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON BRM.His_Regelsituatie TO BRP_Bijhouding;
GRANT USAGE ON BRM.seq_His_Regelsituatie TO BRP_Bijhouding;
GRANT SELECT ON BRM.RegelSrtBer TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON BRM.RegelSrtBer TO BRP_Bijhouding;
GRANT SELECT ON BRM.Regeleffect TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON BRM.Regeleffect TO BRP_Bijhouding;
GRANT SELECT ON BRM.Regelsituatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON BRM.Regelsituatie TO BRP_Bijhouding;
GRANT USAGE ON BRM.seq_Regelsituatie TO BRP_Bijhouding;
GRANT SELECT ON BRM.SrtRegel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON BRM.SrtRegel TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvAandInhingVermissingReis TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvAandInhingVermissingReis TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvAandInhingVermissingReis TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvAangifteAdresh TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvAangifteAdresh TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvAangifteAdresh TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvAdellijkeTitelPredikaat TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvAdellijkeTitelPredikaat TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvAdellijkeTitelPredikaat TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvLO3Rubriek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvLO3Rubriek TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvLO3Rubriek TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvRNIDeelnemer TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvRNIDeelnemer TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvRNIDeelnemer TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvRdnBeeindigenNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvRdnBeeindigenNation TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvRdnBeeindigenNation TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvRdnOntbindingHuwelijkGer TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvRdnOntbindingHuwelijkGer TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvRdnOntbindingHuwelijkGer TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvRdnOpnameNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvRdnOpnameNation TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvRdnOpnameNation TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvRdnOpschorting TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvRdnOpschorting TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvRdnOpschorting TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvSrtNLReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvSrtNLReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvSrtNLReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Conv.ConvVoorvoegsel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Conv.ConvVoorvoegsel TO BRP_Bijhouding;
GRANT USAGE ON Conv.seq_ConvVoorvoegsel TO BRP_Bijhouding;
GRANT SELECT ON IST.Autorisatietabel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON IST.Autorisatietabel TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_Autorisatietabel TO BRP_Bijhouding;
GRANT SELECT ON IST.Stapel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON IST.Stapel TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_Stapel TO BRP_Bijhouding;
GRANT SELECT ON IST.StapelRelatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON IST.StapelRelatie TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_StapelRelatie TO BRP_Bijhouding;
GRANT SELECT ON IST.StapelVoorkomen TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON IST.StapelVoorkomen TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_StapelVoorkomen TO BRP_Bijhouding;
GRANT SELECT ON Kern.AandInhingVermissingReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AandInhingVermissingReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AandInhingVermissingReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.AandVerblijfsr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AandVerblijfsr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AandVerblijfsr TO BRP_Bijhouding;
GRANT SELECT ON Kern.Aang TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Aang TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Aang TO BRP_Bijhouding;
GRANT SELECT ON Kern.Actie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Actie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Actie TO BRP_Bijhouding;
GRANT SELECT ON Kern.ActieBron TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.ActieBron TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_ActieBron TO BRP_Bijhouding;
GRANT SELECT ON Kern.AdellijkeTitel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AdellijkeTitel TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AdellijkeTitel TO BRP_Bijhouding;
GRANT SELECT ON Kern.AdmHnd TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AdmHnd TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AdmHnd TO BRP_Bijhouding;
GRANT SELECT ON Kern.AdmHndGedeblokkeerdeMelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AdmHndGedeblokkeerdeMelding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AdmHndGedeblokkeerdeMelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.AuttypeVanAfgifteReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.AuttypeVanAfgifteReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AuttypeVanAfgifteReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.Betr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Betr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Betr TO BRP_Bijhouding;
GRANT SELECT ON Kern.Bijhaard TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Bijhaard TO BRP_Bijhouding;
GRANT SELECT ON Kern.BurgerzakenModule TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.BurgerzakenModule TO BRP_Bijhouding;
GRANT SELECT ON Kern.CategorieAdmHnd TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.CategorieAdmHnd TO BRP_Bijhouding;
GRANT SELECT ON Kern.Doc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Doc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Doc TO BRP_Bijhouding;
GRANT SELECT ON Kern.Element TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Element TO BRP_Bijhouding;
GRANT SELECT ON Kern.FunctieAdres TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.FunctieAdres TO BRP_Bijhouding;
GRANT SELECT ON Kern.GedeblokkeerdeMelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.GedeblokkeerdeMelding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_GedeblokkeerdeMelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.GegevenInOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.GegevenInOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_GegevenInOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.GegevenInTerugmelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.GegevenInTerugmelding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_GegevenInTerugmelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.Gem TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Gem TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Gem TO BRP_Bijhouding;
GRANT SELECT ON Kern.Geslachtsaand TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Geslachtsaand TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Betr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Betr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Betr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Doc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Doc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Doc TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Onderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Onderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Onderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_OnderzoekAfgeleidAdminis TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_OnderzoekAfgeleidAdminis TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_OnderzoekAfgeleidAdminis TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_OuderOuderlijkGezag TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_OuderOuderlijkGezag TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_OuderOuderlijkGezag TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_OuderOuderschap TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_OuderOuderschap TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_OuderOuderschap TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Partij TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Partij TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Partij TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PartijBijhouding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PartijBijhouding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PartijBijhouding TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PartijOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PartijOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PartijOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PartijRol TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PartijRol TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PartijRol TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersAdres TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersAdres TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersAdres TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersAfgeleidAdministrati TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersAfgeleidAdministrati TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersAfgeleidAdministrati TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersBijhouding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersBijhouding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersBijhouding TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersDeelnEUVerkiezingen TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersDeelnEUVerkiezingen TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersDeelnEUVerkiezingen TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeboorte TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersGeboorte TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeboorte TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeslachtsaand TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersGeslachtsaand TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeslachtsaand TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeslnaamcomp TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersIDs TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersIDs TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersIDs TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersIndicatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersIndicatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersIndicatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersInschr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersInschr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersInschr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersMigratie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersMigratie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersMigratie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNaamgebruik TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersNaamgebruik TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNaamgebruik TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNrverwijzing TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersNrverwijzing TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNrverwijzing TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersOverlijden TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersOverlijden TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersOverlijden TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersPK TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersPK TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersPK TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersSamengesteldeNaam TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersSamengesteldeNaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersSamengesteldeNaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersUitslKiesr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersUitslKiesr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersUitslKiesr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerblijfsr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersVerblijfsr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerblijfsr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerificatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersVerificatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerificatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerstrbeperking TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersVerstrbeperking TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerstrbeperking TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVoornaam TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_PersVoornaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVoornaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Relatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Relatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Relatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Terugmelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_Terugmelding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Terugmelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_TerugmeldingContactpers TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.His_TerugmeldingContactpers TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_TerugmeldingContactpers TO BRP_Bijhouding;
GRANT SELECT ON Kern.Koppelvlak TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Koppelvlak TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Koppelvlak TO BRP_Bijhouding;
GRANT SELECT ON Kern.LandGebied TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.LandGebied TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_LandGebied TO BRP_Bijhouding;
GRANT SELECT ON Kern.Naamgebruik TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Naamgebruik TO BRP_Bijhouding;
GRANT SELECT ON Kern.NadereBijhaard TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.NadereBijhaard TO BRP_Bijhouding;
GRANT SELECT ON Kern.Nation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Nation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Nation TO BRP_Bijhouding;
GRANT SELECT ON Kern.Onderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Onderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Onderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.Partij TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Partij TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Partij TO BRP_Bijhouding;
GRANT SELECT ON Kern.PartijOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PartijOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PartijOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.PartijRol TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PartijRol TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PartijRol TO BRP_Bijhouding;
GRANT SELECT ON Kern.Pers TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Pers TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Pers TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersAdres TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersAdres TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersAdres TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersCache TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersCache TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersCache TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersGeslnaamcomp TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersGeslnaamcomp TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersIndicatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersIndicatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersIndicatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVerificatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersVerificatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVerificatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVerstrbeperking TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersVerstrbeperking TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVerstrbeperking TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVoornaam TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.PersVoornaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVoornaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.Plaats TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Plaats TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Plaats TO BRP_Bijhouding;
GRANT SELECT ON Kern.Predicaat TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Predicaat TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Predicaat TO BRP_Bijhouding;
GRANT SELECT ON Kern.RdnEindeRelatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.RdnEindeRelatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_RdnEindeRelatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.RdnVerkNLNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.RdnVerkNLNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_RdnVerkNLNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.RdnVerliesNLNation TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.RdnVerliesNLNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_RdnVerliesNLNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.RdnWijzVerblijf TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.RdnWijzVerblijf TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_RdnWijzVerblijf TO BRP_Bijhouding;
GRANT SELECT ON Kern.Rechtsgrond TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Rechtsgrond TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Rechtsgrond TO BRP_Bijhouding;
GRANT SELECT ON Kern.Regel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Regel TO BRP_Bijhouding;
GRANT SELECT ON Kern.Regelverantwoording TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Regelverantwoording TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Regelverantwoording TO BRP_Bijhouding;
GRANT SELECT ON Kern.Relatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Relatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Relatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.Rol TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Rol TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtActie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtActie TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtAdmHnd TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtAdmHnd TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtBetr TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtBetr TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtDoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtDoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_SrtDoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtElement TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtElement TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtElementAutorisatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtElementAutorisatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtIndicatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtIndicatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtMigratie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtMigratie TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtNLReisdoc TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtNLReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_SrtNLReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtPartij TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtPartij TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtPartijOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtPartijOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtPers TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtPers TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtPersOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtPersOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtRechtsgrond TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtRechtsgrond TO BRP_Bijhouding;
GRANT SELECT ON Kern.SrtRelatie TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.SrtRelatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.StatusOnderzoek TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.StatusOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.StatusTerugmelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.StatusTerugmelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.Stelsel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Stelsel TO BRP_Bijhouding;
GRANT SELECT ON Kern.Terugmelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Terugmelding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Terugmelding TO BRP_Bijhouding;
GRANT SELECT ON Kern.Voorvoegsel TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON Kern.Voorvoegsel TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Voorvoegsel TO BRP_Bijhouding;
GRANT SELECT ON MigBlok.Blokkering TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON MigBlok.Blokkering TO BRP_Bijhouding;
GRANT USAGE ON MigBlok.seq_Blokkering TO BRP_Bijhouding;
GRANT SELECT ON MigBlok.RdnBlokkering TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON MigBlok.RdnBlokkering TO BRP_Bijhouding;
GRANT USAGE ON MigBlok.seq_RdnBlokkering TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3AandOuder TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3AandOuder TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3AandOuder TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Ber TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3Ber TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Ber TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3BerBron TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3BerBron TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3CategorieMelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3CategorieMelding TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Melding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3Melding TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Melding TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Severity TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3Severity TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3SrtAandOuder TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3SrtAandOuder TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3SrtMelding TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3SrtMelding TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Voorkomen TO BRP_Lezen;
GRANT SELECT, INSERT, UPDATE, DELETE ON VerConv.LO3Voorkomen TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Voorkomen TO BRP_Bijhouding;
