// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.lev;

import java.util.List;
import nl.bzk.brp.model.data.lev.Abonnement;
import nl.bzk.brp.model.data.lev.AbonnementDataOnDemand;
import nl.bzk.brp.model.data.lev.AbonnementIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AbonnementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AbonnementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AbonnementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AbonnementIntegrationTest: @Transactional;
    
    @Autowired
    private AbonnementDataOnDemand AbonnementIntegrationTest.dod;
    
    @Test
    public void AbonnementIntegrationTest.testCountAbonnements() {
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", dod.getRandomAbonnement());
        long count = Abonnement.countAbonnements();
        Assert.assertTrue("Counter for 'Abonnement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AbonnementIntegrationTest.testFindAbonnement() {
        Abonnement obj = dod.getRandomAbonnement();
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to provide an identifier", id);
        obj = Abonnement.findAbonnement(id);
        Assert.assertNotNull("Find method for 'Abonnement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Abonnement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AbonnementIntegrationTest.testFindAllAbonnements() {
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", dod.getRandomAbonnement());
        long count = Abonnement.countAbonnements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Abonnement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Abonnement> result = Abonnement.findAllAbonnements();
        Assert.assertNotNull("Find all method for 'Abonnement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Abonnement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AbonnementIntegrationTest.testFindAbonnementEntries() {
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", dod.getRandomAbonnement());
        long count = Abonnement.countAbonnements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Abonnement> result = Abonnement.findAbonnementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Abonnement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Abonnement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AbonnementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", dod.getRandomAbonnement());
        Abonnement obj = dod.getNewTransientAbonnement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Abonnement' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Abonnement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AbonnementIntegrationTest.testRemove() {
        Abonnement obj = dod.getRandomAbonnement();
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Abonnement' failed to provide an identifier", id);
        obj = Abonnement.findAbonnement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Abonnement' with identifier '" + id + "'", Abonnement.findAbonnement(id));
    }
    
}
