TRUNCATE SCHEMA autaut RESTART IDENTITY AND COMMIT;
TRUNCATE SCHEMA beh RESTART IDENTITY AND COMMIT;
TRUNCATE SCHEMA ber RESTART IDENTITY AND COMMIT;
TRUNCATE SCHEMA conv RESTART IDENTITY AND COMMIT;
TRUNCATE SCHEMA kern RESTART IDENTITY AND COMMIT;
