
--ALTER TABLE Kern.Bron DROP CONSTRAINT FK3875;
--ALTER TABLE Kern.Bron ADD CONSTRAINT FK3875 FOREIGN KEY (Actie) REFERENCES Kern.Actie (ID) ON DELETE CASCADE;
ALTER TABLE Kern.ActieBron DROP CONSTRAINT FK8122;
ALTER TABLE Kern.ActieBron ADD CONSTRAINT FK8122 FOREIGN KEY (Actie) REFERENCES Kern.Actie (ID) ON DELETE CASCADE;

--ALTER TABLE Kern.Bron DROP CONSTRAINT FK3876;
--ALTER TABLE Kern.Bron ADD CONSTRAINT FK3876 FOREIGN KEY (Doc) REFERENCES Kern.Doc (ID) ON DELETE CASCADE;
ALTER TABLE Kern.ActieBron DROP CONSTRAINT FK8123;
ALTER TABLE Kern.ActieBron ADD CONSTRAINT FK8123 FOREIGN KEY (Doc) REFERENCES Kern.Doc (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_Doc DROP CONSTRAINT FK4043;
ALTER TABLE Kern.His_Doc ADD CONSTRAINT FK4043 FOREIGN KEY (Doc) REFERENCES Kern.Doc (ID) ON DELETE CASCADE;

ALTER TABLE Kern.MultiRealiteitRegel DROP CONSTRAINT FK2053;
ALTER TABLE Kern.MultiRealiteitRegel ADD CONSTRAINT FK2053 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

-- Relatie tables
ALTER TABLE Kern.MultiRealiteitRegel DROP CONSTRAINT FK2055;
ALTER TABLE Kern.MultiRealiteitRegel ADD CONSTRAINT FK2055 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE;

--ALTER TABLE KERN.His_Relatie DROP CONSTRAINT FK4369;
--ALTER TABLE Kern.His_Relatie ADD CONSTRAINT FK4369 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE; 
ALTER TABLE Kern.His_ErkenningOngeborenVrucht DROP CONSTRAINT FK9418;
ALTER TABLE Kern.His_ErkenningOngeborenVrucht ADD CONSTRAINT FK9418 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE;
ALTER TABLE Kern.His_HuwelijkGeregistreerdPar DROP CONSTRAINT FK4369;
ALTER TABLE Kern.His_HuwelijkGeregistreerdPar ADD CONSTRAINT FK4369 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE;
ALTER TABLE Kern.His_NaamskeuzeOngeborenVruch DROP CONSTRAINT FK9404;
ALTER TABLE Kern.His_NaamskeuzeOngeborenVruch ADD CONSTRAINT FK9404 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE;

-- Betrokkenheid tables
ALTER TABLE Kern.MultiRealiteitRegel DROP CONSTRAINT FK2056;
ALTER TABLE Kern.MultiRealiteitRegel ADD CONSTRAINT FK2056 FOREIGN KEY (Betr) REFERENCES Kern.Betr (ID) ON DELETE CASCADE;

ALTER TABLE Kern.Betr DROP CONSTRAINT FK3860;
ALTER TABLE Kern.Betr ADD CONSTRAINT FK3860 FOREIGN KEY (Relatie) REFERENCES Kern.Relatie (ID) ON DELETE CASCADE;

ALTER TABLE Kern.Betr DROP CONSTRAINT FK3859;
ALTER TABLE Kern.Betr ADD CONSTRAINT FK3859 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID)  ON DELETE CASCADE;

--ALTER TABLE Kern.His_BetrOuderlijkGezag DROP CONSTRAINT FK4033;
--ALTER TABLE Kern.His_BetrOuderlijkGezag ADD CONSTRAINT FK4033 FOREIGN KEY (Betr) REFERENCES Kern.Betr (ID) ON DELETE CASCADE;
ALTER TABLE Kern.His_OuderOuderlijkGezag DROP CONSTRAINT FK4033;
ALTER TABLE Kern.His_OuderOuderlijkGezag ADD CONSTRAINT FK4033 FOREIGN KEY (Betr) REFERENCES Kern.Betr (ID) ON DELETE CASCADE;

--ALTER TABLE Kern.His_BetrOuderschap DROP CONSTRAINT FK4025;
--ALTER TABLE Kern.His_BetrOuderschap ADD CONSTRAINT FK4025 FOREIGN KEY (Betr) REFERENCES Kern.Betr (ID) ON DELETE CASCADE;
ALTER TABLE Kern.His_OuderOuderschap DROP CONSTRAINT FK4025;
ALTER TABLE Kern.His_OuderOuderschap ADD CONSTRAINT FK4025 FOREIGN KEY (Betr) REFERENCES Kern.Betr (ID) ON DELETE CASCADE;

-- Pers tables
ALTER TABLE Ber.AdmHndBijgehoudenPers DROP CONSTRAINT FK6253;
ALTER TABLE Ber.AdmHndBijgehoudenPers ADD CONSTRAINT FK6253 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.MultiRealiteitRegel DROP CONSTRAINT FK2053;
ALTER TABLE Kern.MultiRealiteitRegel ADD CONSTRAINT FK2053 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersAanschr DROP CONSTRAINT FK4115;
ALTER TABLE Kern.His_PersAanschr ADD CONSTRAINT FK4115 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersBijhgem DROP CONSTRAINT FK4205;
ALTER TABLE Kern.His_PersBijhgem ADD CONSTRAINT FK4205 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersBijhaard DROP CONSTRAINT FK4188;
ALTER TABLE Kern.His_PersBijhaard ADD CONSTRAINT FK4188 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersBVP DROP CONSTRAINT FK9357;
ALTER TABLE Kern.His_PersBVP ADD CONSTRAINT FK9357 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersEUVerkiezingen DROP CONSTRAINT FK4179;
ALTER TABLE Kern.His_PersEUVerkiezingen ADD CONSTRAINT FK4179 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersGeboorte DROP CONSTRAINT FK4132;
ALTER TABLE Kern.His_PersGeboorte ADD CONSTRAINT FK4132 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersGeslachtsaand DROP CONSTRAINT FK4088;
ALTER TABLE Kern.His_PersGeslachtsaand ADD CONSTRAINT FK4088 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersIDs DROP CONSTRAINT FK4077;
ALTER TABLE Kern.His_PersIDs ADD CONSTRAINT FK4077 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersImmigratie DROP CONSTRAINT FK4225;
ALTER TABLE Kern.His_PersImmigratie ADD CONSTRAINT FK4225 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersInschr DROP CONSTRAINT FK4236;
ALTER TABLE Kern.His_PersInschr ADD CONSTRAINT FK4236 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersOpschorting DROP CONSTRAINT FK4198;
ALTER TABLE Kern.His_PersOpschorting ADD CONSTRAINT FK4198 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersOverlijden DROP CONSTRAINT FK4145;
ALTER TABLE Kern.His_PersOverlijden ADD CONSTRAINT FK4145 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersPK DROP CONSTRAINT FK4217;
ALTER TABLE Kern.His_PersPK ADD CONSTRAINT FK4217 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersSamengesteldeNaam DROP CONSTRAINT FK4098;
ALTER TABLE Kern.His_PersSamengesteldeNaam ADD CONSTRAINT FK4098 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersUitslNLKiesr DROP CONSTRAINT FK4171;
ALTER TABLE Kern.His_PersUitslNLKiesr ADD CONSTRAINT FK4171 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersVerblijfstitel DROP CONSTRAINT FK4158;
ALTER TABLE Kern.His_PersVerblijfstitel ADD CONSTRAINT FK4158 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;
--ALTER TABLE Kern.His_PersVerblijfsr DROP CONSTRAINT FK4158;
--ALTER TABLE Kern.His_PersVerblijfsr ADD CONSTRAINT FK4158 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.PersAdres DROP CONSTRAINT FK3241;
ALTER TABLE Kern.PersAdres ADD CONSTRAINT FK3241 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersAdres DROP CONSTRAINT FK6065;
ALTER TABLE Kern.His_PersAdres ADD CONSTRAINT FK6065 FOREIGN KEY (PersAdres) REFERENCES Kern.PersAdres (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersGeslnaamcomp DROP CONSTRAINT FK3024;
ALTER TABLE Kern.PersGeslnaamcomp ADD CONSTRAINT FK3024 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersGeslnaamcomp DROP CONSTRAINT FK4301;
ALTER TABLE Kern.His_PersGeslnaamcomp ADD CONSTRAINT FK4301 FOREIGN KEY (PersGeslnaamcomp) REFERENCES Kern.PersGeslnaamcomp (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersIndicatie DROP CONSTRAINT FK3657;
ALTER TABLE Kern.PersIndicatie ADD CONSTRAINT FK3657 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersIndicatie DROP CONSTRAINT FK4315;
ALTER TABLE Kern.His_PersIndicatie ADD CONSTRAINT FK4315 FOREIGN KEY (PersIndicatie) REFERENCES Kern.PersIndicatie (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersNation DROP CONSTRAINT FK3130;
ALTER TABLE Kern.PersNation ADD CONSTRAINT FK3130 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersNation DROP CONSTRAINT FK4325;
ALTER TABLE Kern.His_PersNation ADD CONSTRAINT FK4325 FOREIGN KEY (PersNation) REFERENCES Kern.PersNation (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersReisdoc DROP CONSTRAINT FK3752;
ALTER TABLE Kern.PersReisdoc ADD CONSTRAINT FK3752 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersReisdoc DROP CONSTRAINT FK4336;
ALTER TABLE Kern.His_PersReisdoc ADD CONSTRAINT FK4336 FOREIGN KEY (PersReisdoc) REFERENCES Kern.PersReisdoc (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersVerificatie DROP CONSTRAINT FK2142;
ALTER TABLE Kern.PersVerificatie ADD CONSTRAINT FK2142 FOREIGN KEY (Geverifieerde) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersVerificatie DROP CONSTRAINT FK4352;
ALTER TABLE Kern.His_PersVerificatie ADD CONSTRAINT FK4352 FOREIGN KEY (PersVerificatie) REFERENCES Kern.PersVerificatie (ID) ON DELETE CASCADE;


ALTER TABLE Kern.PersVoornaam DROP CONSTRAINT FK3023;
ALTER TABLE Kern.PersVoornaam ADD CONSTRAINT FK3023 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

ALTER TABLE Kern.His_PersVoornaam DROP CONSTRAINT FK4359;
ALTER TABLE Kern.His_PersVoornaam ADD CONSTRAINT FK4359 FOREIGN KEY (PersVoornaam) REFERENCES Kern.PersVoornaam (ID) ON DELETE CASCADE;

-- PersOnderzoek
ALTER TABLE Kern.PersOnderzoek DROP CONSTRAINT FK6131;
ALTER TABLE Kern.PersOnderzoek ADD CONSTRAINT FK6131 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

-- Pers verstrekking derde
ALTER TABLE Kern.His_VerstrDerde DROP CONSTRAINT FK9364;
ALTER TABLE Kern.His_VerstrDerde ADD CONSTRAINT FK9364 FOREIGN KEY (VerstrDerde) REFERENCES Kern.VerstrDerde (ID) ON DELETE CASCADE;

ALTER TABLE Kern.VerstrDerde DROP CONSTRAINT FK9351;
ALTER TABLE Kern.VerstrDerde ADD CONSTRAINT FK9351 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;

-- Pers Levering
ALTER TABLE Lev.LevPers DROP CONSTRAINT FK4843;
ALTER TABLE Lev.LevPers ADD CONSTRAINT FK4843 FOREIGN KEY (Pers) REFERENCES Kern.Pers (ID) ON DELETE CASCADE;
