/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA

/**
 * HisErkenningongeborenvrucht generated by hbm2java
 */
public class HisErkenningongeborenvrucht extends His {

     private Relatie relatie;
     private int daterkenningongeborenvrucht;

    public HisErkenningongeborenvrucht() {
    }

    public Relatie getRelatie() {
        return this.relatie;
    }

    public void setRelatie(Relatie relatie) {
        this.relatie = relatie;
    }

    public int getDaterkenningongeborenvrucht() {
        return this.daterkenningongeborenvrucht;
    }

    public void setDaterkenningongeborenvrucht(int daterkenningongeborenvrucht) {
        this.daterkenningongeborenvrucht = daterkenningongeborenvrucht;
    }
}


