/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * HisHuwelijkgeregistreerdpar generated by hbm2java
 */
public class HisHuwelijkgeregistreerdpar extends HisMaterieel {

     private Plaats plaatsByWplaanv;
     private Partij partijByGemeinde;
     private Plaats plaatsByWpleinde;
     private Relatie relatie;
     private Rdnbeeindrelatie rdnbeeindrelatie;
     private Partij partijByGemaanv;
     private Land landByLandaanv;
     private Land landByLandeinde;
     private String blplaatsaanv;
     private String blregioaanv;
     private String omslocaanv;
     private String blplaatseinde;
     private String blregioeinde;
     private String omsloceinde;

    public HisHuwelijkgeregistreerdpar() {
    }


    public Plaats getPlaatsByWplaanv() {
        return this.plaatsByWplaanv;
    }

    public void setPlaatsByWplaanv(Plaats plaatsByWplaanv) {
        this.plaatsByWplaanv = plaatsByWplaanv;
    }

    public Partij getPartijByGemeinde() {
        return this.partijByGemeinde;
    }

    public void setPartijByGemeinde(Partij partijByGemeinde) {
        this.partijByGemeinde = partijByGemeinde;
    }
    public Plaats getPlaatsByWpleinde() {
        return this.plaatsByWpleinde;
    }

    public void setPlaatsByWpleinde(Plaats plaatsByWpleinde) {
        this.plaatsByWpleinde = plaatsByWpleinde;
    }
    public Relatie getRelatie() {
        return this.relatie;
    }

    public void setRelatie(Relatie relatie) {
        this.relatie = relatie;
    }
    public Rdnbeeindrelatie getRdnbeeindrelatie() {
        return this.rdnbeeindrelatie;
    }

    public void setRdnbeeindrelatie(Rdnbeeindrelatie rdnbeeindrelatie) {
        this.rdnbeeindrelatie = rdnbeeindrelatie;
    }
    public Partij getPartijByGemaanv() {
        return this.partijByGemaanv;
    }

    public void setPartijByGemaanv(Partij partijByGemaanv) {
        this.partijByGemaanv = partijByGemaanv;
    }

    public Land getLandByLandaanv() {
        return this.landByLandaanv;
    }

    public void setLandByLandaanv(Land landByLandaanv) {
        this.landByLandaanv = landByLandaanv;
    }
    public Land getLandByLandeinde() {
        return this.landByLandeinde;
    }

    public void setLandByLandeinde(Land landByLandeinde) {
        this.landByLandeinde = landByLandeinde;
    }

    public String getBlplaatsaanv() {
        return this.blplaatsaanv;
    }

    public void setBlplaatsaanv(String blplaatsaanv) {
        this.blplaatsaanv = blplaatsaanv;
    }
    public String getBlregioaanv() {
        return this.blregioaanv;
    }

    public void setBlregioaanv(String blregioaanv) {
        this.blregioaanv = blregioaanv;
    }
    public String getOmslocaanv() {
        return this.omslocaanv;
    }

    public void setOmslocaanv(String omslocaanv) {
        this.omslocaanv = omslocaanv;
    }

    public String getBlplaatseinde() {
        return this.blplaatseinde;
    }

    public void setBlplaatseinde(String blplaatseinde) {
        this.blplaatseinde = blplaatseinde;
    }
    public String getBlregioeinde() {
        return this.blregioeinde;
    }

    public void setBlregioeinde(String blregioeinde) {
        this.blregioeinde = blregioeinde;
    }
    public String getOmsloceinde() {
        return this.omsloceinde;
    }

    public void setOmsloceinde(String omsloceinde) {
        this.omsloceinde = omsloceinde;
    }
}


