/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * HisPersverblijfstitel generated by hbm2java
 */
public class HisPersverblijfstitel extends HisMaterieel {

     private Pers pers;
     private Verblijfstitel verblijfstitel;
     private int dataanvverblijfstitel;
     private Integer datvoorzeindeverblijfstitel;
     private Integer dataanvaaneenslverblijfsr;

    public HisPersverblijfstitel() {
    }

    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }

    public Verblijfstitel getVerblijfstitel() {
        return this.verblijfstitel;
    }

    public void setVerblijfstitel(Verblijfstitel verblijfstitel) {
        this.verblijfstitel = verblijfstitel;
    }

    public int getDataanvverblijfstitel() {
        return this.dataanvverblijfstitel;
    }

    public void setDataanvverblijfstitel(int dataanvverblijfstitel) {
        this.dataanvverblijfstitel = dataanvverblijfstitel;
    }
    public Integer getDatvoorzeindeverblijfstitel() {
        return this.datvoorzeindeverblijfstitel;
    }

    public void setDatvoorzeindeverblijfstitel(Integer datvoorzeindeverblijfstitel) {
        this.datvoorzeindeverblijfstitel = datvoorzeindeverblijfstitel;
    }
    public Integer getDataanvaaneenslverblijfsr() {
        return this.dataanvaaneenslverblijfsr;
    }

    public void setDataanvaaneenslverblijfsr(Integer dataanvaaneenslverblijfsr) {
        this.dataanvaaneenslverblijfsr = dataanvaaneenslverblijfsr;
    }

}
