/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * HisUitgeslotene generated by hbm2java
 */
public class HisUitgeslotene extends His {

     private Uitgeslotene uitgeslotene;

    public HisUitgeslotene() {
    }

    public Uitgeslotene getUitgeslotene() {
        return this.uitgeslotene;
    }

    public void setUitgeslotene(Uitgeslotene uitgeslotene) {
        this.uitgeslotene = uitgeslotene;
    }
}
