/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * Levpers generated by hbm2java
 */
public class Levpers  implements java.io.Serializable {


     private Long id;
     private Pers pers;
     private Lev lev;

    public Levpers() {
    }

    public Levpers(Pers pers, Lev lev) {
       this.pers = pers;
       this.lev = lev;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Pers getPers() {
        return this.pers;
    }
    
    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Lev getLev() {
        return this.lev;
    }
    
    public void setLev(Lev lev) {
        this.lev = lev;
    }




}


