/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * Persindicatie generated by hbm2java
 */
public class Persindicatie  implements java.io.Serializable {


     private Integer id;
     private Srtindicatie srtindicatie;
     private Pers pers;
     private Boolean waarde;
     private String persindicatiestatushis = StatusHis.A.name();

    public Persindicatie() {
    }


    public Persindicatie(Srtindicatie srtindicatie, Pers pers, String persindicatiestatushis) {
        this.srtindicatie = srtindicatie;
        this.pers = pers;
        this.persindicatiestatushis = persindicatiestatushis;
    }
    public Persindicatie(Srtindicatie srtindicatie, Pers pers, Boolean waarde, String persindicatiestatushis) {
       this.srtindicatie = srtindicatie;
       this.pers = pers;
       this.waarde = waarde;
       this.persindicatiestatushis = persindicatiestatushis;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Srtindicatie getSrtindicatie() {
        return this.srtindicatie;
    }

    public void setSrtindicatie(Srtindicatie srtindicatie) {
        this.srtindicatie = srtindicatie;
    }
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Boolean getWaarde() {
        return this.waarde;
    }

    public void setWaarde(Boolean waarde) {
        this.waarde = waarde;
    }
    public String getPersindicatiestatushis() {
        return this.persindicatiestatushis;
    }

    public void setPersindicatiestatushis(String persindicatiestatushis) {
        this.persindicatiestatushis = persindicatiestatushis;
    }




}


