/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * Relatie generated by hbm2java
 */
public class Relatie  implements java.io.Serializable {


     private int id;
     private Srtrelatie srtrelatie;
     private Plaats plaatsByWplaanv;
     private Partij partijByGemeinde;
     private Plaats plaatsByWpleinde;
     private Rdnbeeindrelatie rdnbeeindrelatie;
     private Partij partijByGemaanv;
     private Land landByLandaanv;
     private Land landByLandeinde;
     private Integer dataanv;
     private String blplaatsaanv;
     private String blregioaanv;
     private String omslocaanv;
     private Integer dateinde;
     private String blplaatseinde;
     private String blregioeinde;
     private String omsloceinde;
     private String huwelijkgeregistreerdpartner = StatusHis.A.name();
     private Integer datnaamskeuzeongeborenvrucht;
     private String naamskeuzeongeborenvruchtsta = StatusHis.A.name();
     private Integer datontkenningouderschapongeb;
     private String ontkenningouderschapongebore = StatusHis.A.name();
     private Integer daterkenningongeborenvrucht;
     private String erkenningongeborenvruchtstat = StatusHis.A.name();

    public Relatie() {
    }


    public Relatie(Srtrelatie srtrelatie, String huwelijkgeregistreerdpartner, String naamskeuzeongeborenvruchtsta, String ontkenningouderschapongebore, String erkenningongeborenvruchtstat) {
        this.srtrelatie = srtrelatie;
        this.huwelijkgeregistreerdpartner = huwelijkgeregistreerdpartner;
        this.naamskeuzeongeborenvruchtsta = naamskeuzeongeborenvruchtsta;
        this.ontkenningouderschapongebore = ontkenningouderschapongebore;
        this.erkenningongeborenvruchtstat = erkenningongeborenvruchtstat;
    }
    public Relatie(Srtrelatie srtrelatie, Plaats plaatsByWplaanv, Partij partijByGemeinde, Plaats plaatsByWpleinde, Rdnbeeindrelatie rdnbeeindrelatie, Partij partijByGemaanv, Land landByLandaanv, Land landByLandeinde, Integer dataanv, String blplaatsaanv, String blregioaanv, String omslocaanv, Integer dateinde, String blplaatseinde, String blregioeinde, String omsloceinde, String huwelijkgeregistreerdpartner, Integer datnaamskeuzeongeborenvrucht, String naamskeuzeongeborenvruchtsta, Integer datontkenningouderschapongeb, String ontkenningouderschapongebore, Integer daterkenningongeborenvrucht, String erkenningongeborenvruchtstat) {
       this.srtrelatie = srtrelatie;
       this.plaatsByWplaanv = plaatsByWplaanv;
       this.partijByGemeinde = partijByGemeinde;
       this.plaatsByWpleinde = plaatsByWpleinde;
       this.rdnbeeindrelatie = rdnbeeindrelatie;
       this.partijByGemaanv = partijByGemaanv;
       this.landByLandaanv = landByLandaanv;
       this.landByLandeinde = landByLandeinde;
       this.dataanv = dataanv;
       this.blplaatsaanv = blplaatsaanv;
       this.blregioaanv = blregioaanv;
       this.omslocaanv = omslocaanv;
       this.dateinde = dateinde;
       this.blplaatseinde = blplaatseinde;
       this.blregioeinde = blregioeinde;
       this.omsloceinde = omsloceinde;
       this.huwelijkgeregistreerdpartner = huwelijkgeregistreerdpartner;
       this.datnaamskeuzeongeborenvrucht = datnaamskeuzeongeborenvrucht;
       this.naamskeuzeongeborenvruchtsta = naamskeuzeongeborenvruchtsta;
       this.datontkenningouderschapongeb = datontkenningouderschapongeb;
       this.ontkenningouderschapongebore = ontkenningouderschapongebore;
       this.daterkenningongeborenvrucht = daterkenningongeborenvrucht;
       this.erkenningongeborenvruchtstat = erkenningongeborenvruchtstat;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public Srtrelatie getSrtrelatie() {
        return this.srtrelatie;
    }

    public void setSrtrelatie(Srtrelatie srtrelatie) {
        this.srtrelatie = srtrelatie;
    }
    public Plaats getPlaatsByWplaanv() {
        return this.plaatsByWplaanv;
    }

    public void setPlaatsByWplaanv(Plaats plaatsByWplaanv) {
        this.plaatsByWplaanv = plaatsByWplaanv;
    }
    public Partij getPartijByGemeinde() {
        return this.partijByGemeinde;
    }

    public void setPartijByGemeinde(Partij partijByGemeinde) {
        this.partijByGemeinde = partijByGemeinde;
    }
    public Plaats getPlaatsByWpleinde() {
        return this.plaatsByWpleinde;
    }

    public void setPlaatsByWpleinde(Plaats plaatsByWpleinde) {
        this.plaatsByWpleinde = plaatsByWpleinde;
    }
    public Rdnbeeindrelatie getRdnbeeindrelatie() {
        return this.rdnbeeindrelatie;
    }

    public void setRdnbeeindrelatie(Rdnbeeindrelatie rdnbeeindrelatie) {
        this.rdnbeeindrelatie = rdnbeeindrelatie;
    }
    public Partij getPartijByGemaanv() {
        return this.partijByGemaanv;
    }

    public void setPartijByGemaanv(Partij partijByGemaanv) {
        this.partijByGemaanv = partijByGemaanv;
    }
    public Land getLandByLandaanv() {
        return this.landByLandaanv;
    }

    public void setLandByLandaanv(Land landByLandaanv) {
        this.landByLandaanv = landByLandaanv;
    }
    public Land getLandByLandeinde() {
        return this.landByLandeinde;
    }

    public void setLandByLandeinde(Land landByLandeinde) {
        this.landByLandeinde = landByLandeinde;
    }
    public Integer getDataanv() {
        return this.dataanv;
    }

    public void setDataanv(Integer dataanv) {
        this.dataanv = dataanv;
    }
    public String getBlplaatsaanv() {
        return this.blplaatsaanv;
    }

    public void setBlplaatsaanv(String blplaatsaanv) {
        this.blplaatsaanv = blplaatsaanv;
    }
    public String getBlregioaanv() {
        return this.blregioaanv;
    }

    public void setBlregioaanv(String blregioaanv) {
        this.blregioaanv = blregioaanv;
    }
    public String getOmslocaanv() {
        return this.omslocaanv;
    }

    public void setOmslocaanv(String omslocaanv) {
        this.omslocaanv = omslocaanv;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }

    public void setDateinde(Integer dateinde) {
        this.dateinde = dateinde;
    }
    public String getBlplaatseinde() {
        return this.blplaatseinde;
    }

    public void setBlplaatseinde(String blplaatseinde) {
        this.blplaatseinde = blplaatseinde;
    }
    public String getBlregioeinde() {
        return this.blregioeinde;
    }

    public void setBlregioeinde(String blregioeinde) {
        this.blregioeinde = blregioeinde;
    }
    public String getOmsloceinde() {
        return this.omsloceinde;
    }

    public void setOmsloceinde(String omsloceinde) {
        this.omsloceinde = omsloceinde;
    }
    public String getHuwelijkgeregistreerdpartner() {
        return this.huwelijkgeregistreerdpartner;
    }

    public void setHuwelijkgeregistreerdpartner(String huwelijkgeregistreerdpartner) {
        this.huwelijkgeregistreerdpartner = huwelijkgeregistreerdpartner;
    }
    public Integer getDatnaamskeuzeongeborenvrucht() {
        return this.datnaamskeuzeongeborenvrucht;
    }

    public void setDatnaamskeuzeongeborenvrucht(Integer datnaamskeuzeongeborenvrucht) {
        this.datnaamskeuzeongeborenvrucht = datnaamskeuzeongeborenvrucht;
    }
    public String getNaamskeuzeongeborenvruchtsta() {
        return this.naamskeuzeongeborenvruchtsta;
    }

    public void setNaamskeuzeongeborenvruchtsta(String naamskeuzeongeborenvruchtsta) {
        this.naamskeuzeongeborenvruchtsta = naamskeuzeongeborenvruchtsta;
    }
    public Integer getDatontkenningouderschapongeb() {
        return this.datontkenningouderschapongeb;
    }

    public void setDatontkenningouderschapongeb(Integer datontkenningouderschapongeb) {
        this.datontkenningouderschapongeb = datontkenningouderschapongeb;
    }
    public String getOntkenningouderschapongebore() {
        return this.ontkenningouderschapongebore;
    }

    public void setOntkenningouderschapongebore(String ontkenningouderschapongebore) {
        this.ontkenningouderschapongebore = ontkenningouderschapongebore;
    }
    public Integer getDaterkenningongeborenvrucht() {
        return this.daterkenningongeborenvrucht;
    }

    public void setDaterkenningongeborenvrucht(Integer daterkenningongeborenvrucht) {
        this.daterkenningongeborenvrucht = daterkenningongeborenvrucht;
    }
    public String getErkenningongeborenvruchtstat() {
        return this.erkenningongeborenvruchtstat;
    }

    public void setErkenningongeborenvruchtstat(String erkenningongeborenvruchtstat) {
        this.erkenningongeborenvruchtstat = erkenningongeborenvruchtstat;
    }




}


