/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import nl.bzk.brp.model.algemeen.stamgegeven.kern.SoortActie;

/**
 * Actie generated by hbm2java
 */
public class Actie  implements java.io.Serializable {


     private long id;
     private Partij partij;
     private Admhnd admhnd;
     private SoortActie srtactie;
     private Date tsreg;

    public Actie() {
    }

    public Actie(Partij partij, Admhnd admhnd, SoortActie srtactie, Date tsreg) {
       this.partij = partij;
       this.admhnd = admhnd;
       this.srtactie = srtactie;
       this.tsreg = tsreg;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Partij getPartij() {
        return this.partij;
    }
    
    public void setPartij(Partij partij) {
        this.partij = partij;
    }
    public Admhnd getAdmhnd() {
        return this.admhnd;
    }
    
    public void setAdmhnd(Admhnd admhnd) {
        this.admhnd = admhnd;
    }
    public SoortActie getSrtactie() {
        return this.srtactie;
    }
    
    public void setSrtactie(SoortActie srtactie) {
        this.srtactie = srtactie;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }




}


