/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersinschr generated by hbm2java
 */
public class HisPersinschr extends His {


     private Integer id;
     private Pers persByVolgendepers;
     private Pers persByPers;
     private Pers persByVorigepers;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private int datinschr;
     private long versienr;

    public HisPersinschr() {
    }


    public HisPersinschr(int datinschr, long versienr) {
        this.datinschr = datinschr;
        this.versienr = versienr;
    }
    public HisPersinschr(Pers persByVolgendepers, Pers persByPers, Pers persByVorigepers, Date tsreg, Date tsverval, Long actieinh, Long actieverval, int datinschr, long versienr) {
       this.persByVolgendepers = persByVolgendepers;
       this.persByPers = persByPers;
       this.persByVorigepers = persByVorigepers;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.datinschr = datinschr;
       this.versienr = versienr;
    }

    public Pers getPersByVolgendepers() {
        return this.persByVolgendepers;
    }

    public void setPersByVolgendepers(Pers persByVolgendepers) {
        this.persByVolgendepers = persByVolgendepers;
    }
    public Pers getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(Pers persByPers) {
        this.persByPers = persByPers;
    }
    public Pers getPersByVorigepers() {
        return this.persByVorigepers;
    }

    public void setPersByVorigepers(Pers persByVorigepers) {
        this.persByVorigepers = persByVorigepers;
    }
    public int getDatinschr() {
        return this.datinschr;
    }

    public void setDatinschr(int datinschr) {
        this.datinschr = datinschr;
    }
    public long getVersienr() {
        return this.versienr;
    }

    public void setVersienr(long versienr) {
        this.versienr = versienr;
    }




}


