/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersoverlijden generated by hbm2java
 */
public class HisPersoverlijden extends His {


     private Integer id;
     private Pers pers;
     private Land land;
     private Plaats plaats;
     private Partij partij;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private int datoverlijden;
     private String blplaatsoverlijden;
     private String blregiooverlijden;
     private String omslocoverlijden;

    public HisPersoverlijden() {
    }


    public HisPersoverlijden(Land land, int datoverlijden) {
        this.land = land;
        this.datoverlijden = datoverlijden;
    }
    public HisPersoverlijden(Pers pers, Land land, Plaats plaats, Partij partij, Date tsreg, Date tsverval, Long actieinh, Long actieverval, int datoverlijden, String blplaatsoverlijden, String blregiooverlijden, String omslocoverlijden) {
       this.pers = pers;
       this.land = land;
       this.plaats = plaats;
       this.partij = partij;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.datoverlijden = datoverlijden;
       this.blplaatsoverlijden = blplaatsoverlijden;
       this.blregiooverlijden = blregiooverlijden;
       this.omslocoverlijden = omslocoverlijden;
    }

    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Land getLand() {
        return this.land;
    }

    public void setLand(Land land) {
        this.land = land;
    }
    public Plaats getPlaats() {
        return this.plaats;
    }

    public void setPlaats(Plaats plaats) {
        this.plaats = plaats;
    }
    public Partij getPartij() {
        return this.partij;
    }

    public void setPartij(Partij partij) {
        this.partij = partij;
    }
    public int getDatoverlijden() {
        return this.datoverlijden;
    }

    public void setDatoverlijden(int datoverlijden) {
        this.datoverlijden = datoverlijden;
    }
    public String getBlplaatsoverlijden() {
        return this.blplaatsoverlijden;
    }

    public void setBlplaatsoverlijden(String blplaatsoverlijden) {
        this.blplaatsoverlijden = blplaatsoverlijden;
    }
    public String getBlregiooverlijden() {
        return this.blregiooverlijden;
    }

    public void setBlregiooverlijden(String blregiooverlijden) {
        this.blregiooverlijden = blregiooverlijden;
    }
    public String getOmslocoverlijden() {
        return this.omslocoverlijden;
    }

    public void setOmslocoverlijden(String omslocoverlijden) {
        this.omslocoverlijden = omslocoverlijden;
    }




}


