/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import nl.bzk.brp.model.algemeen.stamgegeven.kern.SoortMultiRealiteitRegel;

/**
 * Multirealiteitregel generated by hbm2java
 */
public class Multirealiteitregel  implements java.io.Serializable {


     private Integer id;
     private long persByGeldigvoor;
     private SoortMultiRealiteitRegel srtmultirealiteitregel;
     private Long persByPers;
     private Long persByMultirealiteitpers;
     private Long relatie;
     private Long betr;
     private String multirealiteitregelstatushis = StatusHis.A.name();

    public Multirealiteitregel() {
    }




    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public long getPersByGeldigvoor() {
        return this.persByGeldigvoor;
    }

    public void setPersByGeldigvoor(long persByGeldigvoor) {
        this.persByGeldigvoor = persByGeldigvoor;
    }
    public SoortMultiRealiteitRegel getSrtmultirealiteitregel() {
        return this.srtmultirealiteitregel;
    }

    public void setSrtmultirealiteitregel(SoortMultiRealiteitRegel srtmultirealiteitregel) {
        this.srtmultirealiteitregel = srtmultirealiteitregel;
    }
    public Long getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(Long persByPers) {
        this.persByPers = persByPers;
    }
    public Long getPersByMultirealiteitpers() {
        return this.persByMultirealiteitpers;
    }

    public void setPersByMultirealiteitpers(Long persByMultirealiteitpers) {
        this.persByMultirealiteitpers = persByMultirealiteitpers;
    }
    public Long getRelatie() {
        return this.relatie;
    }

    public void setRelatie(Long relatie) {
        this.relatie = relatie;
    }
    public Long getBetr() {
        return this.betr;
    }

    public void setBetr(Long betr) {
        this.betr = betr;
    }
    public String getMultirealiteitregelstatushis() {
        return this.multirealiteitregelstatushis;
    }

    public void setMultirealiteitregelstatushis(String multirealiteitregelstatushis) {
        this.multirealiteitregelstatushis = multirealiteitregelstatushis;
    }




}


