:generateddir: ../../../target/test-classes

== Steps in Scenario's

=== Given steps
*Given* of *Gegeven* steps zijn de stappen die de voorwaarden voor een scenario scheppen.
Het zijn de voorbereidende stappen die beschrijven hoe het systeem in een bepaalde staat wordt gezet.
Een overzicht van alle beschikbare given steps is te vinden in de link:#alle_given_steps[Appendix].

:numbered!:
include::{generateddir}/bdd-steps-given.adoc[]
:numbered:

=== When steps
*When* of *Wanneer* steps zijn de actie of uitvoerende stappen in een scenario.
Deze beschrijven de sleutelacties in een scenario. Een overzicht van alle beschikbare when
steps is te vinden in de link:#alle_when_steps[Appendix].

:numbered!:
include::{generateddir}/bdd-steps-when.adoc[]
:numbered:

=== Then steps
*Then* of *Dan* steps zijn de validatie of controlerende stappen in een scenario.
Ze beschrijven het verwachte resultaat. Een overzicht van alle beschikbare then
steps is te vinden in de link:#alle_then_steps[Appendix].

:numbered!:
include::{generateddir}/bdd-steps-then.adoc[]
:numbered:


[appendix]
== Steps overzicht
Overzicht van alle steps die beschikbaar zijn.

:numbered!:
=== Alle Given steps
Het overzicht van alle beschikbare given steps. De documentatie van de individuele steps
staat bij link:#given_steps[Given Steps].

[source,gherkin]
----
include::{generateddir}/bdd-steps-appendix-given.adoc[]
----
<1> Step bij voorkeur niet meer gebruiken

=== Alle When steps
Het overzicht van alle beschikbare when steps. De documentatie van de individuele steps
staat bij link:#when_steps[When Steps].

[source,gherkin]
----
include::{generateddir}/bdd-steps-appendix-when.adoc[]
----
<1> Step bij voorkeur niet meer gebruiken

=== Alle Then steps
Het overzicht van alle beschikbare then steps. De documentatie van de individuele steps
staat bij link:#then_steps[Then Steps].

[source,gherkin]
----
include::{generateddir}/bdd-steps-appendix-then.adoc[]
----
<1> Step bij voorkeur niet meer gebruiken

