/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.whitebox.vulling;

import java.util.Random;

public class AchternamenGenerator {

    private final static String[] achterName = new String[] {
	"Saul Perlmutter",
	"Brian P. Schmidt",
	"Adam G. Riess",
	"Andre Geim",
	"Konstantin Novoselov",
	"Charles Kuen Kao",
	"Willard S. Boyle",
	"George E. Smith",
	"Yoichiro Nambu",
	"Makoto Kobayashi",
	"Toshihide Maskawa",
	"Albert Fert",
	"Peter Grünberg",
	"John C. Mather",
	"George F. Smoot",
	"Roy J. Glauber",
	"John L. Hall",
	"Theodor W. Hänsch",
	"David J. Gross",
	"H. David Politzer",
	"Frank Wilczek",
	"Alexei A. Abrikosov",
	"Vitaly L. Ginzburg",
	"Anthony J. Leggett",
	"Raymond Davis Jr.",
	"Masatoshi Koshiba",
	"Riccardo Giacconi",
	"Eric A. Cornell",
	"Wolfgang Ketterle",
	"Carl E. Wieman",
	"Zhores I. Alferov",
	"Herbert Kroemer",
	"Jack S. Kilby",
	"Gerardus 't Hooft",
	"Martinus J.G. Veltman",
	"Robert B. Laughlin",
	"Horst L. Störmer",
	"Daniel C. Tsui",
	"Steven Chu",
	"Claude Cohen-Tannoudji",
	"William D. Phillips",
	"David M. Lee",
	"Douglas D. Osheroff",
	"Robert C. Richardson",
	"Martin L. Perl",
	"Frederick Reines",
	"Bertram N. Brockhouse",
	"Clifford G. Shull",
	"Russell A. Hulse",
	"Joseph H. Taylor Jr.",
	"Georges Charpak",
	"Pierre-Gilles de Gennes",
	"Jerome I. Friedman",
	"Henry W. Kendall",
	"Richard E. Taylor",
	"Norman F. Ramsey",
	"Hans G. Dehmelt",
	"Wolfgang Paul",
	"Leon M. Lederman",
	"Melvin Schwartz",
	"Jack Steinberger",
	"J. Georg Bednorz",
	"K. Alexander Müller",
	"Ernst Ruska",
	"Gerd Binnig",
	"Heinrich Rohrer",
	"Klaus von Klitzing",
	"Carlo Rubbia",
	"Simon van der Meer",
	"Subramanyan Chandrasekhar",
	"William Alfred Fowler",
	"Kenneth G. Wilson",
	"Nicolaas Bloembergen",
	"Arthur Leonard Schawlow",
	"Kai M. Siegbahn",
	"James Watson Cronin",
	"Val Logsdon Fitch",
	"Sheldon Lee Glashow",
	"Abdus Salam",
	"Steven Weinberg",
	"Pyotr Leonidovich Kapitsa",
	"Arno Allan Penzias",
	"Robert Woodrow Wilson",
	"Philip Warren Anderson",
	"Sir Nevill Francis Mott",
	"John Hasbrouck van Vleck",
	"Burton Richter",
	"Samuel Chao Chung Ting",
	"Aage Niels Bohr",
	"Ben Roy Mottelson",
	"Leo James Rainwater",
	"Sir Martin Ryle",
	"Antony Hewish",
	"Leo Esaki",
	"Ivar Giaever",
	"Brian David Josephson",
	"John Bardeen",
	"Leon Neil Cooper",
	"John Robert Schrieffer",
	"Dennis Gabor",
	"Hannes Olof Gösta Alfvén",
	"Louis Eugène Félix Néel",
	"Murray Gell-Mann",
	"Luis Walter Alvarez",
	"Hans Albrecht Bethe",
	"Alfred Kastler",
	"Sin-Itiro Tomonaga",
	"Julian Schwinger",
	"Richard P. Feynman",
	"Charles Hard Townes",
	"Nicolay Gennadiyevich Basov",
	"Aleksandr Mikhailovich Prokhorov",
	"Eugene Paul Wigner",
	"Maria Goeppert Mayer",
	"J. Hans D. Jensen",
	"Lev Davidovich Landau",
	"Robert Hofstadter",
	"Rudolf Ludwig Mössbauer",
	"Donald Arthur Glaser",
	"Emilio Gino Segrè",
	"Owen Chamberlain",
	"Pavel Alekseyevich Cherenkov",
	"Il´ja Mikhailovich Frank",
	"Igor Yevgenyevich Tamm",
	"Chen Ning Yang",
	"Tsung-Dao (T.D.) Lee",
	"William Bradford Shockley",
	"John Bardeen",
	"Walter Houser Brattain",
	"Willis Eugene Lamb",
	"Polykarp Kusch",
	"Max Born",
	"Walther Bothe",
	"Frits (Frederik) Zernike",
	"Felix Bloch",
	"Edward Mills Purcell",
	"Sir John Douglas Cockcroft",
	"Ernest Thomas Sinton Walton",
	"Cecil Frank Powell",
	"Hideki Yukawa",
	"Patrick Maynard Stuart Blackett",
	"Sir Edward Victor Appleton",
	"Percy Williams Bridgman",
	"Wolfgang Pauli",
	"Isidor Isaac Rabi",
	"Otto Stern",
	"Ernest Orlando Lawrence",
	"Enrico Fermi",
	"Clinton Joseph Davisson",
	"George Paget Thomson",
	"Victor Franz Hess",
	"Carl David Anderson",
	"James Chadwick",
	"Erwin Schrödinger",
	"Paul Adrien Maurice Dirac",
	"Werner Karl Heisenberg",
	"Sir Chandrasekhara Venkata Raman",
	"Prince Louis-Victor Pierre Raymond de Broglie",
	"Owen Willans Richardson",
	"Arthur Holly Compton",
	"Charles Thomson Rees Wilson",
	"Jean Baptiste Perrin",
	"James Franck",
	"Gustav Ludwig Hertz",
	"Karl Manne Georg Siegbahn",
	"Robert Andrews Millikan",
	"Niels Henrik David Bohr",
	"Albert Einstein",
	"Charles Edouard Guillaume",
	"Johannes Stark",
	"Max Karl Ernst Ludwig Planck",
	"Charles Glover Barkla",
	"Sir William Henry Bragg",
	"William Lawrence Bragg",
	"Max von Laue",
	"Heike Kamerlingh Onnes",
	"Nils Gustaf Dalén",
	"Wilhelm Wien",
	"Johannes Diderik van der Waals",
	"Guglielmo Marconi",
	"Karl Ferdinand Braun",
	"Gabriel Lippmann",
	"Albert Abraham Michelson",
	"Joseph John Thomson",
	"Philipp Eduard Anton von Lenard",
	"(Lord Rayleigh) John William Strutt",
	"Antoine Henri Becquerel",
	"Pierre Curie",
	"Marie Curie, née Sklodowska",
	"Hendrik Antoon Lorentz",
	"Pieter Zeeman",
	"Wilhelm Conrad Röntgen",
	"Dan Shechtman",
	"Richard F. Heck",
	"Ei-ichi Negishi",
	"Akira Suzuki",
	"Venkatraman Ramakrishnan",
	"Thomas A. Steitz",
	"Ada E. Yonath",
	"Osamu Shimomura",
	"Martin Chalfie",
	"Roger Y. Tsien",
	"Gerhard Ertl",
	"Roger D. Kornberg",
	"Yves Chauvin",
	"Robert H. Grubbs",
	"Richard R. Schrock",
	"Aaron Ciechanover",
	"Avram Hershko",
	"Irwin Rose",
	"Peter Agre",
	"Roderick MacKinnon",
	"John B. Fenn",
	"Koichi Tanaka",
	"Kurt Wüthrich",
	"William S. Knowles",
	"Ryoji Noyori",
	"K. Barry Sharpless",
	"Alan J. Heeger",
	"Alan G. MacDiarmid",
	"Hideki Shirakawa",
	"Ahmed H. Zewail",
	"Walter Kohn",
	"John A. Pople",
	"Paul D. Boyer",
	"John E. Walker",
	"Jens C. Skou",
	"Robert F. Curl Jr.",
	"Sir Harold W. Kroto",
	"Richard E. Smalley",
	"Paul J. Crutzen",
	"Mario J. Molina",
	"F. Sherwood Rowland",
	"George A. Olah",
	"Kary B. Mullis",
	"Michael Smith",
	"Rudolph A. Marcus",
	"Richard R. Ernst",
	"Elias James Corey",
	"Sidney Altman",
	"Thomas R. Cech",
	"Johann Deisenhofer",
	"Robert Huber",
	"Hartmut Michel",
	"Donald J. Cram",
	"Jean-Marie Lehn",
	"Charles J. Pedersen",
	"Dudley R. Herschbach",
	"Yuan T. Lee",
	"John C. Polanyi",
	"Herbert A. Hauptman",
	"Jerome Karle",
	"Robert Bruce Merrifield",
	"Henry Taube",
	"Aaron Klug",
	"Kenichi Fukui",
	"Roald Hoffmann",
	"Paul Berg",
	"Walter Gilbert",
	"Frederick Sanger",
	"Herbert C. Brown",
	"Georg Wittig",
	"Peter D. Mitchell",
	"Ilya Prigogine",
	"William N. Lipscomb",
	"John Warcup Cornforth",
	"Vladimir Prelog",
	"Paul J. Flory",
	"Ernst Otto Fischer",
	"Geoffrey Wilkinson",
	"Christian B. Anfinsen",
	"Stanford Moore",
	"William H. Stein",
	"Gerhard Herzberg",
	"Luis F. Leloir",
	"Derek H. R. Barton",
	"Odd Hassel",
	"Lars Onsager",
	"Manfred Eigen",
	"Ronald George Wreyford Norrish",
	"George Porter",
	"Robert S. Mulliken",
	"Robert Burns Woodward",
	"Dorothy Crowfoot Hodgkin",
	"Karl Ziegler",
	"Giulio Natta",
	"Max Ferdinand Perutz",
	"John Cowdery Kendrew",
	"Melvin Calvin",
	"Willard Frank Libby",
	"Jaroslav Heyrovsky",
	"Frederick Sanger",
	"Lord (Alexander R.) Todd",
	"Sir Cyril Norman Hinshelwood",
	"Nikolay Nikolaevich Semenov",
	"Vincent du Vigneaud",
	"Linus Carl Pauling",
	"Hermann Staudinger",
	"Archer John Porter Martin",
	"Richard Laurence Millington Synge",
	"Edwin Mattison McMillan",
	"Glenn Theodore Seaborg",
	"Otto Paul Hermann Diels",
	"Kurt Alder",
	"William Francis Giauque",
	"Arne Wilhelm Kaurin Tiselius",
	"Sir Robert Robinson",
	"James Batcheller Sumner",
	"John Howard Northrop",
	"Wendell Meredith Stanley",
	"Artturi Ilmari Virtanen",
	"Otto Hahn",
	"George de Hevesy",
	"Adolf Friedrich Johann Butenandt",
	"Leopold Ruzicka",
	"Richard Kuhn",
	"Walter Norman Haworth",
	"Paul Karrer",
	"Petrus (Peter) Josephus Wilhelmus Debye",
	"Frédéric Joliot",
	"Irène Joliot-Curie",
	"Harold Clayton Urey",
	"Irving Langmuir",
	"Carl Bosch",
	"Friedrich Bergius",
	"Hans Fischer",
	"Arthur Harden",
	"Hans Karl August Simon von Euler-Chelpin",
	"Adolf Otto Reinhold Windaus",
	"Heinrich Otto Wieland",
	"The (Theodor) Svedberg",
	"Richard Adolf Zsigmondy",
	"Fritz Pregl",
	"Francis William Aston",
	"Frederick Soddy",
	"Walther Hermann Nernst",
	"Fritz Haber",
	"Richard Martin Willstätter",
	"Theodore William Richards",
	"Alfred Werner",
	"Victor Grignard",
	"Paul Sabatier",
	"Marie Curie, née Sklodowska",
	"Otto Wallach",
	"Wilhelm Ostwald",
	"Ernest Rutherford",
	"Eduard Buchner",
	"Henri Moissan",
	"Johann Friedrich Wilhelm Adolf von Baeyer",
	"Sir William Ramsay",
	"Svante August Arrhenius",
	"Hermann Emil Fischer",
	"Jacobus Henricus van 't Hoff",
	"Bruce A. Beutler",
	"Jules A. Hoffmann",
	"Ralph M. Steinman",
	"Robert G. Edwards",
	"Elizabeth H. Blackburn",
	"Carol W. Greider",
	"Jack W. Szostak",
	"Harald zur Hausen",
	"Françoise Barré-Sinoussi",
	"Luc Montagnier",
	"Mario R. Capecchi",
	"Sir Martin J. Evans",
	"Oliver Smithies",
	"Andrew Z. Fire",
	"Craig C. Mello",
	"Barry J. Marshall",
	"J. Robin Warren",
	"Richard Axel",
	"Linda B. Buck",
	"Paul C. Lauterbur",
	"Sir Peter Mansfield",
	"Sydney Brenner",
	"H. Robert Horvitz",
	"John E. Sulston",
	"Leland H. Hartwell",
	"Tim Hunt",
	"Sir Paul M. Nurse",
	"Arvid Carlsson",
	"Paul Greengard",
	"Eric R. Kandel",
	"Günter Blobel",
	"Robert F. Furchgott",
	"Louis J. Ignarro",
	"Ferid Murad",
	"Stanley B. Prusiner",
	"Peter C. Doherty",
	"Rolf M. Zinkernagel",
	"Edward B. Lewis",
	"Christiane Nüsslein-Volhard",
	"Eric F. Wieschaus",
	"Alfred G. Gilman",
	"Martin Rodbell",
	"Richard J. Roberts",
	"Phillip A. Sharp",
	"Edmond H. Fischer",
	"Edwin G. Krebs",
	"Erwin Neher",
	"Bert Sakmann",
	"Joseph E. Murray",
	"E. Donnall Thomas",
	"J. Michael Bishop",
	"Harold E. Varmus",
	"Sir James W. Black",
	"Gertrude B. Elion",
	"George H. Hitchings",
	"Susumu Tonegawa",
	"Stanley Cohen",
	"Rita Levi-Montalcini",
	"Michael S. Brown",
	"Joseph L. Goldstein",
	"Niels K. Jerne",
	"Georges J.F. Köhler",
	"César Milstein",
	"Barbara McClintock",
	"Sune K. Bergström",
	"Bengt I. Samuelsson",
	"John R. Vane",
	"Roger W. Sperry",
	"David H. Hubel",
	"Torsten N. Wiesel",
	"Baruj Benacerraf",
	"Jean Dausset",
	"George D. Snell",
	"Allan M. Cormack",
	"Godfrey N. Hounsfield",
	"Werner Arber",
	"Daniel Nathans",
	"Hamilton O. Smith",
	"Roger Guillemin",
	"Andrew V. Schally",
	"Rosalyn Yalow",
	"Baruch S. Blumberg",
	"D. Carleton Gajdusek",
	"David Baltimore",
	"Renato Dulbecco",
	"Howard Martin Temin",
	"Albert Claude",
	"Christian de Duve",
	"George E. Palade",
	"Karl von Frisch",
	"Konrad Lorenz",
	"Nikolaas Tinbergen",
	"Gerald M. Edelman",
	"Rodney R. Porter",
	"Earl W. Sutherland, Jr.",
	"Sir Bernard Katz",
	"Ulf von Euler",
	"Julius Axelrod",
	"Max Delbrück",
	"Alfred D. Hershey",
	"Salvador E. Luria",
	"Robert W. Holley",
	"Har Gobind Khorana",
	"Marshall W. Nirenberg",
	"Ragnar Granit",
	"Haldan Keffer Hartline",
	"George Wald",
	"Peyton Rous",
	"Charles Brenton Huggins",
	"François Jacob",
	"André Lwoff",
	"Jacques Monod",
	"Konrad Bloch",
	"Feodor Lynen",
	"Sir John Carew Eccles",
	"Alan Lloyd Hodgkin",
	"Andrew Fielding Huxley",
	"Francis Harry Compton Crick",
	"James Dewey Watson",
	"Maurice Hugh Frederick Wilkins",
	"Georg von Békésy",
	"Sir Frank Macfarlane Burnet",
	"Peter Brian Medawar",
	"Severo Ochoa",
	"Arthur Kornberg",
	"George Wells Beadle",
	"Edward Lawrie Tatum",
	"Joshua Lederberg",
	"Daniel Bovet",
	"André Frédéric Cournand",
	"Werner Forssmann",
	"Dickinson W. Richards",
	"Axel Hugo Theodor Theorell",
	"John Franklin Enders",
	"Thomas Huckle Weller",
	"Frederick Chapman Robbins",
	"Hans Adolf Krebs",
	"Fritz Albert Lipmann",
	"Selman Abraham Waksman",
	"Max Theiler",
	"Edward Calvin Kendall",
	"Tadeus Reichstein",
	"Philip Showalter Hench",
	"Walter Rudolf Hess",
	"Antonio Caetano de Abreu Freire Egas Moniz",
	"Paul Hermann Müller",
	"Carl Ferdinand Cori",
	"Gerty Theresa Cori, née Radnitz",
	"Bernardo Alberto Houssay",
	"Hermann Joseph Muller",
	"Sir Alexander Fleming",
	"Ernst Boris Chain",
	"Sir Howard Walter Florey",
	"Joseph Erlanger",
	"Herbert Spencer Gasser",
	"Henrik Carl Peter Dam",
	"Edward Adelbert Doisy",
	"Gerhard Domagk",
	"Corneille Jean François Heymans",
	"Albert von Szent-Györgyi Nagyrápolt",
	"Sir Henry Hallett Dale",
	"Otto Loewi",
	"Hans Spemann",
	"George Hoyt Whipple",
	"George Richards Minot",
	"William Parry Murphy",
	"Thomas Hunt Morgan",
	"Sir Charles Scott Sherrington",
	"Edgar Douglas Adrian",
	"Otto Heinrich Warburg",
	"Karl Landsteiner",
	"Christiaan Eijkman",
	"Sir Frederick Gowland Hopkins",
	"Charles Jules Henri Nicolle",
	"Julius Wagner-Jauregg",
	"Johannes Andreas Grib Fibiger",
	"Willem Einthoven",
	"Frederick Grant Banting",
	"John James Rickard Macleod",
	"Archibald Vivian Hill",
	"Otto Fritz Meyerhof",
	"Schack August Steenberg Krogh",
	"Jules Bordet",
	"Robert Bárány",
	"Charles Robert Richet",
	"Alexis Carrel",
	"Allvar Gullstrand",
	"Albrecht Kossel",
	"Emil Theodor Kocher",
	"Ilya Ilyich Mechnikov",
	"Paul Ehrlich",
	"Charles Louis Alphonse Laveran",
	"Camillo Golgi",
	"Santiago Ramón y Cajal",
	"Robert Koch",
	"Ivan Petrovich Pavlov",
	"Niels Ryberg Finsen",
	"Ronald Ross",
	"Emil Adolf von Behring",
	"Tomas Tranströmer",
	"Mario Vargas Llosa",
	"Herta Müller",
	"Jean-Marie Gustave Le Clézio",
	"Doris Lessing",
	"Orhan Pamuk",
	"Harold Pinter",
	"Elfriede Jelinek",
	"John M. Coetzee",
	"Imre Kertész",
	"Sir Vidiadhar Surajprasad Naipaul",
	"Gao Xingjian",
	"Günter Grass",
	"José Saramago",
	"Dario Fo",
	"Wislawa Szymborska",
	"Seamus Heaney",
	"Kenzaburo Oe",
	"Toni Morrison",
	"Derek Walcott",
	"Nadine Gordimer",
	"Octavio Paz",
	"Camilo José Cela",
	"Naguib Mahfouz",
	"Joseph Brodsky",
	"Wole Soyinka",
	"Claude Simon",
	"Jaroslav Seifert",
	"William Golding",
	"Gabriel García Márquez",
	"Elias Canetti",
	"Czeslaw Milosz",
	"Odysseus Elytis",
	"Isaac Bashevis Singer",
	"Vicente Aleixandre",
	"Saul Bellow",
	"Eugenio Montale",
	"Eyvind Johnson",
	"Harry Martinson",
	"Patrick White",
	"Heinrich Böll",
	"Pablo Neruda",
	"Aleksandr Isayevich Solzhenitsyn",
	"Samuel Beckett",
	"Yasunari Kawabata",
	"Miguel Angel Asturias",
	"Shmuel Yosef Agnon",
	"Nelly Sachs",
	"Mikhail Aleksandrovich Sholokhov",
	"Jean-Paul Sartre",
	"Giorgos Seferis",
	"John Steinbeck",
	"Ivo Andric",
	"Saint-John Perse",
	"Salvatore Quasimodo",
	"Boris Leonidovich Pasternak",
	"Albert Camus",
	"Juan Ramón Jiménez",
	"Halldór Kiljan Laxness",
	"Ernest Miller Hemingway",
	"Sir Winston Leonard Spencer Churchill",
	"François Mauriac",
	"Pär Fabian Lagerkvist",
	"Earl (Bertrand Arthur William) Russell",
	"William Faulkner",
	"Thomas Stearns Eliot",
	"André Paul Guillaume Gide",
	"Hermann Hesse",
	"Gabriela Mistral",
	"Johannes Vilhelm Jensen",
	"Frans Eemil Sillanpää",
	"Pearl Buck",
	"Roger Martin du Gard",
	"Eugene Gladstone O'Neill",
	"Luigi Pirandello",
	"Ivan Alekseyevich Bunin",
	"John Galsworthy",
	"Erik Axel Karlfeldt",
	"Sinclair Lewis",
	"Thomas Mann",
	"Sigrid Undset",
	"Henri Bergson",
	"Grazia Deledda",
	"George Bernard Shaw",
	"Wladyslaw Stanislaw Reymont",
	"William Butler Yeats",
	"Jacinto Benavente",
	"Anatole France",
	"Knut Pedersen Hamsun",
	"Carl Friedrich Georg Spitteler",
	"Karl Adolph Gjellerup",
	"Henrik Pontoppidan",
	"Carl Gustaf Verner von Heidenstam",
	"Romain Rolland",
	"Rabindranath Tagore",
	"Gerhart Johann Robert Hauptmann",
	"Count Maurice (Mooris) Polidore Marie Bernhard Maeterlinck",
	"Paul Johann Ludwig Heyse",
	"Selma Ottilia Lovisa Lagerlöf",
	"Rudolf Christoph Eucken",
	"Rudyard Kipling",
	"Giosuè Carducci",
	"Henryk Sienkiewicz",
	"Frédéric Mistral",
	"José Echegaray y Eizaguirre",
	"Bjørnstjerne Martinus Bjørnson",
	"Christian Matthias Theodor Mommsen",
	"Sully Prudhomme",
	"Ellen Johnson Sirleaf",
	"Leymah Gbowee",
	"Tawakkol Karman",
	"Liu Xiaobo",
	"Barack H. Obama",
	"Martti Ahtisaari",
	"Albert Arnold (Al) Gore Jr.",
	"Muhammad Yunus",
	"Grameen Bank ",
	"Mohamed ElBaradei",
	"Wangari Muta Maathai",
	"Shirin Ebadi",
	"Jimmy Carter",
	"Kofi Annan",
	"Kim Dae-jung",
	"Médecins Sans Frontières ",
	"John Hume",
	"David Trimble",
	"Jody Williams",
	"Carlos Filipe Ximenes Belo",
	"José Ramos-Horta",
	"Joseph Rotblat",
	"Pugwash Conferences on Science and World Affairs ",
	"Yasser Arafat",
	"Shimon Peres",
	"Yitzhak Rabin",
	"Nelson Mandela",
	"Frederik Willem de Klerk",
	"Rigoberta Menchú Tum",
	"Aung San Suu Kyi ",
	"Mikhail Sergeyevich Gorbachev",
	"(The 14th Dalai Lama)  Tenzin Gyatso",
	"United Nations Peacekeeping Forces ",
	"Oscar Arias Sánchez",
	"Elie Wiesel",
	"Desmond Mpilo Tutu",
	"Lech Walesa",
	"Alva Myrdal",
	"Alfonso García Robles",
	"Adolfo Pérez Esquivel",
	"Mother Teresa ",
	"Mohamed Anwar al-Sadat",
	"Menachem Begin",
	"Amnesty International ",
	"Betty Williams",
	"Mairead Corrigan",
	"Andrei Dmitrievich Sakharov",
	"Seán MacBride",
	"Eisaku Sato",
	"Henry A. Kissinger",
	"Le Duc Tho ",
	"Willy Brandt",
	"Norman E. Borlaug",
	"René Cassin",
	"Martin Luther King Jr.",
	"Linus Carl Pauling",
	"Dag Hjalmar Agne Carl Hammarskjöld",
	"Albert John Lutuli",
	"Philip J. Noel-Baker",
	"Georges Pire",
	"Lester Bowles Pearson",
	"George Catlett Marshall",
	"Albert Schweitzer",
	"Léon Jouhaux",
	"Ralph Bunche",
	"Lord (John) Boyd Orr of Brechin",
	"Huisman",
	"John Raleigh Mott",
	"Cordell Hull",
	"(Cecil of Chelwood, Viscount) Lord Edgar Algernon Robert Gascoyne Cecil",
	"Carlos Saavedra Lamas",
	"Carl von Ossietzky",
	"Arthur Henderson",
	"Sir Norman Angell (Ralph Lane)",
	"Jane Addams",
	"Nicholas Murray Butler",
	"Lars Olof Jonathan (Nathan) Söderblom",
	"Frank Billings Kellogg",
	"Ferdinand Buisson",
	"Ludwig Quidde",
	"Aristide Briand",
	"Gustav Stresemann",
	"Sir Austen Chamberlain",
	"Charles Gates Dawes",
	"Fridtjof Nansen",
	"Karl Hjalmar Branting",
	"Christian Lous Lange",
	"Léon Victor Auguste Bourgeois",
	"Thomas Woodrow Wilson",
	"Henri La Fontaine",
	"Elihu Root",
	"Tobias Michael Carel Asser",
	"Alfred Hermann Fried",
	"Auguste Marie François Beernaert",
	"Paul Henri Benjamin Balluet d'Estournelles de Constant, Baron de Constant de",
	"Rebecque",
	"Klas Pontus Arnoldson",
	"Fredrik Bajer",
	"Ernesto Teodoro Moneta",
	"Louis Renault",
	"Theodore Roosevelt",
	"Baroness Bertha Sophie Felicita von Suttner, née Countess Kinsky von Chinic",
	"und Tettau",
	"William Randal Cremer",
	"Élie Ducommun",
	"Charles Albert Gobat",
	"Jean Henry Dunant",
	"Frédéric Passy",
	"Thomas J. Sargent",
	"Christopher A. Sims",
	"Peter A. Diamond",
	"Dale T. Mortensen",
	"Christopher A. Pissarides",
	"Elinor Ostrom",
	"Oliver E. Williamson",
	"Paul Krugman",
	"Leonid Hurwicz",
	"Eric S. Maskin",
	"Roger B. Myerson",
	"Edmund S. Phelps",
	"Robert J. Aumann",
	"Thomas C. Schelling",
	"Finn E. Kydland",
	"Edward C. Prescott",
	"Robert F. Engle III",
	"Clive W.J. Granger",
	"Daniel Kahneman",
	"Vernon L. Smith",
	"George A. Akerlof",
	"A. Michael Spence",
	"Joseph E. Stiglitz",
	"James J. Heckman",
	"Daniel L. McFadden",
	"Robert A. Mundell",
	"Amartya Sen",
	"Robert C. Merton",
	"Myron S. Scholes",
	"James A. Mirrlees",
	"William Vickrey",
	"Robert E. Lucas Jr.",
	"John C. Harsanyi",
	"John F. Nash Jr.",
	"Reinhard Selten",
	"Robert W. Fogel",
	"Douglass C. North",
	"Gary S. Becker",
	"Ronald H. Coase",
	"Harry M. Markowitz",
	"Merton H. Miller",
	"William F. Sharpe",
	"Trygve Haavelmo",
	"Maurice Allais",
	"Robert M. Solow",
	"James M. Buchanan Jr.",
	"Franco Modigliani",
	"Richard Stone",
	"Gerard Debreu",
	"George J. Stigler",
	"James Tobin",
	"Lawrence R. Klein",
	"Theodore W. Schultz",
	"Sir Arthur Lewis",
	"Herbert A. Simon",
	"Bertil Ohlin",
	"James E. Meade",
	"Milton Friedman",
	"Leonid Vitaliyevich Kantorovich",
	"Tjalling C. Koopmans",
	"Gunnar Myrdal",
	"Friedrich August von Hayek",
	"Wassily Leontief",
	"John R. Hicks",
	"Kenneth J. Arrow",
	"Simon Kuznets",
	"Paul A. Samuelson",
	"Ragnar Frisch",
	"Jan Tinbergen", };

    static Random rand = new Random();

    public static String getNextNaam() {
	String result = "";

	while (result.length() < 5) {
	    result = achterName[Math.abs(rand.nextInt() % achterName.length)];
	    if (result.lastIndexOf(" ") > 0) {
		result = result.substring(result.lastIndexOf(" ")).trim();
	    }
	}

	result = result.replaceAll("'", "''");

	return result;
    }

}
