#!/usr/bin/env bash

psql -U $POSTGRES_USER -c "CREATE ROLE $USERNAME LOGIN ENCRYPTED PASSWORD '$PASSWORD' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE;"
psql -U $POSTGRES_USER -c "CREATE DATABASE $USERNAME WITH OWNER = $PASSWORD ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;"
