/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.bronnen;

// Generated 6-jan-2012 16:35:30 by Hibernate Tools 3.2.2.GA

/**
 * Onderzoek generated by hbm2java
 */
public class Onderzoek extends Bron {

    private OnderzoekId id;

    public Onderzoek() {
    }

    public OnderzoekId getId() {
        return this.id;
    }

    public void setId(final OnderzoekId id) {
        this.id = id;
    }

}
