/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.bronnen;

import nl.bzk.brp.testdatageneratie.MetaRepo;
import nl.bzk.brp.testdatageneratie.domain.kern.Dbobject;

// Generated 6-jan-2012 16:35:30 by Hibernate Tools 3.2.2.GA

/**
 * OnderzoekId generated by hbm2java
 */
public class OnderzoekId implements java.io.Serializable {

    private static int currentIndex;

    private int        index = ++currentIndex;

    private int        gegevensAand;
    private int        start;
    private int        eind;

    public OnderzoekId() {
    }

    public int getGegevensAand() {
        return this.gegevensAand;
    }

    public void setGegevensAand(final int gegevensAand) {
        this.gegevensAand = gegevensAand;
    }

    public int getStart() {
        return this.start;
    }

    public void setStart(final int start) {
        this.start = start;
    }

    public int getEind() {
        return this.eind;
    }

    public void setEind(final int eind) {
        this.eind = eind;
    }

    public Dbobject getDbobject() {
        return MetaRepo.getByIndex(Dbobject.class, index);
    }

}
