/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;

/**
 * Certificaat generated by hbm2java
 */
public class Certificaat  implements java.io.Serializable {


     private int id;
     private String subject;
     private BigDecimal serial;
     private String signature;

    public Certificaat() {
    }

    public Certificaat(int id, String subject, BigDecimal serial, String signature) {
       this.id = id;
       this.subject = subject;
       this.serial = serial;
       this.signature = signature;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public BigDecimal getSerial() {
        return this.serial;
    }
    
    public void setSerial(BigDecimal serial) {
        this.serial = serial;
    }
    public String getSignature() {
        return this.signature;
    }
    
    public void setSignature(String signature) {
        this.signature = signature;
    }




}


