/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersinschr generated by hbm2java
 */
public class HisPersinschr extends His {


     private Pers persByVolgendepers;
     private Pers persByPers;
     private Pers persByVorigepers;
     private int datinschr;
     private long versienr;

    public HisPersinschr() {
    }

    public HisPersinschr(Pers pers) {
        this.persByVolgendepers = pers.getPersByVolgendepers();
        this.persByPers = pers;
        this.persByVorigepers = pers.getPersByVorigepers();
        this.datinschr = pers.getDatinschr();
        this.versienr = pers.getVersienr();
    }

    public Pers getPersByVolgendepers() {
        return this.persByVolgendepers;
    }

    public void setPersByVolgendepers(final Pers persByVolgendepers) {
        this.persByVolgendepers = persByVolgendepers;
    }
    public Pers getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(final Pers persByPers) {
        this.persByPers = persByPers;
    }
    public Pers getPersByVorigepers() {
        return this.persByVorigepers;
    }

    public void setPersByVorigepers(final Pers persByVorigepers) {
        this.persByVorigepers = persByVorigepers;
    }
    public int getDatinschr() {
        return this.datinschr;
    }

    public void setDatinschr(final int datinschr) {
        this.datinschr = datinschr;
    }
    public long getVersienr() {
        return this.versienr;
    }

    public void setVersienr(final long versienr) {
        this.versienr = versienr;
    }




}


