/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisRegelsituatie generated by hbm2java
 */
public class HisRegelsituatie extends His {


     private Regeleffect regeleffect;
     private Rdnopschorting rdnopschorting;
     private Regelsituatie regelsituatie;
     private Verantwoordelijke verantwoordelijke;
     private Boolean indopgeschort;
     private boolean indactief;

    public HisRegelsituatie() {
    }

    public Regeleffect getRegeleffect() {
        return this.regeleffect;
    }

    public void setRegeleffect(final Regeleffect regeleffect) {
        this.regeleffect = regeleffect;
    }
    public Rdnopschorting getRdnopschorting() {
        return this.rdnopschorting;
    }

    public void setRdnopschorting(final Rdnopschorting rdnopschorting) {
        this.rdnopschorting = rdnopschorting;
    }
    public Regelsituatie getRegelsituatie() {
        return this.regelsituatie;
    }

    public void setRegelsituatie(final Regelsituatie regelsituatie) {
        this.regelsituatie = regelsituatie;
    }
    public Verantwoordelijke getVerantwoordelijke() {
        return this.verantwoordelijke;
    }

    public void setVerantwoordelijke(final Verantwoordelijke verantwoordelijke) {
        this.verantwoordelijke = verantwoordelijke;
    }
    public Boolean getIndopgeschort() {
        return this.indopgeschort;
    }

    public void setIndopgeschort(final Boolean indopgeschort) {
        this.indopgeschort = indopgeschort;
    }
    public boolean isIndactief() {
        return this.indactief;
    }

    public void setIndactief(final boolean indactief) {
        this.indactief = indactief;
    }




}


