/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Overrule generated by hbm2java
 */
public class Overrule  implements java.io.Serializable {


     private long id;
     private Regel regel;
     private Element element;
     private String melding;

    public Overrule() {
    }

	
    public Overrule(long id, Regel regel) {
        this.id = id;
        this.regel = regel;
    }
    public Overrule(long id, Regel regel, Element element, String melding) {
       this.id = id;
       this.regel = regel;
       this.element = element;
       this.melding = melding;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Regel getRegel() {
        return this.regel;
    }
    
    public void setRegel(Regel regel) {
        this.regel = regel;
    }
    public Element getElement() {
        return this.element;
    }
    
    public void setElement(Element element) {
        this.element = element;
    }
    public String getMelding() {
        return this.melding;
    }
    
    public void setMelding(String melding) {
        this.melding = melding;
    }




}


