delete from Kern.srtnlreisdoc;
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (1, $$..$$, $$Onbekend$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (2, $$BJ$$, $$Identiteitskaart (toeristenkaart) BJ$$ , 19920401 , 19950101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (3, $$EK$$, $$Europese identiteitskaart$$ , 19950101 , 20011001);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (4, $$IA$$, $$Identiteitskaart (toeristenkaart) A$$ , null , 19920101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (5, $$IB$$, $$Identiteitskaart (toeristenkaart) B$$ , null , 19950101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (6, $$IC$$, $$Identiteitskaart (toeristenkaart) C$$ , null , 19920101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (7, $$ID$$, $$Gemeentelijke Identiteitskaart$$ , 19930101 , 19950101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (8, $$KE$$, $$Kaart met paspoortboekje, 64 pag.$$ , 19920101 , 19920101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (9, $$KN$$, $$Kaart met paspoortboekje, 32 pag.$$ , 19920101 , 19920101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (10, $$KZ$$, $$Kaart zonder paspoortboekje$$ , 19920101 , 19920101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (11, $$LP$$, $$Laissez-passer$$ , 19950101 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (12, $$NB$$, $$Nooddocument (model reisdocument vreemdelingen)$$ , 19950101 , 20010401);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (13, $$NI$$, $$Nederlandse identiteitskaart$$ , 20011001 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (14, $$NN$$, $$Noodpaspoort (model nationaal paspoort)$$ , 19950101 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (15, $$NP$$, $$Noodpaspoort$$ , null , 19950101);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (16, $$NV$$, $$Nooddocument (model reisdocument vluchtelingen)$$ , 19950101 , 20010401);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (17, $$PB$$, $$Reisdocument voor vreemdelingen$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (18, $$PD$$, $$Diplomatiek paspoort$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (19, $$PF$$, $$Faciliteitenpaspoort$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (20, $$PN$$, $$Nationaal paspoort$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (21, $$PV$$, $$Reisdocument voor vluchtelingen$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (22, $$PZ$$, $$Dienstpaspoort$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (23, $$R1$$, $$Reisdocument ouder1$$ , 20010201 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (24, $$R2$$, $$Reisdocument ouder2$$ , 20010201 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (25, $$RD$$, $$Reisdocument voogd$$ , null , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (26, $$RM$$, $$Reisdocument moeder$$ , null , 20010201);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (27, $$RV$$, $$Reisdocument vader$$ , null , 20010201);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (28, $$TE$$, $$Tweede paspoort (zakenpaspoort)$$ , 19920401 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (29, $$TN$$, $$Tweede paspoort$$ , 19920401 , null);
insert into Kern.srtnlreisdoc (ID, code, Oms, dataanvgel, dateindegel) values (30, $$ZN$$, $$Nationaal paspoort (zakenpaspoort)$$ , 19920401 , null);
