/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.bronnen;
// Generated 6-jan-2012 16:35:30 by Hibernate Tools 3.2.2.GA



/**
 * GeslachtsnaamId generated by hbm2java
 */
public class GeslachtsnaamId  implements java.io.Serializable {


     private String geslachtsnaam;
     private String geslachtsnaamDiak;

    public GeslachtsnaamId() {
    }

    public GeslachtsnaamId(String geslachtsnaam, String geslachtsnaamDiak) {
       this.geslachtsnaam = geslachtsnaam;
       this.geslachtsnaamDiak = geslachtsnaamDiak;
    }
   
    public String getGeslachtsnaam() {
        return this.geslachtsnaam;
    }
    
    public void setGeslachtsnaam(String geslachtsnaam) {
        this.geslachtsnaam = geslachtsnaam;
    }
    public String getGeslachtsnaamDiak() {
        return this.geslachtsnaamDiak;
    }
    
    public void setGeslachtsnaamDiak(String geslachtsnaamDiak) {
        this.geslachtsnaamDiak = geslachtsnaamDiak;
    }




}


