<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:VraagPL="http://brp.bzk.nl/delivery/bevraging/gba/ws" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  targetNamespace="http://brp.bzk.nl/delivery/bevraging/gba/ws">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="../xsd/ws.xsd" namespace="http://brp.bzk.nl/delivery/bevraging/gba/ws"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="vraagRequest">
        <wsdl:part name="parameters" element="VraagPL:vraagPL"/>
    </wsdl:message>

    <wsdl:message name="vraagResponse">
        <wsdl:part name="parameters" element="VraagPL:vraagResponse"/>
    </wsdl:message>

    <wsdl:portType name="VraagPLService">
        <wsdl:operation name="vraagPL">
            <wsdl:input name="vraagRequest" message="VraagPL:vraagRequest"/>
            <wsdl:output name="vraagResponse" message="VraagPL:vraagResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="VraagPLServiceSoapBinding" type="VraagPL:VraagPLService">
        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="vraagPL">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="vraagRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="vraagResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="VraagPLServiceClient">
        <wsdl:port name="VraagPLService" binding="VraagPL:VraagPLServiceSoapBinding">
            <wsdlsoap:address location="http://localhost:8080/services/vraagplservice"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
