-- Deze script mag alleen voor unittest gebruikt worden, het is een fix om te voorkomen dat de testdata.xml id in botsing komt.

BEGIN;

SELECT SETVAL('lev.seq_abonnement', (select 90000+ coalesce(max(id),0)  FROM "lev"."abonnement"), true);
SELECT SETVAL('lev.seq_abonnementgegevenselement', (select 90000+ coalesce(max(id),0)  FROM "lev"."abonnementgegevenselement"), true);
SELECT SETVAL('lev.seq_abonnementsrtber', (select 90000+ coalesce(max(id),0)  FROM "lev"."abonnementsrtber"), true);
SELECT SETVAL('kern.seq_actie', (select 90000+ coalesce(max(id),0)  FROM "kern"."actie"), true);
SELECT SETVAL('autaut.seq_authenticatiemiddel', (select 90000+ coalesce(max(id),0)  FROM "autaut"."authenticatiemiddel"), true);
SELECT SETVAL('autaut.seq_autorisatiebesluit', (select 90000+ coalesce(max(id),0)  FROM "autaut"."autorisatiebesluit"), true);
SELECT SETVAL('ber.seq_ber', (select 90000+ coalesce(max(id),0)  FROM "ber"."ber"), true);
SELECT SETVAL('kern.seq_betr', (select 90000+ coalesce(max(id),0)  FROM "kern"."betr"), true);
SELECT SETVAL('autaut.seq_bijhautorisatie', (select 90000+ coalesce(max(id),0)  FROM "autaut"."bijhautorisatie"), true);
SELECT SETVAL('autaut.seq_bijhsituatie', (select 90000+ coalesce(max(id),0)  FROM "autaut"."bijhsituatie"), true);
-- SELECT SETVAL('kern.seq_bron', (select 90000+ coalesce(max(id),0)  FROM "kern"."bron"), true);
SELECT SETVAL('autaut.seq_certificaat', (select 90000+ coalesce(max(id),0)  FROM "autaut"."certificaat"), true);
SELECT SETVAL('kern.seq_doc', (select 90000+ coalesce(max(id),0)  FROM "kern"."doc"), true);
SELECT SETVAL('autaut.seq_doelbinding', (select 90000+ coalesce(max(id),0)  FROM "autaut"."doelbinding"), true);
SELECT SETVAL('autaut.seq_doelbindinggegevenselement', (select 90000+ coalesce(max(id),0)  FROM "autaut"."doelbindinggegevenselement"), true);
SELECT SETVAL('kern.seq_gegeveninonderzoek', (select 90000+ coalesce(max(id),0)  FROM "kern"."gegeveninonderzoek"), true);
SELECT SETVAL('lev.seq_his_abonnement', (select 90000+ coalesce(max(id),0)  FROM "lev"."his_abonnement"), true);
SELECT SETVAL('lev.seq_his_abonnementsrtber', (select 90000+ coalesce(max(id),0)  FROM "lev"."his_abonnementsrtber"), true);
SELECT SETVAL('autaut.seq_his_authenticatiemiddel', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_authenticatiemiddel"), true);
SELECT SETVAL('autaut.seq_his_autorisatiebesluit', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_autorisatiebesluit"), true);
SELECT SETVAL('autaut.seq_his_autorisatiebesluitbijhau', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_autorisatiebesluitbijhau"), true);
SELECT SETVAL('kern.seq_his_ouderouderschap', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_ouderouderschap"), true);
SELECT SETVAL('kern.seq_his_ouderouderlijkgezag', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_ouderouderlijkgezag"), true);
SELECT SETVAL('autaut.seq_his_bijhautorisatie', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_bijhautorisatie"), true);
SELECT SETVAL('autaut.seq_his_bijhsituatie', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_bijhsituatie"), true);
SELECT SETVAL('kern.seq_his_doc', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_doc"), true);
SELECT SETVAL('autaut.seq_his_doelbinding', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_doelbinding"), true);
SELECT SETVAL('kern.seq_his_partijgem', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_partijgem"), true);
SELECT SETVAL('kern.seq_his_multirealiteitregel', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_multirealiteitregel"), true);
SELECT SETVAL('kern.seq_his_onderzoek', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_onderzoek"), true);
SELECT SETVAL('kern.seq_his_partij', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_partij"), true);
SELECT SETVAL('kern.seq_his_persaanschr', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persaanschr"), true);
SELECT SETVAL('kern.seq_his_persadres', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persadres"), true);
SELECT SETVAL('kern.seq_his_persbijhgem', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persbijhgem"), true);
SELECT SETVAL('kern.seq_his_persbijhaard', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persbijhaard"), true);
SELECT SETVAL('kern.seq_his_perseuverkiezingen', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_perseuverkiezingen"), true);
SELECT SETVAL('kern.seq_his_persgeboorte', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persgeboorte"), true);
SELECT SETVAL('kern.seq_his_persgeslachtsaand', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persgeslachtsaand"), true);
SELECT SETVAL('kern.seq_his_persgeslnaamcomp', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persgeslnaamcomp"), true);
SELECT SETVAL('kern.seq_his_persids', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persids"), true);
SELECT SETVAL('kern.seq_his_persimmigratie', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persimmigratie"), true);
SELECT SETVAL('kern.seq_his_persindicatie', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persindicatie"), true);
SELECT SETVAL('kern.seq_his_persinschr', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persinschr"), true);
SELECT SETVAL('kern.seq_his_persnation', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persnation"), true);
SELECT SETVAL('kern.seq_his_persopschorting', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persopschorting"), true);
SELECT SETVAL('kern.seq_his_persoverlijden', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persoverlijden"), true);
SELECT SETVAL('kern.seq_his_perspk', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_perspk"), true);
SELECT SETVAL('kern.seq_his_persreisdoc', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persreisdoc"), true);
SELECT SETVAL('kern.seq_his_perssamengesteldenaam', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_perssamengesteldenaam"), true);
SELECT SETVAL('kern.seq_his_persuitslnlkiesr', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persuitslnlkiesr"), true);
-- SELECT SETVAL('kern.seq_his_persverblijfsr', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persverblijfsr"), true);
SELECT SETVAL('kern.seq_his_persverificatie', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persverificatie"), true);
SELECT SETVAL('kern.seq_his_persvoornaam', (select 90000+ coalesce(max(id),0)  FROM "kern"."his_persvoornaam"), true);
SELECT SETVAL('brm.seq_his_regelsituatie', (select 90000+ coalesce(max(id),0)  FROM "brm"."his_regelsituatie"), true);
SELECT SETVAL('autaut.seq_his_uitgeslotene', (select 90000+ coalesce(max(id),0)  FROM "autaut"."his_uitgeslotene"), true);
SELECT SETVAL('lev.seq_lev', (select 90000+ coalesce(max(id),0)  FROM "lev"."lev"), true);
SELECT SETVAL('lev.seq_levcommunicatie', (select 90000+ coalesce(max(id),0)  FROM "lev"."levcommunicatie"), true);
SELECT SETVAL('lev.seq_levpers', (select 90000+ coalesce(max(id),0)  FROM "lev"."levpers"), true);
SELECT SETVAL('kern.seq_multirealiteitregel', (select 90000+ coalesce(max(id),0)  FROM "kern"."multirealiteitregel"), true);
SELECT SETVAL('kern.seq_onderzoek', (select 90000+ coalesce(max(id),0)  FROM "kern"."onderzoek"), true);
SELECT SETVAL('kern.seq_partij', (select 90000+ coalesce(max(id),0)  FROM "kern"."partij"), true);
SELECT SETVAL('kern.seq_partijrol', (select 90000+ coalesce(max(id),0)  FROM "kern"."partijrol"), true);
SELECT SETVAL('kern.seq_pers', (select 90000+ coalesce(max(id),0)  FROM "kern"."pers"), true);
SELECT SETVAL('kern.seq_persadres', (select 90000+ coalesce(max(id),0)  FROM "kern"."persadres"), true);
SELECT SETVAL('kern.seq_persgeslnaamcomp', (select 90000+ coalesce(max(id),0)  FROM "kern"."persgeslnaamcomp"), true);
SELECT SETVAL('kern.seq_persindicatie', (select 90000+ coalesce(max(id),0)  FROM "kern"."persindicatie"), true);
SELECT SETVAL('kern.seq_persnation', (select 90000+ coalesce(max(id),0)  FROM "kern"."persnation"), true);
SELECT SETVAL('kern.seq_persreisdoc', (select 90000+ coalesce(max(id),0)  FROM "kern"."persreisdoc"), true);
SELECT SETVAL('kern.seq_persverificatie', (select 90000+ coalesce(max(id),0)  FROM "kern"."persverificatie"), true);
SELECT SETVAL('kern.seq_persvoornaam', (select 90000+ coalesce(max(id),0)  FROM "kern"."persvoornaam"), true);
SELECT SETVAL('brm.seq_regelsituatie', (select 90000+ coalesce(max(id),0)  FROM "brm"."regelsituatie"), true);
SELECT SETVAL('kern.seq_relatie', (select 90000+ coalesce(max(id),0)  FROM "kern"."relatie"), true);
SELECT SETVAL('kern.seq_sector', (select 90000+ coalesce(max(id),0)  FROM "kern"."sector"), true);
SELECT SETVAL('autaut.seq_uitgeslotene', (select 90000+ coalesce(max(id),0)  FROM "autaut"."uitgeslotene"), true);

COMMIT;