
== Algemeen

=== Waarom een DSL?
Ten tijde van het maken ervan was het gebruikelijk om een persoon te beschrijven door een Excel bestand
te maken die de database tabellen beschrijft. Deze werkwijze zorgt ervoor
dat het aanmaken van personen foutgevoellig is, veel tijd kost, het niet inzichtelijk is wat de
toestand van een persoon is en dat het maken dus geen pretje is.

=== Wat is de DSL
De Persoon DSL is een in http://groovy-lang.org[Groovy] geschreven _Domain Specific Language_.
Door de expressiviteit en dynamische aard van Groovy ziet een persoonsbeschrijving er bijna uit
als een tekstuele beschijving.

De DSL gebruikt de `PersoonHisVolledigBuilder` om zorgenloos personen te kunnen maken
waarvan de historie-patronen correct verlopen en waarbij afgeleide groepen niet
met de hand hoeven worden vastgelegd. In wezen doet de DSL wat de bijhouding doet:
een persoon met groepen maken. Echter de DSL werkt zonder bedrijfsregels, wat de mogelijkheid
open laat om specifieke testdata te maken.

De DSL is op twee manieren te gebruiken. Ten eerste is de DSL losstaand te gebruiken, dus
voor het maken van een 'basisset' personen die gebruikt kunnen worden bij het testen
van de BRP Software. Omdat de DSL beschrijvend is, kan aan de beschijvingen van
de personen snel worden gezien welke persoon voor een testsituatie geschikt is.
De DSL is ook te gebruiken vanuit de https://www.modernodam.nl/ci/view/BRP/job/BRP%20Alles%20Incrementeel/ws/trunk/art/art-framework/funqmachine/target/generated-docs/handleiding.html[FunqMachinator].
In een testscenario is het mogelijk om nog extra gebeurtenissen aan een persoon toe
te voegen, voordat deze wordt gebruikt in de test.
