/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisOnderzoek generated by hbm2java
 */
public class HisOnderzoek extends His {


     private Onderzoek onderzoek;
     private Integer datbegin;
     private Integer dateinde;
     private String oms;

    public HisOnderzoek() {
    }

    public HisOnderzoek(Onderzoek onderzoekParam) {
        this.onderzoek = onderzoekParam;
        this.datbegin = onderzoekParam.getDatbegin();
        this.dateinde = onderzoekParam.getDateinde();
        this.oms = onderzoekParam.getOms();
    }

    public Onderzoek getOnderzoek() {
        return this.onderzoek;
    }

    public void setOnderzoek(final Onderzoek onderzoek) {
        this.onderzoek = onderzoek;
    }
    public Integer getDatbegin() {
        return this.datbegin;
    }

    public void setDatbegin(final Integer datbegin) {
        this.datbegin = datbegin;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }

    public void setDateinde(final Integer dateinde) {
        this.dateinde = dateinde;
    }
    public String getOms() {
        return this.oms;
    }

    public void setOms(final String oms) {
        this.oms = oms;
    }




}


