#!/usr/bin/env bash

psql -U $POSTGRES_USER -c "CREATE ROLE brp LOGIN ENCRYPTED PASSWORD 'brp' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE;"
psql -U $POSTGRES_USER -c "CREATE DATABASE \"brp\" WITH OWNER = brp ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;"
