
=== Afnemerindicaties
Afnemers mogen een indicatie op een persoon plaatsen, om aan te geven
dat zij in deze persoon zijn geinteresseerd. In mag alleen indien de afnemer
een correct abonnement heeft, met de dienst *Onderhouden afnemerindicatie*.

==== Afnemerindicatie plaatsen
Een indicatie wordt geplaatst voor een partij en abonnement (dat de dienst *Onderhouden afnemerindicatie* moet hebben).
Optioneel worden extra waardes bij de indicatie opgenomen:

[source,groovy]
.Afnemerindicatie plaatsen
----
afnemerindicaties {
    plaatsVoor(afnemer: 36101, abonnement: 'abonnementnaam') {
        datumAanvangMaterielePeriode '2000/02/02' <1>
        eindeVolgen '2010/12/31' <2>
    }
}
----
<1> Optioneel, beperking van de (hoeveelheid) historie die een afnemer wil ontvangen
<2> Optioneel, moment waarna een afnemer geen berichten meer ontvangt over de persoon

==== Afnemerindicatie verwijderen
Een geregistreerde indicatie volledige verstrekkingsbeperking kan door een afnemer
ook weer worden verwijderd. Hiervoor zijn ook partij en abonnement nodig.

[source,groovy]
.Volledige verstrekkingsbeperking verwijderen
----
afnemerindicaties {
    verwijderVan(afnemer: 'Belastingdienst BV', abonnement: 'abonnementnaam')
}
----
