/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Abonnementgegevenselement generated by hbm2java
 */
public class Abonnementgegevenselement  implements java.io.Serializable {


     private int id;
     private Abonnement abonnement;
     private Dbobject dbobject;

    public Abonnementgegevenselement() {
    }

    public Abonnementgegevenselement(int id, Abonnement abonnement, Dbobject dbobject) {
       this.id = id;
       this.abonnement = abonnement;
       this.dbobject = dbobject;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Abonnement getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(Abonnement abonnement) {
        this.abonnement = abonnement;
    }
    public Dbobject getDbobject() {
        return this.dbobject;
    }
    
    public void setDbobject(Dbobject dbobject) {
        this.dbobject = dbobject;
    }




}


