/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Partijrol generated by hbm2java
 */
public class Partijrol  implements java.io.Serializable {


     private int id;
     private Partij partij;
     private Rol rol;
     private String partijrolstatushis;

    public Partijrol() {
    }

    public Partijrol(int id, Partij partij, Rol rol, String partijrolstatushis) {
       this.id = id;
       this.partij = partij;
       this.rol = rol;
       this.partijrolstatushis = partijrolstatushis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Partij getPartij() {
        return this.partij;
    }
    
    public void setPartij(Partij partij) {
        this.partij = partij;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getPartijrolstatushis() {
        return this.partijrolstatushis;
    }
    
    public void setPartijrolstatushis(String partijrolstatushis) {
        this.partijrolstatushis = partijrolstatushis;
    }




}


