/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.brp;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * BrpPers generated by hbm2java
 */
public class BrpPers  implements java.io.Serializable {


     private Integer id;
     private Integer setNr;
     private Integer logischPersId;
     private Integer bsn;

    public BrpPers() {
    }

	
    public BrpPers(Integer id) {
        this.id = id;
    }
    public BrpPers(Integer id, Integer setNr, Integer logischPersId, Integer bsn) {
       this.id = id;
       this.setNr = setNr;
       this.logischPersId = logischPersId;
       this.bsn = bsn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getSetNr() {
        return this.setNr;
    }
    
    public void setSetNr(Integer setNr) {
        this.setNr = setNr;
    }
    public Integer getLogischPersId() {
        return this.logischPersId;
    }
    
    public void setLogischPersId(Integer logischPersId) {
        this.logischPersId = logischPersId;
    }
    public Integer getBsn() {
        return this.bsn;
    }
    
    public void setBsn(Integer bsn) {
        this.bsn = bsn;
    }




}


