// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.lev;

import java.util.List;
import nl.bzk.brp.model.data.lev.Srtabonnement;
import nl.bzk.brp.model.data.lev.SrtabonnementDataOnDemand;
import nl.bzk.brp.model.data.lev.SrtabonnementIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SrtabonnementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SrtabonnementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SrtabonnementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SrtabonnementIntegrationTest: @Transactional;
    
    @Autowired
    private SrtabonnementDataOnDemand SrtabonnementIntegrationTest.dod;
    
    @Test
    public void SrtabonnementIntegrationTest.testCountSrtabonnements() {
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", dod.getRandomSrtabonnement());
        long count = Srtabonnement.countSrtabonnements();
        Assert.assertTrue("Counter for 'Srtabonnement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SrtabonnementIntegrationTest.testFindSrtabonnement() {
        Srtabonnement obj = dod.getRandomSrtabonnement();
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to provide an identifier", id);
        obj = Srtabonnement.findSrtabonnement(id);
        Assert.assertNotNull("Find method for 'Srtabonnement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Srtabonnement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SrtabonnementIntegrationTest.testFindAllSrtabonnements() {
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", dod.getRandomSrtabonnement());
        long count = Srtabonnement.countSrtabonnements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Srtabonnement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Srtabonnement> result = Srtabonnement.findAllSrtabonnements();
        Assert.assertNotNull("Find all method for 'Srtabonnement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Srtabonnement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SrtabonnementIntegrationTest.testFindSrtabonnementEntries() {
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", dod.getRandomSrtabonnement());
        long count = Srtabonnement.countSrtabonnements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Srtabonnement> result = Srtabonnement.findSrtabonnementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Srtabonnement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Srtabonnement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SrtabonnementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", dod.getRandomSrtabonnement());
        Srtabonnement obj = dod.getNewTransientSrtabonnement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Srtabonnement' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Srtabonnement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SrtabonnementIntegrationTest.testRemove() {
        Srtabonnement obj = dod.getRandomSrtabonnement();
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtabonnement' failed to provide an identifier", id);
        obj = Srtabonnement.findSrtabonnement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Srtabonnement' with identifier '" + id + "'", Srtabonnement.findSrtabonnement(id));
    }
    
}
