--------------------------------------------------------------------------------
-- PostgreSQL SQL bestand voor Basisregistratie Personen (BRP) om alle 
-- constraints toe te voegen.
--------------------------------------------------------------------------------
--
-- Gegenereerd via volgende query, toegepast op BRP.sql:
-- SELECT 'ALTER TABLE "'||nspname||'"."'||relname||'" ADD CONSTRAINT "'||conname||'" '||
-- pg_get_constraintdef(pg_constraint.oid)||';'
-- FROM pg_constraint
-- INNER JOIN pg_class ON conrelid=pg_class.oid
-- INNER JOIN pg_namespace ON pg_namespace.oid=pg_class.relnamespace
-- ORDER BY CASE WHEN contype='f' THEN 0 ELSE 1 END DESC,contype DESC,nspname DESC,relname DESC,conname DESC;
-- 

ALTER TABLE "lev"."srtlev" ADD CONSTRAINT "br4830" UNIQUE (naam);
ALTER TABLE "lev"."srtabonnement" ADD CONSTRAINT "br4994" UNIQUE (naam);
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "br4851" UNIQUE (lev, pers);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "br4849" UNIQUE (lev, uitgaandber);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "br5606" UNIQUE (abonnementsrtber, tsreg);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "br4958" UNIQUE (abonnement, tsreg);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "br5608" UNIQUE (abonnement, srtber);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "br4986" UNIQUE (abonnement, gegevenselement);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "br4984" UNIQUE (doelbinding, srtabonnement);
ALTER TABLE "kern"."wijzegebruikgeslnaam" ADD CONSTRAINT "br4454" UNIQUE (naam);
ALTER TABLE "kern"."wijzegebruikgeslnaam" ADD CONSTRAINT "br4453" UNIQUE (code);
ALTER TABLE "kern"."verdrag" ADD CONSTRAINT "br4475" UNIQUE (oms);
ALTER TABLE "kern"."verblijfsr" ADD CONSTRAINT "br4442" UNIQUE (oms);
ALTER TABLE "kern"."verantwoordelijke" ADD CONSTRAINT "br4445" UNIQUE (code);
ALTER TABLE "kern"."verantwoordelijke" ADD CONSTRAINT "br4444" UNIQUE (naam);
ALTER TABLE "kern"."srtverificatie" ADD CONSTRAINT "br4473" UNIQUE (naam);
ALTER TABLE "kern"."srtrelatie" ADD CONSTRAINT "br4427" UNIQUE (code);
ALTER TABLE "kern"."srtrelatie" ADD CONSTRAINT "br4426" UNIQUE (naam);
ALTER TABLE "kern"."srtpers" ADD CONSTRAINT "br4487" UNIQUE (naam);
ALTER TABLE "kern"."srtpers" ADD CONSTRAINT "br4486" UNIQUE (code);
ALTER TABLE "kern"."srtnlreisdoc" ADD CONSTRAINT "br4465" UNIQUE (oms);
ALTER TABLE "kern"."srtnlreisdoc" ADD CONSTRAINT "br4464" UNIQUE (code);
ALTER TABLE "kern"."srtmultirealiteitregel" ADD CONSTRAINT "br4490" UNIQUE (naam);
ALTER TABLE "kern"."srtindicatie" ADD CONSTRAINT "br4448" UNIQUE (naam);
ALTER TABLE "kern"."srtelement" ADD CONSTRAINT "br4458" UNIQUE (naam);
ALTER TABLE "kern"."srtdoc" ADD CONSTRAINT "br4420" UNIQUE (naam);
ALTER TABLE "kern"."srtbetr" ADD CONSTRAINT "br4478" UNIQUE (naam);
ALTER TABLE "kern"."srtbetr" ADD CONSTRAINT "br4477" UNIQUE (code);
ALTER TABLE "kern"."srtactie" ADD CONSTRAINT "br4402" UNIQUE (naam);
ALTER TABLE "kern"."rol" ADD CONSTRAINT "br4492" UNIQUE (naam);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "br6052" UNIQUE (oms);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "br6051" UNIQUE (specificatie);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "br6050" UNIQUE (code);
ALTER TABLE "kern"."rdnwijzadres" ADD CONSTRAINT "br4462" UNIQUE (naam);
ALTER TABLE "kern"."rdnwijzadres" ADD CONSTRAINT "br4461" UNIQUE (code);
ALTER TABLE "kern"."rdnvervallenreisdoc" ADD CONSTRAINT "br4471" UNIQUE (naam);
ALTER TABLE "kern"."rdnvervallenreisdoc" ADD CONSTRAINT "br4470" UNIQUE (code);
ALTER TABLE "kern"."rdnverliesnlnation" ADD CONSTRAINT "br4433" UNIQUE (code);
ALTER TABLE "kern"."rdnverknlnation" ADD CONSTRAINT "br6264" UNIQUE (code);
ALTER TABLE "kern"."rdnverknlnation" ADD CONSTRAINT "br4431" UNIQUE (oms);
ALTER TABLE "kern"."rdnopschorting" ADD CONSTRAINT "br4451" UNIQUE (naam);
ALTER TABLE "kern"."rdnopschorting" ADD CONSTRAINT "br4450" UNIQUE (code);
ALTER TABLE "kern"."rdnbeeindrelatie" ADD CONSTRAINT "br4429" UNIQUE (oms);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "br4409" UNIQUE (naamvrouwelijk);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "br4408" UNIQUE (naammannelijk);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "br4407" UNIQUE (code);
ALTER TABLE "kern"."plaats" ADD CONSTRAINT "br4398" UNIQUE (code);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "br4394" UNIQUE (pers, volgnr);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "br6138" UNIQUE (onderzoek, pers);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "br4415" UNIQUE (pers, nation);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "br4456" UNIQUE (pers, srt);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "br4392" UNIQUE (pers, volgnr);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "br4688" UNIQUE (partij, rol);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "br4418" UNIQUE (naam);
ALTER TABLE "kern"."nation" ADD CONSTRAINT "br4405" UNIQUE (naam);
ALTER TABLE "kern"."land" ADD CONSTRAINT "br4400" UNIQUE (naam);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "br4389" UNIQUE (relatie, tsreg);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "br4368" UNIQUE (persvoornaam, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "br4358" UNIQUE (persverificatie, tsreg);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "br4170" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "br4178" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "br4114" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "br4351" UNIQUE (persreisdoc, tsreg);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "br4224" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "br4157" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "br4204" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "br4335" UNIQUE (persnation, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "br4248" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "br4324" UNIQUE (persindicatie, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "br4235" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "br4087" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "br4314" UNIQUE (persgeslnaamcomp, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "br4097" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "br4144" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "br4187" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "br4197" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "br4216" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "br6073" UNIQUE (persadres, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "br4131" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "br6122" UNIQUE (partij, tsreg);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "br4628" UNIQUE (partij, tsreg);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "br4076" UNIQUE (onderzoek, tsreg);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "br5477" UNIQUE (multirealiteitregel, tsreg);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "br4052" UNIQUE (doc, tsreg);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "br4032" UNIQUE (betr, tsreg, dataanvgel);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "br4042" UNIQUE (betr, tsreg, dataanvgel);
ALTER TABLE "kern"."geslachtsaand" ADD CONSTRAINT "br4484" UNIQUE (naam);
ALTER TABLE "kern"."geslachtsaand" ADD CONSTRAINT "br4483" UNIQUE (code);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "br4480" UNIQUE (onderzoek, srtgegeven);
ALTER TABLE "kern"."functieadres" ADD CONSTRAINT "br4437" UNIQUE (code);
ALTER TABLE "kern"."functieadres" ADD CONSTRAINT "br4436" UNIQUE (naam);
ALTER TABLE "kern"."element" ADD CONSTRAINT "br4423" UNIQUE (srt, naam, ouder);
ALTER TABLE "kern"."categoriesrtdoc" ADD CONSTRAINT "br5986" UNIQUE (oms);
ALTER TABLE "kern"."categoriesrtdoc" ADD CONSTRAINT "br5985" UNIQUE (naam);
ALTER TABLE "kern"."categoriesrtactie" ADD CONSTRAINT "br5983" UNIQUE (oms);
ALTER TABLE "kern"."categoriesrtactie" ADD CONSTRAINT "br5982" UNIQUE (naam);
ALTER TABLE "kern"."categoriepersonen" ADD CONSTRAINT "br6170" UNIQUE (naam);
ALTER TABLE "kern"."bron" ADD CONSTRAINT "br4481" UNIQUE (actie, doc);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "br6105" UNIQUE (relatie, pers);
ALTER TABLE "kern"."autvanafgiftereisdoc" ADD CONSTRAINT "br4468" UNIQUE (oms);
ALTER TABLE "kern"."autvanafgiftereisdoc" ADD CONSTRAINT "br4467" UNIQUE (code);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "br4413" UNIQUE (naamvrouwelijk);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "br4412" UNIQUE (code);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "br4411" UNIQUE (naammannelijk);
ALTER TABLE "kern"."aangadresh" ADD CONSTRAINT "br4440" UNIQUE (code);
ALTER TABLE "kern"."aangadresh" ADD CONSTRAINT "br4439" UNIQUE (naam);
ALTER TABLE "brm"."srtregel" ADD CONSTRAINT "br5975" UNIQUE (oms);
ALTER TABLE "brm"."srtregel" ADD CONSTRAINT "br5974" UNIQUE (naam);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "br6062" UNIQUE (regel, srtber);
ALTER TABLE "brm"."regeleffect" ADD CONSTRAINT "br5980" UNIQUE (oms);
ALTER TABLE "brm"."regeleffect" ADD CONSTRAINT "br5979" UNIQUE (naam);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "br5972" UNIQUE (regelsituatie, tsreg);
ALTER TABLE "ber"."verwerkingsresultaat" ADD CONSTRAINT "br6323" UNIQUE (code);
ALTER TABLE "ber"."srtmelding" ADD CONSTRAINT "br6318" UNIQUE (code);
ALTER TABLE "ber"."srtber" ADD CONSTRAINT "br5028" UNIQUE (naam);
ALTER TABLE "ber"."bijhresultaat" ADD CONSTRAINT "br6325" UNIQUE (code);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "br5792" UNIQUE (bijhautorisatie, uitgeslotenpartij);
ALTER TABLE "autaut"."srtbevoegdheid" ADD CONSTRAINT "br5751" UNIQUE (naam);
ALTER TABLE "autaut"."srtautorisatiebesluit" ADD CONSTRAINT "br4989" UNIQUE (naam);
ALTER TABLE "autaut"."srtautorisatiebesluit" ADD CONSTRAINT "br4988" UNIQUE (oms);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "br5035" UNIQUE (code);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "br4992" UNIQUE (oms);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "br4991" UNIQUE (naam);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "br5789" UNIQUE (uitgeslotene, tsreg);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "br4977" UNIQUE (doelbinding, tsreg, dataanvgel);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "br5745" UNIQUE (bijhsituatie, tsreg);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "br5739" UNIQUE (bijhautorisatie, tsreg);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "br5729" UNIQUE (autorisatiebesluit, tsreg);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "br4965" UNIQUE (autorisatiebesluit, tsreg);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "br4687" UNIQUE (authenticatiemiddel, tsreg);
ALTER TABLE "autaut"."functie" ADD CONSTRAINT "br4726" UNIQUE (naam);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "br4982" UNIQUE (doelbinding, gegevenselement);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "br4980" UNIQUE (geautoriseerde, levsautorisatiebesluit);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "br5037" UNIQUE (signature);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "br4728" UNIQUE (subject, serial);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "br5749" UNIQUE (bijhautorisatie, categoriesrtactie, srtactie, categoriesrtdoc, srtdoc);
ALTER TABLE "lev"."srtlev" ADD CONSTRAINT "br4829" PRIMARY KEY (id);
ALTER TABLE "lev"."srtabonnement" ADD CONSTRAINT "br4993" PRIMARY KEY (id);
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "br4850" PRIMARY KEY (id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "br4848" PRIMARY KEY (id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "br4828" PRIMARY KEY (id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "br5611" PRIMARY KEY (id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "br4997" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "br5607" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "br4985" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "br4983" PRIMARY KEY (id);
ALTER TABLE "kern"."wijzegebruikgeslnaam" ADD CONSTRAINT "br4452" PRIMARY KEY (id);
ALTER TABLE "kern"."verdrag" ADD CONSTRAINT "br4474" PRIMARY KEY (id);
ALTER TABLE "kern"."verblijfsr" ADD CONSTRAINT "br4441" PRIMARY KEY (id);
ALTER TABLE "kern"."verantwoordelijke" ADD CONSTRAINT "br4443" PRIMARY KEY (id);
ALTER TABLE "kern"."srtverificatie" ADD CONSTRAINT "br4472" PRIMARY KEY (id);
ALTER TABLE "kern"."srtrelatie" ADD CONSTRAINT "br4425" PRIMARY KEY (id);
ALTER TABLE "kern"."srtpers" ADD CONSTRAINT "br4485" PRIMARY KEY (id);
ALTER TABLE "kern"."srtpartij" ADD CONSTRAINT "br4493" PRIMARY KEY (id);
ALTER TABLE "kern"."srtnlreisdoc" ADD CONSTRAINT "br4463" PRIMARY KEY (id);
ALTER TABLE "kern"."srtmultirealiteitregel" ADD CONSTRAINT "br4489" PRIMARY KEY (id);
ALTER TABLE "kern"."srtindicatie" ADD CONSTRAINT "br4447" PRIMARY KEY (id);
ALTER TABLE "kern"."srtelement" ADD CONSTRAINT "br4457" PRIMARY KEY (id);
ALTER TABLE "kern"."srtdoc" ADD CONSTRAINT "br4419" PRIMARY KEY (id);
ALTER TABLE "kern"."srtdbobject" ADD CONSTRAINT "br5660" PRIMARY KEY (id);
ALTER TABLE "kern"."srtbetr" ADD CONSTRAINT "br4476" PRIMARY KEY (id);
ALTER TABLE "kern"."srtactie" ADD CONSTRAINT "br4401" PRIMARY KEY (id);
ALTER TABLE "kern"."sector" ADD CONSTRAINT "br4494" PRIMARY KEY (id);
ALTER TABLE "kern"."rol" ADD CONSTRAINT "br4491" PRIMARY KEY (id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "br4424" PRIMARY KEY (id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "br6158" PRIMARY KEY (id);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "br5811" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnwijzadres" ADD CONSTRAINT "br4460" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnvervallenreisdoc" ADD CONSTRAINT "br4469" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnverliesnlnation" ADD CONSTRAINT "br4432" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnverknlnation" ADD CONSTRAINT "br4430" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnopschorting" ADD CONSTRAINT "br4449" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnbeeindrelatie" ADD CONSTRAINT "br4428" PRIMARY KEY (id);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "br4406" PRIMARY KEY (id);
ALTER TABLE "kern"."plaats" ADD CONSTRAINT "br4397" PRIMARY KEY (id);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "br4393" PRIMARY KEY (id);
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "br4459" PRIMARY KEY (id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "br4446" PRIMARY KEY (id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "br6137" PRIMARY KEY (id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "br4414" PRIMARY KEY (id);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "br4455" PRIMARY KEY (id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "br4391" PRIMARY KEY (id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "br4434" PRIMARY KEY (id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "br4390" PRIMARY KEY (id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "br4495" PRIMARY KEY (id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "br4417" PRIMARY KEY (id);
ALTER TABLE "kern"."onderzoek" ADD CONSTRAINT "br4421" PRIMARY KEY (id);
ALTER TABLE "kern"."nation" ADD CONSTRAINT "br4404" PRIMARY KEY (id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "br4488" PRIMARY KEY (id);
ALTER TABLE "kern"."land" ADD CONSTRAINT "br4399" PRIMARY KEY (id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "br4597" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "br4594" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "br4591" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "br4543" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "br4546" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "br4531" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "br4588" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "br4561" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "br4540" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "br4555" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "br4585" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "br4567" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "br4582" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "br4564" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "br4525" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "br4579" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "br4528" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "br4537" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "br4549" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "br4552" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "br4558" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "br6076" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "br4534" PRIMARY KEY (id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "br6125" PRIMARY KEY (id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "br4631" PRIMARY KEY (id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "br4522" PRIMARY KEY (id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "br5480" PRIMARY KEY (id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "br4516" PRIMARY KEY (id);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "br4510" PRIMARY KEY (id);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "br4513" PRIMARY KEY (id);
ALTER TABLE "kern"."geslachtsaand" ADD CONSTRAINT "br4482" PRIMARY KEY (id);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "br4507" PRIMARY KEY (id);
ALTER TABLE "kern"."functieadres" ADD CONSTRAINT "br4435" PRIMARY KEY (id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "br4422" PRIMARY KEY (id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "br4416" PRIMARY KEY (id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "br5659" PRIMARY KEY (id);
ALTER TABLE "kern"."categoriesrtdoc" ADD CONSTRAINT "br5984" PRIMARY KEY (id);
ALTER TABLE "kern"."categoriesrtactie" ADD CONSTRAINT "br5981" PRIMARY KEY (id);
ALTER TABLE "kern"."categoriepersonen" ADD CONSTRAINT "br6169" PRIMARY KEY (id);
ALTER TABLE "kern"."bron" ADD CONSTRAINT "br4504" PRIMARY KEY (id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "br6104" PRIMARY KEY (id);
ALTER TABLE "kern"."autvanafgiftereisdoc" ADD CONSTRAINT "br4466" PRIMARY KEY (id);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "br4410" PRIMARY KEY (id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "br4403" PRIMARY KEY (id);
ALTER TABLE "kern"."aangadresh" ADD CONSTRAINT "br4438" PRIMARY KEY (id);
ALTER TABLE "brm"."srtregel" ADD CONSTRAINT "br5973" PRIMARY KEY (id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "br6060" PRIMARY KEY (id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "br5976" PRIMARY KEY (id);
ALTER TABLE "brm"."regeleffect" ADD CONSTRAINT "br5978" PRIMARY KEY (id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "br5989" PRIMARY KEY (id);
ALTER TABLE "ber"."verwerkingsresultaat" ADD CONSTRAINT "br6322" PRIMARY KEY (id);
ALTER TABLE "ber"."srtmelding" ADD CONSTRAINT "br6317" PRIMARY KEY (id);
ALTER TABLE "ber"."srtber" ADD CONSTRAINT "br5027" PRIMARY KEY (id);
ALTER TABLE "ber"."richting" ADD CONSTRAINT "br5635" PRIMARY KEY (id);
ALTER TABLE "ber"."overrule" ADD CONSTRAINT "br6320" PRIMARY KEY (id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "br6316" PRIMARY KEY (id);
ALTER TABLE "ber"."bijhresultaat" ADD CONSTRAINT "br6324" PRIMARY KEY (id);
ALTER TABLE "ber"."beroverrule" ADD CONSTRAINT "br6321" PRIMARY KEY (id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "br6319" PRIMARY KEY (id);
ALTER TABLE "ber"."berbijgehoudenpers" ADD CONSTRAINT "br6326" PRIMARY KEY (id);
ALTER TABLE "ber"."beractie" ADD CONSTRAINT "br6315" PRIMARY KEY (id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "br4827" PRIMARY KEY (id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "br5791" PRIMARY KEY (id);
ALTER TABLE "autaut"."toestand" ADD CONSTRAINT "br5746" PRIMARY KEY (id);
ALTER TABLE "autaut"."srtbevoegdheid" ADD CONSTRAINT "br5750" PRIMARY KEY (id);
ALTER TABLE "autaut"."srtautorisatiebesluit" ADD CONSTRAINT "br4987" PRIMARY KEY (id);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "br4990" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "br5795" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "br5003" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "br5760" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "br5757" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "br5754" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "br5000" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "br4691" PRIMARY KEY (id);
ALTER TABLE "autaut"."functie" ADD CONSTRAINT "br4725" PRIMARY KEY (id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "br4981" PRIMARY KEY (id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "br4979" PRIMARY KEY (id);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "br4727" PRIMARY KEY (id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "br5748" PRIMARY KEY (id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "br5747" PRIMARY KEY (id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "br4978" PRIMARY KEY (id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "br4497" PRIMARY KEY (id);
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "fk4843" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "fk4842" FOREIGN KEY (lev) REFERENCES lev.lev(id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "fk4836" FOREIGN KEY (uitgaandber) REFERENCES ber.ber(id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "fk4835" FOREIGN KEY (lev) REFERENCES lev.lev(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk5670" FOREIGN KEY (gebaseerdop) REFERENCES ber.ber(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk5626" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk4821" FOREIGN KEY (authenticatiemiddel) REFERENCES autaut.authenticatiemiddel(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk4820" FOREIGN KEY (srt) REFERENCES lev.srtlev(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5605" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5604" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5601" FOREIGN KEY (abonnementsrtber) REFERENCES lev.abonnementsrtber(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4956" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4955" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4952" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "fk5597" FOREIGN KEY (srtber) REFERENCES ber.srtber(id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "fk5596" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "fk4908" FOREIGN KEY (gegevenselement) REFERENCES kern.dbobject(id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "fk4907" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "fk4903" FOREIGN KEY (srtabonnement) REFERENCES lev.srtabonnement(id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "fk4902" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "kern"."srtdoc" ADD CONSTRAINT "fk5846" FOREIGN KEY (categoriesrtdoc) REFERENCES kern.categoriesrtdoc(id);
ALTER TABLE "kern"."srtactie" ADD CONSTRAINT "fk5845" FOREIGN KEY (categoriesrtactie) REFERENCES kern.categoriesrtactie(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3768" FOREIGN KEY (landeinde) REFERENCES kern.land(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3764" FOREIGN KEY (wpleinde) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3763" FOREIGN KEY (gemeinde) REFERENCES kern.partij(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3760" FOREIGN KEY (landaanv) REFERENCES kern.land(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3756" FOREIGN KEY (wplaanv) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3755" FOREIGN KEY (gemaanv) REFERENCES kern.partij(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3207" FOREIGN KEY (rdneinde) REFERENCES kern.rdnbeeindrelatie(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3198" FOREIGN KEY (srt) REFERENCES kern.srtrelatie(id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "fk6152" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "fk6149" FOREIGN KEY (actie) REFERENCES kern.actie(id);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "fk5990" FOREIGN KEY (srt) REFERENCES brm.srtregel(id);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "fk3023" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "fk3779" FOREIGN KEY (srt) REFERENCES kern.srtverificatie(id);
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "fk2142" FOREIGN KEY (geverifieerde) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3752" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3747" FOREIGN KEY (rdnvervallen) REFERENCES kern.rdnvervallenreisdoc(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3744" FOREIGN KEY (autvanafgifte) REFERENCES kern.autvanafgiftereisdoc(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3739" FOREIGN KEY (srt) REFERENCES kern.srtnlreisdoc(id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "fk6132" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "fk6131" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3230" FOREIGN KEY (rdnverlies) REFERENCES kern.rdnverliesnlnation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3229" FOREIGN KEY (rdnverk) REFERENCES kern.rdnverknlnation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3131" FOREIGN KEY (nation) REFERENCES kern.nation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3130" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "fk3658" FOREIGN KEY (srt) REFERENCES kern.srtindicatie(id);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "fk3657" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3118" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3117" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3024" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3788" FOREIGN KEY (gem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3715" FOREIGN KEY (rdnwijz) REFERENCES kern.rdnwijzadres(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3301" FOREIGN KEY (aangadresh) REFERENCES kern.aangadresh(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3289" FOREIGN KEY (land) REFERENCES kern.land(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3282" FOREIGN KEY (wpl) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3263" FOREIGN KEY (srt) REFERENCES kern.functieadres(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3241" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk6113" FOREIGN KEY (adellijketitelaanschr) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3703" FOREIGN KEY (predikaataanschr) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3676" FOREIGN KEY (wplgeboorte) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3675" FOREIGN KEY (gemgeboorte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3667" FOREIGN KEY (volgendepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3666" FOREIGN KEY (vorigepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3663" FOREIGN KEY (rdnopschortingbijhouding) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3593" FOREIGN KEY (gebrgeslnaamegp) REFERENCES kern.wijzegebruikgeslnaam(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3579" FOREIGN KEY (landvanwaargevestigd) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3573" FOREIGN KEY (bijhgem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3568" FOREIGN KEY (verantwoordelijke) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3558" FOREIGN KEY (landoverlijden) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3551" FOREIGN KEY (gemoverlijden) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3544" FOREIGN KEY (wploverlijden) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3543" FOREIGN KEY (landgeboorte) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3310" FOREIGN KEY (verblijfsr) REFERENCES kern.verblijfsr(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3233" FOREIGN KEY (gempk) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3031" FOREIGN KEY (geslachtsaand) REFERENCES kern.geslachtsaand(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1997" FOREIGN KEY (srt) REFERENCES kern.srtpers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1969" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1968" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "fk2186" FOREIGN KEY (rol) REFERENCES kern.rol(id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "fk2185" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk4602" FOREIGN KEY (onderdeelvan) REFERENCES kern.partij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2196" FOREIGN KEY (sector) REFERENCES kern.sector(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2195" FOREIGN KEY (srt) REFERENCES kern.srtpartij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2005" FOREIGN KEY (voortzettendegem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2056" FOREIGN KEY (betr) REFERENCES kern.betr(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2055" FOREIGN KEY (relatie) REFERENCES kern.relatie(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2054" FOREIGN KEY (multirealiteitpers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2053" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2051" FOREIGN KEY (srt) REFERENCES kern.srtmultirealiteitregel(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2050" FOREIGN KEY (geldigvoor) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4387" FOREIGN KEY (landeinde) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4384" FOREIGN KEY (wpleinde) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4383" FOREIGN KEY (gemeinde) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4381" FOREIGN KEY (rdneinde) REFERENCES kern.rdnbeeindrelatie(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4379" FOREIGN KEY (landaanv) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4376" FOREIGN KEY (wplaanv) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4375" FOREIGN KEY (gemaanv) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4373" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4372" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_relatie" ADD CONSTRAINT "fk4369" FOREIGN KEY (relatie) REFERENCES kern.relatie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4366" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4365" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4364" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4359" FOREIGN KEY (persvoornaam) REFERENCES kern.persvoornaam(id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4356" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4355" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4352" FOREIGN KEY (persverificatie) REFERENCES kern.persverificatie(id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "fk4166" FOREIGN KEY (verblijfsr) REFERENCES kern.verblijfsr(id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "fk4165" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "fk4164" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "fk4163" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfsr" ADD CONSTRAINT "fk4158" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4175" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4174" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4171" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4110" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4106" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4105" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4104" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4103" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4098" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4349" FOREIGN KEY (rdnvervallen) REFERENCES kern.rdnvervallenreisdoc(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4346" FOREIGN KEY (autvanafgifte) REFERENCES kern.autvanafgiftereisdoc(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4342" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4341" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4336" FOREIGN KEY (persreisdoc) REFERENCES kern.persreisdoc(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4222" FOREIGN KEY (gempk) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4221" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4220" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4217" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4155" FOREIGN KEY (landoverlijden) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4152" FOREIGN KEY (wploverlijden) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4151" FOREIGN KEY (gemoverlijden) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4149" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4148" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4145" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk5006" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4203" FOREIGN KEY (rdnopschortingbijhouding) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4202" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4201" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4198" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4334" FOREIGN KEY (rdnverk) REFERENCES kern.rdnverknlnation(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4333" FOREIGN KEY (rdnverlies) REFERENCES kern.rdnverliesnlnation(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4332" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4331" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4330" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4325" FOREIGN KEY (persnation) REFERENCES kern.persnation(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4247" FOREIGN KEY (volgendepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4246" FOREIGN KEY (vorigepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4242" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4241" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4236" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4322" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4321" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4320" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4315" FOREIGN KEY (persindicatie) REFERENCES kern.persindicatie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4233" FOREIGN KEY (landvanwaargevestigd) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4232" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4231" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4230" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4225" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4084" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4083" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4082" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4077" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4313" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4312" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4308" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4307" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4306" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4301" FOREIGN KEY (persgeslnaamcomp) REFERENCES kern.persgeslnaamcomp(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4096" FOREIGN KEY (geslachtsaand) REFERENCES kern.geslachtsaand(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4095" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4094" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4093" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4088" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4142" FOREIGN KEY (landgeboorte) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4139" FOREIGN KEY (wplgeboorte) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4138" FOREIGN KEY (gemgeboorte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4136" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4135" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4132" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4183" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4182" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4179" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4196" FOREIGN KEY (verantwoordelijke) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4195" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4194" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4193" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4188" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4213" FOREIGN KEY (bijhgem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4212" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4211" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4210" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4205" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6072" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6071" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6070" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6065" FOREIGN KEY (persadres) REFERENCES kern.persadres(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4298" FOREIGN KEY (land) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4280" FOREIGN KEY (wpl) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4272" FOREIGN KEY (gem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4259" FOREIGN KEY (aangadresh) REFERENCES kern.aangadresh(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4258" FOREIGN KEY (rdnwijz) REFERENCES kern.rdnwijzadres(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4257" FOREIGN KEY (srt) REFERENCES kern.functieadres(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk6114" FOREIGN KEY (adellijketitelaanschr) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4126" FOREIGN KEY (predikaataanschr) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4123" FOREIGN KEY (gebrgeslnaamegp) REFERENCES kern.wijzegebruikgeslnaam(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4122" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4121" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4120" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4115" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6121" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6120" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6117" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk4613" FOREIGN KEY (onderdeelvan) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk4611" FOREIGN KEY (voortzettendegem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4627" FOREIGN KEY (sector) REFERENCES kern.sector(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4624" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4623" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4620" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4072" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4071" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4068" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5476" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5475" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5472" FOREIGN KEY (multirealiteitregel) REFERENCES kern.multirealiteitregel(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4051" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4047" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4046" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4043" FOREIGN KEY (doc) REFERENCES kern.doc(id);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "fk6091" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "fk4029" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "fk4028" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderschap" ADD CONSTRAINT "fk4025" FOREIGN KEY (betr) REFERENCES kern.betr(id);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "fk4040" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "fk4039" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "fk4038" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_betrouderlijkgezag" ADD CONSTRAINT "fk4033" FOREIGN KEY (betr) REFERENCES kern.betr(id);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "fk3866" FOREIGN KEY (srtgegeven) REFERENCES kern.dbobject(id);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "fk3865" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "fk5663" FOREIGN KEY (ouder) REFERENCES kern.element(id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "fk3721" FOREIGN KEY (srt) REFERENCES kern.srtelement(id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "fk3157" FOREIGN KEY (srt) REFERENCES kern.srtdoc(id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "fk3139" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "fk5661" FOREIGN KEY (ouder) REFERENCES kern.dbobject(id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "fk5644" FOREIGN KEY (srt) REFERENCES kern.srtdbobject(id);
ALTER TABLE "kern"."bron" ADD CONSTRAINT "fk3876" FOREIGN KEY (doc) REFERENCES kern.doc(id);
ALTER TABLE "kern"."bron" ADD CONSTRAINT "fk3875" FOREIGN KEY (actie) REFERENCES kern.actie(id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3861" FOREIGN KEY (rol) REFERENCES kern.srtbetr(id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3860" FOREIGN KEY (relatie) REFERENCES kern.relatie(id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3859" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk3212" FOREIGN KEY (verdrag) REFERENCES kern.verdrag(id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk3209" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk3055" FOREIGN KEY (srt) REFERENCES kern.srtactie(id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "fk6059" FOREIGN KEY (srtber) REFERENCES ber.srtber(id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "fk6058" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk6000" FOREIGN KEY (rdnopschorting) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5999" FOREIGN KEY (bijhverantwoordelijkheid) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5829" FOREIGN KEY (effect) REFERENCES brm.regeleffect(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5828" FOREIGN KEY (regelimplementatie) REFERENCES brm.regelsrtber(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6157" FOREIGN KEY (regelsituatie) REFERENCES brm.regelsituatie(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6022" FOREIGN KEY (rdnopschorting) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6021" FOREIGN KEY (bijhverantwoordelijkheid) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5970" FOREIGN KEY (effect) REFERENCES brm.regeleffect(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5969" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5968" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "ber"."overrule" ADD CONSTRAINT "fk6221" FOREIGN KEY (attribuut) REFERENCES kern.element(id);
ALTER TABLE "ber"."overrule" ADD CONSTRAINT "fk6220" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6209" FOREIGN KEY (attribuut) REFERENCES kern.element(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6206" FOREIGN KEY (srt) REFERENCES ber.srtmelding(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6198" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "ber"."beroverrule" ADD CONSTRAINT "fk6227" FOREIGN KEY (overrule) REFERENCES ber.overrule(id);
ALTER TABLE "ber"."beroverrule" ADD CONSTRAINT "fk6226" FOREIGN KEY (ber) REFERENCES ber.ber(id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "fk6215" FOREIGN KEY (melding) REFERENCES ber.melding(id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "fk6214" FOREIGN KEY (ber) REFERENCES ber.ber(id);
ALTER TABLE "ber"."berbijgehoudenpers" ADD CONSTRAINT "fk6253" FOREIGN KEY (pers) REFERENCES kern.pers(id);
ALTER TABLE "ber"."berbijgehoudenpers" ADD CONSTRAINT "fk6252" FOREIGN KEY (ber) REFERENCES ber.ber(id);
ALTER TABLE "ber"."beractie" ADD CONSTRAINT "fk6193" FOREIGN KEY (srt) REFERENCES kern.srtactie(id);
ALTER TABLE "ber"."beractie" ADD CONSTRAINT "fk6182" FOREIGN KEY (actie) REFERENCES kern.actie(id);
ALTER TABLE "ber"."beractie" ADD CONSTRAINT "fk6181" FOREIGN KEY (ber) REFERENCES ber.ber(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6246" FOREIGN KEY (hoogstemeldingsniveau) REFERENCES ber.srtmelding(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6245" FOREIGN KEY (bijhouding) REFERENCES ber.bijhresultaat(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6230" FOREIGN KEY (verwerking) REFERENCES ber.verwerkingsresultaat(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6183" FOREIGN KEY (srt) REFERENCES ber.srtber(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk5633" FOREIGN KEY (richting) REFERENCES ber.richting(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk5612" FOREIGN KEY (antwoordop) REFERENCES ber.ber(id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "fk5780" FOREIGN KEY (uitgeslotenpartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "fk5779" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5797" FOREIGN KEY (uitgeslotene) REFERENCES autaut.uitgeslotene(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5788" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5787" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4974" FOREIGN KEY (protocolleringsniveau) REFERENCES autaut.protocolleringsniveau(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4973" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4972" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4971" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4966" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5744" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5743" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5740" FOREIGN KEY (bijhsituatie) REFERENCES autaut.bijhsituatie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk6166" FOREIGN KEY (categoriepersonen) REFERENCES kern.categoriepersonen(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5790" FOREIGN KEY (srtbevoegdheid) REFERENCES autaut.srtbevoegdheid(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5738" FOREIGN KEY (geautoriseerdesrtpartij) REFERENCES kern.srtpartij(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5737" FOREIGN KEY (geautoriseerdepartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5735" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5734" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5733" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5730" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5728" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5727" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5726" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5723" FOREIGN KEY (autorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4963" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4962" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4959" FOREIGN KEY (autorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4685" FOREIGN KEY (certificaattbvondertekening) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4684" FOREIGN KEY (certificaattbvssl) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4683" FOREIGN KEY (functie) REFERENCES autaut.functie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4682" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4681" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4678" FOREIGN KEY (authenticatiemiddel) REFERENCES autaut.authenticatiemiddel(id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "fk4893" FOREIGN KEY (gegevenselement) REFERENCES kern.dbobject(id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "fk4892" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4885" FOREIGN KEY (levsautorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4884" FOREIGN KEY (geautoriseerde) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4883" FOREIGN KEY (protocolleringsniveau) REFERENCES autaut.protocolleringsniveau(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk6040" FOREIGN KEY (categoriesrtdoc) REFERENCES kern.categoriesrtdoc(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk6039" FOREIGN KEY (categoriesrtactie) REFERENCES kern.categoriesrtactie(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk5701" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk5698" FOREIGN KEY (srtdoc) REFERENCES kern.srtdoc(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk5697" FOREIGN KEY (srtactie) REFERENCES kern.srtactie(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk6165" FOREIGN KEY (categoriepersonen) REFERENCES kern.categoriepersonen(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5713" FOREIGN KEY (srtbevoegdheid) REFERENCES autaut.srtbevoegdheid(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5704" FOREIGN KEY (geautoriseerdesrtpartij) REFERENCES kern.srtpartij(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5703" FOREIGN KEY (geautoriseerdepartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5691" FOREIGN KEY (bijhautorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5689" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk5677" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4868" FOREIGN KEY (gebaseerdop) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4866" FOREIGN KEY (autoriseerder) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4863" FOREIGN KEY (srt) REFERENCES autaut.srtautorisatiebesluit(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4668" FOREIGN KEY (certificaattbvondertekening) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4667" FOREIGN KEY (certificaattbvssl) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4665" FOREIGN KEY (functie) REFERENCES autaut.functie(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk2233" FOREIGN KEY (rol) REFERENCES kern.rol(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk2232" FOREIGN KEY (partij) REFERENCES kern.partij(id);
