// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.brm;

import java.util.List;
import nl.bzk.brp.model.data.brm.Regeleffect;
import nl.bzk.brp.model.data.brm.RegeleffectDataOnDemand;
import nl.bzk.brp.model.data.brm.RegeleffectIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RegeleffectIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RegeleffectIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RegeleffectIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RegeleffectIntegrationTest: @Transactional;
    
    @Autowired
    private RegeleffectDataOnDemand RegeleffectIntegrationTest.dod;
    
    @Test
    public void RegeleffectIntegrationTest.testCountRegeleffects() {
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", dod.getRandomRegeleffect());
        long count = Regeleffect.countRegeleffects();
        Assert.assertTrue("Counter for 'Regeleffect' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RegeleffectIntegrationTest.testFindRegeleffect() {
        Regeleffect obj = dod.getRandomRegeleffect();
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to provide an identifier", id);
        obj = Regeleffect.findRegeleffect(id);
        Assert.assertNotNull("Find method for 'Regeleffect' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Regeleffect' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RegeleffectIntegrationTest.testFindAllRegeleffects() {
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", dod.getRandomRegeleffect());
        long count = Regeleffect.countRegeleffects();
        Assert.assertTrue("Too expensive to perform a find all test for 'Regeleffect', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Regeleffect> result = Regeleffect.findAllRegeleffects();
        Assert.assertNotNull("Find all method for 'Regeleffect' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Regeleffect' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RegeleffectIntegrationTest.testFindRegeleffectEntries() {
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", dod.getRandomRegeleffect());
        long count = Regeleffect.countRegeleffects();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Regeleffect> result = Regeleffect.findRegeleffectEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Regeleffect' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Regeleffect' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RegeleffectIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", dod.getRandomRegeleffect());
        Regeleffect obj = dod.getNewTransientRegeleffect(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Regeleffect' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Regeleffect' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RegeleffectIntegrationTest.testRemove() {
        Regeleffect obj = dod.getRandomRegeleffect();
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regeleffect' failed to provide an identifier", id);
        obj = Regeleffect.findRegeleffect(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Regeleffect' with identifier '" + id + "'", Regeleffect.findRegeleffect(id));
    }
    
}
