// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.brm;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.brm.Srtregel;
import nl.bzk.brp.model.data.brm.SrtregelDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect SrtregelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SrtregelDataOnDemand: @Component;
    
    private Random SrtregelDataOnDemand.rnd = new SecureRandom();
    
    private List<Srtregel> SrtregelDataOnDemand.data;
    
    public Srtregel SrtregelDataOnDemand.getNewTransientSrtregel(int index) {
        Srtregel obj = new Srtregel();
        setDataanvgel(obj, index);
        setDateindegel(obj, index);
        setNaam(obj, index);
        setOms(obj, index);
        return obj;
    }
    
    public void SrtregelDataOnDemand.setDataanvgel(Srtregel obj, int index) {
        BigDecimal dataanvgel = BigDecimal.valueOf(index);
        obj.setDataanvgel(dataanvgel);
    }
    
    public void SrtregelDataOnDemand.setDateindegel(Srtregel obj, int index) {
        BigDecimal dateindegel = BigDecimal.valueOf(index);
        obj.setDateindegel(dateindegel);
    }
    
    public void SrtregelDataOnDemand.setNaam(Srtregel obj, int index) {
        String naam = "naam_" + index;
        if (naam.length() > 40) {
            naam = new Random().nextInt(10) + naam.substring(1, 40);
        }
        obj.setNaam(naam);
    }
    
    public void SrtregelDataOnDemand.setOms(Srtregel obj, int index) {
        String oms = "oms_" + index;
        if (oms.length() > 250) {
            oms = new Random().nextInt(10) + oms.substring(1, 250);
        }
        obj.setOms(oms);
    }
    
    public Srtregel SrtregelDataOnDemand.getSpecificSrtregel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Srtregel obj = data.get(index);
        Short id = obj.getId();
        return Srtregel.findSrtregel(id);
    }
    
    public Srtregel SrtregelDataOnDemand.getRandomSrtregel() {
        init();
        Srtregel obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getId();
        return Srtregel.findSrtregel(id);
    }
    
    public boolean SrtregelDataOnDemand.modifySrtregel(Srtregel obj) {
        return false;
    }
    
    public void SrtregelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Srtregel.findSrtregelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Srtregel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Srtregel>();
        for (int i = 0; i < 10; i++) {
            Srtregel obj = getNewTransientSrtregel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
