/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.poc.berichtenverwerker.model;

// Generated 10-aug-2011 15:03:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersadresadresh generated by hbm2java
 */
@Entity
@Table(name = "hispersadresadresh", schema = "kern",
       uniqueConstraints = @UniqueConstraint(columnNames = { "persadres", "dataanvgel", "dattijdverval" }))
public class Hispersadresadresh implements java.io.Serializable {

    private long         id;
    private Actie        actieByActieeinde;
    private Rdnwijzadres rdnwijzadres;
    private Aangadresh   aangadresh;
    private Functieadres functieadres;
    private Persadres    persadres;
    private Actie        actieByActiebegin;
    private BigDecimal   dataanvgel;
    private BigDecimal   dateindegel;
    private Date         dattijdreg;
    private Date         dattijdverval;
    private BigDecimal   dataanvadresh;
    private Integer      actiebeingeld;

    public Hispersadresadresh() {
    }

    public Hispersadresadresh(long id, Rdnwijzadres rdnwijzadres, Functieadres functieadres, BigDecimal dataanvadresh) {
        this.id = id;
        this.rdnwijzadres = rdnwijzadres;
        this.functieadres = functieadres;
        this.dataanvadresh = dataanvadresh;
    }

    public Hispersadresadresh(long id, Actie actieByActieeinde, Rdnwijzadres rdnwijzadres, Aangadresh aangadresh,
            Functieadres functieadres, Persadres persadres, Actie actieByActiebegin, BigDecimal dataanvgel,
            BigDecimal dateindegel, Date dattijdreg, Date dattijdverval, BigDecimal dataanvadresh, Integer actiebeingeld) {
        this.id = id;
        this.actieByActieeinde = actieByActieeinde;
        this.rdnwijzadres = rdnwijzadres;
        this.aangadresh = aangadresh;
        this.functieadres = functieadres;
        this.persadres = persadres;
        this.actieByActiebegin = actieByActiebegin;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.dataanvadresh = dataanvadresh;
        this.actiebeingeld = actiebeingeld;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actieeinde")
    public Actie getActieByActieeinde() {
        return this.actieByActieeinde;
    }

    public void setActieByActieeinde(Actie actieByActieeinde) {
        this.actieByActieeinde = actieByActieeinde;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rdnwijz", nullable = false)
    public Rdnwijzadres getRdnwijzadres() {
        return this.rdnwijzadres;
    }

    public void setRdnwijzadres(Rdnwijzadres rdnwijzadres) {
        this.rdnwijzadres = rdnwijzadres;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "aangadresh")
    public Aangadresh getAangadresh() {
        return this.aangadresh;
    }

    public void setAangadresh(Aangadresh aangadresh) {
        this.aangadresh = aangadresh;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "functie", nullable = false)
    public Functieadres getFunctieadres() {
        return this.functieadres;
    }

    public void setFunctieadres(Functieadres functieadres) {
        this.functieadres = functieadres;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "persadres")
    public Persadres getPersadres() {
        return this.persadres;
    }

    public void setPersadres(Persadres persadres) {
        this.persadres = persadres;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actiebegin")
    public Actie getActieByActiebegin() {
        return this.actieByActiebegin;
    }

    public void setActieByActiebegin(Actie actieByActiebegin) {
        this.actieByActiebegin = actieByActiebegin;
    }

    @Column(name = "dataanvgel", precision = 8)
    public BigDecimal getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(BigDecimal dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8)
    public BigDecimal getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(BigDecimal dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "dataanvadresh", nullable = false, precision = 8)
    public BigDecimal getDataanvadresh() {
        return this.dataanvadresh;
    }

    public void setDataanvadresh(BigDecimal dataanvadresh) {
        this.dataanvadresh = dataanvadresh;
    }

    @Column(name = "actiebeingeld")
    public Integer getActiebeingeld() {
        return this.actiebeingeld;
    }

    public void setActiebeingeld(Integer actiebeingeld) {
        this.actiebeingeld = actiebeingeld;
    }

}
