/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.poc.berichtenverwerker.model;

// Generated 10-aug-2011 15:03:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersaanschr generated by hbm2java
 */
@Entity
@Table(name = "hispersaanschr", schema = "kern",
       uniqueConstraints = @UniqueConstraint(columnNames = { "pers", "dataanvgel", "dattijdverval" }))
public class Hispersaanschr implements java.io.Serializable {

    private long                 id;
    private Predikaat            predikaat;
    private Actie                actieByActieeinde;
    private Pers                 pers;
    private Wijzegebruikgeslnaam wijzegebruikgeslnaam;
    private Actie                actieByActiebegin;
    private BigDecimal           dataanvgel;
    private BigDecimal           dateindegel;
    private Date                 dattijdreg;
    private Date                 dattijdverval;
    private String               indaanschrmetatp;
    private String               indaanschrafgeleid;
    private String               voornamenaanschr;
    private String               voorvoegselaanschr;
    private String               scheidingstekenaanschr;
    private String               geslnaamaanschr;
    private Integer              actiebeingeld;

    public Hispersaanschr() {
    }

    public Hispersaanschr(long id, String indaanschrafgeleid, String geslnaamaanschr) {
        this.id = id;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.geslnaamaanschr = geslnaamaanschr;
    }

    public Hispersaanschr(long id, Predikaat predikaat, Actie actieByActieeinde, Pers pers,
            Wijzegebruikgeslnaam wijzegebruikgeslnaam, Actie actieByActiebegin, BigDecimal dataanvgel,
            BigDecimal dateindegel, Date dattijdreg, Date dattijdverval, String indaanschrmetatp,
            String indaanschrafgeleid, String voornamenaanschr, String voorvoegselaanschr,
            String scheidingstekenaanschr, String geslnaamaanschr, Integer actiebeingeld) {
        this.id = id;
        this.predikaat = predikaat;
        this.actieByActieeinde = actieByActieeinde;
        this.pers = pers;
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
        this.actieByActiebegin = actieByActiebegin;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.indaanschrmetatp = indaanschrmetatp;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.voornamenaanschr = voornamenaanschr;
        this.voorvoegselaanschr = voorvoegselaanschr;
        this.scheidingstekenaanschr = scheidingstekenaanschr;
        this.geslnaamaanschr = geslnaamaanschr;
        this.actiebeingeld = actiebeingeld;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predikaataanschr")
    public Predikaat getPredikaat() {
        return this.predikaat;
    }

    public void setPredikaat(Predikaat predikaat) {
        this.predikaat = predikaat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actieeinde")
    public Actie getActieByActieeinde() {
        return this.actieByActieeinde;
    }

    public void setActieByActieeinde(Actie actieByActieeinde) {
        this.actieByActieeinde = actieByActieeinde;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pers")
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gebrgeslnaamegp")
    public Wijzegebruikgeslnaam getWijzegebruikgeslnaam() {
        return this.wijzegebruikgeslnaam;
    }

    public void setWijzegebruikgeslnaam(Wijzegebruikgeslnaam wijzegebruikgeslnaam) {
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actiebegin")
    public Actie getActieByActiebegin() {
        return this.actieByActiebegin;
    }

    public void setActieByActiebegin(Actie actieByActiebegin) {
        this.actieByActiebegin = actieByActiebegin;
    }

    @Column(name = "dataanvgel", precision = 8)
    public BigDecimal getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(BigDecimal dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8)
    public BigDecimal getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(BigDecimal dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "indaanschrmetatp", length = 1)
    public String getIndaanschrmetatp() {
        return this.indaanschrmetatp;
    }

    public void setIndaanschrmetatp(String indaanschrmetatp) {
        this.indaanschrmetatp = indaanschrmetatp;
    }

    @Column(name = "indaanschrafgeleid", nullable = false, length = 1)
    public String getIndaanschrafgeleid() {
        return this.indaanschrafgeleid;
    }

    public void setIndaanschrafgeleid(String indaanschrafgeleid) {
        this.indaanschrafgeleid = indaanschrafgeleid;
    }

    @Column(name = "voornamenaanschr", length = 200)
    public String getVoornamenaanschr() {
        return this.voornamenaanschr;
    }

    public void setVoornamenaanschr(String voornamenaanschr) {
        this.voornamenaanschr = voornamenaanschr;
    }

    @Column(name = "voorvoegselaanschr", length = 10)
    public String getVoorvoegselaanschr() {
        return this.voorvoegselaanschr;
    }

    public void setVoorvoegselaanschr(String voorvoegselaanschr) {
        this.voorvoegselaanschr = voorvoegselaanschr;
    }

    @Column(name = "scheidingstekenaanschr", length = 1)
    public String getScheidingstekenaanschr() {
        return this.scheidingstekenaanschr;
    }

    public void setScheidingstekenaanschr(String scheidingstekenaanschr) {
        this.scheidingstekenaanschr = scheidingstekenaanschr;
    }

    @Column(name = "geslnaamaanschr", nullable = false, length = 200)
    public String getGeslnaamaanschr() {
        return this.geslnaamaanschr;
    }

    public void setGeslnaamaanschr(String geslnaamaanschr) {
        this.geslnaamaanschr = geslnaamaanschr;
    }

    @Column(name = "actiebeingeld")
    public Integer getActiebeingeld() {
        return this.actiebeingeld;
    }

    public void setActiebeingeld(Integer actiebeingeld) {
        this.actiebeingeld = actiebeingeld;
    }

}
