/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.poc.berichtenverwerker.model;

// Generated 10-aug-2011 15:03:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersuitslnlkiesr generated by hbm2java
 */
@Entity
@Table(name = "hispersuitslnlkiesr", schema = "kern",
       uniqueConstraints = @UniqueConstraint(columnNames = { "pers", "dataanvgel", "dattijdverval" }))
public class Hispersuitslnlkiesr implements java.io.Serializable {

    private long       id;
    private Actie      actieByActieeinde;
    private Pers       pers;
    private Actie      actieByActiebegin;
    private BigDecimal dataanvgel;
    private BigDecimal dateindegel;
    private Date       dattijdreg;
    private Date       dattijdverval;
    private String     induitslnlkiesr;
    private BigDecimal dateindeuitslnlkiesr;
    private Integer    actiebeingeld;

    public Hispersuitslnlkiesr() {
    }

    public Hispersuitslnlkiesr(long id) {
        this.id = id;
    }

    public Hispersuitslnlkiesr(long id, Actie actieByActieeinde, Pers pers, Actie actieByActiebegin,
            BigDecimal dataanvgel, BigDecimal dateindegel, Date dattijdreg, Date dattijdverval, String induitslnlkiesr,
            BigDecimal dateindeuitslnlkiesr, Integer actiebeingeld) {
        this.id = id;
        this.actieByActieeinde = actieByActieeinde;
        this.pers = pers;
        this.actieByActiebegin = actieByActiebegin;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.induitslnlkiesr = induitslnlkiesr;
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
        this.actiebeingeld = actiebeingeld;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actieeinde")
    public Actie getActieByActieeinde() {
        return this.actieByActieeinde;
    }

    public void setActieByActieeinde(Actie actieByActieeinde) {
        this.actieByActieeinde = actieByActieeinde;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pers")
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actiebegin")
    public Actie getActieByActiebegin() {
        return this.actieByActiebegin;
    }

    public void setActieByActiebegin(Actie actieByActiebegin) {
        this.actieByActiebegin = actieByActiebegin;
    }

    @Column(name = "dataanvgel", precision = 8)
    public BigDecimal getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(BigDecimal dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8)
    public BigDecimal getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(BigDecimal dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "induitslnlkiesr", length = 1)
    public String getInduitslnlkiesr() {
        return this.induitslnlkiesr;
    }

    public void setInduitslnlkiesr(String induitslnlkiesr) {
        this.induitslnlkiesr = induitslnlkiesr;
    }

    @Column(name = "dateindeuitslnlkiesr", precision = 8)
    public BigDecimal getDateindeuitslnlkiesr() {
        return this.dateindeuitslnlkiesr;
    }

    public void setDateindeuitslnlkiesr(BigDecimal dateindeuitslnlkiesr) {
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
    }

    @Column(name = "actiebeingeld")
    public Integer getActiebeingeld() {
        return this.actiebeingeld;
    }

    public void setActiebeingeld(Integer actiebeingeld) {
        this.actiebeingeld = actiebeingeld;
    }

}
