/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.poc.berichtenverwerker.model;

// Generated 10-aug-2011 15:03:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersnation generated by hbm2java
 */
@Entity
@Table(name = "hispersnation", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = { "persnation",
                                                                                                     "dataanvgel",
                                                                                                     "dattijdverval" }))
public class Hispersnation implements java.io.Serializable {

    private long               id;
    private Persnation         persnation;
    private Actie              actieByActieeinde;
    private Actie              actieByActiebegin;
    private Rdnverknlnation    rdnverknlnation;
    private Rdnverliesnlnation rdnverliesnlnation;
    private BigDecimal         dataanvgel;
    private BigDecimal         dateindegel;
    private Date               dattijdreg;
    private Date               dattijdverval;

    public Hispersnation() {
    }

    public Hispersnation(long id) {
        this.id = id;
    }

    public Hispersnation(long id, Actie actieByActieeinde, Rdnverliesnlnation rdnverliesnlnation,
            Persnation persnation, Rdnverknlnation rdnverknlnation, Actie actieByActiebegin, BigDecimal dataanvgel,
            BigDecimal dateindegel, Date dattijdreg, Date dattijdverval) {
        this.id = id;
        this.actieByActieeinde = actieByActieeinde;
        this.rdnverliesnlnation = rdnverliesnlnation;
        this.persnation = persnation;
        this.rdnverknlnation = rdnverknlnation;
        this.actieByActiebegin = actieByActiebegin;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
    }

    @SequenceGenerator(name="HISPERSNATION_SEQUENCE_GENERATOR", sequenceName="SEQ_HISPERSNATION")
    @Id @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="HISPERSNATION_SEQUENCE_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actieeinde")
    public Actie getActieByActieeinde() {
        return this.actieByActieeinde;
    }

    public void setActieByActieeinde(Actie actieByActieeinde) {
        this.actieByActieeinde = actieByActieeinde;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rdnverlies")
    public Rdnverliesnlnation getRdnverliesnlnation() {
        return this.rdnverliesnlnation;
    }

    public void setRdnverliesnlnation(Rdnverliesnlnation rdnverliesnlnation) {
        this.rdnverliesnlnation = rdnverliesnlnation;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "persnation")
    public Persnation getPersnation() {
        return this.persnation;
    }

    public void setPersnation(Persnation persnation) {
        this.persnation = persnation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rdnverk")
    public Rdnverknlnation getRdnverknlnation() {
        return this.rdnverknlnation;
    }

    public void setRdnverknlnation(Rdnverknlnation rdnverknlnation) {
        this.rdnverknlnation = rdnverknlnation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actiebegin")
    public Actie getActieByActiebegin() {
        return this.actieByActiebegin;
    }

    public void setActieByActiebegin(Actie actieByActiebegin) {
        this.actieByActiebegin = actieByActiebegin;
    }

    @Column(name = "dataanvgel", precision = 8)
    public BigDecimal getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(BigDecimal dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8)
    public BigDecimal getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(BigDecimal dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

}
