/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.poc.berichtenverwerker.model;

// Generated 10-aug-2011 15:03:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Nation generated by hbm2java
 */
@Entity
@Table(name = "nation", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = "naam"))
public class Nation implements java.io.Serializable {

    private int             id;
    private String          naam;
    private BigDecimal      dataanvgel;
    private BigDecimal      dateindegel;
    private Set<Persnation> persnations = new HashSet<Persnation>(0);

    public Nation() {
    }

    public Nation(int id, String naam) {
        this.id = id;
        this.naam = naam;
    }

    public Nation(int id, String naam, BigDecimal dataanvgel, BigDecimal dateindegel, Set<Persnation> persnations) {
        this.id = id;
        this.naam = naam;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.persnations = persnations;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "naam", unique = true, nullable = false, length = 40)
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    @Column(name = "dataanvgel", precision = 8)
    public BigDecimal getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(BigDecimal dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8)
    public BigDecimal getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(BigDecimal dateindegel) {
        this.dateindegel = dateindegel;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "nation")
    public Set<Persnation> getPersnations() {
        return this.persnations;
    }

    public void setPersnations(Set<Persnation> persnations) {
        this.persnations = persnations;
    }

}
