CREATE ROLE migratie LOGIN ENCRYPTED PASSWORD 'M1gratie' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE brp LOGIN ENCRYPTED PASSWORD 'brp' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE migratiero LOGIN ENCRYPTED PASSWORD 'M1gratie';

CREATE DATABASE "BRP" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;

CREATE DATABASE "GBAV" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;

CREATE DATABASE "soa" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;
GRANT CONNECT ON DATABASE soa TO migratiero;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO migratiero;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO migratiero;

CREATE DATABASE "viewer" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;
CREATE DATABASE "voisc" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;

CREATE DATABASE "activemq" WITH OWNER = brp ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;
CREATE DATABASE "brp_brp" WITH OWNER = migratie ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;
CREATE DATABASE "brp_alp" WITH OWNER = brp ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;



CREATE DATABASE brpjunit WITH OWNER = brp ENCODING = 'UTF8' TABLESPACE = pg_default TEMPLATE = template0 LC_COLLATE = 'POSIX' LC_CTYPE = 'POSIX' CONNECTION LIMIT = -1;
