drop schema autaut cascade;
drop schema ber cascade;
drop schema blokkering cascade;
drop schema brm cascade;
drop schema conv cascade;
drop schema ist cascade;
drop schema kern cascade;
drop schema lev cascade;
drop schema verconv cascade;
