// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.Gegeveninonderzoek;
import nl.bzk.brp.model.data.kern.GegeveninonderzoekDataOnDemand;
import nl.bzk.brp.model.data.kern.GegeveninonderzoekIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GegeveninonderzoekIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GegeveninonderzoekIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GegeveninonderzoekIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GegeveninonderzoekIntegrationTest: @Transactional;
    
    @Autowired
    private GegeveninonderzoekDataOnDemand GegeveninonderzoekIntegrationTest.dod;
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testCountGegeveninonderzoeks() {
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", dod.getRandomGegeveninonderzoek());
        long count = Gegeveninonderzoek.countGegeveninonderzoeks();
        Assert.assertTrue("Counter for 'Gegeveninonderzoek' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testFindGegeveninonderzoek() {
        Gegeveninonderzoek obj = dod.getRandomGegeveninonderzoek();
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to provide an identifier", id);
        obj = Gegeveninonderzoek.findGegeveninonderzoek(id);
        Assert.assertNotNull("Find method for 'Gegeveninonderzoek' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Gegeveninonderzoek' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testFindAllGegeveninonderzoeks() {
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", dod.getRandomGegeveninonderzoek());
        long count = Gegeveninonderzoek.countGegeveninonderzoeks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Gegeveninonderzoek', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Gegeveninonderzoek> result = Gegeveninonderzoek.findAllGegeveninonderzoeks();
        Assert.assertNotNull("Find all method for 'Gegeveninonderzoek' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Gegeveninonderzoek' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testFindGegeveninonderzoekEntries() {
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", dod.getRandomGegeveninonderzoek());
        long count = Gegeveninonderzoek.countGegeveninonderzoeks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Gegeveninonderzoek> result = Gegeveninonderzoek.findGegeveninonderzoekEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Gegeveninonderzoek' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Gegeveninonderzoek' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", dod.getRandomGegeveninonderzoek());
        Gegeveninonderzoek obj = dod.getNewTransientGegeveninonderzoek(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Gegeveninonderzoek' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Gegeveninonderzoek' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GegeveninonderzoekIntegrationTest.testRemove() {
        Gegeveninonderzoek obj = dod.getRandomGegeveninonderzoek();
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Gegeveninonderzoek' failed to provide an identifier", id);
        obj = Gegeveninonderzoek.findGegeveninonderzoek(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Gegeveninonderzoek' with identifier '" + id + "'", Gegeveninonderzoek.findGegeveninonderzoek(id));
    }
    
}
