// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.HisPartij;
import nl.bzk.brp.model.data.kern.HisPartijDataOnDemand;
import nl.bzk.brp.model.data.kern.HisPartijIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HisPartijIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HisPartijIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HisPartijIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HisPartijIntegrationTest: @Transactional;
    
    @Autowired
    private HisPartijDataOnDemand HisPartijIntegrationTest.dod;
    
    @Test
    public void HisPartijIntegrationTest.testCountHisPartijs() {
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", dod.getRandomHisPartij());
        long count = HisPartij.countHisPartijs();
        Assert.assertTrue("Counter for 'HisPartij' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HisPartijIntegrationTest.testFindHisPartij() {
        HisPartij obj = dod.getRandomHisPartij();
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to provide an identifier", id);
        obj = HisPartij.findHisPartij(id);
        Assert.assertNotNull("Find method for 'HisPartij' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HisPartij' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HisPartijIntegrationTest.testFindAllHisPartijs() {
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", dod.getRandomHisPartij());
        long count = HisPartij.countHisPartijs();
        Assert.assertTrue("Too expensive to perform a find all test for 'HisPartij', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HisPartij> result = HisPartij.findAllHisPartijs();
        Assert.assertNotNull("Find all method for 'HisPartij' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HisPartij' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HisPartijIntegrationTest.testFindHisPartijEntries() {
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", dod.getRandomHisPartij());
        long count = HisPartij.countHisPartijs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HisPartij> result = HisPartij.findHisPartijEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HisPartij' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HisPartij' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HisPartijIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", dod.getRandomHisPartij());
        HisPartij obj = dod.getNewTransientHisPartij(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HisPartij' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HisPartij' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HisPartijIntegrationTest.testRemove() {
        HisPartij obj = dod.getRandomHisPartij();
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPartij' failed to provide an identifier", id);
        obj = HisPartij.findHisPartij(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HisPartij' with identifier '" + id + "'", HisPartij.findHisPartij(id));
    }
    
}
