// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.kern.Rdnverliesnlnation;
import nl.bzk.brp.model.data.kern.RdnverliesnlnationDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect RdnverliesnlnationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RdnverliesnlnationDataOnDemand: @Component;
    
    private Random RdnverliesnlnationDataOnDemand.rnd = new SecureRandom();
    
    private List<Rdnverliesnlnation> RdnverliesnlnationDataOnDemand.data;
    
    public Rdnverliesnlnation RdnverliesnlnationDataOnDemand.getNewTransientRdnverliesnlnation(int index) {
        Rdnverliesnlnation obj = new Rdnverliesnlnation();
        setDataanvgel(obj, index);
        setDateindegel(obj, index);
        setNaam(obj, index);
        return obj;
    }
    
    public void RdnverliesnlnationDataOnDemand.setDataanvgel(Rdnverliesnlnation obj, int index) {
        BigDecimal dataanvgel = BigDecimal.valueOf(index);
        obj.setDataanvgel(dataanvgel);
    }
    
    public void RdnverliesnlnationDataOnDemand.setDateindegel(Rdnverliesnlnation obj, int index) {
        BigDecimal dateindegel = BigDecimal.valueOf(index);
        obj.setDateindegel(dateindegel);
    }
    
    public void RdnverliesnlnationDataOnDemand.setNaam(Rdnverliesnlnation obj, int index) {
        String naam = "naam_" + index;
        if (naam.length() > 40) {
            naam = new Random().nextInt(10) + naam.substring(1, 40);
        }
        obj.setNaam(naam);
    }
    
    public Rdnverliesnlnation RdnverliesnlnationDataOnDemand.getSpecificRdnverliesnlnation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Rdnverliesnlnation obj = data.get(index);
        Integer id = obj.getId();
        return Rdnverliesnlnation.findRdnverliesnlnation(id);
    }
    
    public Rdnverliesnlnation RdnverliesnlnationDataOnDemand.getRandomRdnverliesnlnation() {
        init();
        Rdnverliesnlnation obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Rdnverliesnlnation.findRdnverliesnlnation(id);
    }
    
    public boolean RdnverliesnlnationDataOnDemand.modifyRdnverliesnlnation(Rdnverliesnlnation obj) {
        return false;
    }
    
    public void RdnverliesnlnationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Rdnverliesnlnation.findRdnverliesnlnationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Rdnverliesnlnation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Rdnverliesnlnation>();
        for (int i = 0; i < 10; i++) {
            Rdnverliesnlnation obj = getNewTransientRdnverliesnlnation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
