// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import nl.bzk.brp.model.data.kern.WijzegebruikgeslnaamIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WijzegebruikgeslnaamIntegrationTest_Roo_Configurable {
    
    declare @type: WijzegebruikgeslnaamIntegrationTest: @Configurable;
    
}
