/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersadresbladres generated by hbm2java
 */
@Entity
@Table(name = "hispersadresbladres", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = {
        "persadres", "dataanvgel", "dattijdreg" }))
public class Hispersadresbladres implements java.io.Serializable {

    private long      id;
    private Land      land;
    private Brpactie  brpactieByBrpactiebegin;
    private Persadres persadres;
    private Brpactie  brpactieByBrpactiebeingeld;
    private Brpactie  brpactieByBrpactieeinde;
    private Integer   dataanvgel;
    private Integer   dateindegel;
    private Date      dattijdreg;
    private Date      dattijdverval;
    private String    bladresregel1;
    private String    bladresregel2;
    private String    bladresregel3;
    private String    bladresregel4;
    private String    bladresregel5;
    private String    bladresregel6;
    private int       datvertrekuitnederland;

    public Hispersadresbladres() {
    }

    public Hispersadresbladres(long id, Land land, int datvertrekuitnederland) {
        this.id = id;
        this.land = land;
        this.datvertrekuitnederland = datvertrekuitnederland;
    }

    public Hispersadresbladres(long id, Land land, Brpactie brpactieByBrpactiebegin, Persadres persadres,
            Brpactie brpactieByBrpactiebeingeld, Brpactie brpactieByBrpactieeinde, Integer dataanvgel,
            Integer dateindegel, Date dattijdreg, Date dattijdverval, String bladresregel1, String bladresregel2,
            String bladresregel3, String bladresregel4, String bladresregel5, String bladresregel6,
            int datvertrekuitnederland)
    {
        this.id = id;
        this.land = land;
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
        this.persadres = persadres;
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.bladresregel1 = bladresregel1;
        this.bladresregel2 = bladresregel2;
        this.bladresregel3 = bladresregel3;
        this.bladresregel4 = bladresregel4;
        this.bladresregel5 = bladresregel5;
        this.bladresregel6 = bladresregel6;
        this.datvertrekuitnederland = datvertrekuitnederland;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "land", nullable = false)
    public Land getLand() {
        return this.land;
    }

    public void setLand(Land land) {
        this.land = land;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebegin")
    public Brpactie getBrpactieByBrpactiebegin() {
        return this.brpactieByBrpactiebegin;
    }

    public void setBrpactieByBrpactiebegin(Brpactie brpactieByBrpactiebegin) {
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "persadres")
    public Persadres getPersadres() {
        return this.persadres;
    }

    public void setPersadres(Persadres persadres) {
        this.persadres = persadres;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebeingeld")
    public Brpactie getBrpactieByBrpactiebeingeld() {
        return this.brpactieByBrpactiebeingeld;
    }

    public void setBrpactieByBrpactiebeingeld(Brpactie brpactieByBrpactiebeingeld) {
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactieeinde")
    public Brpactie getBrpactieByBrpactieeinde() {
        return this.brpactieByBrpactieeinde;
    }

    public void setBrpactieByBrpactieeinde(Brpactie brpactieByBrpactieeinde) {
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "bladresregel1", length = 40)
    public String getBladresregel1() {
        return this.bladresregel1;
    }

    public void setBladresregel1(String bladresregel1) {
        this.bladresregel1 = bladresregel1;
    }

    @Column(name = "bladresregel2", length = 40)
    public String getBladresregel2() {
        return this.bladresregel2;
    }

    public void setBladresregel2(String bladresregel2) {
        this.bladresregel2 = bladresregel2;
    }

    @Column(name = "bladresregel3", length = 40)
    public String getBladresregel3() {
        return this.bladresregel3;
    }

    public void setBladresregel3(String bladresregel3) {
        this.bladresregel3 = bladresregel3;
    }

    @Column(name = "bladresregel4", length = 40)
    public String getBladresregel4() {
        return this.bladresregel4;
    }

    public void setBladresregel4(String bladresregel4) {
        this.bladresregel4 = bladresregel4;
    }

    @Column(name = "bladresregel5", length = 40)
    public String getBladresregel5() {
        return this.bladresregel5;
    }

    public void setBladresregel5(String bladresregel5) {
        this.bladresregel5 = bladresregel5;
    }

    @Column(name = "bladresregel6", length = 40)
    public String getBladresregel6() {
        return this.bladresregel6;
    }

    public void setBladresregel6(String bladresregel6) {
        this.bladresregel6 = bladresregel6;
    }

    @Column(name = "datvertrekuitnederland", nullable = false, precision = 8, scale = 0)
    public int getDatvertrekuitnederland() {
        return this.datvertrekuitnederland;
    }

    public void setDatvertrekuitnederland(int datvertrekuitnederland) {
        this.datvertrekuitnederland = datvertrekuitnederland;
    }

}
