/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Srtverificatie generated by hbm2java
 */
@Entity
@Table(name = "srtverificatie", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = "naam"))
public class Srtverificatie implements java.io.Serializable {

    private int                  id;
    private String               naam;
    private Set<Persverificatie> persverificaties = new HashSet<Persverificatie>(0);

    public Srtverificatie() {
    }

    public Srtverificatie(int id, String naam) {
        this.id = id;
        this.naam = naam;
    }

    public Srtverificatie(int id, String naam, Set<Persverificatie> persverificaties) {
        this.id = id;
        this.naam = naam;
        this.persverificaties = persverificaties;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "naam", unique = true, nullable = false, length = 40)
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "srtverificatie")
    public Set<Persverificatie> getPersverificaties() {
        return this.persverificaties;
    }

    public void setPersverificaties(Set<Persverificatie> persverificaties) {
        this.persverificaties = persverificaties;
    }

}
