-- Wellicht zijn niet alle stappen nodig

GRANT CONNECT ON DATABASE "synthetisch" TO "brp";
GRANT USAGE ON SCHEMA "kern" TO "brp";
GRANT USAGE ON SCHEMA "autaut" TO "brp";
GRANT USAGE ON SCHEMA "ber" TO "brp";
GRANT USAGE ON SCHEMA "brm" TO "brp";
GRANT USAGE ON SCHEMA "lev" TO "brp";
GRANT SELECT ON ALL TABLES IN SCHEMA "kern" TO "brp";
GRANT SELECT ON ALL TABLES IN SCHEMA "autaut" TO "brp";
GRANT SELECT ON ALL TABLES IN SCHEMA "ber" TO "brp";
GRANT SELECT ON ALL TABLES IN SCHEMA "brm" TO "brp";
GRANT SELECT ON ALL TABLES IN SCHEMA "lev" TO "brp";
--GRANT SELECT ON ALL SEQUENCES IN SCHEMA "kern" TO "brp";
--GRANT SELECT ON ALL SEQUENCES IN SCHEMA "autaut" TO "brp";
--GRANT SELECT ON ALL SEQUENCES IN SCHEMA "ber" TO "brp";
--GRANT SELECT ON ALL SEQUENCES IN SCHEMA "brm" TO "brp";
--GRANT SELECT ON ALL SEQUENCES IN SCHEMA "lev" TO "brp";
