--select * from kern.his_persadres where persadres in (select id from kern.persadres where id in (select id from kern.pers where bsn=677080426));
--select * from kern.persadres where id in (select id from kern.pers where bsn=677080426);
--delete from kern.his_persadres where  persadres in ( select id from kern.persadres where pers in (select id from kern.pers where bsn = 677080426));
--delete from kern.persadres where id in (select id from kern.pers where bsn=677080426);677080426
--select * from kern.persadres where id in (select id from kern.pers where bsn=677080426);
--select * from kern.his_persadres where persadres in (select id from kern.persadres where id in (select id from kern.pers where bsn=677080426));
--select hpa.id, p.voornamen, p.geslnaam, hpa.dataanvgel, hpa.dateindegel, hpa.tsreg, hpa.tsverval, hpa.dataanvadresh, g.naam gemeente, pl.naam plaats, hpa.postcode, hpa.nor, hpa.huisnr, hpa.huisletter, hpa.huisnrtoevoeging, lnd.naam from kern.his_persadres hpa, kern.persadres pa, kern.pers p, kern.partij g, kern.plaats pl, kern.land lnd   where hpa.tsverval is not null and hpa.persadres = pa.id and pa.pers = p.id and hpa.gem = g.id  and hpa.wpl = pl.id and lnd.id = hpa.land and  p.bsn = 677080426 order by hpa.tsverval asc, hpa.dataanvgel desc
--select hpa.id, hpa.actieinh, hpa.actieverval, hpa.actieaanpgel,   actie.id actie_id, actie.srt actie_srt, actie.partij actie_partij, actie.verdrag actie_verdrag, actie.TijdstipOntlening actie_ontlening, actie.TijdstipReg actie_tsreg , p.voornamen, p.geslnaam, hpa.dataanvgel, hpa.dateindegel, hpa.tsreg, hpa.dataanvadresh, g.naam gemeente, pl.naam plaats, hpa.postcode, hpa.nor, hpa.huisnr, hpa.huisletter, hpa.huisnrtoevoeging, lnd.naam  from   kern.actie actie, kern.his_persadres hpa, kern.persadres pa, kern.pers p, kern.partij g, kern.plaats pl, kern.land lnd   where lnd.id =pa.land and hpa.tsverval is null and hpa.persadres = pa.id and p.bsn = 677080426 and hpa.land = lnd.id and hpa.wpl = pl.id and pa.pers = p.id  and hpa.gem = g.id   and hpa.actieinh = actie.id  order by hpa.tsverval asc
--select hpa.id, p.voornamen, p.geslnaam, hpa.dataanvgel, hpa.dateindegel, hpa.tsreg, hpa.tsverval, hpa.dataanvadresh, g.naam gemeente, pl.naam plaats, hpa.postcode, hpa.nor, hpa.huisnr, hpa.huisletter, hpa.huisnrtoevoeging, lnd.naam from kern.his_persadres hpa, kern.persadres pa, kern.pers p, kern.partij g, kern.plaats pl, kern.land lnd   where hpa.tsverval is not null and hpa.persadres = pa.id and pa.pers = p.id and hpa.gem = g.id  and hpa.wpl = pl.id and lnd.id = hpa.land and  p.bsn = 677080426 order by hpa.tsverval asc, hpa.dataanvgel desc
select distinct padres1.srt, padres1.postcode, padres1.huisnr, prs.bsn from kern.pers prs, kern.persadres padres1 where prs.id in (select padres.id from kern.persadres padres where id in (select id from kern.pers )) order by padres1.postcode, padres1.huisnr;
