/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;

import nl.bzk.brp.testdatageneratie.Cacheable;


// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA

/**
 * Dbobject generated by hbm2java
 */
public class Dbobject implements Cacheable<System> {

    private int         id;
    private Srtdbobject srtdbobject;
    private Dbobject    dbobject;
    private String      naam;
    private String      javaidentifier;
    private Integer     dataanvgel;
    private Integer     dateindegel;

    public Dbobject() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public Srtdbobject getSrtdbobject() {
        return this.srtdbobject;
    }

    public void setSrtdbobject(final Srtdbobject srtdbobject) {
        this.srtdbobject = srtdbobject;
    }

    public Dbobject getDbobject() {
        return this.dbobject;
    }

    public void setDbobject(final Dbobject dbobject) {
        this.dbobject = dbobject;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(final String naam) {
        this.naam = naam;
    }

    public String getJavaidentifier() {
        return this.javaidentifier;
    }

    public void setJavaidentifier(final String javaidentifier) {
        this.javaidentifier = javaidentifier;
    }

    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(final Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(final Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Override
    public System getKey() {
        return null;
    }

}
