/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisDoelbinding generated by hbm2java
 */
public class HisDoelbinding extends His {


     private Actie actieByActieaanpgel;
     private Doelbinding doelbinding;
     private Protocolleringsniveau protocolleringsniveau;
     private String tekstdoelbinding;
     private String populatiecriterium;
     private boolean indverstrbeperkinghonoreren;

    public HisDoelbinding() {
    }

    public Actie getActieByActieaanpgel() {
        return this.actieByActieaanpgel;
    }

    public void setActieByActieaanpgel(final Actie actieByActieaanpgel) {
        this.actieByActieaanpgel = actieByActieaanpgel;
    }
    public Doelbinding getDoelbinding() {
        return this.doelbinding;
    }

    public void setDoelbinding(final Doelbinding doelbinding) {
        this.doelbinding = doelbinding;
    }
    public Protocolleringsniveau getProtocolleringsniveau() {
        return this.protocolleringsniveau;
    }

    public void setProtocolleringsniveau(final Protocolleringsniveau protocolleringsniveau) {
        this.protocolleringsniveau = protocolleringsniveau;
    }
    public String getTekstdoelbinding() {
        return this.tekstdoelbinding;
    }

    public void setTekstdoelbinding(final String tekstdoelbinding) {
        this.tekstdoelbinding = tekstdoelbinding;
    }
    public String getPopulatiecriterium() {
        return this.populatiecriterium;
    }

    public void setPopulatiecriterium(final String populatiecriterium) {
        this.populatiecriterium = populatiecriterium;
    }
    public boolean isIndverstrbeperkinghonoreren() {
        return this.indverstrbeperkinghonoreren;
    }

    public void setIndverstrbeperkinghonoreren(final boolean indverstrbeperkinghonoreren) {
        this.indverstrbeperkinghonoreren = indverstrbeperkinghonoreren;
    }




}


