/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersindicatie generated by hbm2java
 */
public class HisPersindicatie extends His {


     private Persindicatie persindicatie;
     private Actie actieByActieaanpgel;
     private boolean waarde;

    public HisPersindicatie() {
    }

    public HisPersindicatie(final Persindicatie persindicatie) {
        this.persindicatie = persindicatie;
        persindicatie.setPersindicatiestatushis(StatusHis.A);
        waarde = persindicatie.getWaarde();
    }
    
    public Persindicatie getPersindicatie() {
        return this.persindicatie;
    }

    public void setPersindicatie(final Persindicatie persindicatie) {
        this.persindicatie = persindicatie;
    }
    public Actie getActieByActieaanpgel() {
        return this.actieByActieaanpgel;
    }

    public void setActieByActieaanpgel(final Actie actieByActieaanpgel) {
        this.actieByActieaanpgel = actieByActieaanpgel;
    }
    public boolean isWaarde() {
        return this.waarde;
    }

    public void setWaarde(final boolean waarde) {
        this.waarde = waarde;
    }




}


