/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisRelatie generated by hbm2java
 */
public class HisRelatie extends His {


     private Plaats plaatsByWplaanv;
     private Partij partijByGemeinde;
     private Plaats plaatsByWpleinde;
     private Relatie relatie;
     private Rdnbeeindrelatie rdnbeeindrelatie;
     private Partij partijByGemaanv;
     private Land landByLandaanv;
     private Land landByLandeinde;
     private int dataanv;
     private String blplaatsaanv;
     private String blregioaanv;
     private String omslocaanv;
     private Integer dateinde;
     private String blplaatseinde;
     private String blregioeinde;
     private String omsloceinde;

    public HisRelatie() {
    }

    public HisRelatie(final Relatie relatie) {
        this.relatie = relatie;
        relatie.setRelatiestatushis(StatusHis.A);
        this.plaatsByWplaanv = relatie.getPlaatsByWplaanv();
        this.partijByGemeinde = relatie.getPartijByGemeinde();
        this.plaatsByWpleinde = relatie.getPlaatsByWpleinde();
        this.rdnbeeindrelatie = relatie.getRdnbeeindrelatie();
        this.partijByGemaanv = relatie.getPartijByGemaanv();
        this.landByLandaanv = relatie.getLandByLandaanv();
        this.landByLandeinde = relatie.getLandByLandeinde();
        this.blplaatsaanv = relatie.getBlplaatsaanv();
        this.blregioaanv = relatie.getBlregioaanv();
        this.omslocaanv = relatie.getOmslocaanv();
        this.blplaatseinde = relatie.getBlplaatseinde();
        this.blregioeinde = relatie.getBlregioeinde();
        this.omsloceinde = relatie.getOmsloceinde();
    }
   
    public Plaats getPlaatsByWplaanv() {
        return this.plaatsByWplaanv;
    }
    
    public void setPlaatsByWplaanv(Plaats plaatsByWplaanv) {
        this.plaatsByWplaanv = plaatsByWplaanv;
    }
    public Partij getPartijByGemeinde() {
        return this.partijByGemeinde;
    }
    
    public void setPartijByGemeinde(Partij partijByGemeinde) {
        this.partijByGemeinde = partijByGemeinde;
    }
    public Plaats getPlaatsByWpleinde() {
        return this.plaatsByWpleinde;
    }
    
    public void setPlaatsByWpleinde(Plaats plaatsByWpleinde) {
        this.plaatsByWpleinde = plaatsByWpleinde;
    }
    public Relatie getRelatie() {
        return this.relatie;
    }
    
    public void setRelatie(Relatie relatie) {
        this.relatie = relatie;
    }
    public Rdnbeeindrelatie getRdnbeeindrelatie() {
        return this.rdnbeeindrelatie;
    }
    
    public void setRdnbeeindrelatie(Rdnbeeindrelatie rdnbeeindrelatie) {
        this.rdnbeeindrelatie = rdnbeeindrelatie;
    }
    public Partij getPartijByGemaanv() {
        return this.partijByGemaanv;
    }
    
    public void setPartijByGemaanv(Partij partijByGemaanv) {
        this.partijByGemaanv = partijByGemaanv;
    }
    public Land getLandByLandaanv() {
        return this.landByLandaanv;
    }
    
    public void setLandByLandaanv(Land landByLandaanv) {
        this.landByLandaanv = landByLandaanv;
    }
    public Land getLandByLandeinde() {
        return this.landByLandeinde;
    }
    
    public void setLandByLandeinde(Land landByLandeinde) {
        this.landByLandeinde = landByLandeinde;
    }
    public int getDataanv() {
        return this.dataanv;
    }
    
    public void setDataanv(int dataanv) {
        this.dataanv = dataanv;
    }
    public String getBlplaatsaanv() {
        return this.blplaatsaanv;
    }
    
    public void setBlplaatsaanv(String blplaatsaanv) {
        this.blplaatsaanv = blplaatsaanv;
    }
    public String getBlregioaanv() {
        return this.blregioaanv;
    }
    
    public void setBlregioaanv(String blregioaanv) {
        this.blregioaanv = blregioaanv;
    }
    public String getOmslocaanv() {
        return this.omslocaanv;
    }
    
    public void setOmslocaanv(String omslocaanv) {
        this.omslocaanv = omslocaanv;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }
    
    public void setDateinde(Integer dateinde) {
        this.dateinde = dateinde;
    }
    public String getBlplaatseinde() {
        return this.blplaatseinde;
    }
    
    public void setBlplaatseinde(String blplaatseinde) {
        this.blplaatseinde = blplaatseinde;
    }
    public String getBlregioeinde() {
        return this.blregioeinde;
    }
    
    public void setBlregioeinde(String blregioeinde) {
        this.blregioeinde = blregioeinde;
    }
    public String getOmsloceinde() {
        return this.omsloceinde;
    }
    
    public void setOmsloceinde(String omsloceinde) {
        this.omsloceinde = omsloceinde;
    }




}


