/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;

// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA

/**
 * Persvoornaam generated by hbm2java
 */
public class Persvoornaam implements java.io.Serializable {

    private int       id;
    private Pers      pers;
    private String    naam;
    private StatusHis persvoornaamstatushis = StatusHis.X;
    private int       volgnr;

    public Persvoornaam() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public Pers getPers() {
        return this.pers;
    }

    public void setPers(final Pers pers) {
        this.pers = pers;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(final String naam) {
        this.naam = naam;
    }

    public StatusHis getPersvoornaamstatushis() {
        return this.persvoornaamstatushis;
    }

    public void setPersvoornaamstatushis(final StatusHis persvoornaamstatushis) {
        this.persvoornaamstatushis = persvoornaamstatushis;
    }

    public int getVolgnr() {
        return this.volgnr;
    }

    public void setVolgnr(final int volgnr) {
        this.volgnr = volgnr;
    }

}
