ALTER TABLE "lev"."levpers" ADD CONSTRAINT "r4851" UNIQUE (lev, pers);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "r4849" UNIQUE (lev, uitgaandber);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "r5606" UNIQUE (abonnementsrtber, tsreg);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "r4958" UNIQUE (abonnement, tsreg);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "r5608" UNIQUE (abonnement, srtber);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "r4986" UNIQUE (abonnement, gegevenselement);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "r4984" UNIQUE (doelbinding, srtabonnement);
ALTER TABLE "kern"."wijzegebruikgeslnaam" ADD CONSTRAINT "r4454" UNIQUE (naam);
ALTER TABLE "kern"."verblijfstitel" ADD CONSTRAINT "r4442" UNIQUE (oms);
ALTER TABLE "kern"."verantwoordelijke" ADD CONSTRAINT "r4444" UNIQUE (naam);
ALTER TABLE "kern"."srtrelatie" ADD CONSTRAINT "r4426" UNIQUE (naam);
ALTER TABLE "kern"."srtpers" ADD CONSTRAINT "r4487" UNIQUE (naam);
ALTER TABLE "kern"."srtnlreisdoc" ADD CONSTRAINT "r4465" UNIQUE (oms);
ALTER TABLE "kern"."srtbetr" ADD CONSTRAINT "r4478" UNIQUE (naam);
ALTER TABLE "kern"."srtadmhnd" ADD CONSTRAINT "r9261" UNIQUE (naam);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "r6052" UNIQUE (oms);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "r6051" UNIQUE (specificatie);
ALTER TABLE "kern"."rdnwijzadres" ADD CONSTRAINT "r4462" UNIQUE (naam);
ALTER TABLE "kern"."rdnvervallenreisdoc" ADD CONSTRAINT "r4471" UNIQUE (naam);
ALTER TABLE "kern"."rdnverknlnation" ADD CONSTRAINT "r4431" UNIQUE (oms);
ALTER TABLE "kern"."rdnopschorting" ADD CONSTRAINT "r4451" UNIQUE (naam);
ALTER TABLE "kern"."rdnbeeindrelatie" ADD CONSTRAINT "r4429" UNIQUE (oms);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "r4409" UNIQUE (naamvrouwelijk);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "r4408" UNIQUE (naammannelijk);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "r4394" UNIQUE (pers, volgnr);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "r6138" UNIQUE (onderzoek, pers);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "r4415" UNIQUE (pers, nation);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "r4456" UNIQUE (pers, srt);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "r4392" UNIQUE (pers, volgnr);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "r4688" UNIQUE (partij, rol);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "r4418" UNIQUE (naam);
ALTER TABLE "kern"."his_verstrderde" ADD CONSTRAINT "r9369" UNIQUE (verstrderde, tsreg);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "r4368" UNIQUE (persvoornaam, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "r4358" UNIQUE (persverificatie, tsreg);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "r4170" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "r4178" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "r4114" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "r4351" UNIQUE (persreisdoc, tsreg);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "r4224" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "r4157" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "r4204" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "r4335" UNIQUE (persnation, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "r4248" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "r4324" UNIQUE (persindicatie, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "r4235" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "r4087" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "r4314" UNIQUE (persgeslnaamcomp, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "r4097" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "r4144" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "r4187" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "r9363" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "r4197" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "r4216" UNIQUE (pers, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "r6073" UNIQUE (persadres, tsreg, dataanvgel);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "r4131" UNIQUE (pers, tsreg);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "r6122" UNIQUE (partij, tsreg);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "r4628" UNIQUE (partij, tsreg);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "r4032" UNIQUE (betr, tsreg, dataanvgel);
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "r4042" UNIQUE (betr, tsreg, dataanvgel);
ALTER TABLE "kern"."his_ontkenningouderschaponge" ADD CONSTRAINT "r9417" UNIQUE (relatie, tsreg);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "r4076" UNIQUE (onderzoek, tsreg);
ALTER TABLE "kern"."his_naamskeuzeongeborenvruch" ADD CONSTRAINT "r9410" UNIQUE (relatie, tsreg);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "r5477" UNIQUE (multirealiteitregel, tsreg);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "r4389" UNIQUE (relatie, tsreg);
ALTER TABLE "kern"."his_erkenningongeborenvrucht" ADD CONSTRAINT "r9424" UNIQUE (relatie, tsreg);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "r4052" UNIQUE (doc, tsreg);
ALTER TABLE "kern"."geslachtsaand" ADD CONSTRAINT "r4484" UNIQUE (naam);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "r4480" UNIQUE (onderzoek, srtgegeven);
ALTER TABLE "kern"."functieadres" ADD CONSTRAINT "r4436" UNIQUE (naam);
ALTER TABLE "kern"."element" ADD CONSTRAINT "r4423" UNIQUE (srt, naam, ouder);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "r6105" UNIQUE (relatie, pers);
ALTER TABLE "kern"."autvanafgiftereisdoc" ADD CONSTRAINT "r4468" UNIQUE (oms);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "r4413" UNIQUE (naamvrouwelijk);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "r4411" UNIQUE (naammannelijk);
ALTER TABLE "kern"."actiebron" ADD CONSTRAINT "r9176" UNIQUE (actie, doc, rechtsgrond);
ALTER TABLE "kern"."aangadresh" ADD CONSTRAINT "r4439" UNIQUE (naam);
ALTER TABLE "brm"."srtregel" ADD CONSTRAINT "r5975" UNIQUE (oms);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "r6062" UNIQUE (regel, srtber);
ALTER TABLE "brm"."regeleffect" ADD CONSTRAINT "r5980" UNIQUE (oms);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "r5972" UNIQUE (regelsituatie, tsreg);
ALTER TABLE "ber"."bijhresultaat" ADD CONSTRAINT "r9425" UNIQUE (naam);
ALTER TABLE "ber"."admhnddoc" ADD CONSTRAINT "r9527" UNIQUE (admhnd, doc);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "r5792" UNIQUE (bijhautorisatie, uitgeslotenpartij);
ALTER TABLE "autaut"."srtautorisatiebesluit" ADD CONSTRAINT "r4988" UNIQUE (oms);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "r4992" UNIQUE (oms);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "r4991" UNIQUE (naam);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "r5789" UNIQUE (uitgeslotene, tsreg);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "r4977" UNIQUE (doelbinding, tsreg, dataanvgel);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "r5745" UNIQUE (bijhsituatie, tsreg);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "r5739" UNIQUE (bijhautorisatie, tsreg);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "r5729" UNIQUE (autorisatiebesluit, tsreg);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "r4965" UNIQUE (autorisatiebesluit, tsreg);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "r4687" UNIQUE (authenticatiemiddel, tsreg);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "r4982" UNIQUE (doelbinding, gegevenselement);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "r4980" UNIQUE (geautoriseerde, levsautorisatiebesluit);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "r5037" UNIQUE (signature);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "r4728" UNIQUE (subject, serial);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "r5749" UNIQUE (bijhautorisatie, srtadmhnd, srtdoc);
ALTER TABLE "lev"."srtlev" ADD CONSTRAINT "r4829" PRIMARY KEY (id);
ALTER TABLE "lev"."srtabonnement" ADD CONSTRAINT "r4993" PRIMARY KEY (id);
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "r4850" PRIMARY KEY (id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "r4848" PRIMARY KEY (id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "r4828" PRIMARY KEY (id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "r5611" PRIMARY KEY (id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "r4997" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "r5607" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "r4985" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "r4983" PRIMARY KEY (id);
ALTER TABLE "kern"."wijzegebruikgeslnaam" ADD CONSTRAINT "r4452" PRIMARY KEY (id);
ALTER TABLE "kern"."voorvoegsel" ADD CONSTRAINT "r9270" PRIMARY KEY (id);
ALTER TABLE "kern"."verstrderde" ADD CONSTRAINT "r9371" PRIMARY KEY (id);
ALTER TABLE "kern"."verblijfstitel" ADD CONSTRAINT "r4441" PRIMARY KEY (id);
ALTER TABLE "kern"."verantwoordelijke" ADD CONSTRAINT "r4443" PRIMARY KEY (id);
ALTER TABLE "kern"."srtverificatie" ADD CONSTRAINT "r4472" PRIMARY KEY (id);
ALTER TABLE "kern"."srtrelatie" ADD CONSTRAINT "r4425" PRIMARY KEY (id);
ALTER TABLE "kern"."srtrechtsgrond" ADD CONSTRAINT "r9178" PRIMARY KEY (id);
ALTER TABLE "kern"."srtpers" ADD CONSTRAINT "r4485" PRIMARY KEY (id);
ALTER TABLE "kern"."srtpartij" ADD CONSTRAINT "r4493" PRIMARY KEY (id);
ALTER TABLE "kern"."srtnlreisdoc" ADD CONSTRAINT "r4463" PRIMARY KEY (id);
ALTER TABLE "kern"."srtmultirealiteitregel" ADD CONSTRAINT "r4489" PRIMARY KEY (id);
ALTER TABLE "kern"."srtindicatie" ADD CONSTRAINT "r4447" PRIMARY KEY (id);
ALTER TABLE "kern"."srtelement" ADD CONSTRAINT "r4457" PRIMARY KEY (id);
ALTER TABLE "kern"."srtdoc" ADD CONSTRAINT "r4419" PRIMARY KEY (id);
ALTER TABLE "kern"."srtdbobject" ADD CONSTRAINT "r5660" PRIMARY KEY (id);
ALTER TABLE "kern"."srtbetr" ADD CONSTRAINT "r4476" PRIMARY KEY (id);
ALTER TABLE "kern"."srtadmhnd" ADD CONSTRAINT "r9260" PRIMARY KEY (id);
ALTER TABLE "kern"."srtactie" ADD CONSTRAINT "r4401" PRIMARY KEY (id);
ALTER TABLE "kern"."sector" ADD CONSTRAINT "r4494" PRIMARY KEY (id);
ALTER TABLE "kern"."rol" ADD CONSTRAINT "r4491" PRIMARY KEY (id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "r4424" PRIMARY KEY (id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "r6158" PRIMARY KEY (id);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "r5811" PRIMARY KEY (id);
ALTER TABLE "kern"."rechtsgrond" ADD CONSTRAINT "r9177" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnwijzadres" ADD CONSTRAINT "r4460" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnvervallenreisdoc" ADD CONSTRAINT "r4469" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnverliesnlnation" ADD CONSTRAINT "r4432" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnverknlnation" ADD CONSTRAINT "r4430" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnopschorting" ADD CONSTRAINT "r4449" PRIMARY KEY (id);
ALTER TABLE "kern"."rdnbeeindrelatie" ADD CONSTRAINT "r4428" PRIMARY KEY (id);
ALTER TABLE "kern"."predikaat" ADD CONSTRAINT "r4406" PRIMARY KEY (id);
ALTER TABLE "kern"."plaats" ADD CONSTRAINT "r4397" PRIMARY KEY (id);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "r4393" PRIMARY KEY (id);
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "r4459" PRIMARY KEY (id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "r4446" PRIMARY KEY (id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "r6137" PRIMARY KEY (id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "r4414" PRIMARY KEY (id);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "r4455" PRIMARY KEY (id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "r4391" PRIMARY KEY (id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "r4434" PRIMARY KEY (id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "r4390" PRIMARY KEY (id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "r4495" PRIMARY KEY (id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "r4417" PRIMARY KEY (id);
ALTER TABLE "kern"."onderzoek" ADD CONSTRAINT "r4421" PRIMARY KEY (id);
ALTER TABLE "kern"."nation" ADD CONSTRAINT "r4404" PRIMARY KEY (id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "r4488" PRIMARY KEY (id);
ALTER TABLE "kern"."land" ADD CONSTRAINT "r4399" PRIMARY KEY (id);
ALTER TABLE "kern"."his_verstrderde" ADD CONSTRAINT "r9377" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "r4594" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "r4591" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "r4543" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "r4546" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "r4531" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "r4588" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "r4561" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "r4540" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "r4555" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "r4585" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "r4567" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "r4582" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "r4564" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "r4525" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "r4579" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "r4528" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "r4537" PRIMARY KEY (id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "r4549" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "r9374" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "r4552" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "r4558" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "r6076" PRIMARY KEY (id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "r4534" PRIMARY KEY (id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "r6125" PRIMARY KEY (id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "r4631" PRIMARY KEY (id);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "r4510" PRIMARY KEY (id);
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "r4513" PRIMARY KEY (id);
ALTER TABLE "kern"."his_ontkenningouderschaponge" ADD CONSTRAINT "r9431" PRIMARY KEY (id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "r4522" PRIMARY KEY (id);
ALTER TABLE "kern"."his_naamskeuzeongeborenvruch" ADD CONSTRAINT "r9428" PRIMARY KEY (id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "r5480" PRIMARY KEY (id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "r4597" PRIMARY KEY (id);
ALTER TABLE "kern"."his_erkenningongeborenvrucht" ADD CONSTRAINT "r9434" PRIMARY KEY (id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "r4516" PRIMARY KEY (id);
ALTER TABLE "kern"."geslachtsaand" ADD CONSTRAINT "r4482" PRIMARY KEY (id);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "r4507" PRIMARY KEY (id);
ALTER TABLE "kern"."functieadres" ADD CONSTRAINT "r4435" PRIMARY KEY (id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "r4422" PRIMARY KEY (id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "r4416" PRIMARY KEY (id);
ALTER TABLE "kern"."dbversion" ADD CONSTRAINT "pk_dbversion" PRIMARY KEY (id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "r5659" PRIMARY KEY (id);
ALTER TABLE "kern"."categoriepersonen" ADD CONSTRAINT "r6169" PRIMARY KEY (id);
ALTER TABLE "kern"."bvp" ADD CONSTRAINT "r9370" PRIMARY KEY (id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "r6104" PRIMARY KEY (id);
ALTER TABLE "kern"."autvanafgiftereisdoc" ADD CONSTRAINT "r4466" PRIMARY KEY (id);
ALTER TABLE "kern"."admhnd" ADD CONSTRAINT "r9179" PRIMARY KEY (id);
ALTER TABLE "kern"."adellijketitel" ADD CONSTRAINT "r4410" PRIMARY KEY (id);
ALTER TABLE "kern"."actiebron" ADD CONSTRAINT "r9175" PRIMARY KEY (id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "r4403" PRIMARY KEY (id);
ALTER TABLE "kern"."aangadresh" ADD CONSTRAINT "r4438" PRIMARY KEY (id);
ALTER TABLE "brm"."srtregel" ADD CONSTRAINT "r5973" PRIMARY KEY (id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "r6060" PRIMARY KEY (id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "r5976" PRIMARY KEY (id);
ALTER TABLE "brm"."regeleffect" ADD CONSTRAINT "r5978" PRIMARY KEY (id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "r5989" PRIMARY KEY (id);
ALTER TABLE "ber"."verwerkingsresultaat" ADD CONSTRAINT "r6322" PRIMARY KEY (id);
ALTER TABLE "ber"."srtmelding" ADD CONSTRAINT "r6317" PRIMARY KEY (id);
ALTER TABLE "ber"."srtber" ADD CONSTRAINT "r5027" PRIMARY KEY (id);
ALTER TABLE "ber"."richting" ADD CONSTRAINT "r5635" PRIMARY KEY (id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "r6316" PRIMARY KEY (id);
ALTER TABLE "ber"."gedeblokkeerdemelding" ADD CONSTRAINT "r6320" PRIMARY KEY (id);
ALTER TABLE "ber"."burgerzakenmodule" ADD CONSTRAINT "r9528" PRIMARY KEY (id);
ALTER TABLE "ber"."bijhresultaat" ADD CONSTRAINT "r6324" PRIMARY KEY (id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "r6319" PRIMARY KEY (id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "r4827" PRIMARY KEY (id);
ALTER TABLE "ber"."admhndgedeblokkeerdemelding" ADD CONSTRAINT "r6321" PRIMARY KEY (id);
ALTER TABLE "ber"."admhnddoc" ADD CONSTRAINT "r9531" PRIMARY KEY (id);
ALTER TABLE "ber"."admhndbijgehoudenpers" ADD CONSTRAINT "r6326" PRIMARY KEY (id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "r5791" PRIMARY KEY (id);
ALTER TABLE "autaut"."toestand" ADD CONSTRAINT "r5746" PRIMARY KEY (id);
ALTER TABLE "autaut"."srtbevoegdheid" ADD CONSTRAINT "r5750" PRIMARY KEY (id);
ALTER TABLE "autaut"."srtautorisatiebesluit" ADD CONSTRAINT "r4987" PRIMARY KEY (id);
ALTER TABLE "autaut"."protocolleringsniveau" ADD CONSTRAINT "r4990" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "r5795" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "r5003" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "r5760" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "r5757" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "r5754" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "r5000" PRIMARY KEY (id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "r4691" PRIMARY KEY (id);
ALTER TABLE "autaut"."functie" ADD CONSTRAINT "r4725" PRIMARY KEY (id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "r4981" PRIMARY KEY (id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "r4979" PRIMARY KEY (id);
ALTER TABLE "autaut"."certificaat" ADD CONSTRAINT "r4727" PRIMARY KEY (id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "r5748" PRIMARY KEY (id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "r5747" PRIMARY KEY (id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "r4978" PRIMARY KEY (id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "r4497" PRIMARY KEY (id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "abonnementsrtber_abonnementsrtberstatushis_check" CHECK (((abonnementsrtberstatushis IS NULL) OR ((abonnementsrtberstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "abonnement_abonnementstatushis_check" CHECK (((abonnementstatushis IS NULL) OR ((abonnementstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."verstrderde" ADD CONSTRAINT "verstrderde_verstrderdestatushis_check" CHECK (((verstrderdestatushis IS NULL) OR ((verstrderdestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "relatie_ontkenningouderschapongebore_check" CHECK (((ontkenningouderschapongebore IS NULL) OR ((ontkenningouderschapongebore)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "relatie_naamskeuzeongeborenvruchtsta_check" CHECK (((naamskeuzeongeborenvruchtsta IS NULL) OR ((naamskeuzeongeborenvruchtsta)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "relatie_huwelijkgeregistreerdpartner_check" CHECK (((huwelijkgeregistreerdpartner IS NULL) OR ((huwelijkgeregistreerdpartner)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "relatie_erkenningongeborenvruchtstat_check" CHECK (((erkenningongeborenvruchtstat IS NULL) OR ((erkenningongeborenvruchtstat)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "persvoornaam_persvoornaamstatushis_check" CHECK (((persvoornaamstatushis IS NULL) OR ((persvoornaamstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "persverificatie_persverificatiestatushis_check" CHECK (((persverificatiestatushis IS NULL) OR ((persverificatiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "persreisdoc_persreisdocstatushis_check" CHECK (((persreisdocstatushis IS NULL) OR ((persreisdocstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "persnation_persnationstatushis_check" CHECK (((persnationstatushis IS NULL) OR ((persnationstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "persindicatie_waarde_check" CHECK (((waarde IS NULL) OR (waarde = true)));
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "persindicatie_persindicatiestatushis_check" CHECK (((persindicatiestatushis IS NULL) OR ((persindicatiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "persgeslnaamcomp_persgeslnaamcompstatushis_check" CHECK (((persgeslnaamcompstatushis IS NULL) OR ((persgeslnaamcompstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "persadres_persadresstatushis_check" CHECK (((persadresstatushis IS NULL) OR ((persadresstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "persadres_loctovadres_check" CHECK (((loctovadres IS NULL) OR ((loctovadres)::text = ANY (ARRAY[('by'::character varying)::text, ('to'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_verblijfstitelstatushis_check" CHECK (((verblijfstitelstatushis IS NULL) OR ((verblijfstitelstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_uitslnlkiesrstatushis_check" CHECK (((uitslnlkiesrstatushis IS NULL) OR ((uitslnlkiesrstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_samengesteldenaamstatushis_check" CHECK (((samengesteldenaamstatushis IS NULL) OR ((samengesteldenaamstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_pkstatushis_check" CHECK (((pkstatushis IS NULL) OR ((pkstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_overlijdenstatushis_check" CHECK (((overlijdenstatushis IS NULL) OR ((overlijdenstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_opschortingstatushis_check" CHECK (((opschortingstatushis IS NULL) OR ((opschortingstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_inschrstatushis_check" CHECK (((inschrstatushis IS NULL) OR ((inschrstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_induitslnlkiesr_check" CHECK (((induitslnlkiesr IS NULL) OR (induitslnlkiesr = true)));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_immigratiestatushis_check" CHECK (((immigratiestatushis IS NULL) OR ((immigratiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_idsstatushis_check" CHECK (((idsstatushis IS NULL) OR ((idsstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_geslachtsaandstatushis_check" CHECK (((geslachtsaandstatushis IS NULL) OR ((geslachtsaandstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_geboortestatushis_check" CHECK (((geboortestatushis IS NULL) OR ((geboortestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_euverkiezingenstatushis_check" CHECK (((euverkiezingenstatushis IS NULL) OR ((euverkiezingenstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_bvpstatushis_check" CHECK (((bvpstatushis IS NULL) OR ((bvpstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_bijhverantwoordelijkheidstat_check" CHECK (((bijhverantwoordelijkheidstat IS NULL) OR ((bijhverantwoordelijkheidstat)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_bijhgemstatushis_check" CHECK (((bijhgemstatushis IS NULL) OR ((bijhgemstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."pers" ADD CONSTRAINT "pers_aanschrstatushis_check" CHECK (((aanschrstatushis IS NULL) OR ((aanschrstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "partijrol_partijrolstatushis_check" CHECK (((partijrolstatushis IS NULL) OR ((partijrolstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."partij" ADD CONSTRAINT "partij_partijstatushis_check" CHECK (((partijstatushis IS NULL) OR ((partijstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."partij" ADD CONSTRAINT "partij_gemstatushis_check" CHECK (((gemstatushis IS NULL) OR ((gemstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."onderzoek" ADD CONSTRAINT "onderzoek_onderzoekstatushis_check" CHECK (((onderzoekstatushis IS NULL) OR ((onderzoekstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "multirealiteitregel_multirealiteitregelstatushis_check" CHECK (((multirealiteitregelstatushis IS NULL) OR ((multirealiteitregelstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "his_persuitslnlkiesr_induitslnlkiesr_check" CHECK (((induitslnlkiesr IS NULL) OR (induitslnlkiesr = true)));
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "his_persindicatie_waarde_check" CHECK (((waarde IS NULL) OR (waarde = true)));
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "his_persadres_loctovadres_check" CHECK (((loctovadres IS NULL) OR ((loctovadres)::text = ANY (ARRAY[('by'::character varying)::text, ('to'::character varying)::text]))));
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "his_ouderouderschap_ouderuitwiekindisvoortgekome_check" CHECK (((ouderuitwiekindisvoortgekome IS NULL) OR (ouderuitwiekindisvoortgekome = true)));
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "his_ouderouderschap_indouder_check" CHECK (((indouder IS NULL) OR (indouder = true)));
ALTER TABLE "kern"."doc" ADD CONSTRAINT "doc_docstatushis_check" CHECK (((docstatushis IS NULL) OR ((docstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."betr" ADD CONSTRAINT "betr_ouderuitwiekindisvoortgekome_check" CHECK (((ouderuitwiekindisvoortgekome IS NULL) OR (ouderuitwiekindisvoortgekome = true)));
ALTER TABLE "kern"."betr" ADD CONSTRAINT "betr_ouderschapstatushis_check" CHECK (((ouderschapstatushis IS NULL) OR ((ouderschapstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."betr" ADD CONSTRAINT "betr_ouderlijkgezagstatushis_check" CHECK (((ouderlijkgezagstatushis IS NULL) OR ((ouderlijkgezagstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "kern"."betr" ADD CONSTRAINT "betr_indouder_check" CHECK (((indouder IS NULL) OR (indouder = true)));
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "regelsituatie_regelsituatiestatushis_check" CHECK (((regelsituatiestatushis IS NULL) OR ((regelsituatiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "ber"."ber" ADD CONSTRAINT "ber_verwerkingswijze_check" CHECK (((verwerkingswijze IS NULL) OR ((verwerkingswijze)::text = ANY (ARRAY[('B'::character varying)::text, ('P'::character varying)::text]))));
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "uitgeslotene_uitgeslotenestatushis_check" CHECK (((uitgeslotenestatushis IS NULL) OR ((uitgeslotenestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "doelbinding_doelbindingstatushis_check" CHECK (((doelbindingstatushis IS NULL) OR ((doelbindingstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "bijhsituatie_bijhsituatiestatushis_check" CHECK (((bijhsituatiestatushis IS NULL) OR ((bijhsituatiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "bijhautorisatie_bijhautorisatiestatushis_check" CHECK (((bijhautorisatiestatushis IS NULL) OR ((bijhautorisatiestatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "autorisatiebesluit_bijhautorisatiebesluitstatus_check" CHECK (((bijhautorisatiebesluitstatus IS NULL) OR ((bijhautorisatiebesluitstatus)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "autorisatiebesluit_autorisatiebesluitstatushis_check" CHECK (((autorisatiebesluitstatushis IS NULL) OR ((autorisatiebesluitstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "authenticatiemiddel_authenticatiemiddelstatushis_check" CHECK (((authenticatiemiddelstatushis IS NULL) OR ((authenticatiemiddelstatushis)::text = ANY (ARRAY[('A'::character varying)::text, ('T'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text, ('X'::character varying)::text]))));
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "fk4843" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "lev"."levpers" ADD CONSTRAINT "fk4842" FOREIGN KEY (lev) REFERENCES lev.lev(id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "fk4836" FOREIGN KEY (uitgaandber) REFERENCES ber.ber(id);
ALTER TABLE "lev"."levcommunicatie" ADD CONSTRAINT "fk4835" FOREIGN KEY (lev) REFERENCES lev.lev(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk5670" FOREIGN KEY (gebaseerdop) REFERENCES ber.ber(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk5626" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk4821" FOREIGN KEY (authenticatiemiddel) REFERENCES autaut.authenticatiemiddel(id);
ALTER TABLE "lev"."lev" ADD CONSTRAINT "fk4820" FOREIGN KEY (srt) REFERENCES lev.srtlev(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5605" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5604" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnementsrtber" ADD CONSTRAINT "fk5601" FOREIGN KEY (abonnementsrtber) REFERENCES lev.abonnementsrtber(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4956" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4955" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "lev"."his_abonnement" ADD CONSTRAINT "fk4952" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "fk5597" FOREIGN KEY (srtber) REFERENCES ber.srtber(id);
ALTER TABLE "lev"."abonnementsrtber" ADD CONSTRAINT "fk5596" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "fk4908" FOREIGN KEY (gegevenselement) REFERENCES kern.dbobject(id);
ALTER TABLE "lev"."abonnementgegevenselement" ADD CONSTRAINT "fk4907" FOREIGN KEY (abonnement) REFERENCES lev.abonnement(id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "fk4903" FOREIGN KEY (srtabonnement) REFERENCES lev.srtabonnement(id);
ALTER TABLE "lev"."abonnement" ADD CONSTRAINT "fk4902" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "kern"."verstrderde" ADD CONSTRAINT "fk9352" FOREIGN KEY (derde) REFERENCES kern.partij(id);
ALTER TABLE "kern"."verstrderde" ADD CONSTRAINT "fk9351" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."srtadmhnd" ADD CONSTRAINT "fk9532" FOREIGN KEY (module) REFERENCES ber.burgerzakenmodule(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3768" FOREIGN KEY (landeinde) REFERENCES kern.land(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3764" FOREIGN KEY (wpleinde) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3763" FOREIGN KEY (gemeinde) REFERENCES kern.partij(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3760" FOREIGN KEY (landaanv) REFERENCES kern.land(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3756" FOREIGN KEY (wplaanv) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3755" FOREIGN KEY (gemaanv) REFERENCES kern.partij(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3207" FOREIGN KEY (rdneinde) REFERENCES kern.rdnbeeindrelatie(id);
ALTER TABLE "kern"."relatie" ADD CONSTRAINT "fk3198" FOREIGN KEY (srt) REFERENCES kern.srtrelatie(id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "fk6152" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "kern"."regelverantwoording" ADD CONSTRAINT "fk6149" FOREIGN KEY (actie) REFERENCES kern.actie(id);
ALTER TABLE "kern"."regel" ADD CONSTRAINT "fk5990" FOREIGN KEY (srt) REFERENCES brm.srtregel(id);
ALTER TABLE "kern"."rechtsgrond" ADD CONSTRAINT "fk8141" FOREIGN KEY (srt) REFERENCES kern.srtrechtsgrond(id);
ALTER TABLE "kern"."persvoornaam" ADD CONSTRAINT "fk3023" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "fk3779" FOREIGN KEY (srt) REFERENCES kern.srtverificatie(id);
ALTER TABLE "kern"."persverificatie" ADD CONSTRAINT "fk2142" FOREIGN KEY (geverifieerde) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk9188" FOREIGN KEY (landautaangifte) REFERENCES kern.land(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk9186" FOREIGN KEY (gemautafgifte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3752" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3747" FOREIGN KEY (rdnvervallen) REFERENCES kern.rdnvervallenreisdoc(id);
ALTER TABLE "kern"."persreisdoc" ADD CONSTRAINT "fk3739" FOREIGN KEY (srt) REFERENCES kern.srtnlreisdoc(id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "fk6132" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."personderzoek" ADD CONSTRAINT "fk6131" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3230" FOREIGN KEY (rdnverlies) REFERENCES kern.rdnverliesnlnation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3229" FOREIGN KEY (rdnverk) REFERENCES kern.rdnverknlnation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3131" FOREIGN KEY (nation) REFERENCES kern.nation(id);
ALTER TABLE "kern"."persnation" ADD CONSTRAINT "fk3130" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "fk3658" FOREIGN KEY (srt) REFERENCES kern.srtindicatie(id);
ALTER TABLE "kern"."persindicatie" ADD CONSTRAINT "fk3657" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3118" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3117" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."persgeslnaamcomp" ADD CONSTRAINT "fk3024" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3788" FOREIGN KEY (gem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3715" FOREIGN KEY (rdnwijz) REFERENCES kern.rdnwijzadres(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3301" FOREIGN KEY (aangadresh) REFERENCES kern.aangadresh(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3289" FOREIGN KEY (land) REFERENCES kern.land(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3282" FOREIGN KEY (wpl) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3263" FOREIGN KEY (srt) REFERENCES kern.functieadres(id);
ALTER TABLE "kern"."persadres" ADD CONSTRAINT "fk3241" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk9322" FOREIGN KEY (bvp) REFERENCES kern.bvp(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk6113" FOREIGN KEY (adellijketitelaanschr) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3703" FOREIGN KEY (predikaataanschr) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3676" FOREIGN KEY (wplgeboorte) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3675" FOREIGN KEY (gemgeboorte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3667" FOREIGN KEY (volgendepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3666" FOREIGN KEY (vorigepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3663" FOREIGN KEY (rdnopschortingbijhouding) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3593" FOREIGN KEY (naamgebruik) REFERENCES kern.wijzegebruikgeslnaam(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3579" FOREIGN KEY (landvanwaargevestigd) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3573" FOREIGN KEY (bijhgem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3568" FOREIGN KEY (verantwoordelijke) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3558" FOREIGN KEY (landoverlijden) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3551" FOREIGN KEY (gemoverlijden) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3544" FOREIGN KEY (wploverlijden) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3543" FOREIGN KEY (landgeboorte) REFERENCES kern.land(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3310" FOREIGN KEY (verblijfstitel) REFERENCES kern.verblijfstitel(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3233" FOREIGN KEY (gempk) REFERENCES kern.partij(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk3031" FOREIGN KEY (geslachtsaand) REFERENCES kern.geslachtsaand(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1997" FOREIGN KEY (srt) REFERENCES kern.srtpers(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1969" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."pers" ADD CONSTRAINT "fk1968" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "fk2186" FOREIGN KEY (rol) REFERENCES kern.rol(id);
ALTER TABLE "kern"."partijrol" ADD CONSTRAINT "fk2185" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk4602" FOREIGN KEY (onderdeelvan) REFERENCES kern.partij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2196" FOREIGN KEY (sector) REFERENCES kern.sector(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2195" FOREIGN KEY (srt) REFERENCES kern.srtpartij(id);
ALTER TABLE "kern"."partij" ADD CONSTRAINT "fk2005" FOREIGN KEY (voortzettendegem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2056" FOREIGN KEY (betr) REFERENCES kern.betr(id) ON DELETE CASCADE;
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2055" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2054" FOREIGN KEY (multirealiteitpers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2053" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2051" FOREIGN KEY (srt) REFERENCES kern.srtmultirealiteitregel(id);
ALTER TABLE "kern"."multirealiteitregel" ADD CONSTRAINT "fk2050" FOREIGN KEY (geldigvoor) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_verstrderde" ADD CONSTRAINT "fk9368" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_verstrderde" ADD CONSTRAINT "fk9367" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_verstrderde" ADD CONSTRAINT "fk9364" FOREIGN KEY (verstrderde) REFERENCES kern.verstrderde(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4366" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4365" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4364" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persvoornaam" ADD CONSTRAINT "fk4359" FOREIGN KEY (persvoornaam) REFERENCES kern.persvoornaam(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4356" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4355" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverificatie" ADD CONSTRAINT "fk4352" FOREIGN KEY (persverificatie) REFERENCES kern.persverificatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "fk4166" FOREIGN KEY (verblijfstitel) REFERENCES kern.verblijfstitel(id);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "fk4165" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "fk4164" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "fk4163" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persverblijfstitel" ADD CONSTRAINT "fk4158" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4175" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4174" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persuitslnlkiesr" ADD CONSTRAINT "fk4171" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4110" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4106" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4105" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4104" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4103" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perssamengesteldenaam" ADD CONSTRAINT "fk4098" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk9195" FOREIGN KEY (landautaangifte) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk9193" FOREIGN KEY (gemautafgifte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4349" FOREIGN KEY (rdnvervallen) REFERENCES kern.rdnvervallenreisdoc(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4342" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4341" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persreisdoc" ADD CONSTRAINT "fk4336" FOREIGN KEY (persreisdoc) REFERENCES kern.persreisdoc(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4222" FOREIGN KEY (gempk) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4221" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4220" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perspk" ADD CONSTRAINT "fk4217" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4155" FOREIGN KEY (landoverlijden) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4152" FOREIGN KEY (wploverlijden) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4151" FOREIGN KEY (gemoverlijden) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4149" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4148" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persoverlijden" ADD CONSTRAINT "fk4145" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk5006" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4203" FOREIGN KEY (rdnopschortingbijhouding) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4202" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4201" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persopschorting" ADD CONSTRAINT "fk4198" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4334" FOREIGN KEY (rdnverk) REFERENCES kern.rdnverknlnation(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4333" FOREIGN KEY (rdnverlies) REFERENCES kern.rdnverliesnlnation(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4332" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4331" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4330" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persnation" ADD CONSTRAINT "fk4325" FOREIGN KEY (persnation) REFERENCES kern.persnation(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4247" FOREIGN KEY (volgendepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4246" FOREIGN KEY (vorigepers) REFERENCES kern.pers(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4242" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4241" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persinschr" ADD CONSTRAINT "fk4236" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4322" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4321" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4320" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persindicatie" ADD CONSTRAINT "fk4315" FOREIGN KEY (persindicatie) REFERENCES kern.persindicatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4233" FOREIGN KEY (landvanwaargevestigd) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4232" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4231" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4230" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persimmigratie" ADD CONSTRAINT "fk4225" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4084" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4083" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4082" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persids" ADD CONSTRAINT "fk4077" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4313" FOREIGN KEY (adellijketitel) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4312" FOREIGN KEY (predikaat) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4308" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4307" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4306" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslnaamcomp" ADD CONSTRAINT "fk4301" FOREIGN KEY (persgeslnaamcomp) REFERENCES kern.persgeslnaamcomp(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4096" FOREIGN KEY (geslachtsaand) REFERENCES kern.geslachtsaand(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4095" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4094" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4093" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeslachtsaand" ADD CONSTRAINT "fk4088" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4142" FOREIGN KEY (landgeboorte) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4139" FOREIGN KEY (wplgeboorte) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4138" FOREIGN KEY (gemgeboorte) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4136" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4135" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persgeboorte" ADD CONSTRAINT "fk4132" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4183" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4182" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_perseuverkiezingen" ADD CONSTRAINT "fk4179" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "fk9362" FOREIGN KEY (bvp) REFERENCES kern.bvp(id);
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "fk9361" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "fk9360" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbvp" ADD CONSTRAINT "fk9357" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4196" FOREIGN KEY (verantwoordelijke) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4195" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4194" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4193" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhverantwoordelijk" ADD CONSTRAINT "fk4188" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4213" FOREIGN KEY (bijhgem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4212" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4211" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4210" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persbijhgem" ADD CONSTRAINT "fk4205" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6072" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6071" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6070" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk6065" FOREIGN KEY (persadres) REFERENCES kern.persadres(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4298" FOREIGN KEY (land) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4280" FOREIGN KEY (wpl) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4272" FOREIGN KEY (gem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4259" FOREIGN KEY (aangadresh) REFERENCES kern.aangadresh(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4258" FOREIGN KEY (rdnwijz) REFERENCES kern.rdnwijzadres(id);
ALTER TABLE "kern"."his_persadres" ADD CONSTRAINT "fk4257" FOREIGN KEY (srt) REFERENCES kern.functieadres(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk6114" FOREIGN KEY (adellijketitelaanschr) REFERENCES kern.adellijketitel(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4126" FOREIGN KEY (predikaataanschr) REFERENCES kern.predikaat(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4123" FOREIGN KEY (naamgebruik) REFERENCES kern.wijzegebruikgeslnaam(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4121" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4120" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_persaanschr" ADD CONSTRAINT "fk4115" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6121" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6120" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk6117" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk4613" FOREIGN KEY (onderdeelvan) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partijgem" ADD CONSTRAINT "fk4611" FOREIGN KEY (voortzettendegem) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4627" FOREIGN KEY (sector) REFERENCES kern.sector(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4624" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4623" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_partij" ADD CONSTRAINT "fk4620" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "fk6091" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "fk4029" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "fk4028" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderschap" ADD CONSTRAINT "fk4025" FOREIGN KEY (betr) REFERENCES kern.betr(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "fk4040" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "fk4039" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "fk4038" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ouderouderlijkgezag" ADD CONSTRAINT "fk4033" FOREIGN KEY (betr) REFERENCES kern.betr(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_ontkenningouderschaponge" ADD CONSTRAINT "fk9415" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ontkenningouderschaponge" ADD CONSTRAINT "fk9414" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_ontkenningouderschaponge" ADD CONSTRAINT "fk9411" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4072" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4071" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_onderzoek" ADD CONSTRAINT "fk4068" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."his_naamskeuzeongeborenvruch" ADD CONSTRAINT "fk9408" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_naamskeuzeongeborenvruch" ADD CONSTRAINT "fk9407" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_naamskeuzeongeborenvruch" ADD CONSTRAINT "fk9404" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5476" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5475" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_multirealiteitregel" ADD CONSTRAINT "fk5472" FOREIGN KEY (multirealiteitregel) REFERENCES kern.multirealiteitregel(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4387" FOREIGN KEY (landeinde) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4384" FOREIGN KEY (wpleinde) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4383" FOREIGN KEY (gemeinde) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4381" FOREIGN KEY (rdneinde) REFERENCES kern.rdnbeeindrelatie(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4379" FOREIGN KEY (landaanv) REFERENCES kern.land(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4376" FOREIGN KEY (wplaanv) REFERENCES kern.plaats(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4375" FOREIGN KEY (gemaanv) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4373" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4372" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_huwelijkgeregistreerdpar" ADD CONSTRAINT "fk4369" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_erkenningongeborenvrucht" ADD CONSTRAINT "fk9422" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_erkenningongeborenvrucht" ADD CONSTRAINT "fk9421" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_erkenningongeborenvrucht" ADD CONSTRAINT "fk9418" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4051" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4047" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4046" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "kern"."his_doc" ADD CONSTRAINT "fk4043" FOREIGN KEY (doc) REFERENCES kern.doc(id) ON DELETE CASCADE;
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "fk3866" FOREIGN KEY (srtgegeven) REFERENCES kern.dbobject(id);
ALTER TABLE "kern"."gegeveninonderzoek" ADD CONSTRAINT "fk3865" FOREIGN KEY (onderzoek) REFERENCES kern.onderzoek(id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "fk5663" FOREIGN KEY (ouder) REFERENCES kern.element(id);
ALTER TABLE "kern"."element" ADD CONSTRAINT "fk3721" FOREIGN KEY (srt) REFERENCES kern.srtelement(id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "fk3157" FOREIGN KEY (srt) REFERENCES kern.srtdoc(id);
ALTER TABLE "kern"."doc" ADD CONSTRAINT "fk3139" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "fk5661" FOREIGN KEY (ouder) REFERENCES kern.dbobject(id);
ALTER TABLE "kern"."dbobject" ADD CONSTRAINT "fk5644" FOREIGN KEY (srt) REFERENCES kern.srtdbobject(id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3861" FOREIGN KEY (rol) REFERENCES kern.srtbetr(id);
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3860" FOREIGN KEY (relatie) REFERENCES kern.relatie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."betr" ADD CONSTRAINT "fk3859" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "kern"."admhnd" ADD CONSTRAINT "fk9208" FOREIGN KEY (srt) REFERENCES kern.srtadmhnd(id);
ALTER TABLE "kern"."admhnd" ADD CONSTRAINT "fk9172" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."actiebron" ADD CONSTRAINT "fk8124" FOREIGN KEY (rechtsgrond) REFERENCES kern.rechtsgrond(id);
ALTER TABLE "kern"."actiebron" ADD CONSTRAINT "fk8123" FOREIGN KEY (doc) REFERENCES kern.doc(id) ON DELETE CASCADE;
ALTER TABLE "kern"."actiebron" ADD CONSTRAINT "fk8122" FOREIGN KEY (actie) REFERENCES kern.actie(id) ON DELETE CASCADE;
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk9023" FOREIGN KEY (admhnd) REFERENCES kern.admhnd(id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk3209" FOREIGN KEY (partij) REFERENCES kern.partij(id);
ALTER TABLE "kern"."actie" ADD CONSTRAINT "fk3055" FOREIGN KEY (srt) REFERENCES kern.srtactie(id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "fk6059" FOREIGN KEY (srtber) REFERENCES ber.srtber(id);
ALTER TABLE "brm"."regelsrtber" ADD CONSTRAINT "fk6058" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk6000" FOREIGN KEY (rdnopschorting) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5999" FOREIGN KEY (bijhverantwoordelijkheid) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5829" FOREIGN KEY (effect) REFERENCES brm.regeleffect(id);
ALTER TABLE "brm"."regelsituatie" ADD CONSTRAINT "fk5828" FOREIGN KEY (regelimplementatie) REFERENCES brm.regelsrtber(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6157" FOREIGN KEY (regelsituatie) REFERENCES brm.regelsituatie(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6022" FOREIGN KEY (rdnopschorting) REFERENCES kern.rdnopschorting(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk6021" FOREIGN KEY (bijhverantwoordelijkheid) REFERENCES kern.verantwoordelijke(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5970" FOREIGN KEY (effect) REFERENCES brm.regeleffect(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5969" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "brm"."his_regelsituatie" ADD CONSTRAINT "fk5968" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "ber"."srtber" ADD CONSTRAINT "fk9518" FOREIGN KEY (module) REFERENCES ber.burgerzakenmodule(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6209" FOREIGN KEY (attribuut) REFERENCES kern.element(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6206" FOREIGN KEY (srt) REFERENCES ber.srtmelding(id);
ALTER TABLE "ber"."melding" ADD CONSTRAINT "fk6198" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "ber"."gedeblokkeerdemelding" ADD CONSTRAINT "fk6221" FOREIGN KEY (attribuut) REFERENCES kern.element(id);
ALTER TABLE "ber"."gedeblokkeerdemelding" ADD CONSTRAINT "fk6220" FOREIGN KEY (regel) REFERENCES kern.regel(id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "fk6215" FOREIGN KEY (melding) REFERENCES ber.melding(id);
ALTER TABLE "ber"."bermelding" ADD CONSTRAINT "fk6214" FOREIGN KEY (ber) REFERENCES ber.ber(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk9301" FOREIGN KEY (admhnd) REFERENCES kern.admhnd(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6246" FOREIGN KEY (hoogstemeldingsniveau) REFERENCES ber.srtmelding(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6245" FOREIGN KEY (bijhouding) REFERENCES ber.bijhresultaat(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6230" FOREIGN KEY (verwerking) REFERENCES ber.verwerkingsresultaat(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk6183" FOREIGN KEY (srt) REFERENCES ber.srtber(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk5633" FOREIGN KEY (richting) REFERENCES ber.richting(id);
ALTER TABLE "ber"."ber" ADD CONSTRAINT "fk5612" FOREIGN KEY (antwoordop) REFERENCES ber.ber(id);
ALTER TABLE "ber"."admhndgedeblokkeerdemelding" ADD CONSTRAINT "fk6227" FOREIGN KEY (gedeblokkeerdemelding) REFERENCES ber.gedeblokkeerdemelding(id);
ALTER TABLE "ber"."admhndgedeblokkeerdemelding" ADD CONSTRAINT "fk6226" FOREIGN KEY (admhnd) REFERENCES kern.admhnd(id);
ALTER TABLE "ber"."admhnddoc" ADD CONSTRAINT "fk9509" FOREIGN KEY (doc) REFERENCES kern.doc(id);
ALTER TABLE "ber"."admhnddoc" ADD CONSTRAINT "fk9508" FOREIGN KEY (admhnd) REFERENCES kern.admhnd(id);
ALTER TABLE "ber"."admhndbijgehoudenpers" ADD CONSTRAINT "fk6253" FOREIGN KEY (pers) REFERENCES kern.pers(id) ON DELETE CASCADE;
ALTER TABLE "ber"."admhndbijgehoudenpers" ADD CONSTRAINT "fk6252" FOREIGN KEY (admhnd) REFERENCES kern.admhnd(id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "fk5780" FOREIGN KEY (uitgeslotenpartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."uitgeslotene" ADD CONSTRAINT "fk5779" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5797" FOREIGN KEY (uitgeslotene) REFERENCES autaut.uitgeslotene(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5788" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_uitgeslotene" ADD CONSTRAINT "fk5787" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4974" FOREIGN KEY (protocolleringsniveau) REFERENCES autaut.protocolleringsniveau(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4973" FOREIGN KEY (actieaanpgel) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4972" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4971" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_doelbinding" ADD CONSTRAINT "fk4966" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5744" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5743" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhsituatie" ADD CONSTRAINT "fk5740" FOREIGN KEY (bijhsituatie) REFERENCES autaut.bijhsituatie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk6166" FOREIGN KEY (categoriepersonen) REFERENCES kern.categoriepersonen(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5790" FOREIGN KEY (srtbevoegdheid) REFERENCES autaut.srtbevoegdheid(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5738" FOREIGN KEY (geautoriseerdesrtpartij) REFERENCES kern.srtpartij(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5737" FOREIGN KEY (geautoriseerdepartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5735" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5734" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5733" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_bijhautorisatie" ADD CONSTRAINT "fk5730" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5728" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5727" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5726" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluitbijhau" ADD CONSTRAINT "fk5723" FOREIGN KEY (autorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4963" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4962" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_autorisatiebesluit" ADD CONSTRAINT "fk4959" FOREIGN KEY (autorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4685" FOREIGN KEY (certificaattbvondertekening) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4684" FOREIGN KEY (certificaattbvssl) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4683" FOREIGN KEY (functie) REFERENCES autaut.functie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4682" FOREIGN KEY (actieverval) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4681" FOREIGN KEY (actieinh) REFERENCES kern.actie(id);
ALTER TABLE "autaut"."his_authenticatiemiddel" ADD CONSTRAINT "fk4678" FOREIGN KEY (authenticatiemiddel) REFERENCES autaut.authenticatiemiddel(id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "fk4893" FOREIGN KEY (gegevenselement) REFERENCES kern.dbobject(id);
ALTER TABLE "autaut"."doelbindinggegevenselement" ADD CONSTRAINT "fk4892" FOREIGN KEY (doelbinding) REFERENCES autaut.doelbinding(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4885" FOREIGN KEY (levsautorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4884" FOREIGN KEY (geautoriseerde) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."doelbinding" ADD CONSTRAINT "fk4883" FOREIGN KEY (protocolleringsniveau) REFERENCES autaut.protocolleringsniveau(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk6039" FOREIGN KEY (srtadmhnd) REFERENCES kern.srtadmhnd(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk5701" FOREIGN KEY (bijhautorisatie) REFERENCES autaut.bijhautorisatie(id);
ALTER TABLE "autaut"."bijhsituatie" ADD CONSTRAINT "fk5698" FOREIGN KEY (srtdoc) REFERENCES kern.srtdoc(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk6165" FOREIGN KEY (categoriepersonen) REFERENCES kern.categoriepersonen(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5713" FOREIGN KEY (srtbevoegdheid) REFERENCES autaut.srtbevoegdheid(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5704" FOREIGN KEY (geautoriseerdesrtpartij) REFERENCES kern.srtpartij(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5703" FOREIGN KEY (geautoriseerdepartij) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5691" FOREIGN KEY (bijhautorisatiebesluit) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."bijhautorisatie" ADD CONSTRAINT "fk5689" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk5677" FOREIGN KEY (toestand) REFERENCES autaut.toestand(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4868" FOREIGN KEY (gebaseerdop) REFERENCES autaut.autorisatiebesluit(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4866" FOREIGN KEY (autoriseerder) REFERENCES kern.partij(id);
ALTER TABLE "autaut"."autorisatiebesluit" ADD CONSTRAINT "fk4863" FOREIGN KEY (srt) REFERENCES autaut.srtautorisatiebesluit(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4668" FOREIGN KEY (certificaattbvondertekening) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4667" FOREIGN KEY (certificaattbvssl) REFERENCES autaut.certificaat(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk4665" FOREIGN KEY (functie) REFERENCES autaut.functie(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk2233" FOREIGN KEY (rol) REFERENCES kern.rol(id);
ALTER TABLE "autaut"."authenticatiemiddel" ADD CONSTRAINT "fk2232" FOREIGN KEY (partij) REFERENCES kern.partij(id);
