// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.autaut;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.autaut.Toestand;
import nl.bzk.brp.model.data.autaut.ToestandDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect ToestandDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ToestandDataOnDemand: @Component;
    
    private Random ToestandDataOnDemand.rnd = new SecureRandom();
    
    private List<Toestand> ToestandDataOnDemand.data;
    
    public Toestand ToestandDataOnDemand.getNewTransientToestand(int index) {
        Toestand obj = new Toestand();
        setDataanvgel(obj, index);
        setDateindegel(obj, index);
        setNaam(obj, index);
        setOms(obj, index);
        return obj;
    }
    
    public void ToestandDataOnDemand.setDataanvgel(Toestand obj, int index) {
        BigDecimal dataanvgel = BigDecimal.valueOf(index);
        obj.setDataanvgel(dataanvgel);
    }
    
    public void ToestandDataOnDemand.setDateindegel(Toestand obj, int index) {
        BigDecimal dateindegel = BigDecimal.valueOf(index);
        obj.setDateindegel(dateindegel);
    }
    
    public void ToestandDataOnDemand.setNaam(Toestand obj, int index) {
        String naam = "naam_" + index;
        if (naam.length() > 40) {
            naam = naam.substring(0, 40);
        }
        obj.setNaam(naam);
    }
    
    public void ToestandDataOnDemand.setOms(Toestand obj, int index) {
        String oms = "oms_" + index;
        if (oms.length() > 250) {
            oms = oms.substring(0, 250);
        }
        obj.setOms(oms);
    }
    
    public Toestand ToestandDataOnDemand.getSpecificToestand(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Toestand obj = data.get(index);
        Short id = obj.getId();
        return Toestand.findToestand(id);
    }
    
    public Toestand ToestandDataOnDemand.getRandomToestand() {
        init();
        Toestand obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getId();
        return Toestand.findToestand(id);
    }
    
    public boolean ToestandDataOnDemand.modifyToestand(Toestand obj) {
        return false;
    }
    
    public void ToestandDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Toestand.findToestandEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Toestand' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Toestand>();
        for (int i = 0; i < 10; i++) {
            Toestand obj = getNewTransientToestand(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
