insert into initvul.initvullingresult_afnind (pl_id, a_nr, bericht_resultaat) values (1, 1326432129, 'TE_VERZENDEN');
insert into initvul.initvullingresult_afnind (pl_id, a_nr, bericht_resultaat) values (2, 4157015073, 'TE_VERZENDEN');
insert into initvul.initvullingresult_afnind (pl_id, a_nr, bericht_resultaat) values (3, 1326432128, 'TE_VERZENDEN');
insert into initvul.initvullingresult_afnind (pl_id, a_nr, bericht_resultaat) values (4, 4157015072, 'TE_VERZENDEN');
insert into initvul.initvullingresult_afnind (pl_id, a_nr, bericht_resultaat) values (5, 1326432127, 'TE_VERZENDEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (1, 0, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (1, 1, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (2, 0, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (3, 0, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (3, 1, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (4, 0, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (5, 0, 'TE_VERWERKEN');
insert into initvul.initvullingresult_afnind_stapel (pl_id, stapel_nr, conversie_resultaat) values (5, 1, 'TE_VERWERKEN');
commit;