// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.brpreview.data.ber;

import nl.bzk.brp.brpreview.data.ber.Overrule;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Overrule_Roo_Configurable {
    
    declare @type: Overrule: @Configurable;
    
}
