// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.autaut;

import java.util.List;
import nl.bzk.brp.model.data.autaut.HisUitgeslotene;
import nl.bzk.brp.model.data.autaut.HisUitgesloteneDataOnDemand;
import nl.bzk.brp.model.data.autaut.HisUitgesloteneIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HisUitgesloteneIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HisUitgesloteneIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HisUitgesloteneIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HisUitgesloteneIntegrationTest: @Transactional;
    
    @Autowired
    private HisUitgesloteneDataOnDemand HisUitgesloteneIntegrationTest.dod;
    
    @Test
    public void HisUitgesloteneIntegrationTest.testCountHisUitgeslotenes() {
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", dod.getRandomHisUitgeslotene());
        long count = HisUitgeslotene.countHisUitgeslotenes();
        Assert.assertTrue("Counter for 'HisUitgeslotene' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HisUitgesloteneIntegrationTest.testFindHisUitgeslotene() {
        HisUitgeslotene obj = dod.getRandomHisUitgeslotene();
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to provide an identifier", id);
        obj = HisUitgeslotene.findHisUitgeslotene(id);
        Assert.assertNotNull("Find method for 'HisUitgeslotene' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HisUitgeslotene' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HisUitgesloteneIntegrationTest.testFindAllHisUitgeslotenes() {
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", dod.getRandomHisUitgeslotene());
        long count = HisUitgeslotene.countHisUitgeslotenes();
        Assert.assertTrue("Too expensive to perform a find all test for 'HisUitgeslotene', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HisUitgeslotene> result = HisUitgeslotene.findAllHisUitgeslotenes();
        Assert.assertNotNull("Find all method for 'HisUitgeslotene' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HisUitgeslotene' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HisUitgesloteneIntegrationTest.testFindHisUitgesloteneEntries() {
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", dod.getRandomHisUitgeslotene());
        long count = HisUitgeslotene.countHisUitgeslotenes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HisUitgeslotene> result = HisUitgeslotene.findHisUitgesloteneEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HisUitgeslotene' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HisUitgeslotene' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HisUitgesloteneIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", dod.getRandomHisUitgeslotene());
        HisUitgeslotene obj = dod.getNewTransientHisUitgeslotene(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HisUitgeslotene' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HisUitgeslotene' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HisUitgesloteneIntegrationTest.testRemove() {
        HisUitgeslotene obj = dod.getRandomHisUitgeslotene();
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisUitgeslotene' failed to provide an identifier", id);
        obj = HisUitgeslotene.findHisUitgeslotene(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HisUitgeslotene' with identifier '" + id + "'", HisUitgeslotene.findHisUitgeslotene(id));
    }
    
}
