/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * Bvp generated by hbm2java
 */
public enum Bvp  {

    _0,
    G,
    M,

//    /**
//     * Ordinal van een enum begint bij 0, maar de id van tuples van statische tabellen bij 1.
//     */
//    ORDINAL_NUL_NIET_GEBRUIKEN(null),
//    /**
//     * College van burgemeester en wethouders.
//     */
//    GEPRIVILIGIEERDE("Gepriviligieerde"),
//    /**
//     * Minister.
//     */
//    MILITAIR("Militair");
//
//    private String naam;
//
//    public String getNaam() {
//        return this.naam;
//    }
//
//    /**
//     * Private constructor ten behoeve van eenmalige initialisatie.
//     *
//     * @param naam de naam van de verantwoordelijke.
//     */
//    private Bvp(final String naam) {
//        this.naam = naam;
//    }

}


