/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA



/**
 * Doc generated by hbm2java
 */
public class Doc  implements java.io.Serializable {


     private long id;
     private Partij partij;
     private Srtdoc srtdoc;
     private String ident;
     private String aktenr;
     private String oms;
     private String docstatushis = StatusHis.A.name();

    public Doc() {
    }


    public Doc(Srtdoc srtdoc, String docstatushis) {
        this.srtdoc = srtdoc;
        this.docstatushis = docstatushis;
    }
    public Doc(Partij partij, Srtdoc srtdoc, String ident, String aktenr, String oms, String docstatushis) {
       this.partij = partij;
       this.srtdoc = srtdoc;
       this.ident = ident;
       this.aktenr = aktenr;
       this.oms = oms;
       this.docstatushis = docstatushis;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }
    public Partij getPartij() {
        return this.partij;
    }

    public void setPartij(Partij partij) {
        this.partij = partij;
    }
    public Srtdoc getSrtdoc() {
        return this.srtdoc;
    }

    public void setSrtdoc(Srtdoc srtdoc) {
        this.srtdoc = srtdoc;
    }
    public String getIdent() {
        return this.ident;
    }

    public void setIdent(String ident) {
        this.ident = ident;
    }
    public String getAktenr() {
        return this.aktenr;
    }

    public void setAktenr(String aktenr) {
        this.aktenr = aktenr;
    }
    public String getOms() {
        return this.oms;
    }

    public void setOms(String oms) {
        this.oms = oms;
    }
    public String getDocstatushis() {
        return this.docstatushis;
    }

    public void setDocstatushis(String docstatushis) {
        this.docstatushis = docstatushis;
    }




}


