/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA



/**
 * Doelbindinggegevenselement generated by hbm2java
 */
public class Doelbindinggegevenselement  implements java.io.Serializable {


     private Integer id;
     private Dbobject dbobject;
     private Doelbinding doelbinding;

    public Doelbindinggegevenselement() {
    }

    public Doelbindinggegevenselement(Dbobject dbobject, Doelbinding doelbinding) {
       this.dbobject = dbobject;
       this.doelbinding = doelbinding;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dbobject getDbobject() {
        return this.dbobject;
    }
    
    public void setDbobject(Dbobject dbobject) {
        this.dbobject = dbobject;
    }
    public Doelbinding getDoelbinding() {
        return this.doelbinding;
    }
    
    public void setDoelbinding(Doelbinding doelbinding) {
        this.doelbinding = doelbinding;
    }




}


