/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersverblijfstitel generated by hbm2java
 */
public class HisPersverblijfstitel extends HisMaterieel {


     private Integer id;
     private Pers pers;
     private Verblijfstitel verblijfstitel;
     private Integer dataanvgel;
     private Integer dateindegel;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private Long actieaanpgel;
     private int dataanvverblijfstitel;
     private Integer datvoorzeindeverblijfstitel;

    public HisPersverblijfstitel() {
    }


    public HisPersverblijfstitel(Verblijfstitel verblijfstitel, int dataanvverblijfstitel) {
        this.verblijfstitel = verblijfstitel;
        this.dataanvverblijfstitel = dataanvverblijfstitel;
    }
    public HisPersverblijfstitel(Pers pers, Verblijfstitel verblijfstitel, Integer dataanvgel, Integer dateindegel, Date tsreg, Date tsverval, Long actieinh, Long actieverval, Long actieaanpgel, int dataanvverblijfstitel, Integer datvoorzeindeverblijfstitel) {
       this.pers = pers;
       this.verblijfstitel = verblijfstitel;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.actieaanpgel = actieaanpgel;
       this.dataanvverblijfstitel = dataanvverblijfstitel;
       this.datvoorzeindeverblijfstitel = datvoorzeindeverblijfstitel;
    }

    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Verblijfstitel getVerblijfstitel() {
        return this.verblijfstitel;
    }

    public void setVerblijfstitel(Verblijfstitel verblijfstitel) {
        this.verblijfstitel = verblijfstitel;
    }
    public Long getActieaanpgel() {
        return this.actieaanpgel;
    }

    public void setActieaanpgel(Long actieaanpgel) {
        this.actieaanpgel = actieaanpgel;
    }
    public int getDataanvverblijfstitel() {
        return this.dataanvverblijfstitel;
    }

    public void setDataanvverblijfstitel(int dataanvverblijfstitel) {
        this.dataanvverblijfstitel = dataanvverblijfstitel;
    }
    public Integer getDatvoorzeindeverblijfstitel() {
        return this.datvoorzeindeverblijfstitel;
    }

    public void setDatvoorzeindeverblijfstitel(Integer datvoorzeindeverblijfstitel) {
        this.datvoorzeindeverblijfstitel = datvoorzeindeverblijfstitel;
    }




}


