/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersids generated by hbm2java
 */
public class HisPersids extends HisMaterieel {


     private Integer id;
     private Pers pers;
     private Integer dataanvgel;
     private Integer dateindegel;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private Long actieaanpgel;
     private Integer bsn;
     private Long anr;

    public HisPersids() {
    }

    public HisPersids(Pers pers, Integer dataanvgel, Integer dateindegel, Date tsreg, Date tsverval, Long actieinh, Long actieverval, Long actieaanpgel, Integer bsn, Long anr) {
       this.pers = pers;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.actieaanpgel = actieaanpgel;
       this.bsn = bsn;
       this.anr = anr;
  
        this.id = id;
    }
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Long getActieaanpgel() {
        return this.actieaanpgel;
    }

    public void setActieaanpgel(Long actieaanpgel) {
        this.actieaanpgel = actieaanpgel;
    }
    public Integer getBsn() {
        return this.bsn;
    }

    public void setBsn(Integer bsn) {
        this.bsn = bsn;
    }
    public Long getAnr() {
        return this.anr;
    }

    public void setAnr(Long anr) {
        this.anr = anr;
    }




}


