/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersreisdoc generated by hbm2java
 */
public class HisPersreisdoc extends His {


     private Integer id;
     private Persreisdoc persreisdoc;
     private Rdnvervallenreisdoc rdnvervallenreisdoc;
     private Autvanafgiftereisdoc autvanafgiftereisdoc;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nr;
     private Short lengtehouder;
     private int datingangdoc;
     private int datuitgifte;
     private int datvoorzeeindegel;
     private Integer datinhingvermissing;

    public HisPersreisdoc() {
    }


    public HisPersreisdoc(Autvanafgiftereisdoc autvanafgiftereisdoc, String nr, int datingangdoc, int datuitgifte, int datvoorzeeindegel) {
        this.autvanafgiftereisdoc = autvanafgiftereisdoc;
        this.nr = nr;
        this.datingangdoc = datingangdoc;
        this.datuitgifte = datuitgifte;
        this.datvoorzeeindegel = datvoorzeeindegel;
    }
    public HisPersreisdoc(Persreisdoc persreisdoc, Rdnvervallenreisdoc rdnvervallenreisdoc, Autvanafgiftereisdoc autvanafgiftereisdoc, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nr, Short lengtehouder, int datingangdoc, int datuitgifte, int datvoorzeeindegel, Integer datinhingvermissing) {
       this.persreisdoc = persreisdoc;
       this.rdnvervallenreisdoc = rdnvervallenreisdoc;
       this.autvanafgiftereisdoc = autvanafgiftereisdoc;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nr = nr;
       this.lengtehouder = lengtehouder;
       this.datingangdoc = datingangdoc;
       this.datuitgifte = datuitgifte;
       this.datvoorzeeindegel = datvoorzeeindegel;
       this.datinhingvermissing = datinhingvermissing;
    }

    public Persreisdoc getPersreisdoc() {
        return this.persreisdoc;
    }

    public void setPersreisdoc(Persreisdoc persreisdoc) {
        this.persreisdoc = persreisdoc;
    }
    public Rdnvervallenreisdoc getRdnvervallenreisdoc() {
        return this.rdnvervallenreisdoc;
    }

    public void setRdnvervallenreisdoc(Rdnvervallenreisdoc rdnvervallenreisdoc) {
        this.rdnvervallenreisdoc = rdnvervallenreisdoc;
    }
    public Autvanafgiftereisdoc getAutvanafgiftereisdoc() {
        return this.autvanafgiftereisdoc;
    }

    public void setAutvanafgiftereisdoc(Autvanafgiftereisdoc autvanafgiftereisdoc) {
        this.autvanafgiftereisdoc = autvanafgiftereisdoc;
    }
    public String getNr() {
        return this.nr;
    }

    public void setNr(String nr) {
        this.nr = nr;
    }
    public Short getLengtehouder() {
        return this.lengtehouder;
    }

    public void setLengtehouder(Short lengtehouder) {
        this.lengtehouder = lengtehouder;
    }
    public int getDatingangdoc() {
        return this.datingangdoc;
    }

    public void setDatingangdoc(int datingangdoc) {
        this.datingangdoc = datingangdoc;
    }
    public int getDatuitgifte() {
        return this.datuitgifte;
    }

    public void setDatuitgifte(int datuitgifte) {
        this.datuitgifte = datuitgifte;
    }
    public int getDatvoorzeeindegel() {
        return this.datvoorzeeindegel;
    }

    public void setDatvoorzeeindegel(int datvoorzeeindegel) {
        this.datvoorzeeindegel = datvoorzeeindegel;
    }
    public Integer getDatinhingvermissing() {
        return this.datinhingvermissing;
    }

    public void setDatinhingvermissing(Integer datinhingvermissing) {
        this.datinhingvermissing = datinhingvermissing;
    }




}


