/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Lev generated by hbm2java
 */
public class Lev  implements java.io.Serializable {


     private Long id;
     private Srtlev srtlev;
     private Abonnement abonnement;
     private Authenticatiemiddel authenticatiemiddel;
     private Ber ber;
     private Date tsbesch;
     private Date tsklaarzettenlev;

    public Lev() {
    }

	
    public Lev(Srtlev srtlev, Abonnement abonnement, Authenticatiemiddel authenticatiemiddel) {
        this.srtlev = srtlev;
        this.abonnement = abonnement;
        this.authenticatiemiddel = authenticatiemiddel;
    }
    public Lev(Srtlev srtlev, Abonnement abonnement, Authenticatiemiddel authenticatiemiddel, Ber ber, Date tsbesch, Date tsklaarzettenlev) {
       this.srtlev = srtlev;
       this.abonnement = abonnement;
       this.authenticatiemiddel = authenticatiemiddel;
       this.ber = ber;
       this.tsbesch = tsbesch;
       this.tsklaarzettenlev = tsklaarzettenlev;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Srtlev getSrtlev() {
        return this.srtlev;
    }
    
    public void setSrtlev(Srtlev srtlev) {
        this.srtlev = srtlev;
    }
    public Abonnement getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(Abonnement abonnement) {
        this.abonnement = abonnement;
    }
    public Authenticatiemiddel getAuthenticatiemiddel() {
        return this.authenticatiemiddel;
    }
    
    public void setAuthenticatiemiddel(Authenticatiemiddel authenticatiemiddel) {
        this.authenticatiemiddel = authenticatiemiddel;
    }
    public Ber getBer() {
        return this.ber;
    }
    
    public void setBer(Ber ber) {
        this.ber = ber;
    }
    public Date getTsbesch() {
        return this.tsbesch;
    }
    
    public void setTsbesch(Date tsbesch) {
        this.tsbesch = tsbesch;
    }
    public Date getTsklaarzettenlev() {
        return this.tsklaarzettenlev;
    }
    
    public void setTsklaarzettenlev(Date tsklaarzettenlev) {
        this.tsklaarzettenlev = tsklaarzettenlev;
    }




}


