/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA



/**
 * Regelsituatie generated by hbm2java
 */
public class Regelsituatie  implements java.io.Serializable {


     private int id;
     private Regeleffect regeleffect;
     private Regelsrtber regelsrtber;
     private Short bijhverantwoordelijkheid;
     private Boolean indopgeschort;
     private Short rdnopschorting;
     private Boolean indactief;
     private String regelsituatiestatushis = StatusHis.A.name();

    public Regelsituatie() {
    }


    public Regelsituatie(int id, Regelsrtber regelsrtber, String regelsituatiestatushis) {
        this.id = id;
        this.regelsrtber = regelsrtber;
        this.regelsituatiestatushis = regelsituatiestatushis;
    }
    public Regelsituatie(int id, Regeleffect regeleffect, Regelsrtber regelsrtber, Short bijhverantwoordelijkheid, Boolean indopgeschort, Short rdnopschorting, Boolean indactief, String regelsituatiestatushis) {
       this.id = id;
       this.regeleffect = regeleffect;
       this.regelsrtber = regelsrtber;
       this.bijhverantwoordelijkheid = bijhverantwoordelijkheid;
       this.indopgeschort = indopgeschort;
       this.rdnopschorting = rdnopschorting;
       this.indactief = indactief;
       this.regelsituatiestatushis = regelsituatiestatushis;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public Regeleffect getRegeleffect() {
        return this.regeleffect;
    }

    public void setRegeleffect(Regeleffect regeleffect) {
        this.regeleffect = regeleffect;
    }
    public Regelsrtber getRegelsrtber() {
        return this.regelsrtber;
    }

    public void setRegelsrtber(Regelsrtber regelsrtber) {
        this.regelsrtber = regelsrtber;
    }
    public Short getBijhverantwoordelijkheid() {
        return this.bijhverantwoordelijkheid;
    }

    public void setBijhverantwoordelijkheid(Short bijhverantwoordelijkheid) {
        this.bijhverantwoordelijkheid = bijhverantwoordelijkheid;
    }
    public Boolean getIndopgeschort() {
        return this.indopgeschort;
    }

    public void setIndopgeschort(Boolean indopgeschort) {
        this.indopgeschort = indopgeschort;
    }
    public Short getRdnopschorting() {
        return this.rdnopschorting;
    }

    public void setRdnopschorting(Short rdnopschorting) {
        this.rdnopschorting = rdnopschorting;
    }
    public Boolean getIndactief() {
        return this.indactief;
    }

    public void setIndactief(Boolean indactief) {
        this.indactief = indactief;
    }
    public String getRegelsituatiestatushis() {
        return this.regelsituatiestatushis;
    }

    public void setRegelsituatiestatushis(String regelsituatiestatushis) {
        this.regelsituatiestatushis = regelsituatiestatushis;
    }




}


