/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 5-feb-2013 16:30:05 by Hibernate Tools 3.2.4.GA

import nl.bzk.brp.testdatageneratie.dataaccess.Cacheable;


/**
 * Srtdoc generated by hbm2java
 */
public class Srtdoc implements Cacheable<Short> {


     private short id;
     private String naam;
     private String oms;
     private Integer rangorde;

    public Srtdoc() {
    }

	
    public Srtdoc(short id, String naam, String oms) {
        this.id = id;
        this.naam = naam;
        this.oms = oms;
    }
    public Srtdoc(short id, String naam, String oms, Integer rangorde) {
       this.id = id;
       this.naam = naam;
       this.oms = oms;
       this.rangorde = rangorde;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getOms() {
        return this.oms;
    }
    
    public void setOms(String oms) {
        this.oms = oms;
    }
    public Integer getRangorde() {
        return this.rangorde;
    }
    
    public void setRangorde(Integer rangorde) {
        this.rangorde = rangorde;
    }

    @Override
    public Short getKey() {
        return null;
    }



}


