/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersaanschr generated by hbm2java
 */
@Entity
@Table(name = "hispersaanschr", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = { "pers",
        "dataanvgel", "dattijdreg" }))
public class Hispersaanschr implements java.io.Serializable {

    private long                 id;
    private Predikaat            predikaat;
    private Brpactie             brpactieByBrpactiebegin;
    private Pers                 pers;
    private Wijzegebruikgeslnaam wijzegebruikgeslnaam;
    private Brpactie             brpactieByBrpactiebeingeld;
    private Brpactie             brpactieByBrpactieeinde;
    private Integer              dataanvgel;
    private Integer              dateindegel;
    private Date                 dattijdreg;
    private Date                 dattijdverval;
    private String               indaanschrmetadellijketitel;
    private String               indaanschrafgeleid;
    private String               voornamenaanschr;
    private String               voorvoegselaanschr;
    private String               scheidingstekenaanschr;
    private String               geslnaamaanschr;

    public Hispersaanschr() {
    }

    public Hispersaanschr(long id, String indaanschrafgeleid, String geslnaamaanschr) {
        this.id = id;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.geslnaamaanschr = geslnaamaanschr;
    }

    public Hispersaanschr(long id, Predikaat predikaat, Brpactie brpactieByBrpactiebegin, Pers pers,
            Wijzegebruikgeslnaam wijzegebruikgeslnaam, Brpactie brpactieByBrpactiebeingeld,
            Brpactie brpactieByBrpactieeinde, Integer dataanvgel, Integer dateindegel, Date dattijdreg,
            Date dattijdverval, String indaanschrmetadellijketitel, String indaanschrafgeleid, String voornamenaanschr,
            String voorvoegselaanschr, String scheidingstekenaanschr, String geslnaamaanschr)
    {
        this.id = id;
        this.predikaat = predikaat;
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
        this.pers = pers;
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.indaanschrmetadellijketitel = indaanschrmetadellijketitel;
        this.indaanschrafgeleid = indaanschrafgeleid;
        this.voornamenaanschr = voornamenaanschr;
        this.voorvoegselaanschr = voorvoegselaanschr;
        this.scheidingstekenaanschr = scheidingstekenaanschr;
        this.geslnaamaanschr = geslnaamaanschr;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "predikaataanschr")
    public Predikaat getPredikaat() {
        return this.predikaat;
    }

    public void setPredikaat(Predikaat predikaat) {
        this.predikaat = predikaat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebegin")
    public Brpactie getBrpactieByBrpactiebegin() {
        return this.brpactieByBrpactiebegin;
    }

    public void setBrpactieByBrpactiebegin(Brpactie brpactieByBrpactiebegin) {
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pers")
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gebrgeslnaamegp")
    public Wijzegebruikgeslnaam getWijzegebruikgeslnaam() {
        return this.wijzegebruikgeslnaam;
    }

    public void setWijzegebruikgeslnaam(Wijzegebruikgeslnaam wijzegebruikgeslnaam) {
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebeingeld")
    public Brpactie getBrpactieByBrpactiebeingeld() {
        return this.brpactieByBrpactiebeingeld;
    }

    public void setBrpactieByBrpactiebeingeld(Brpactie brpactieByBrpactiebeingeld) {
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactieeinde")
    public Brpactie getBrpactieByBrpactieeinde() {
        return this.brpactieByBrpactieeinde;
    }

    public void setBrpactieByBrpactieeinde(Brpactie brpactieByBrpactieeinde) {
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "indaanschrmetadellijketitel", length = 1)
    public String getIndaanschrmetadellijketitel() {
        return this.indaanschrmetadellijketitel;
    }

    public void setIndaanschrmetadellijketitel(String indaanschrmetadellijketitel) {
        this.indaanschrmetadellijketitel = indaanschrmetadellijketitel;
    }

    @Column(name = "indaanschrafgeleid", nullable = false, length = 1)
    public String getIndaanschrafgeleid() {
        return this.indaanschrafgeleid;
    }

    public void setIndaanschrafgeleid(String indaanschrafgeleid) {
        this.indaanschrafgeleid = indaanschrafgeleid;
    }

    @Column(name = "voornamenaanschr", length = 200)
    public String getVoornamenaanschr() {
        return this.voornamenaanschr;
    }

    public void setVoornamenaanschr(String voornamenaanschr) {
        this.voornamenaanschr = voornamenaanschr;
    }

    @Column(name = "voorvoegselaanschr", length = 10)
    public String getVoorvoegselaanschr() {
        return this.voorvoegselaanschr;
    }

    public void setVoorvoegselaanschr(String voorvoegselaanschr) {
        this.voorvoegselaanschr = voorvoegselaanschr;
    }

    @Column(name = "scheidingstekenaanschr", length = 1)
    public String getScheidingstekenaanschr() {
        return this.scheidingstekenaanschr;
    }

    public void setScheidingstekenaanschr(String scheidingstekenaanschr) {
        this.scheidingstekenaanschr = scheidingstekenaanschr;
    }

    @Column(name = "geslnaamaanschr", nullable = false, length = 200)
    public String getGeslnaamaanschr() {
        return this.geslnaamaanschr;
    }

    public void setGeslnaamaanschr(String geslnaamaanschr) {
        this.geslnaamaanschr = geslnaamaanschr;
    }

}
