/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Hispersinschr generated by hbm2java
 */
@Entity
@Table(name = "hispersinschr", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = { "pers",
        "dataanvgel", "dattijdreg" }))
public class Hispersinschr implements java.io.Serializable {

    private long     id;
    private Brpactie brpactieByBrpactiebegin;
    private Pers     persByPers;
    private Pers     persByVolgendepers;
    private Pers     persByVorigepers;
    private Brpactie brpactieByBrpactiebeingeld;
    private Brpactie brpactieByBrpactieeinde;
    private Integer  dataanvgel;
    private Integer  dateindegel;
    private Date     dattijdreg;
    private Date     dattijdverval;
    private int      datinschr;
    private long     versienr;

    public Hispersinschr() {
    }

    public Hispersinschr(long id, int datinschr, long versienr) {
        this.id = id;
        this.datinschr = datinschr;
        this.versienr = versienr;
    }

    public Hispersinschr(long id, Brpactie brpactieByBrpactiebegin, Pers persByPers, Pers persByVolgendepers,
            Pers persByVorigepers, Brpactie brpactieByBrpactiebeingeld, Brpactie brpactieByBrpactieeinde,
            Integer dataanvgel, Integer dateindegel, Date dattijdreg, Date dattijdverval, int datinschr, long versienr)
    {
        this.id = id;
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
        this.persByPers = persByPers;
        this.persByVolgendepers = persByVolgendepers;
        this.persByVorigepers = persByVorigepers;
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.dattijdreg = dattijdreg;
        this.dattijdverval = dattijdverval;
        this.datinschr = datinschr;
        this.versienr = versienr;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebegin")
    public Brpactie getBrpactieByBrpactiebegin() {
        return this.brpactieByBrpactiebegin;
    }

    public void setBrpactieByBrpactiebegin(Brpactie brpactieByBrpactiebegin) {
        this.brpactieByBrpactiebegin = brpactieByBrpactiebegin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pers")
    public Pers getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(Pers persByPers) {
        this.persByPers = persByPers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "volgendepers")
    public Pers getPersByVolgendepers() {
        return this.persByVolgendepers;
    }

    public void setPersByVolgendepers(Pers persByVolgendepers) {
        this.persByVolgendepers = persByVolgendepers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vorigepers")
    public Pers getPersByVorigepers() {
        return this.persByVorigepers;
    }

    public void setPersByVorigepers(Pers persByVorigepers) {
        this.persByVorigepers = persByVorigepers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactiebeingeld")
    public Brpactie getBrpactieByBrpactiebeingeld() {
        return this.brpactieByBrpactiebeingeld;
    }

    public void setBrpactieByBrpactiebeingeld(Brpactie brpactieByBrpactiebeingeld) {
        this.brpactieByBrpactiebeingeld = brpactieByBrpactiebeingeld;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brpactieeinde")
    public Brpactie getBrpactieByBrpactieeinde() {
        return this.brpactieByBrpactieeinde;
    }

    public void setBrpactieByBrpactieeinde(Brpactie brpactieByBrpactieeinde) {
        this.brpactieByBrpactieeinde = brpactieByBrpactieeinde;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdreg", length = 29)
    public Date getDattijdreg() {
        return this.dattijdreg;
    }

    public void setDattijdreg(Date dattijdreg) {
        this.dattijdreg = dattijdreg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dattijdverval", length = 29)
    public Date getDattijdverval() {
        return this.dattijdverval;
    }

    public void setDattijdverval(Date dattijdverval) {
        this.dattijdverval = dattijdverval;
    }

    @Column(name = "datinschr", nullable = false, precision = 8, scale = 0)
    public int getDatinschr() {
        return this.datinschr;
    }

    public void setDatinschr(int datinschr) {
        this.datinschr = datinschr;
    }

    @Column(name = "versienr", nullable = false)
    public long getVersienr() {
        return this.versienr;
    }

    public void setVersienr(long versienr) {
        this.versienr = versienr;
    }

}
