/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.toegangsbewaking.test.model;

// Generated 23-sep-2011 15:40:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Verdrag generated by hbm2java
 */
@Entity
@Table(name = "verdrag", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = "oms"))
public class Verdrag implements java.io.Serializable {

    private int           id;
    private String        oms;
    private Integer       dataanvgel;
    private Integer       dateindegel;
    private Set<Brpactie> brpacties = new HashSet<Brpactie>(0);

    public Verdrag() {
    }

    public Verdrag(int id, String oms) {
        this.id = id;
        this.oms = oms;
    }

    public Verdrag(int id, String oms, Integer dataanvgel, Integer dateindegel, Set<Brpactie> brpacties) {
        this.id = id;
        this.oms = oms;
        this.dataanvgel = dataanvgel;
        this.dateindegel = dateindegel;
        this.brpacties = brpacties;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "oms", unique = true, nullable = false, length = 200)
    public String getOms() {
        return this.oms;
    }

    public void setOms(String oms) {
        this.oms = oms;
    }

    @Column(name = "dataanvgel", precision = 8, scale = 0)
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }

    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }

    @Column(name = "dateindegel", precision = 8, scale = 0)
    public Integer getDateindegel() {
        return this.dateindegel;
    }

    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "verdrag")
    public Set<Brpactie> getBrpacties() {
        return this.brpacties;
    }

    public void setBrpacties(Set<Brpactie> brpacties) {
        this.brpacties = brpacties;
    }

}
