#!/bin/bash

for c in `docker ps | grep -v CONTAINER | awk '{print $1}'`;
do
  log=`docker logs $c 2>&1 | grep -e " SEVERE \| ERROR \|FATAL\|Exception" | grep -v -e "Logstash\|appender\| INFO "`
  if [ "${log}" != "" ];
  then
    containername=`docker ps -a | grep $c | awk '{print $NF}'`
    echo "*********    container $containername $c is een beetje stuk    *********"
    echo "kijk maar: ${log}"
  fi
done
