#!/bin/bash

. ./env

if [ $1 == "ai" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-afnemersindicatiecreate
fi

if [ $1 == "aut" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-autorisatiecreate
fi

if [ $1 == "pl" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-persooncreate
fi

#if [ $1 == "proto" ];
#then
#	docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-protocolleringcreate
#fi


