#!/bin/bash

. ./env

if [ $1 == "ai" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-afnemersindicatierun
fi

if [ $1 == "aut" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-autorisatierun
fi

if [ $1 == "pl" ];
then
        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-persoonrun
fi

#if [ $1 == "proto" ];
#then
#        docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarbrp-protocolleringrun
#fi

if [ $1 == "terug" ];
then
	docker-compose -p iv -f integratie.yml up -d --no-recreate iv-naarlo3-persoonterug
fi

