/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Dbobject generated by hbm2java
 */
public class Dbobject  implements java.io.Serializable {


     private int id;
     private Srtdbobject srtdbobject;
     private Dbobject dbobject;
     private String naam;
     private String javaidentifier;
     private Integer dataanvgel;
     private Integer dateindegel;

    public Dbobject() {
    }

	
    public Dbobject(int id, Srtdbobject srtdbobject, String naam, String javaidentifier) {
        this.id = id;
        this.srtdbobject = srtdbobject;
        this.naam = naam;
        this.javaidentifier = javaidentifier;
    }
    public Dbobject(int id, Srtdbobject srtdbobject, Dbobject dbobject, String naam, String javaidentifier, Integer dataanvgel, Integer dateindegel) {
       this.id = id;
       this.srtdbobject = srtdbobject;
       this.dbobject = dbobject;
       this.naam = naam;
       this.javaidentifier = javaidentifier;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Srtdbobject getSrtdbobject() {
        return this.srtdbobject;
    }
    
    public void setSrtdbobject(Srtdbobject srtdbobject) {
        this.srtdbobject = srtdbobject;
    }
    public Dbobject getDbobject() {
        return this.dbobject;
    }
    
    public void setDbobject(Dbobject dbobject) {
        this.dbobject = dbobject;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getJavaidentifier() {
        return this.javaidentifier;
    }
    
    public void setJavaidentifier(String javaidentifier) {
        this.javaidentifier = javaidentifier;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }




}


