/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersuitslnlkiesr generated by hbm2java
 */
public class HisPersuitslnlkiesr extends His {


     private Pers pers;
     private boolean induitslnlkiesr;
     private Integer dateindeuitslnlkiesr;

    public HisPersuitslnlkiesr() {
    }

    public HisPersuitslnlkiesr(final Pers pers) {
        this.pers = pers;
        pers.setUitslnlkiesrstatushis(StatusHis.A);
        induitslnlkiesr = pers.getInduitslnlkiesr();
        dateindeuitslnlkiesr = pers.getDateindeuitslnlkiesr();
    }
   
    public Pers getPers() {
        return this.pers;
    }
    
    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public boolean isInduitslnlkiesr() {
        return this.induitslnlkiesr;
    }
    
    public void setInduitslnlkiesr(boolean induitslnlkiesr) {
        this.induitslnlkiesr = induitslnlkiesr;
    }
    public Integer getDateindeuitslnlkiesr() {
        return this.dateindeuitslnlkiesr;
    }
    
    public void setDateindeuitslnlkiesr(Integer dateindeuitslnlkiesr) {
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
    }




}


