/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersgeboorte generated by hbm2java
 */
public class HisPersgeboorte extends His {


     private Plaats plaats;
     private Pers pers;
     private Land land;
     private Partij partij;
     private int datgeboorte;
     private String blgeboorteplaats;
     private String blregiogeboorte;
     private String omsgeboorteloc;

    public HisPersgeboorte() {
    }

    public HisPersgeboorte(final Pers pers) {
        this.pers = pers;
        pers.setGeboortestatushis(StatusHis.A);
        datgeboorte = pers.getDatgeboorte();
        land = pers.getLandByLandgeboorte();
        plaats = pers.getPlaatsByWplgeboorte();
        partij = pers.getPartijByGemgeboorte();
        omsgeboorteloc = pers.getOmsgeboorteloc();
        blregiogeboorte = pers.getBlregiogeboorte();
        blgeboorteplaats = pers.getBlgeboorteplaats();
    }
   
    public Plaats getPlaats() {
        return this.plaats;
    }
    
    public void setPlaats(Plaats plaats) {
        this.plaats = plaats;
    }
    public Pers getPers() {
        return this.pers;
    }
    
    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Land getLand() {
        return this.land;
    }
    
    public void setLand(Land land) {
        this.land = land;
    }
    public Partij getPartij() {
        return this.partij;
    }
    
    public void setPartij(Partij partij) {
        this.partij = partij;
    }
    public int getDatgeboorte() {
        return this.datgeboorte;
    }
    
    public void setDatgeboorte(int datgeboorte) {
        this.datgeboorte = datgeboorte;
    }
    public String getBlgeboorteplaats() {
        return this.blgeboorteplaats;
    }
    
    public void setBlgeboorteplaats(String blgeboorteplaats) {
        this.blgeboorteplaats = blgeboorteplaats;
    }
    public String getBlregiogeboorte() {
        return this.blregiogeboorte;
    }
    
    public void setBlregiogeboorte(String blregiogeboorte) {
        this.blregiogeboorte = blregiogeboorte;
    }
    public String getOmsgeboorteloc() {
        return this.omsgeboorteloc;
    }
    
    public void setOmsgeboorteloc(String omsgeboorteloc) {
        this.omsgeboorteloc = omsgeboorteloc;
    }




}


