/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Onderzoek generated by hbm2java
 */
public class Onderzoek  implements java.io.Serializable {


     private int id;
     private Integer datbegin;
     private Integer dateinde;
     private String oms;
     private String onderzoekstatushis;

    public Onderzoek() {
    }

	
    public Onderzoek(int id, String onderzoekstatushis) {
        this.id = id;
        this.onderzoekstatushis = onderzoekstatushis;
    }
    public Onderzoek(int id, Integer datbegin, Integer dateinde, String oms, String onderzoekstatushis) {
       this.id = id;
       this.datbegin = datbegin;
       this.dateinde = dateinde;
       this.oms = oms;
       this.onderzoekstatushis = onderzoekstatushis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getDatbegin() {
        return this.datbegin;
    }
    
    public void setDatbegin(Integer datbegin) {
        this.datbegin = datbegin;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }
    
    public void setDateinde(Integer dateinde) {
        this.dateinde = dateinde;
    }
    public String getOms() {
        return this.oms;
    }
    
    public void setOms(String oms) {
        this.oms = oms;
    }
    public String getOnderzoekstatushis() {
        return this.onderzoekstatushis;
    }
    
    public void setOnderzoekstatushis(String onderzoekstatushis) {
        this.onderzoekstatushis = onderzoekstatushis;
    }




}


