/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Srtdoc generated by hbm2java
 */
public class Srtdoc  implements java.io.Serializable {


     private short id;
     private Categoriesrtdoc categoriesrtdoc;
     private String naam;

    public Srtdoc() {
    }

    public Srtdoc(short id, Categoriesrtdoc categoriesrtdoc, String naam) {
       this.id = id;
       this.categoriesrtdoc = categoriesrtdoc;
       this.naam = naam;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Categoriesrtdoc getCategoriesrtdoc() {
        return this.categoriesrtdoc;
    }
    
    public void setCategoriesrtdoc(Categoriesrtdoc categoriesrtdoc) {
        this.categoriesrtdoc = categoriesrtdoc;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }




}


