/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Actie generated by hbm2java
 */
public class Actie  implements java.io.Serializable {


     private long id;
     private short srt;
     private Long admhnd;
     private short partij;
     private Date tsreg;
     private Integer datontlening;

    public Actie() {
    }

	
    public Actie(long id, short srt, short partij, Date tsreg) {
        this.id = id;
        this.srt = srt;
        this.partij = partij;
        this.tsreg = tsreg;
    }
    public Actie(long id, short srt, Long admhnd, short partij, Date tsreg, Integer datontlening) {
       this.id = id;
       this.srt = srt;
       this.admhnd = admhnd;
       this.partij = partij;
       this.tsreg = tsreg;
       this.datontlening = datontlening;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public Long getAdmhnd() {
        return this.admhnd;
    }
    
    public void setAdmhnd(Long admhnd) {
        this.admhnd = admhnd;
    }
    public short getPartij() {
        return this.partij;
    }
    
    public void setPartij(short partij) {
        this.partij = partij;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Integer getDatontlening() {
        return this.datontlening;
    }
    
    public void setDatontlening(Integer datontlening) {
        this.datontlening = datontlening;
    }




}


