/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Element generated by hbm2java
 */
public class Element  implements java.io.Serializable {


     private int id;
     private String naam;
     private short srt;
     private Integer ouder;
     private Integer groep;
     private Boolean indonderdeelpl;
     private Boolean indonderdeelplouder;
     private Boolean indonderdeelplkind;
     private Boolean indonderdeelplpartner;
     private Boolean indverantwoordingpl;
     private Boolean indalgemeen;
     private Boolean indadministratief;
     private Integer dataanvgel;
     private Integer dateindegel;

    public Element() {
    }

	
    public Element(int id, String naam, short srt) {
        this.id = id;
        this.naam = naam;
        this.srt = srt;
    }
    public Element(int id, String naam, short srt, Integer ouder, Integer groep, Boolean indonderdeelpl, Boolean indonderdeelplouder, Boolean indonderdeelplkind, Boolean indonderdeelplpartner, Boolean indverantwoordingpl, Boolean indalgemeen, Boolean indadministratief, Integer dataanvgel, Integer dateindegel) {
       this.id = id;
       this.naam = naam;
       this.srt = srt;
       this.ouder = ouder;
       this.groep = groep;
       this.indonderdeelpl = indonderdeelpl;
       this.indonderdeelplouder = indonderdeelplouder;
       this.indonderdeelplkind = indonderdeelplkind;
       this.indonderdeelplpartner = indonderdeelplpartner;
       this.indverantwoordingpl = indverantwoordingpl;
       this.indalgemeen = indalgemeen;
       this.indadministratief = indadministratief;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public Integer getOuder() {
        return this.ouder;
    }
    
    public void setOuder(Integer ouder) {
        this.ouder = ouder;
    }
    public Integer getGroep() {
        return this.groep;
    }
    
    public void setGroep(Integer groep) {
        this.groep = groep;
    }
    public Boolean getIndonderdeelpl() {
        return this.indonderdeelpl;
    }
    
    public void setIndonderdeelpl(Boolean indonderdeelpl) {
        this.indonderdeelpl = indonderdeelpl;
    }
    public Boolean getIndonderdeelplouder() {
        return this.indonderdeelplouder;
    }
    
    public void setIndonderdeelplouder(Boolean indonderdeelplouder) {
        this.indonderdeelplouder = indonderdeelplouder;
    }
    public Boolean getIndonderdeelplkind() {
        return this.indonderdeelplkind;
    }
    
    public void setIndonderdeelplkind(Boolean indonderdeelplkind) {
        this.indonderdeelplkind = indonderdeelplkind;
    }
    public Boolean getIndonderdeelplpartner() {
        return this.indonderdeelplpartner;
    }
    
    public void setIndonderdeelplpartner(Boolean indonderdeelplpartner) {
        this.indonderdeelplpartner = indonderdeelplpartner;
    }
    public Boolean getIndverantwoordingpl() {
        return this.indverantwoordingpl;
    }
    
    public void setIndverantwoordingpl(Boolean indverantwoordingpl) {
        this.indverantwoordingpl = indverantwoordingpl;
    }
    public Boolean getIndalgemeen() {
        return this.indalgemeen;
    }
    
    public void setIndalgemeen(Boolean indalgemeen) {
        this.indalgemeen = indalgemeen;
    }
    public Boolean getIndadministratief() {
        return this.indadministratief;
    }
    
    public void setIndadministratief(Boolean indadministratief) {
        this.indadministratief = indadministratief;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }




}


