/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Gegeveninterugmelding generated by hbm2java
 */
public class Gegeveninterugmelding  implements java.io.Serializable {


     private int id;
     private int terugmelding;
     private int gegevenselement;
     private String betwijfeldewaarde;
     private String verwachtewaarde;

    public Gegeveninterugmelding() {
    }

	
    public Gegeveninterugmelding(int id, int terugmelding, int gegevenselement) {
        this.id = id;
        this.terugmelding = terugmelding;
        this.gegevenselement = gegevenselement;
    }
    public Gegeveninterugmelding(int id, int terugmelding, int gegevenselement, String betwijfeldewaarde, String verwachtewaarde) {
       this.id = id;
       this.terugmelding = terugmelding;
       this.gegevenselement = gegevenselement;
       this.betwijfeldewaarde = betwijfeldewaarde;
       this.verwachtewaarde = verwachtewaarde;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTerugmelding() {
        return this.terugmelding;
    }
    
    public void setTerugmelding(int terugmelding) {
        this.terugmelding = terugmelding;
    }
    public int getGegevenselement() {
        return this.gegevenselement;
    }
    
    public void setGegevenselement(int gegevenselement) {
        this.gegevenselement = gegevenselement;
    }
    public String getBetwijfeldewaarde() {
        return this.betwijfeldewaarde;
    }
    
    public void setBetwijfeldewaarde(String betwijfeldewaarde) {
        this.betwijfeldewaarde = betwijfeldewaarde;
    }
    public String getVerwachtewaarde() {
        return this.verwachtewaarde;
    }
    
    public void setVerwachtewaarde(String verwachtewaarde) {
        this.verwachtewaarde = verwachtewaarde;
    }




}


