/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Gem generated by hbm2java
 */
public class Gem  implements nl.bzk.brp.testdatageneratie.dataaccess.Cacheable<Short>,java.io.Serializable {


     private short id;
     private String naam;
     private short code;
     private short partij;
     private Short voortzettendegem;
     private Integer dataanvgel;
     private Integer dateindegel;

    public Gem() {
    }

	
    public Gem(short id, String naam, short code, short partij) {
        this.id = id;
        this.naam = naam;
        this.code = code;
        this.partij = partij;
    }
    public Gem(short id, String naam, short code, short partij, Short voortzettendegem, Integer dataanvgel, Integer dateindegel) {
       this.id = id;
       this.naam = naam;
       this.code = code;
       this.partij = partij;
       this.voortzettendegem = voortzettendegem;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public short getCode() {
        return this.code;
    }
    
    public void setCode(short code) {
        this.code = code;
    }
    public short getPartij() {
        return this.partij;
    }
    
    public void setPartij(short partij) {
        this.partij = partij;
    }
    public Short getVoortzettendegem() {
        return this.voortzettendegem;
    }
    
    public void setVoortzettendegem(Short voortzettendegem) {
        this.voortzettendegem = voortzettendegem;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }



  // The following is extra code specified in the hbm.xml files
@Override public Short getKey() { return code; }
  // end of extra code specified in the hbm.xml files

}


