/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisOuderouderlijkgezag generated by hbm2java
 */
public class HisOuderouderlijkgezag  implements HisMaterieel,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int betr;
     private Integer dataanvgel;
     private Integer dateindegel;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private Long actieaanpgel;
     private boolean indouderheeftgezag;

    public HisOuderouderlijkgezag() {
    }

	
    public HisOuderouderlijkgezag(int id, int betr, boolean indouderheeftgezag) {
        this.id = id;
        this.betr = betr;
        this.indouderheeftgezag = indouderheeftgezag;
    }
    public HisOuderouderlijkgezag(int id, int betr, Integer dataanvgel, Integer dateindegel, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, Long actieaanpgel, boolean indouderheeftgezag) {
       this.id = id;
       this.betr = betr;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.actieaanpgel = actieaanpgel;
       this.indouderheeftgezag = indouderheeftgezag;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getBetr() {
        return this.betr;
    }
    
    public void setBetr(int betr) {
        this.betr = betr;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public Long getActieaanpgel() {
        return this.actieaanpgel;
    }
    
    public void setActieaanpgel(Long actieaanpgel) {
        this.actieaanpgel = actieaanpgel;
    }
    public boolean isIndouderheeftgezag() {
        return this.indouderheeftgezag;
    }
    
    public void setIndouderheeftgezag(boolean indouderheeftgezag) {
        this.indouderheeftgezag = indouderheeftgezag;
    }




}


