/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersadres generated by hbm2java
 */
public class HisPersadres  implements HisMaterieel,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int persadres;
     private Integer dataanvgel;
     private Integer dateindegel;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private Long actieaanpgel;
     private short srt;
     private Short rdnwijz;
     private Short aangadresh;
     private Integer dataanvadresh;
     private String identcodeadresseerbaarobject;
     private String identcodenraand;
     private Short gem;
     private String nor;
     private String afgekortenor;
     private String gemdeel;
     private Integer huisnr;
     private String huisletter;
     private String huisnrtoevoeging;
     private String postcode;
     private String wplnaam;
     private String loctenopzichtevanadres;
     private String locoms;
     private String bladresregel1;
     private String bladresregel2;
     private String bladresregel3;
     private String bladresregel4;
     private String bladresregel5;
     private String bladresregel6;
     private int landgebied;
     private Boolean indpersaangetroffenopadres;

    public HisPersadres() {
    }

	
    public HisPersadres(int id, int persadres, short srt, int landgebied) {
        this.id = id;
        this.persadres = persadres;
        this.srt = srt;
        this.landgebied = landgebied;
    }
    public HisPersadres(int id, int persadres, Integer dataanvgel, Integer dateindegel, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, Long actieaanpgel, short srt, Short rdnwijz, Short aangadresh, Integer dataanvadresh, String identcodeadresseerbaarobject, String identcodenraand, Short gem, String nor, String afgekortenor, String gemdeel, Integer huisnr, String huisletter, String huisnrtoevoeging, String postcode, String wplnaam, String loctenopzichtevanadres, String locoms, String bladresregel1, String bladresregel2, String bladresregel3, String bladresregel4, String bladresregel5, String bladresregel6, int landgebied, Boolean indpersaangetroffenopadres) {
       this.id = id;
       this.persadres = persadres;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.actieaanpgel = actieaanpgel;
       this.srt = srt;
       this.rdnwijz = rdnwijz;
       this.aangadresh = aangadresh;
       this.dataanvadresh = dataanvadresh;
       this.identcodeadresseerbaarobject = identcodeadresseerbaarobject;
       this.identcodenraand = identcodenraand;
       this.gem = gem;
       this.nor = nor;
       this.afgekortenor = afgekortenor;
       this.gemdeel = gemdeel;
       this.huisnr = huisnr;
       this.huisletter = huisletter;
       this.huisnrtoevoeging = huisnrtoevoeging;
       this.postcode = postcode;
       this.wplnaam = wplnaam;
       this.loctenopzichtevanadres = loctenopzichtevanadres;
       this.locoms = locoms;
       this.bladresregel1 = bladresregel1;
       this.bladresregel2 = bladresregel2;
       this.bladresregel3 = bladresregel3;
       this.bladresregel4 = bladresregel4;
       this.bladresregel5 = bladresregel5;
       this.bladresregel6 = bladresregel6;
       this.landgebied = landgebied;
       this.indpersaangetroffenopadres = indpersaangetroffenopadres;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPersadres() {
        return this.persadres;
    }
    
    public void setPersadres(int persadres) {
        this.persadres = persadres;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public Long getActieaanpgel() {
        return this.actieaanpgel;
    }
    
    public void setActieaanpgel(Long actieaanpgel) {
        this.actieaanpgel = actieaanpgel;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public Short getRdnwijz() {
        return this.rdnwijz;
    }
    
    public void setRdnwijz(Short rdnwijz) {
        this.rdnwijz = rdnwijz;
    }
    public Short getAangadresh() {
        return this.aangadresh;
    }
    
    public void setAangadresh(Short aangadresh) {
        this.aangadresh = aangadresh;
    }
    public Integer getDataanvadresh() {
        return this.dataanvadresh;
    }
    
    public void setDataanvadresh(Integer dataanvadresh) {
        this.dataanvadresh = dataanvadresh;
    }
    public String getIdentcodeadresseerbaarobject() {
        return this.identcodeadresseerbaarobject;
    }
    
    public void setIdentcodeadresseerbaarobject(String identcodeadresseerbaarobject) {
        this.identcodeadresseerbaarobject = identcodeadresseerbaarobject;
    }
    public String getIdentcodenraand() {
        return this.identcodenraand;
    }
    
    public void setIdentcodenraand(String identcodenraand) {
        this.identcodenraand = identcodenraand;
    }
    public Short getGem() {
        return this.gem;
    }
    
    public void setGem(Short gem) {
        this.gem = gem;
    }
    public String getNor() {
        return this.nor;
    }
    
    public void setNor(String nor) {
        this.nor = nor;
    }
    public String getAfgekortenor() {
        return this.afgekortenor;
    }
    
    public void setAfgekortenor(String afgekortenor) {
        this.afgekortenor = afgekortenor;
    }
    public String getGemdeel() {
        return this.gemdeel;
    }
    
    public void setGemdeel(String gemdeel) {
        this.gemdeel = gemdeel;
    }
    public Integer getHuisnr() {
        return this.huisnr;
    }
    
    public void setHuisnr(Integer huisnr) {
        this.huisnr = huisnr;
    }
    public String getHuisletter() {
        return this.huisletter;
    }
    
    public void setHuisletter(String huisletter) {
        this.huisletter = huisletter;
    }
    public String getHuisnrtoevoeging() {
        return this.huisnrtoevoeging;
    }
    
    public void setHuisnrtoevoeging(String huisnrtoevoeging) {
        this.huisnrtoevoeging = huisnrtoevoeging;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getWplnaam() {
        return this.wplnaam;
    }
    
    public void setWplnaam(String wplnaam) {
        this.wplnaam = wplnaam;
    }
    public String getLoctenopzichtevanadres() {
        return this.loctenopzichtevanadres;
    }
    
    public void setLoctenopzichtevanadres(String loctenopzichtevanadres) {
        this.loctenopzichtevanadres = loctenopzichtevanadres;
    }
    public String getLocoms() {
        return this.locoms;
    }
    
    public void setLocoms(String locoms) {
        this.locoms = locoms;
    }
    public String getBladresregel1() {
        return this.bladresregel1;
    }
    
    public void setBladresregel1(String bladresregel1) {
        this.bladresregel1 = bladresregel1;
    }
    public String getBladresregel2() {
        return this.bladresregel2;
    }
    
    public void setBladresregel2(String bladresregel2) {
        this.bladresregel2 = bladresregel2;
    }
    public String getBladresregel3() {
        return this.bladresregel3;
    }
    
    public void setBladresregel3(String bladresregel3) {
        this.bladresregel3 = bladresregel3;
    }
    public String getBladresregel4() {
        return this.bladresregel4;
    }
    
    public void setBladresregel4(String bladresregel4) {
        this.bladresregel4 = bladresregel4;
    }
    public String getBladresregel5() {
        return this.bladresregel5;
    }
    
    public void setBladresregel5(String bladresregel5) {
        this.bladresregel5 = bladresregel5;
    }
    public String getBladresregel6() {
        return this.bladresregel6;
    }
    
    public void setBladresregel6(String bladresregel6) {
        this.bladresregel6 = bladresregel6;
    }
    public int getLandgebied() {
        return this.landgebied;
    }
    
    public void setLandgebied(int landgebied) {
        this.landgebied = landgebied;
    }
    public Boolean getIndpersaangetroffenopadres() {
        return this.indpersaangetroffenopadres;
    }
    
    public void setIndpersaangetroffenopadres(Boolean indpersaangetroffenopadres) {
        this.indpersaangetroffenopadres = indpersaangetroffenopadres;
    }




}


