/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPerspk generated by hbm2java
 */
public class HisPerspk  implements His,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int pers;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private Short gempk;
     private boolean indpkvollediggeconv;

    public HisPerspk() {
    }

	
    public HisPerspk(int id, int pers, boolean indpkvollediggeconv) {
        this.id = id;
        this.pers = pers;
        this.indpkvollediggeconv = indpkvollediggeconv;
    }
    public HisPerspk(int id, int pers, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, Short gempk, boolean indpkvollediggeconv) {
       this.id = id;
       this.pers = pers;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.gempk = gempk;
       this.indpkvollediggeconv = indpkvollediggeconv;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public Short getGempk() {
        return this.gempk;
    }
    
    public void setGempk(Short gempk) {
        this.gempk = gempk;
    }
    public boolean isIndpkvollediggeconv() {
        return this.indpkvollediggeconv;
    }
    
    public void setIndpkvollediggeconv(boolean indpkvollediggeconv) {
        this.indpkvollediggeconv = indpkvollediggeconv;
    }




}


