/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersreisdoc generated by hbm2java
 */
public class HisPersreisdoc  implements His,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int persreisdoc;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private String nr;
     private Short lengtehouder;
     private String autvanafgifte;
     private int datingangdoc;
     private int dateindedoc;
     private int datuitgifte;
     private Integer datinhingvermissing;
     private Short aandinhingvermissing;

    public HisPersreisdoc() {
    }

	
    public HisPersreisdoc(int id, int persreisdoc, String nr, String autvanafgifte, int datingangdoc, int dateindedoc, int datuitgifte) {
        this.id = id;
        this.persreisdoc = persreisdoc;
        this.nr = nr;
        this.autvanafgifte = autvanafgifte;
        this.datingangdoc = datingangdoc;
        this.dateindedoc = dateindedoc;
        this.datuitgifte = datuitgifte;
    }
    public HisPersreisdoc(int id, int persreisdoc, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, String nr, Short lengtehouder, String autvanafgifte, int datingangdoc, int dateindedoc, int datuitgifte, Integer datinhingvermissing, Short aandinhingvermissing) {
       this.id = id;
       this.persreisdoc = persreisdoc;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.nr = nr;
       this.lengtehouder = lengtehouder;
       this.autvanafgifte = autvanafgifte;
       this.datingangdoc = datingangdoc;
       this.dateindedoc = dateindedoc;
       this.datuitgifte = datuitgifte;
       this.datinhingvermissing = datinhingvermissing;
       this.aandinhingvermissing = aandinhingvermissing;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPersreisdoc() {
        return this.persreisdoc;
    }
    
    public void setPersreisdoc(int persreisdoc) {
        this.persreisdoc = persreisdoc;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public String getNr() {
        return this.nr;
    }
    
    public void setNr(String nr) {
        this.nr = nr;
    }
    public Short getLengtehouder() {
        return this.lengtehouder;
    }
    
    public void setLengtehouder(Short lengtehouder) {
        this.lengtehouder = lengtehouder;
    }
    public String getAutvanafgifte() {
        return this.autvanafgifte;
    }
    
    public void setAutvanafgifte(String autvanafgifte) {
        this.autvanafgifte = autvanafgifte;
    }
    public int getDatingangdoc() {
        return this.datingangdoc;
    }
    
    public void setDatingangdoc(int datingangdoc) {
        this.datingangdoc = datingangdoc;
    }
    public int getDateindedoc() {
        return this.dateindedoc;
    }
    
    public void setDateindedoc(int dateindedoc) {
        this.dateindedoc = dateindedoc;
    }
    public int getDatuitgifte() {
        return this.datuitgifte;
    }
    
    public void setDatuitgifte(int datuitgifte) {
        this.datuitgifte = datuitgifte;
    }
    public Integer getDatinhingvermissing() {
        return this.datinhingvermissing;
    }
    
    public void setDatinhingvermissing(Integer datinhingvermissing) {
        this.datinhingvermissing = datinhingvermissing;
    }
    public Short getAandinhingvermissing() {
        return this.aandinhingvermissing;
    }
    
    public void setAandinhingvermissing(Short aandinhingvermissing) {
        this.aandinhingvermissing = aandinhingvermissing;
    }




}


