/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersmigratie generated by hbm2java
 */
public class HisPersmigratie  implements HisMaterieel,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int pers;
     private Integer dataanvgel;
     private Integer dateindegel;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private Long actieaanpgel;
     private short srtmigratie;
     private Short rdnwijzmigratie;
     private Short aangmigratie;
     private Integer landgebiedmigratie;
     private String bladresregel1migratie;
     private String bladresregel2migratie;
     private String bladresregel3migratie;
     private String bladresregel4migratie;
     private String bladresregel5migratie;
     private String bladresregel6migratie;

    public HisPersmigratie() {
    }

	
    public HisPersmigratie(int id, int pers, short srtmigratie) {
        this.id = id;
        this.pers = pers;
        this.srtmigratie = srtmigratie;
    }
    public HisPersmigratie(int id, int pers, Integer dataanvgel, Integer dateindegel, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, Long actieaanpgel, short srtmigratie, Short rdnwijzmigratie, Short aangmigratie, Integer landgebiedmigratie, String bladresregel1migratie, String bladresregel2migratie, String bladresregel3migratie, String bladresregel4migratie, String bladresregel5migratie, String bladresregel6migratie) {
       this.id = id;
       this.pers = pers;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.actieaanpgel = actieaanpgel;
       this.srtmigratie = srtmigratie;
       this.rdnwijzmigratie = rdnwijzmigratie;
       this.aangmigratie = aangmigratie;
       this.landgebiedmigratie = landgebiedmigratie;
       this.bladresregel1migratie = bladresregel1migratie;
       this.bladresregel2migratie = bladresregel2migratie;
       this.bladresregel3migratie = bladresregel3migratie;
       this.bladresregel4migratie = bladresregel4migratie;
       this.bladresregel5migratie = bladresregel5migratie;
       this.bladresregel6migratie = bladresregel6migratie;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public Long getActieaanpgel() {
        return this.actieaanpgel;
    }
    
    public void setActieaanpgel(Long actieaanpgel) {
        this.actieaanpgel = actieaanpgel;
    }
    public short getSrtmigratie() {
        return this.srtmigratie;
    }
    
    public void setSrtmigratie(short srtmigratie) {
        this.srtmigratie = srtmigratie;
    }
    public Short getRdnwijzmigratie() {
        return this.rdnwijzmigratie;
    }
    
    public void setRdnwijzmigratie(Short rdnwijzmigratie) {
        this.rdnwijzmigratie = rdnwijzmigratie;
    }
    public Short getAangmigratie() {
        return this.aangmigratie;
    }
    
    public void setAangmigratie(Short aangmigratie) {
        this.aangmigratie = aangmigratie;
    }
    public Integer getLandgebiedmigratie() {
        return this.landgebiedmigratie;
    }
    
    public void setLandgebiedmigratie(Integer landgebiedmigratie) {
        this.landgebiedmigratie = landgebiedmigratie;
    }
    public String getBladresregel1migratie() {
        return this.bladresregel1migratie;
    }
    
    public void setBladresregel1migratie(String bladresregel1migratie) {
        this.bladresregel1migratie = bladresregel1migratie;
    }
    public String getBladresregel2migratie() {
        return this.bladresregel2migratie;
    }
    
    public void setBladresregel2migratie(String bladresregel2migratie) {
        this.bladresregel2migratie = bladresregel2migratie;
    }
    public String getBladresregel3migratie() {
        return this.bladresregel3migratie;
    }
    
    public void setBladresregel3migratie(String bladresregel3migratie) {
        this.bladresregel3migratie = bladresregel3migratie;
    }
    public String getBladresregel4migratie() {
        return this.bladresregel4migratie;
    }
    
    public void setBladresregel4migratie(String bladresregel4migratie) {
        this.bladresregel4migratie = bladresregel4migratie;
    }
    public String getBladresregel5migratie() {
        return this.bladresregel5migratie;
    }
    
    public void setBladresregel5migratie(String bladresregel5migratie) {
        this.bladresregel5migratie = bladresregel5migratie;
    }
    public String getBladresregel6migratie() {
        return this.bladresregel6migratie;
    }
    
    public void setBladresregel6migratie(String bladresregel6migratie) {
        this.bladresregel6migratie = bladresregel6migratie;
    }




}


