/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersgeboorte generated by hbm2java
 */
public class HisPersgeboorte  implements His,IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int pers;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private int datgeboorte;
     private Short gemgeboorte;
     private String wplnaamgeboorte;
     private String blplaatsgeboorte;
     private String blregiogeboorte;
     private String omslocgeboorte;
     private int landgebiedgeboorte;

    public HisPersgeboorte() {
    }

	
    public HisPersgeboorte(int id, int pers, int datgeboorte, int landgebiedgeboorte) {
        this.id = id;
        this.pers = pers;
        this.datgeboorte = datgeboorte;
        this.landgebiedgeboorte = landgebiedgeboorte;
    }
    public HisPersgeboorte(int id, int pers, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, int datgeboorte, Short gemgeboorte, String wplnaamgeboorte, String blplaatsgeboorte, String blregiogeboorte, String omslocgeboorte, int landgebiedgeboorte) {
       this.id = id;
       this.pers = pers;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.datgeboorte = datgeboorte;
       this.gemgeboorte = gemgeboorte;
       this.wplnaamgeboorte = wplnaamgeboorte;
       this.blplaatsgeboorte = blplaatsgeboorte;
       this.blregiogeboorte = blregiogeboorte;
       this.omslocgeboorte = omslocgeboorte;
       this.landgebiedgeboorte = landgebiedgeboorte;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public int getDatgeboorte() {
        return this.datgeboorte;
    }
    
    public void setDatgeboorte(int datgeboorte) {
        this.datgeboorte = datgeboorte;
    }
    public Short getGemgeboorte() {
        return this.gemgeboorte;
    }
    
    public void setGemgeboorte(Short gemgeboorte) {
        this.gemgeboorte = gemgeboorte;
    }
    public String getWplnaamgeboorte() {
        return this.wplnaamgeboorte;
    }
    
    public void setWplnaamgeboorte(String wplnaamgeboorte) {
        this.wplnaamgeboorte = wplnaamgeboorte;
    }
    public String getBlplaatsgeboorte() {
        return this.blplaatsgeboorte;
    }
    
    public void setBlplaatsgeboorte(String blplaatsgeboorte) {
        this.blplaatsgeboorte = blplaatsgeboorte;
    }
    public String getBlregiogeboorte() {
        return this.blregiogeboorte;
    }
    
    public void setBlregiogeboorte(String blregiogeboorte) {
        this.blregiogeboorte = blregiogeboorte;
    }
    public String getOmslocgeboorte() {
        return this.omslocgeboorte;
    }
    
    public void setOmslocgeboorte(String omslocgeboorte) {
        this.omslocgeboorte = omslocgeboorte;
    }
    public int getLandgebiedgeboorte() {
        return this.landgebiedgeboorte;
    }
    
    public void setLandgebiedgeboorte(int landgebiedgeboorte) {
        this.landgebiedgeboorte = landgebiedgeboorte;
    }




}


