/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisPersverificatie generated by hbm2java
 */
public class HisPersverificatie  implements His,LongAsPrimaryKey,java.io.Serializable {


     private long id;
     private long persverificatie;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private int dat;

    public HisPersverificatie() {
    }

	
    public HisPersverificatie(long id, long persverificatie, int dat) {
        this.id = id;
        this.persverificatie = persverificatie;
        this.dat = dat;
    }
    public HisPersverificatie(long id, long persverificatie, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, int dat) {
       this.id = id;
       this.persverificatie = persverificatie;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.dat = dat;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getPersverificatie() {
        return this.persverificatie;
    }
    
    public void setPersverificatie(long persverificatie) {
        this.persverificatie = persverificatie;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public int getDat() {
        return this.dat;
    }
    
    public void setDat(int dat) {
        this.dat = dat;
    }




}


