/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Partijrol generated by hbm2java
 */
public class Partijrol  implements java.io.Serializable {


     private int id;
     private short partij;
     private short rol;

    public Partijrol() {
    }

    public Partijrol(int id, short partij, short rol) {
       this.id = id;
       this.partij = partij;
       this.rol = rol;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public short getPartij() {
        return this.partij;
    }
    
    public void setPartij(short partij) {
        this.partij = partij;
    }
    public short getRol() {
        return this.rol;
    }
    
    public void setRol(short rol) {
        this.rol = rol;
    }




}


