/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Persverificatie generated by hbm2java
 */
public class Persverificatie  implements java.io.Serializable {


     private long id;
     private int geverifieerde;
     private short partij;
     private String srt;
     private Integer dat;

    public Persverificatie() {
    }

	
    public Persverificatie(long id, int geverifieerde, short partij, String srt) {
        this.id = id;
        this.geverifieerde = geverifieerde;
        this.partij = partij;
        this.srt = srt;
    }
    public Persverificatie(long id, int geverifieerde, short partij, String srt, Integer dat) {
       this.id = id;
       this.geverifieerde = geverifieerde;
       this.partij = partij;
       this.srt = srt;
       this.dat = dat;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public int getGeverifieerde() {
        return this.geverifieerde;
    }
    
    public void setGeverifieerde(int geverifieerde) {
        this.geverifieerde = geverifieerde;
    }
    public short getPartij() {
        return this.partij;
    }
    
    public void setPartij(short partij) {
        this.partij = partij;
    }
    public String getSrt() {
        return this.srt;
    }
    
    public void setSrt(String srt) {
        this.srt = srt;
    }
    public Integer getDat() {
        return this.dat;
    }
    
    public void setDat(Integer dat) {
        this.dat = dat;
    }




}


