/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Persindicatie generated by hbm2java
 */
public class Persindicatie  implements IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int pers;
     private short srt;
     private Boolean waarde;

    public Persindicatie() {
    }

	
    public Persindicatie(int id, int pers, short srt) {
        this.id = id;
        this.pers = pers;
        this.srt = srt;
    }
    public Persindicatie(int id, int pers, short srt, Boolean waarde) {
       this.id = id;
       this.pers = pers;
       this.srt = srt;
       this.waarde = waarde;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public Boolean getWaarde() {
        return this.waarde;
    }
    
    public void setWaarde(Boolean waarde) {
        this.waarde = waarde;
    }




}


