/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Pers generated by hbm2java
 */
public class Pers  implements IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private short srt;
     private Long admhnd;
     private Date tslaatstewijz;
     private Boolean indonderzoeknaarnietopgenome;
     private Short sorteervolgorde;
     private Boolean indonverwbijhvoorstelnieting;
     private Date tslaatstewijzgbasystematiek;
     private Integer bsn;
     private Long anr;
     private Boolean indafgeleid;
     private Boolean indnreeks;
     private Short predicaat;
     private String voornamen;
     private Short adellijketitel;
     private String voorvoegsel;
     private String scheidingsteken;
     private String geslnaamstam;
     private Integer datgeboorte;
     private Short gemgeboorte;
     private String wplnaamgeboorte;
     private String blplaatsgeboorte;
     private String blregiogeboorte;
     private String omslocgeboorte;
     private Integer landgebiedgeboorte;
     private Short geslachtsaand;
     private Integer datinschr;
     private Long versienr;
     private Date dattijdstempel;
     private Integer vorigebsn;
     private Integer volgendebsn;
     private Long vorigeanr;
     private Long volgendeanr;
     private Short bijhpartij;
     private Short bijhaard;
     private Short naderebijhaard;
     private Boolean indonverwdocaanw;
     private Integer datoverlijden;
     private Short gemoverlijden;
     private String wplnaamoverlijden;
     private String blplaatsoverlijden;
     private String blregiooverlijden;
     private String omslocoverlijden;
     private Integer landgebiedoverlijden;
     private Short naamgebruik;
     private Boolean indnaamgebruikafgeleid;
     private Short predicaatnaamgebruik;
     private String voornamennaamgebruik;
     private Short adellijketitelnaamgebruik;
     private String voorvoegselnaamgebruik;
     private String scheidingstekennaamgebruik;
     private String geslnaamstamnaamgebruik;
     private Short srtmigratie;
     private Short rdnwijzmigratie;
     private Short aangmigratie;
     private Integer landgebiedmigratie;
     private String bladresregel1migratie;
     private String bladresregel2migratie;
     private String bladresregel3migratie;
     private String bladresregel4migratie;
     private String bladresregel5migratie;
     private String bladresregel6migratie;
     private Short aandverblijfsr;
     private Integer datmededelingverblijfsr;
     private Integer datvoorzeindeverblijfsr;
     private Boolean induitslkiesr;
     private Integer datvoorzeindeuitslkiesr;
     private Boolean inddeelneuverkiezingen;
     private Integer dataanlaanpdeelneuverkiezing;
     private Integer datvoorzeindeuitsleuverkiezi;
     private Short gempk;
     private Boolean indpkvollediggeconv;

    public Pers() {
    }

	
    public Pers(int id, short srt) {
        this.id = id;
        this.srt = srt;
    }
    public Pers(int id, short srt, Long admhnd, Date tslaatstewijz, Boolean indonderzoeknaarnietopgenome, Short sorteervolgorde, Boolean indonverwbijhvoorstelnieting, Date tslaatstewijzgbasystematiek, Integer bsn, Long anr, Boolean indafgeleid, Boolean indnreeks, Short predicaat, String voornamen, Short adellijketitel, String voorvoegsel, String scheidingsteken, String geslnaamstam, Integer datgeboorte, Short gemgeboorte, String wplnaamgeboorte, String blplaatsgeboorte, String blregiogeboorte, String omslocgeboorte, Integer landgebiedgeboorte, Short geslachtsaand, Integer datinschr, Long versienr, Date dattijdstempel, Integer vorigebsn, Integer volgendebsn, Long vorigeanr, Long volgendeanr, Short bijhpartij, Short bijhaard, Short naderebijhaard, Boolean indonverwdocaanw, Integer datoverlijden, Short gemoverlijden, String wplnaamoverlijden, String blplaatsoverlijden, String blregiooverlijden, String omslocoverlijden, Integer landgebiedoverlijden, Short naamgebruik, Boolean indnaamgebruikafgeleid, Short predicaatnaamgebruik, String voornamennaamgebruik, Short adellijketitelnaamgebruik, String voorvoegselnaamgebruik, String scheidingstekennaamgebruik, String geslnaamstamnaamgebruik, Short srtmigratie, Short rdnwijzmigratie, Short aangmigratie, Integer landgebiedmigratie, String bladresregel1migratie, String bladresregel2migratie, String bladresregel3migratie, String bladresregel4migratie, String bladresregel5migratie, String bladresregel6migratie, Short aandverblijfsr, Integer datmededelingverblijfsr, Integer datvoorzeindeverblijfsr, Boolean induitslkiesr, Integer datvoorzeindeuitslkiesr, Boolean inddeelneuverkiezingen, Integer dataanlaanpdeelneuverkiezing, Integer datvoorzeindeuitsleuverkiezi, Short gempk, Boolean indpkvollediggeconv) {
       this.id = id;
       this.srt = srt;
       this.admhnd = admhnd;
       this.tslaatstewijz = tslaatstewijz;
       this.indonderzoeknaarnietopgenome = indonderzoeknaarnietopgenome;
       this.sorteervolgorde = sorteervolgorde;
       this.indonverwbijhvoorstelnieting = indonverwbijhvoorstelnieting;
       this.tslaatstewijzgbasystematiek = tslaatstewijzgbasystematiek;
       this.bsn = bsn;
       this.anr = anr;
       this.indafgeleid = indafgeleid;
       this.indnreeks = indnreeks;
       this.predicaat = predicaat;
       this.voornamen = voornamen;
       this.adellijketitel = adellijketitel;
       this.voorvoegsel = voorvoegsel;
       this.scheidingsteken = scheidingsteken;
       this.geslnaamstam = geslnaamstam;
       this.datgeboorte = datgeboorte;
       this.gemgeboorte = gemgeboorte;
       this.wplnaamgeboorte = wplnaamgeboorte;
       this.blplaatsgeboorte = blplaatsgeboorte;
       this.blregiogeboorte = blregiogeboorte;
       this.omslocgeboorte = omslocgeboorte;
       this.landgebiedgeboorte = landgebiedgeboorte;
       this.geslachtsaand = geslachtsaand;
       this.datinschr = datinschr;
       this.versienr = versienr;
       this.dattijdstempel = dattijdstempel;
       this.vorigebsn = vorigebsn;
       this.volgendebsn = volgendebsn;
       this.vorigeanr = vorigeanr;
       this.volgendeanr = volgendeanr;
       this.bijhpartij = bijhpartij;
       this.bijhaard = bijhaard;
       this.naderebijhaard = naderebijhaard;
       this.indonverwdocaanw = indonverwdocaanw;
       this.datoverlijden = datoverlijden;
       this.gemoverlijden = gemoverlijden;
       this.wplnaamoverlijden = wplnaamoverlijden;
       this.blplaatsoverlijden = blplaatsoverlijden;
       this.blregiooverlijden = blregiooverlijden;
       this.omslocoverlijden = omslocoverlijden;
       this.landgebiedoverlijden = landgebiedoverlijden;
       this.naamgebruik = naamgebruik;
       this.indnaamgebruikafgeleid = indnaamgebruikafgeleid;
       this.predicaatnaamgebruik = predicaatnaamgebruik;
       this.voornamennaamgebruik = voornamennaamgebruik;
       this.adellijketitelnaamgebruik = adellijketitelnaamgebruik;
       this.voorvoegselnaamgebruik = voorvoegselnaamgebruik;
       this.scheidingstekennaamgebruik = scheidingstekennaamgebruik;
       this.geslnaamstamnaamgebruik = geslnaamstamnaamgebruik;
       this.srtmigratie = srtmigratie;
       this.rdnwijzmigratie = rdnwijzmigratie;
       this.aangmigratie = aangmigratie;
       this.landgebiedmigratie = landgebiedmigratie;
       this.bladresregel1migratie = bladresregel1migratie;
       this.bladresregel2migratie = bladresregel2migratie;
       this.bladresregel3migratie = bladresregel3migratie;
       this.bladresregel4migratie = bladresregel4migratie;
       this.bladresregel5migratie = bladresregel5migratie;
       this.bladresregel6migratie = bladresregel6migratie;
       this.aandverblijfsr = aandverblijfsr;
       this.datmededelingverblijfsr = datmededelingverblijfsr;
       this.datvoorzeindeverblijfsr = datvoorzeindeverblijfsr;
       this.induitslkiesr = induitslkiesr;
       this.datvoorzeindeuitslkiesr = datvoorzeindeuitslkiesr;
       this.inddeelneuverkiezingen = inddeelneuverkiezingen;
       this.dataanlaanpdeelneuverkiezing = dataanlaanpdeelneuverkiezing;
       this.datvoorzeindeuitsleuverkiezi = datvoorzeindeuitsleuverkiezi;
       this.gempk = gempk;
       this.indpkvollediggeconv = indpkvollediggeconv;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public Long getAdmhnd() {
        return this.admhnd;
    }
    
    public void setAdmhnd(Long admhnd) {
        this.admhnd = admhnd;
    }
    public Date getTslaatstewijz() {
        return this.tslaatstewijz;
    }
    
    public void setTslaatstewijz(Date tslaatstewijz) {
        this.tslaatstewijz = tslaatstewijz;
    }
    public Boolean getIndonderzoeknaarnietopgenome() {
        return this.indonderzoeknaarnietopgenome;
    }
    
    public void setIndonderzoeknaarnietopgenome(Boolean indonderzoeknaarnietopgenome) {
        this.indonderzoeknaarnietopgenome = indonderzoeknaarnietopgenome;
    }
    public Short getSorteervolgorde() {
        return this.sorteervolgorde;
    }
    
    public void setSorteervolgorde(Short sorteervolgorde) {
        this.sorteervolgorde = sorteervolgorde;
    }
    public Boolean getIndonverwbijhvoorstelnieting() {
        return this.indonverwbijhvoorstelnieting;
    }
    
    public void setIndonverwbijhvoorstelnieting(Boolean indonverwbijhvoorstelnieting) {
        this.indonverwbijhvoorstelnieting = indonverwbijhvoorstelnieting;
    }
    public Date getTslaatstewijzgbasystematiek() {
        return this.tslaatstewijzgbasystematiek;
    }
    
    public void setTslaatstewijzgbasystematiek(Date tslaatstewijzgbasystematiek) {
        this.tslaatstewijzgbasystematiek = tslaatstewijzgbasystematiek;
    }
    public Integer getBsn() {
        return this.bsn;
    }
    
    public void setBsn(Integer bsn) {
        this.bsn = bsn;
    }
    public Long getAnr() {
        return this.anr;
    }
    
    public void setAnr(Long anr) {
        this.anr = anr;
    }
    public Boolean getIndafgeleid() {
        return this.indafgeleid;
    }
    
    public void setIndafgeleid(Boolean indafgeleid) {
        this.indafgeleid = indafgeleid;
    }
    public Boolean getIndnreeks() {
        return this.indnreeks;
    }
    
    public void setIndnreeks(Boolean indnreeks) {
        this.indnreeks = indnreeks;
    }
    public Short getPredicaat() {
        return this.predicaat;
    }
    
    public void setPredicaat(Short predicaat) {
        this.predicaat = predicaat;
    }
    public String getVoornamen() {
        return this.voornamen;
    }
    
    public void setVoornamen(String voornamen) {
        this.voornamen = voornamen;
    }
    public Short getAdellijketitel() {
        return this.adellijketitel;
    }
    
    public void setAdellijketitel(Short adellijketitel) {
        this.adellijketitel = adellijketitel;
    }
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }
    
    public void setVoorvoegsel(String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }
    public String getScheidingsteken() {
        return this.scheidingsteken;
    }
    
    public void setScheidingsteken(String scheidingsteken) {
        this.scheidingsteken = scheidingsteken;
    }
    public String getGeslnaamstam() {
        return this.geslnaamstam;
    }
    
    public void setGeslnaamstam(String geslnaamstam) {
        this.geslnaamstam = geslnaamstam;
    }
    public Integer getDatgeboorte() {
        return this.datgeboorte;
    }
    
    public void setDatgeboorte(Integer datgeboorte) {
        this.datgeboorte = datgeboorte;
    }
    public Short getGemgeboorte() {
        return this.gemgeboorte;
    }
    
    public void setGemgeboorte(Short gemgeboorte) {
        this.gemgeboorte = gemgeboorte;
    }
    public String getWplnaamgeboorte() {
        return this.wplnaamgeboorte;
    }
    
    public void setWplnaamgeboorte(String wplnaamgeboorte) {
        this.wplnaamgeboorte = wplnaamgeboorte;
    }
    public String getBlplaatsgeboorte() {
        return this.blplaatsgeboorte;
    }
    
    public void setBlplaatsgeboorte(String blplaatsgeboorte) {
        this.blplaatsgeboorte = blplaatsgeboorte;
    }
    public String getBlregiogeboorte() {
        return this.blregiogeboorte;
    }
    
    public void setBlregiogeboorte(String blregiogeboorte) {
        this.blregiogeboorte = blregiogeboorte;
    }
    public String getOmslocgeboorte() {
        return this.omslocgeboorte;
    }
    
    public void setOmslocgeboorte(String omslocgeboorte) {
        this.omslocgeboorte = omslocgeboorte;
    }
    public Integer getLandgebiedgeboorte() {
        return this.landgebiedgeboorte;
    }
    
    public void setLandgebiedgeboorte(Integer landgebiedgeboorte) {
        this.landgebiedgeboorte = landgebiedgeboorte;
    }
    public Short getGeslachtsaand() {
        return this.geslachtsaand;
    }
    
    public void setGeslachtsaand(Short geslachtsaand) {
        this.geslachtsaand = geslachtsaand;
    }
    public Integer getDatinschr() {
        return this.datinschr;
    }
    
    public void setDatinschr(Integer datinschr) {
        this.datinschr = datinschr;
    }
    public Long getVersienr() {
        return this.versienr;
    }
    
    public void setVersienr(Long versienr) {
        this.versienr = versienr;
    }
    public Date getDattijdstempel() {
        return this.dattijdstempel;
    }
    
    public void setDattijdstempel(Date dattijdstempel) {
        this.dattijdstempel = dattijdstempel;
    }
    public Integer getVorigebsn() {
        return this.vorigebsn;
    }
    
    public void setVorigebsn(Integer vorigebsn) {
        this.vorigebsn = vorigebsn;
    }
    public Integer getVolgendebsn() {
        return this.volgendebsn;
    }
    
    public void setVolgendebsn(Integer volgendebsn) {
        this.volgendebsn = volgendebsn;
    }
    public Long getVorigeanr() {
        return this.vorigeanr;
    }
    
    public void setVorigeanr(Long vorigeanr) {
        this.vorigeanr = vorigeanr;
    }
    public Long getVolgendeanr() {
        return this.volgendeanr;
    }
    
    public void setVolgendeanr(Long volgendeanr) {
        this.volgendeanr = volgendeanr;
    }
    public Short getBijhpartij() {
        return this.bijhpartij;
    }
    
    public void setBijhpartij(Short bijhpartij) {
        this.bijhpartij = bijhpartij;
    }
    public Short getBijhaard() {
        return this.bijhaard;
    }
    
    public void setBijhaard(Short bijhaard) {
        this.bijhaard = bijhaard;
    }
    public Short getNaderebijhaard() {
        return this.naderebijhaard;
    }
    
    public void setNaderebijhaard(Short naderebijhaard) {
        this.naderebijhaard = naderebijhaard;
    }
    public Boolean getIndonverwdocaanw() {
        return this.indonverwdocaanw;
    }
    
    public void setIndonverwdocaanw(Boolean indonverwdocaanw) {
        this.indonverwdocaanw = indonverwdocaanw;
    }
    public Integer getDatoverlijden() {
        return this.datoverlijden;
    }
    
    public void setDatoverlijden(Integer datoverlijden) {
        this.datoverlijden = datoverlijden;
    }
    public Short getGemoverlijden() {
        return this.gemoverlijden;
    }
    
    public void setGemoverlijden(Short gemoverlijden) {
        this.gemoverlijden = gemoverlijden;
    }
    public String getWplnaamoverlijden() {
        return this.wplnaamoverlijden;
    }
    
    public void setWplnaamoverlijden(String wplnaamoverlijden) {
        this.wplnaamoverlijden = wplnaamoverlijden;
    }
    public String getBlplaatsoverlijden() {
        return this.blplaatsoverlijden;
    }
    
    public void setBlplaatsoverlijden(String blplaatsoverlijden) {
        this.blplaatsoverlijden = blplaatsoverlijden;
    }
    public String getBlregiooverlijden() {
        return this.blregiooverlijden;
    }
    
    public void setBlregiooverlijden(String blregiooverlijden) {
        this.blregiooverlijden = blregiooverlijden;
    }
    public String getOmslocoverlijden() {
        return this.omslocoverlijden;
    }
    
    public void setOmslocoverlijden(String omslocoverlijden) {
        this.omslocoverlijden = omslocoverlijden;
    }
    public Integer getLandgebiedoverlijden() {
        return this.landgebiedoverlijden;
    }
    
    public void setLandgebiedoverlijden(Integer landgebiedoverlijden) {
        this.landgebiedoverlijden = landgebiedoverlijden;
    }
    public Short getNaamgebruik() {
        return this.naamgebruik;
    }
    
    public void setNaamgebruik(Short naamgebruik) {
        this.naamgebruik = naamgebruik;
    }
    public Boolean getIndnaamgebruikafgeleid() {
        return this.indnaamgebruikafgeleid;
    }
    
    public void setIndnaamgebruikafgeleid(Boolean indnaamgebruikafgeleid) {
        this.indnaamgebruikafgeleid = indnaamgebruikafgeleid;
    }
    public Short getPredicaatnaamgebruik() {
        return this.predicaatnaamgebruik;
    }
    
    public void setPredicaatnaamgebruik(Short predicaatnaamgebruik) {
        this.predicaatnaamgebruik = predicaatnaamgebruik;
    }
    public String getVoornamennaamgebruik() {
        return this.voornamennaamgebruik;
    }
    
    public void setVoornamennaamgebruik(String voornamennaamgebruik) {
        this.voornamennaamgebruik = voornamennaamgebruik;
    }
    public Short getAdellijketitelnaamgebruik() {
        return this.adellijketitelnaamgebruik;
    }
    
    public void setAdellijketitelnaamgebruik(Short adellijketitelnaamgebruik) {
        this.adellijketitelnaamgebruik = adellijketitelnaamgebruik;
    }
    public String getVoorvoegselnaamgebruik() {
        return this.voorvoegselnaamgebruik;
    }
    
    public void setVoorvoegselnaamgebruik(String voorvoegselnaamgebruik) {
        this.voorvoegselnaamgebruik = voorvoegselnaamgebruik;
    }
    public String getScheidingstekennaamgebruik() {
        return this.scheidingstekennaamgebruik;
    }
    
    public void setScheidingstekennaamgebruik(String scheidingstekennaamgebruik) {
        this.scheidingstekennaamgebruik = scheidingstekennaamgebruik;
    }
    public String getGeslnaamstamnaamgebruik() {
        return this.geslnaamstamnaamgebruik;
    }
    
    public void setGeslnaamstamnaamgebruik(String geslnaamstamnaamgebruik) {
        this.geslnaamstamnaamgebruik = geslnaamstamnaamgebruik;
    }
    public Short getSrtmigratie() {
        return this.srtmigratie;
    }
    
    public void setSrtmigratie(Short srtmigratie) {
        this.srtmigratie = srtmigratie;
    }
    public Short getRdnwijzmigratie() {
        return this.rdnwijzmigratie;
    }
    
    public void setRdnwijzmigratie(Short rdnwijzmigratie) {
        this.rdnwijzmigratie = rdnwijzmigratie;
    }
    public Short getAangmigratie() {
        return this.aangmigratie;
    }
    
    public void setAangmigratie(Short aangmigratie) {
        this.aangmigratie = aangmigratie;
    }
    public Integer getLandgebiedmigratie() {
        return this.landgebiedmigratie;
    }
    
    public void setLandgebiedmigratie(Integer landgebiedmigratie) {
        this.landgebiedmigratie = landgebiedmigratie;
    }
    public String getBladresregel1migratie() {
        return this.bladresregel1migratie;
    }
    
    public void setBladresregel1migratie(String bladresregel1migratie) {
        this.bladresregel1migratie = bladresregel1migratie;
    }
    public String getBladresregel2migratie() {
        return this.bladresregel2migratie;
    }
    
    public void setBladresregel2migratie(String bladresregel2migratie) {
        this.bladresregel2migratie = bladresregel2migratie;
    }
    public String getBladresregel3migratie() {
        return this.bladresregel3migratie;
    }
    
    public void setBladresregel3migratie(String bladresregel3migratie) {
        this.bladresregel3migratie = bladresregel3migratie;
    }
    public String getBladresregel4migratie() {
        return this.bladresregel4migratie;
    }
    
    public void setBladresregel4migratie(String bladresregel4migratie) {
        this.bladresregel4migratie = bladresregel4migratie;
    }
    public String getBladresregel5migratie() {
        return this.bladresregel5migratie;
    }
    
    public void setBladresregel5migratie(String bladresregel5migratie) {
        this.bladresregel5migratie = bladresregel5migratie;
    }
    public String getBladresregel6migratie() {
        return this.bladresregel6migratie;
    }
    
    public void setBladresregel6migratie(String bladresregel6migratie) {
        this.bladresregel6migratie = bladresregel6migratie;
    }
    public Short getAandverblijfsr() {
        return this.aandverblijfsr;
    }
    
    public void setAandverblijfsr(Short aandverblijfsr) {
        this.aandverblijfsr = aandverblijfsr;
    }
    public Integer getDatmededelingverblijfsr() {
        return this.datmededelingverblijfsr;
    }
    
    public void setDatmededelingverblijfsr(Integer datmededelingverblijfsr) {
        this.datmededelingverblijfsr = datmededelingverblijfsr;
    }
    public Integer getDatvoorzeindeverblijfsr() {
        return this.datvoorzeindeverblijfsr;
    }
    
    public void setDatvoorzeindeverblijfsr(Integer datvoorzeindeverblijfsr) {
        this.datvoorzeindeverblijfsr = datvoorzeindeverblijfsr;
    }
    public Boolean getInduitslkiesr() {
        return this.induitslkiesr;
    }
    
    public void setInduitslkiesr(Boolean induitslkiesr) {
        this.induitslkiesr = induitslkiesr;
    }
    public Integer getDatvoorzeindeuitslkiesr() {
        return this.datvoorzeindeuitslkiesr;
    }
    
    public void setDatvoorzeindeuitslkiesr(Integer datvoorzeindeuitslkiesr) {
        this.datvoorzeindeuitslkiesr = datvoorzeindeuitslkiesr;
    }
    public Boolean getInddeelneuverkiezingen() {
        return this.inddeelneuverkiezingen;
    }
    
    public void setInddeelneuverkiezingen(Boolean inddeelneuverkiezingen) {
        this.inddeelneuverkiezingen = inddeelneuverkiezingen;
    }
    public Integer getDataanlaanpdeelneuverkiezing() {
        return this.dataanlaanpdeelneuverkiezing;
    }
    
    public void setDataanlaanpdeelneuverkiezing(Integer dataanlaanpdeelneuverkiezing) {
        this.dataanlaanpdeelneuverkiezing = dataanlaanpdeelneuverkiezing;
    }
    public Integer getDatvoorzeindeuitsleuverkiezi() {
        return this.datvoorzeindeuitsleuverkiezi;
    }
    
    public void setDatvoorzeindeuitsleuverkiezi(Integer datvoorzeindeuitsleuverkiezi) {
        this.datvoorzeindeuitsleuverkiezi = datvoorzeindeuitsleuverkiezi;
    }
    public Short getGempk() {
        return this.gempk;
    }
    
    public void setGempk(Short gempk) {
        this.gempk = gempk;
    }
    public Boolean getIndpkvollediggeconv() {
        return this.indpkvollediggeconv;
    }
    
    public void setIndpkvollediggeconv(Boolean indpkvollediggeconv) {
        this.indpkvollediggeconv = indpkvollediggeconv;
    }




}


