/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Persverstrbeperking generated by hbm2java
 */
public class Persverstrbeperking  implements java.io.Serializable {


     private int id;
     private int pers;
     private Short partij;
     private String omsderde;
     private Short gemverordening;

    public Persverstrbeperking() {
    }

	
    public Persverstrbeperking(int id, int pers) {
        this.id = id;
        this.pers = pers;
    }
    public Persverstrbeperking(int id, int pers, Short partij, String omsderde, Short gemverordening) {
       this.id = id;
       this.pers = pers;
       this.partij = partij;
       this.omsderde = omsderde;
       this.gemverordening = gemverordening;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public Short getPartij() {
        return this.partij;
    }
    
    public void setPartij(Short partij) {
        this.partij = partij;
    }
    public String getOmsderde() {
        return this.omsderde;
    }
    
    public void setOmsderde(String omsderde) {
        this.omsderde = omsderde;
    }
    public Short getGemverordening() {
        return this.gemverordening;
    }
    
    public void setGemverordening(Short gemverordening) {
        this.gemverordening = gemverordening;
    }




}


