/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Persvoornaam generated by hbm2java
 */
public class Persvoornaam  implements IntegerAsPrimaryKey,java.io.Serializable {


     private int id;
     private int pers;
     private int volgnr;
     private String naam;

    public Persvoornaam() {
    }

	
    public Persvoornaam(int id, int pers, int volgnr) {
        this.id = id;
        this.pers = pers;
        this.volgnr = volgnr;
    }
    public Persvoornaam(int id, int pers, int volgnr, String naam) {
       this.id = id;
       this.pers = pers;
       this.volgnr = volgnr;
       this.naam = naam;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPers() {
        return this.pers;
    }
    
    public void setPers(int pers) {
        this.pers = pers;
    }
    public int getVolgnr() {
        return this.volgnr;
    }
    
    public void setVolgnr(int volgnr) {
        this.volgnr = volgnr;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }




}


