/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 4-feb-2014 12:16:23 by Hibernate Tools 3.2.4.GA



/**
 * Rdneinderelatie generated by hbm2java
 */
public enum Rdneinderelatie  implements java.io.Serializable {
    _0, X, A, N, O, R, S, V, Z;

}


