/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Rechtsgrond generated by hbm2java
 */
public class Rechtsgrond  implements java.io.Serializable {


     private short id;
     private short code;
     private short srt;
     private String oms;
     private Boolean indleidttotstrijdigheid;
     private Integer dataanvgel;
     private Integer dateindegel;

    public Rechtsgrond() {
    }

	
    public Rechtsgrond(short id, short code, short srt, String oms) {
        this.id = id;
        this.code = code;
        this.srt = srt;
        this.oms = oms;
    }
    public Rechtsgrond(short id, short code, short srt, String oms, Boolean indleidttotstrijdigheid, Integer dataanvgel, Integer dateindegel) {
       this.id = id;
       this.code = code;
       this.srt = srt;
       this.oms = oms;
       this.indleidttotstrijdigheid = indleidttotstrijdigheid;
       this.dataanvgel = dataanvgel;
       this.dateindegel = dateindegel;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public short getCode() {
        return this.code;
    }
    
    public void setCode(short code) {
        this.code = code;
    }
    public short getSrt() {
        return this.srt;
    }
    
    public void setSrt(short srt) {
        this.srt = srt;
    }
    public String getOms() {
        return this.oms;
    }
    
    public void setOms(String oms) {
        this.oms = oms;
    }
    public Boolean getIndleidttotstrijdigheid() {
        return this.indleidttotstrijdigheid;
    }
    
    public void setIndleidttotstrijdigheid(Boolean indleidttotstrijdigheid) {
        this.indleidttotstrijdigheid = indleidttotstrijdigheid;
    }
    public Integer getDataanvgel() {
        return this.dataanvgel;
    }
    
    public void setDataanvgel(Integer dataanvgel) {
        this.dataanvgel = dataanvgel;
    }
    public Integer getDateindegel() {
        return this.dateindegel;
    }
    
    public void setDateindegel(Integer dateindegel) {
        this.dateindegel = dateindegel;
    }




}


