/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated Jul 24, 2014 5:36:58 PM by Hibernate Tools 3.2.4.GA



/**
 * Regelverantwoording generated by hbm2java
 */
public class Regelverantwoording  implements java.io.Serializable {


     private long id;
     private long actie;
     private int regel;

    public Regelverantwoording() {
    }

    public Regelverantwoording(long id, long actie, int regel) {
       this.id = id;
       this.actie = actie;
       this.regel = regel;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getActie() {
        return this.actie;
    }
    
    public void setActie(long actie) {
        this.actie = actie;
    }
    public int getRegel() {
        return this.regel;
    }
    
    public void setRegel(int regel) {
        this.regel = regel;
    }




}


