/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Abonnementgroep generated by hbm2java
 */
public class Abonnementgroep  implements java.io.Serializable {


     private int id;
     private int abonnement;
     private int groep;
     private Boolean indverantwoordingsinfo;
     private Boolean indkopiebrondoc;
     private Boolean indmaterielehistorie;
     private Boolean indformelehistorie;

    public Abonnementgroep() {
    }

	
    public Abonnementgroep(int id, int abonnement, int groep) {
        this.id = id;
        this.abonnement = abonnement;
        this.groep = groep;
    }
    public Abonnementgroep(int id, int abonnement, int groep, Boolean indverantwoordingsinfo, Boolean indkopiebrondoc, Boolean indmaterielehistorie, Boolean indformelehistorie) {
       this.id = id;
       this.abonnement = abonnement;
       this.groep = groep;
       this.indverantwoordingsinfo = indverantwoordingsinfo;
       this.indkopiebrondoc = indkopiebrondoc;
       this.indmaterielehistorie = indmaterielehistorie;
       this.indformelehistorie = indformelehistorie;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(int abonnement) {
        this.abonnement = abonnement;
    }
    public int getGroep() {
        return this.groep;
    }
    
    public void setGroep(int groep) {
        this.groep = groep;
    }
    public Boolean getIndverantwoordingsinfo() {
        return this.indverantwoordingsinfo;
    }
    
    public void setIndverantwoordingsinfo(Boolean indverantwoordingsinfo) {
        this.indverantwoordingsinfo = indverantwoordingsinfo;
    }
    public Boolean getIndkopiebrondoc() {
        return this.indkopiebrondoc;
    }
    
    public void setIndkopiebrondoc(Boolean indkopiebrondoc) {
        this.indkopiebrondoc = indkopiebrondoc;
    }
    public Boolean getIndmaterielehistorie() {
        return this.indmaterielehistorie;
    }
    
    public void setIndmaterielehistorie(Boolean indmaterielehistorie) {
        this.indmaterielehistorie = indmaterielehistorie;
    }
    public Boolean getIndformelehistorie() {
        return this.indformelehistorie;
    }
    
    public void setIndformelehistorie(Boolean indformelehistorie) {
        this.indformelehistorie = indformelehistorie;
    }




}


