/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Abonnementexpressie generated by hbm2java
 */
public class Abonnementexpressie  implements java.io.Serializable {


     private int id;
     private int abonnement;
     private int expressie;
     private short rol;
     private Boolean actief;

    public Abonnementexpressie() {
    }

	
    public Abonnementexpressie(int id, int abonnement, int expressie, short rol) {
        this.id = id;
        this.abonnement = abonnement;
        this.expressie = expressie;
        this.rol = rol;
    }
    public Abonnementexpressie(int id, int abonnement, int expressie, short rol, Boolean actief) {
       this.id = id;
       this.abonnement = abonnement;
       this.expressie = expressie;
       this.rol = rol;
       this.actief = actief;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(int abonnement) {
        this.abonnement = abonnement;
    }
    public int getExpressie() {
        return this.expressie;
    }
    
    public void setExpressie(int expressie) {
        this.expressie = expressie;
    }
    public short getRol() {
        return this.rol;
    }
    
    public void setRol(short rol) {
        this.rol = rol;
    }
    public Boolean getActief() {
        return this.actief;
    }
    
    public void setActief(Boolean actief) {
        this.actief = actief;
    }




}


