/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Bijhsituatie generated by hbm2java
 */
public class Bijhsituatie  implements java.io.Serializable {


     private int id;
     private short bijhautorisatie;
     private Short srtadmhnd;
     private Short srtdoc;

    public Bijhsituatie() {
    }

	
    public Bijhsituatie(int id, short bijhautorisatie) {
        this.id = id;
        this.bijhautorisatie = bijhautorisatie;
    }
    public Bijhsituatie(int id, short bijhautorisatie, Short srtadmhnd, Short srtdoc) {
       this.id = id;
       this.bijhautorisatie = bijhautorisatie;
       this.srtadmhnd = srtadmhnd;
       this.srtdoc = srtdoc;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public short getBijhautorisatie() {
        return this.bijhautorisatie;
    }
    
    public void setBijhautorisatie(short bijhautorisatie) {
        this.bijhautorisatie = bijhautorisatie;
    }
    public Short getSrtadmhnd() {
        return this.srtadmhnd;
    }
    
    public void setSrtadmhnd(Short srtadmhnd) {
        this.srtadmhnd = srtadmhnd;
    }
    public Short getSrtdoc() {
        return this.srtdoc;
    }
    
    public void setSrtdoc(Short srtdoc) {
        this.srtdoc = srtdoc;
    }




}


