/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Certificaat generated by hbm2java
 */
public class Certificaat  implements java.io.Serializable {


     private int id;
     private String subject;
     private String serial;
     private String signature;
     private short partij;

    public Certificaat() {
    }

    public Certificaat(int id, String subject, String serial, String signature, short partij) {
       this.id = id;
       this.subject = subject;
       this.serial = serial;
       this.signature = signature;
       this.partij = partij;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getSignature() {
        return this.signature;
    }
    
    public void setSignature(String signature) {
        this.signature = signature;
    }
    public short getPartij() {
        return this.partij;
    }
    
    public void setPartij(short partij) {
        this.partij = partij;
    }




}


