/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Dienst generated by hbm2java
 */
public class Dienst  implements java.io.Serializable {


     private int id;
     private int abonnement;
     private int catalogusoptie;
     private String naderepopulatiebeperking;
     private String attenderingscriterium;
     private Integer datingang;
     private Integer dateinde;
     private Short toestand;
     private Integer eersteselectiedat;
     private Short selectieperiodeinmaanden;

    public Dienst() {
    }

	
    public Dienst(int id, int abonnement, int catalogusoptie) {
        this.id = id;
        this.abonnement = abonnement;
        this.catalogusoptie = catalogusoptie;
    }
    public Dienst(int id, int abonnement, int catalogusoptie, String naderepopulatiebeperking, String attenderingscriterium, Integer datingang, Integer dateinde, Short toestand, Integer eersteselectiedat, Short selectieperiodeinmaanden) {
       this.id = id;
       this.abonnement = abonnement;
       this.catalogusoptie = catalogusoptie;
       this.naderepopulatiebeperking = naderepopulatiebeperking;
       this.attenderingscriterium = attenderingscriterium;
       this.datingang = datingang;
       this.dateinde = dateinde;
       this.toestand = toestand;
       this.eersteselectiedat = eersteselectiedat;
       this.selectieperiodeinmaanden = selectieperiodeinmaanden;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(int abonnement) {
        this.abonnement = abonnement;
    }
    public int getCatalogusoptie() {
        return this.catalogusoptie;
    }
    
    public void setCatalogusoptie(int catalogusoptie) {
        this.catalogusoptie = catalogusoptie;
    }
    public String getNaderepopulatiebeperking() {
        return this.naderepopulatiebeperking;
    }
    
    public void setNaderepopulatiebeperking(String naderepopulatiebeperking) {
        this.naderepopulatiebeperking = naderepopulatiebeperking;
    }
    public String getAttenderingscriterium() {
        return this.attenderingscriterium;
    }
    
    public void setAttenderingscriterium(String attenderingscriterium) {
        this.attenderingscriterium = attenderingscriterium;
    }
    public Integer getDatingang() {
        return this.datingang;
    }
    
    public void setDatingang(Integer datingang) {
        this.datingang = datingang;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }
    
    public void setDateinde(Integer dateinde) {
        this.dateinde = dateinde;
    }
    public Short getToestand() {
        return this.toestand;
    }
    
    public void setToestand(Short toestand) {
        this.toestand = toestand;
    }
    public Integer getEersteselectiedat() {
        return this.eersteselectiedat;
    }
    
    public void setEersteselectiedat(Integer eersteselectiedat) {
        this.eersteselectiedat = eersteselectiedat;
    }
    public Short getSelectieperiodeinmaanden() {
        return this.selectieperiodeinmaanden;
    }
    
    public void setSelectieperiodeinmaanden(Short selectieperiodeinmaanden) {
        this.selectieperiodeinmaanden = selectieperiodeinmaanden;
    }




}


