/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA



/**
 * Doelbinding generated by hbm2java
 */
public class Doelbinding  implements java.io.Serializable {


     private int id;
     private String naam;
     private int levsautorisatiebesluit;
     private String tekstdoelbinding;

    public Doelbinding() {
    }

	
    public Doelbinding(int id, String naam, int levsautorisatiebesluit) {
        this.id = id;
        this.naam = naam;
        this.levsautorisatiebesluit = levsautorisatiebesluit;
    }
    public Doelbinding(int id, String naam, int levsautorisatiebesluit, String tekstdoelbinding) {
       this.id = id;
       this.naam = naam;
       this.levsautorisatiebesluit = levsautorisatiebesluit;
       this.tekstdoelbinding = tekstdoelbinding;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public int getLevsautorisatiebesluit() {
        return this.levsautorisatiebesluit;
    }
    
    public void setLevsautorisatiebesluit(int levsautorisatiebesluit) {
        this.levsautorisatiebesluit = levsautorisatiebesluit;
    }
    public String getTekstdoelbinding() {
        return this.tekstdoelbinding;
    }
    
    public void setTekstdoelbinding(String tekstdoelbinding) {
        this.tekstdoelbinding = tekstdoelbinding;
    }




}


