/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisAbonnement generated by hbm2java
 */
public class HisAbonnement  implements java.io.Serializable {


     private int id;
     private int abonnement;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private String populatiebeperking;
     private short protocolleringsniveau;
     private int datingang;
     private Integer dateinde;
     private short toestand;

    public HisAbonnement() {
    }

	
    public HisAbonnement(int id, int abonnement, short protocolleringsniveau, int datingang, short toestand) {
        this.id = id;
        this.abonnement = abonnement;
        this.protocolleringsniveau = protocolleringsniveau;
        this.datingang = datingang;
        this.toestand = toestand;
    }
    public HisAbonnement(int id, int abonnement, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, String populatiebeperking, short protocolleringsniveau, int datingang, Integer dateinde, short toestand) {
       this.id = id;
       this.abonnement = abonnement;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.populatiebeperking = populatiebeperking;
       this.protocolleringsniveau = protocolleringsniveau;
       this.datingang = datingang;
       this.dateinde = dateinde;
       this.toestand = toestand;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(int abonnement) {
        this.abonnement = abonnement;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public String getPopulatiebeperking() {
        return this.populatiebeperking;
    }
    
    public void setPopulatiebeperking(String populatiebeperking) {
        this.populatiebeperking = populatiebeperking;
    }
    public short getProtocolleringsniveau() {
        return this.protocolleringsniveau;
    }
    
    public void setProtocolleringsniveau(short protocolleringsniveau) {
        this.protocolleringsniveau = protocolleringsniveau;
    }
    public int getDatingang() {
        return this.datingang;
    }
    
    public void setDatingang(int datingang) {
        this.datingang = datingang;
    }
    public Integer getDateinde() {
        return this.dateinde;
    }
    
    public void setDateinde(Integer dateinde) {
        this.dateinde = dateinde;
    }
    public short getToestand() {
        return this.toestand;
    }
    
    public void setToestand(short toestand) {
        this.toestand = toestand;
    }




}


