/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisAbonnementexpressie generated by hbm2java
 */
public class HisAbonnementexpressie  implements java.io.Serializable {


     private int id;
     private int abonnementexpressie;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private boolean actief;

    public HisAbonnementexpressie() {
    }

	
    public HisAbonnementexpressie(int id, int abonnementexpressie, boolean actief) {
        this.id = id;
        this.abonnementexpressie = abonnementexpressie;
        this.actief = actief;
    }
    public HisAbonnementexpressie(int id, int abonnementexpressie, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, boolean actief) {
       this.id = id;
       this.abonnementexpressie = abonnementexpressie;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.actief = actief;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbonnementexpressie() {
        return this.abonnementexpressie;
    }
    
    public void setAbonnementexpressie(int abonnementexpressie) {
        this.abonnementexpressie = abonnementexpressie;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public boolean isActief() {
        return this.actief;
    }
    
    public void setActief(boolean actief) {
        this.actief = actief;
    }




}


