/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisDoelbinding generated by hbm2java
 */
public class HisDoelbinding  implements java.io.Serializable {


     private int id;
     private int doelbinding;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private String tekstdoelbinding;

    public HisDoelbinding() {
    }

	
    public HisDoelbinding(int id, int doelbinding, String tekstdoelbinding) {
        this.id = id;
        this.doelbinding = doelbinding;
        this.tekstdoelbinding = tekstdoelbinding;
    }
    public HisDoelbinding(int id, int doelbinding, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, String tekstdoelbinding) {
       this.id = id;
       this.doelbinding = doelbinding;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.tekstdoelbinding = tekstdoelbinding;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDoelbinding() {
        return this.doelbinding;
    }
    
    public void setDoelbinding(int doelbinding) {
        this.doelbinding = doelbinding;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public String getTekstdoelbinding() {
        return this.tekstdoelbinding;
    }
    
    public void setTekstdoelbinding(String tekstdoelbinding) {
        this.tekstdoelbinding = tekstdoelbinding;
    }




}


