/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.autaut;
// Generated Apr 9, 2014 4:42:05 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

import nl.bzk.brp.testdatageneratie.domain.kern.His;

/**
 * HisPersafnemerindicatie generated by hbm2java
 */
public class HisPersafnemerindicatie  implements His {


     private int id;
     private long persafnemerindicatie;
     private Date tsreg;
     private Date tsverval;
     private Long actieinh;
     private Long actieverval;
     private String nadereaandverval;
     private Integer dataanvmaterieleperiode;
     private Date tseindevolgen;

    public HisPersafnemerindicatie() {
    }

	
    public HisPersafnemerindicatie(int id, long persafnemerindicatie) {
        this.id = id;
        this.persafnemerindicatie = persafnemerindicatie;
    }
    public HisPersafnemerindicatie(int id, long persafnemerindicatie, Date tsreg, Date tsverval, Long actieinh, Long actieverval, String nadereaandverval, Integer dataanvmaterieleperiode, Date tseindevolgen) {
       this.id = id;
       this.persafnemerindicatie = persafnemerindicatie;
       this.tsreg = tsreg;
       this.tsverval = tsverval;
       this.actieinh = actieinh;
       this.actieverval = actieverval;
       this.nadereaandverval = nadereaandverval;
       this.dataanvmaterieleperiode = dataanvmaterieleperiode;
       this.tseindevolgen = tseindevolgen;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public long getPersafnemerindicatie() {
        return this.persafnemerindicatie;
    }
    
    public void setPersafnemerindicatie(long persafnemerindicatie) {
        this.persafnemerindicatie = persafnemerindicatie;
    }
    public Date getTsreg() {
        return this.tsreg;
    }
    
    public void setTsreg(Date tsreg) {
        this.tsreg = tsreg;
    }
    public Date getTsverval() {
        return this.tsverval;
    }
    
    public void setTsverval(Date tsverval) {
        this.tsverval = tsverval;
    }
    public Long getActieinh() {
        return this.actieinh;
    }
    
    public void setActieinh(Long actieinh) {
        this.actieinh = actieinh;
    }
    public Long getActieverval() {
        return this.actieverval;
    }
    
    public void setActieverval(Long actieverval) {
        this.actieverval = actieverval;
    }
    public String getNadereaandverval() {
        return this.nadereaandverval;
    }
    
    public void setNadereaandverval(String nadereaandverval) {
        this.nadereaandverval = nadereaandverval;
    }
    public Integer getDataanvmaterieleperiode() {
        return this.dataanvmaterieleperiode;
    }
    
    public void setDataanvmaterieleperiode(Integer dataanvmaterieleperiode) {
        this.dataanvmaterieleperiode = dataanvmaterieleperiode;
    }
    public Date getTseindevolgen() {
        return this.tseindevolgen;
    }
    
    public void setTseindevolgen(Date tseindevolgen) {
        this.tseindevolgen = tseindevolgen;
    }




}


