DROP SCHEMA IF EXISTS Kern CASCADE;
CREATE SCHEMA Kern;
-- Table: kern.pers
DROP TABLE IF EXISTS kern.pers;

CREATE TABLE kern.pers
(
  id integer NOT NULL,
  srt smallint NOT NULL,
  bsn integer,
  anr bigint,
  idsstatushis character varying(1) NOT NULL,
  geslachtsaand smallint,
  geslachtsaandstatushis character varying(1) NOT NULL,
  predikaat smallint,
  voornamen character varying(200),
  voorvoegsel character varying(10),
  scheidingsteken character varying(1),
  adellijketitel smallint,
  geslnaam character varying(200),
  indnreeksalsgeslnaam boolean,
  indalgoritmischafgeleid boolean,
  samengesteldenaamstatushis character varying(1) NOT NULL,
  gebrgeslnaamegp smallint,
  indaanschrmetadellijketitels boolean,
  indaanschralgoritmischafgele boolean,
  predikaataanschr smallint,
  voornamenaanschr character varying(200),
  voorvoegselaanschr character varying(10),
  scheidingstekenaanschr character varying(1),
  adellijketitelaanschr smallint,
  geslnaamaanschr character varying(200),
  aanschrstatushis character varying(1) NOT NULL,
  datgeboorte integer,
  gemgeboorte smallint,
  wplgeboorte integer,
  blgeboorteplaats character varying(40),
  blregiogeboorte character varying(35),
  landgeboorte integer,
  omsgeboorteloc character varying(40),
  geboortestatushis character varying(1) NOT NULL,
  datoverlijden integer,
  gemoverlijden smallint,
  wploverlijden integer,
  blplaatsoverlijden character varying(40),
  blregiooverlijden character varying(35),
  landoverlijden integer,
  omslocoverlijden character varying(40),
  overlijdenstatushis character varying(1) NOT NULL,
  verblijfsr smallint,
  dataanvverblijfsr integer,
  datvoorzeindeverblijfsr integer,
  dataanvaaneenslverblijfsr integer,
  verblijfsrstatushis character varying(1) NOT NULL,
  induitslnlkiesr boolean,
  dateindeuitslnlkiesr integer,
  uitslnlkiesrstatushis character varying(1) NOT NULL,
  inddeelneuverkiezingen boolean,
  dataanlaanpdeelneuverkiezing integer,
  dateindeuitsleukiesr integer,
  euverkiezingenstatushis character varying(1) NOT NULL,
  verantwoordelijke smallint,
  bijhverantwoordelijkheidstat character varying(1) NOT NULL,
  rdnopschortingbijhouding smallint,
  opschortingstatushis character varying(1) NOT NULL,
  bijhgem smallint,
  datinschringem integer,
  bijhgemstatushis character varying(1) NOT NULL,
  gempk smallint,
  indpkvollediggeconv boolean,
  pkstatushis character varying(1) NOT NULL,
  landvanwaargevestigd integer,
  datvestiginginnederland integer,
  immigratiestatushis character varying(1) NOT NULL,
  datinschr integer,
  versienr bigint,
  vorigepers integer,
  volgendepers integer,
  inschrstatushis character varying(1) NOT NULL,
  tijdstiplaatstewijz timestamp without time zone,
  indgegevensinonderzoek boolean
);
