/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.beheer.model;

// Generated 19-okt-2011 11:24:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Partijrol generated by hbm2java
 */
@Entity
@Table(name = "partijrol", schema = "kern", uniqueConstraints = @UniqueConstraint(columnNames = { "partij", "rol" }))
@SequenceGenerator(name = "partijrol_seq", sequenceName = "kern.seq_partijrol")
public class Partijrol implements java.io.Serializable {

    private int    id;
    private Partij partij;
    private Rol    rol;
    private String partijRolStatusHis;

    public Partijrol() {
    }

    public Partijrol(final int id, final Partij partij, final Rol rol, final String partijRolStatusHis) {
        this.id = id;
        this.partij = partij;
        this.rol = rol;
        this.partijRolStatusHis = partijRolStatusHis;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "partijrol_seq")
    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Partij", nullable = false)
    public Partij getPartij() {
        return this.partij;
    }

    public void setPartij(final Partij partij) {
        this.partij = partij;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol", nullable = false)
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(final Rol rol) {
        this.rol = rol;
    }

    @Column(name = "PartijRolStatusHis", nullable = false, length = 1)
    public String getPartijRolStatusHis() {
        return partijRolStatusHis;
    }

    public void setPartijRolStatusHis(final String partijRolStatusHis) {
        this.partijRolStatusHis = partijRolStatusHis;
    }

}
