/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * HisAbonnement generated by hbm2java
 */
public class HisAbonnement extends His {

     private Abonnement abonnement;
     private String populatiecriterium;

    public HisAbonnement() {
    }

    public HisAbonnement(String populatiecriterium) {
        this.populatiecriterium = populatiecriterium;
    }
    public HisAbonnement(Actie actieByActieinh, Abonnement abonnement, Actie actieByActieverval, Date tsreg, Date tsverval, String populatiecriterium) {
       this.abonnement = abonnement;

       this.populatiecriterium = populatiecriterium;
    }

    public Abonnement getAbonnement() {
        return this.abonnement;
    }

    public void setAbonnement(Abonnement abonnement) {
        this.abonnement = abonnement;
    }

    public String getPopulatiecriterium() {
        return this.populatiecriterium;
    }

    public void setPopulatiecriterium(String populatiecriterium) {
        this.populatiecriterium = populatiecriterium;
    }
}


