/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * HisAuthenticatiemiddel generated by hbm2java
 */
public class HisAuthenticatiemiddel extends His {

     private Authenticatiemiddel authenticatiemiddel;
     private Functie functie;
     private Certificaat certificaatByCertificaattbvssl;
     private Certificaat certificaatByCertificaattbvondertekening;
     private String ipadres;

    public HisAuthenticatiemiddel() {
    }


    public HisAuthenticatiemiddel(Certificaat certificaatByCertificaattbvssl, Certificaat certificaatByCertificaattbvondertekening) {
        this.certificaatByCertificaattbvssl = certificaatByCertificaattbvssl;
        this.certificaatByCertificaattbvondertekening = certificaatByCertificaattbvondertekening;
    }

    public Authenticatiemiddel getAuthenticatiemiddel() {
        return this.authenticatiemiddel;
    }

    public void setAuthenticatiemiddel(Authenticatiemiddel authenticatiemiddel) {
        this.authenticatiemiddel = authenticatiemiddel;
    }
    public Functie getFunctie() {
        return this.functie;
    }

    public void setFunctie(Functie functie) {
        this.functie = functie;
    }
    public Certificaat getCertificaatByCertificaattbvssl() {
        return this.certificaatByCertificaattbvssl;
    }

    public void setCertificaatByCertificaattbvssl(Certificaat certificaatByCertificaattbvssl) {
        this.certificaatByCertificaattbvssl = certificaatByCertificaattbvssl;
    }

    public Certificaat getCertificaatByCertificaattbvondertekening() {
        return this.certificaatByCertificaattbvondertekening;
    }

    public void setCertificaatByCertificaattbvondertekening(Certificaat certificaatByCertificaattbvondertekening) {
        this.certificaatByCertificaattbvondertekening = certificaatByCertificaattbvondertekening;
    }

    public String getIpadres() {
        return this.ipadres;
    }

    public void setIpadres(String ipadres) {
        this.ipadres = ipadres;
    }
}


