/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * HisBijhautorisatie generated by hbm2java
 */
public class HisBijhautorisatie extends His {

     private Srtbevoegdheid srtbevoegdheid;
     private Categoriepersonen categoriepersonen;
     private Toestand toestand;
     private Bijhautorisatie bijhautorisatie;
     private Srtpartij srtpartij;
     private Partij partij;
     private String oms;
     private int datingang;
     private int dateinde;

    public HisBijhautorisatie() {
    }


    public HisBijhautorisatie(Srtbevoegdheid srtbevoegdheid, Categoriepersonen categoriepersonen, Toestand toestand, String oms, int datingang, int dateinde) {
        this.srtbevoegdheid = srtbevoegdheid;
        this.categoriepersonen = categoriepersonen;
        this.toestand = toestand;
        this.oms = oms;
        this.datingang = datingang;
        this.dateinde = dateinde;
    }

    public Srtbevoegdheid getSrtbevoegdheid() {
        return this.srtbevoegdheid;
    }

    public void setSrtbevoegdheid(Srtbevoegdheid srtbevoegdheid) {
        this.srtbevoegdheid = srtbevoegdheid;
    }
    public Categoriepersonen getCategoriepersonen() {
        return this.categoriepersonen;
    }

    public void setCategoriepersonen(Categoriepersonen categoriepersonen) {
        this.categoriepersonen = categoriepersonen;
    }

    public Toestand getToestand() {
        return this.toestand;
    }

    public void setToestand(Toestand toestand) {
        this.toestand = toestand;
    }
    public Bijhautorisatie getBijhautorisatie() {
        return this.bijhautorisatie;
    }

    public void setBijhautorisatie(Bijhautorisatie bijhautorisatie) {
        this.bijhautorisatie = bijhautorisatie;
    }

    public Srtpartij getSrtpartij() {
        return this.srtpartij;
    }

    public void setSrtpartij(Srtpartij srtpartij) {
        this.srtpartij = srtpartij;
    }
    public Partij getPartij() {
        return this.partij;
    }

    public void setPartij(Partij partij) {
        this.partij = partij;
    }

    public String getOms() {
        return this.oms;
    }

    public void setOms(String oms) {
        this.oms = oms;
    }
    public int getDatingang() {
        return this.datingang;
    }

    public void setDatingang(int datingang) {
        this.datingang = datingang;
    }
    public int getDateinde() {
        return this.dateinde;
    }

    public void setDateinde(int dateinde) {
        this.dateinde = dateinde;
    }
}


