/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersreisdoc generated by hbm2java
 */
public class HisPersreisdoc extends His {


     private Persreisdoc persreisdoc;
     private Land land;
     private Partij partij;
     private Rdnvervallenreisdoc rdnvervallenreisdoc;
     private String nr;
     private int datingangdoc;
     private int datuitgifte;
     private int datvoorzeeindegel;
     private Integer datinhingvermissing;
     private Short lengtehouder;
     private String typeringautafgifte;
     private String provincieautafgifte;

    public HisPersreisdoc() {
    }

    public Persreisdoc getPersreisdoc() {
        return this.persreisdoc;
    }

    public Land getLand() {
        return land;
    }

    public void setLand(Land land) {
        this.land = land;
    }

    public Partij getPartij() {
        return partij;
    }

    public void setPartij(Partij partij) {
        this.partij = partij;
    }

    public void setPersreisdoc(final Persreisdoc persreisdoc) {
        this.persreisdoc = persreisdoc;
    }
    public Rdnvervallenreisdoc getRdnvervallenreisdoc() {
        return this.rdnvervallenreisdoc;
    }

    public void setRdnvervallenreisdoc(final Rdnvervallenreisdoc rdnvervallenreisdoc) {
        this.rdnvervallenreisdoc = rdnvervallenreisdoc;
    }

    public String getNr() {
        return this.nr;
    }

    public void setNr(final String nr) {
        this.nr = nr;
    }
    public int getDatingangdoc() {
        return this.datingangdoc;
    }

    public void setDatingangdoc(final int datingangdoc) {
        this.datingangdoc = datingangdoc;
    }
    public int getDatuitgifte() {
        return this.datuitgifte;
    }

    public void setDatuitgifte(final int datuitgifte) {
        this.datuitgifte = datuitgifte;
    }
    public int getDatvoorzeeindegel() {
        return this.datvoorzeeindegel;
    }

    public void setDatvoorzeeindegel(final int datvoorzeeindegel) {
        this.datvoorzeeindegel = datvoorzeeindegel;
    }
    public Integer getDatinhingvermissing() {
        return this.datinhingvermissing;
    }

    public void setDatinhingvermissing(final Integer datinhingvermissing) {
        this.datinhingvermissing = datinhingvermissing;
    }
    public Short getLengtehouder() {
        return this.lengtehouder;
    }

    public void setLengtehouder(final Short lengtehouder) {
        this.lengtehouder = lengtehouder;
    }

    public String getTyperingautafgifte() {
        return typeringautafgifte;
    }

    public void setTyperingautafgifte(String typeringautafgifte) {
        this.typeringautafgifte = typeringautafgifte;
    }

    public String getProvincieautafgifte() {
        return provincieautafgifte;
    }

    public void setProvincieautafgifte(String provincieautafgifte) {
        this.provincieautafgifte = provincieautafgifte;
    }




}


