/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 21-dec-2012 11:50:17 by Hibernate Tools 3.2.4.GA



/**
 * Persgeslnaamcomp generated by hbm2java
 */
public class Persgeslnaamcomp  implements java.io.Serializable {


     private Integer id;
     private Pers pers;
     private Predikaat predikaat;
     private Adellijketitel adellijketitel;
     private int volgnr;
     private String voorvoegsel;
     private String scheidingsteken;
     private String naam;
     private String persgeslnaamcompstatushis = StatusHis.A.name();

    public Persgeslnaamcomp() {
    }

    public Persgeslnaamcomp(final Pers pers, final String voorvoegsel, final String naam, final int volgnr) {
        this.pers = pers;
        this.voorvoegsel = voorvoegsel;
        this.naam = naam;
        this.volgnr = volgnr;
        if (voorvoegsel != null) {
            scheidingsteken = " ";
        }
    }

    public Persgeslnaamcomp(Pers pers, int volgnr, String persgeslnaamcompstatushis) {
        this.pers = pers;
        this.volgnr = volgnr;
        this.persgeslnaamcompstatushis = persgeslnaamcompstatushis;
    }
    public Persgeslnaamcomp(Pers pers, Predikaat predikaat, Adellijketitel adellijketitel, int volgnr, String voorvoegsel, String scheidingsteken, String naam, String persgeslnaamcompstatushis) {
       this.pers = pers;
       this.predikaat = predikaat;
       this.adellijketitel = adellijketitel;
       this.volgnr = volgnr;
       this.voorvoegsel = voorvoegsel;
       this.scheidingsteken = scheidingsteken;
       this.naam = naam;
       this.persgeslnaamcompstatushis = persgeslnaamcompstatushis;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(Pers pers) {
        this.pers = pers;
    }
    public Predikaat getPredikaat() {
        return this.predikaat;
    }

    public void setPredikaat(Predikaat predikaat) {
        this.predikaat = predikaat;
    }
    public Adellijketitel getAdellijketitel() {
        return this.adellijketitel;
    }

    public void setAdellijketitel(Adellijketitel adellijketitel) {
        this.adellijketitel = adellijketitel;
    }
    public int getVolgnr() {
        return this.volgnr;
    }

    public void setVolgnr(int volgnr) {
        this.volgnr = volgnr;
    }
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }

    public void setVoorvoegsel(String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }
    public String getScheidingsteken() {
        return this.scheidingsteken;
    }

    public void setScheidingsteken(String scheidingsteken) {
        this.scheidingsteken = scheidingsteken;
    }
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getPersgeslnaamcompstatushis() {
        return this.persgeslnaamcompstatushis;
    }

    public void setPersgeslnaamcompstatushis(String persgeslnaamcompstatushis) {
        this.persgeslnaamcompstatushis = persgeslnaamcompstatushis;
    }




}


