// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.kern.Aangadresh;
import nl.bzk.brp.model.data.kern.AangadreshDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect AangadreshDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AangadreshDataOnDemand: @Component;
    
    private Random AangadreshDataOnDemand.rnd = new SecureRandom();
    
    private List<Aangadresh> AangadreshDataOnDemand.data;
    
    public Aangadresh AangadreshDataOnDemand.getNewTransientAangadresh(int index) {
        Aangadresh obj = new Aangadresh();
        setCode(obj, index);
        setNaam(obj, index);
        setOms(obj, index);
        return obj;
    }
    
    public void AangadreshDataOnDemand.setCode(Aangadresh obj, int index) {
        String code = String.valueOf(index);
        if (code.length() > 1) {
            code = new Random().nextInt(10) + code.substring(1, 1);
        }
        obj.setCode(code);
    }
    
    public void AangadreshDataOnDemand.setNaam(Aangadresh obj, int index) {
        String naam = "naam_" + index;
        if (naam.length() > 40) {
            naam = new Random().nextInt(10) + naam.substring(1, 40);
        }
        obj.setNaam(naam);
    }
    
    public void AangadreshDataOnDemand.setOms(Aangadresh obj, int index) {
        String oms = "oms_" + index;
        if (oms.length() > 250) {
            oms = oms.substring(0, 250);
        }
        obj.setOms(oms);
    }
    
    public Aangadresh AangadreshDataOnDemand.getSpecificAangadresh(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Aangadresh obj = data.get(index);
        Short id = obj.getId();
        return Aangadresh.findAangadresh(id);
    }
    
    public Aangadresh AangadreshDataOnDemand.getRandomAangadresh() {
        init();
        Aangadresh obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getId();
        return Aangadresh.findAangadresh(id);
    }
    
    public boolean AangadreshDataOnDemand.modifyAangadresh(Aangadresh obj) {
        return false;
    }
    
    public void AangadreshDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Aangadresh.findAangadreshEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Aangadresh' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Aangadresh>();
        for (int i = 0; i < 10; i++) {
            Aangadresh obj = getNewTransientAangadresh(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
