// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.HisPerssamengesteldenaam;
import nl.bzk.brp.model.data.kern.HisPerssamengesteldenaamDataOnDemand;
import nl.bzk.brp.model.data.kern.HisPerssamengesteldenaamIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HisPerssamengesteldenaamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HisPerssamengesteldenaamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HisPerssamengesteldenaamIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HisPerssamengesteldenaamIntegrationTest: @Transactional;
    
    @Autowired
    private HisPerssamengesteldenaamDataOnDemand HisPerssamengesteldenaamIntegrationTest.dod;
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testCountHisPerssamengesteldenaams() {
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", dod.getRandomHisPerssamengesteldenaam());
        long count = HisPerssamengesteldenaam.countHisPerssamengesteldenaams();
        Assert.assertTrue("Counter for 'HisPerssamengesteldenaam' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testFindHisPerssamengesteldenaam() {
        HisPerssamengesteldenaam obj = dod.getRandomHisPerssamengesteldenaam();
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to provide an identifier", id);
        obj = HisPerssamengesteldenaam.findHisPerssamengesteldenaam(id);
        Assert.assertNotNull("Find method for 'HisPerssamengesteldenaam' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HisPerssamengesteldenaam' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testFindAllHisPerssamengesteldenaams() {
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", dod.getRandomHisPerssamengesteldenaam());
        long count = HisPerssamengesteldenaam.countHisPerssamengesteldenaams();
        Assert.assertTrue("Too expensive to perform a find all test for 'HisPerssamengesteldenaam', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HisPerssamengesteldenaam> result = HisPerssamengesteldenaam.findAllHisPerssamengesteldenaams();
        Assert.assertNotNull("Find all method for 'HisPerssamengesteldenaam' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HisPerssamengesteldenaam' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testFindHisPerssamengesteldenaamEntries() {
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", dod.getRandomHisPerssamengesteldenaam());
        long count = HisPerssamengesteldenaam.countHisPerssamengesteldenaams();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HisPerssamengesteldenaam> result = HisPerssamengesteldenaam.findHisPerssamengesteldenaamEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HisPerssamengesteldenaam' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HisPerssamengesteldenaam' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", dod.getRandomHisPerssamengesteldenaam());
        HisPerssamengesteldenaam obj = dod.getNewTransientHisPerssamengesteldenaam(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HisPerssamengesteldenaam' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HisPerssamengesteldenaam' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HisPerssamengesteldenaamIntegrationTest.testRemove() {
        HisPerssamengesteldenaam obj = dod.getRandomHisPerssamengesteldenaam();
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPerssamengesteldenaam' failed to provide an identifier", id);
        obj = HisPerssamengesteldenaam.findHisPerssamengesteldenaam(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HisPerssamengesteldenaam' with identifier '" + id + "'", HisPerssamengesteldenaam.findHisPerssamengesteldenaam(id));
    }
    
}
