// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.HisPersoverlijden;
import nl.bzk.brp.model.data.kern.HisPersoverlijdenDataOnDemand;
import nl.bzk.brp.model.data.kern.HisPersoverlijdenIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HisPersoverlijdenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HisPersoverlijdenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HisPersoverlijdenIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HisPersoverlijdenIntegrationTest: @Transactional;
    
    @Autowired
    private HisPersoverlijdenDataOnDemand HisPersoverlijdenIntegrationTest.dod;
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testCountHisPersoverlijdens() {
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", dod.getRandomHisPersoverlijden());
        long count = HisPersoverlijden.countHisPersoverlijdens();
        Assert.assertTrue("Counter for 'HisPersoverlijden' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testFindHisPersoverlijden() {
        HisPersoverlijden obj = dod.getRandomHisPersoverlijden();
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to provide an identifier", id);
        obj = HisPersoverlijden.findHisPersoverlijden(id);
        Assert.assertNotNull("Find method for 'HisPersoverlijden' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HisPersoverlijden' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testFindAllHisPersoverlijdens() {
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", dod.getRandomHisPersoverlijden());
        long count = HisPersoverlijden.countHisPersoverlijdens();
        Assert.assertTrue("Too expensive to perform a find all test for 'HisPersoverlijden', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HisPersoverlijden> result = HisPersoverlijden.findAllHisPersoverlijdens();
        Assert.assertNotNull("Find all method for 'HisPersoverlijden' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HisPersoverlijden' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testFindHisPersoverlijdenEntries() {
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", dod.getRandomHisPersoverlijden());
        long count = HisPersoverlijden.countHisPersoverlijdens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HisPersoverlijden> result = HisPersoverlijden.findHisPersoverlijdenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HisPersoverlijden' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HisPersoverlijden' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", dod.getRandomHisPersoverlijden());
        HisPersoverlijden obj = dod.getNewTransientHisPersoverlijden(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HisPersoverlijden' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HisPersoverlijden' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HisPersoverlijdenIntegrationTest.testRemove() {
        HisPersoverlijden obj = dod.getRandomHisPersoverlijden();
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPersoverlijden' failed to provide an identifier", id);
        obj = HisPersoverlijden.findHisPersoverlijden(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HisPersoverlijden' with identifier '" + id + "'", HisPersoverlijden.findHisPersoverlijden(id));
    }
    
}
