// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.Rdnverliesnlnation;
import nl.bzk.brp.model.data.kern.RdnverliesnlnationDataOnDemand;
import nl.bzk.brp.model.data.kern.RdnverliesnlnationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RdnverliesnlnationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RdnverliesnlnationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RdnverliesnlnationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RdnverliesnlnationIntegrationTest: @Transactional;
    
    @Autowired
    private RdnverliesnlnationDataOnDemand RdnverliesnlnationIntegrationTest.dod;
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testCountRdnverliesnlnations() {
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", dod.getRandomRdnverliesnlnation());
        long count = Rdnverliesnlnation.countRdnverliesnlnations();
        Assert.assertTrue("Counter for 'Rdnverliesnlnation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testFindRdnverliesnlnation() {
        Rdnverliesnlnation obj = dod.getRandomRdnverliesnlnation();
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to provide an identifier", id);
        obj = Rdnverliesnlnation.findRdnverliesnlnation(id);
        Assert.assertNotNull("Find method for 'Rdnverliesnlnation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rdnverliesnlnation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testFindAllRdnverliesnlnations() {
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", dod.getRandomRdnverliesnlnation());
        long count = Rdnverliesnlnation.countRdnverliesnlnations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rdnverliesnlnation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rdnverliesnlnation> result = Rdnverliesnlnation.findAllRdnverliesnlnations();
        Assert.assertNotNull("Find all method for 'Rdnverliesnlnation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rdnverliesnlnation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testFindRdnverliesnlnationEntries() {
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", dod.getRandomRdnverliesnlnation());
        long count = Rdnverliesnlnation.countRdnverliesnlnations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rdnverliesnlnation> result = Rdnverliesnlnation.findRdnverliesnlnationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rdnverliesnlnation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rdnverliesnlnation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", dod.getRandomRdnverliesnlnation());
        Rdnverliesnlnation obj = dod.getNewTransientRdnverliesnlnation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rdnverliesnlnation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Rdnverliesnlnation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RdnverliesnlnationIntegrationTest.testRemove() {
        Rdnverliesnlnation obj = dod.getRandomRdnverliesnlnation();
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rdnverliesnlnation' failed to provide an identifier", id);
        obj = Rdnverliesnlnation.findRdnverliesnlnation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rdnverliesnlnation' with identifier '" + id + "'", Rdnverliesnlnation.findRdnverliesnlnation(id));
    }
    
}
