// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.Srtdbobject;
import nl.bzk.brp.model.data.kern.SrtdbobjectDataOnDemand;
import nl.bzk.brp.model.data.kern.SrtdbobjectIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SrtdbobjectIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SrtdbobjectIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SrtdbobjectIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SrtdbobjectIntegrationTest: @Transactional;
    
    @Autowired
    private SrtdbobjectDataOnDemand SrtdbobjectIntegrationTest.dod;
    
    @Test
    public void SrtdbobjectIntegrationTest.testCountSrtdbobjects() {
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", dod.getRandomSrtdbobject());
        long count = Srtdbobject.countSrtdbobjects();
        Assert.assertTrue("Counter for 'Srtdbobject' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SrtdbobjectIntegrationTest.testFindSrtdbobject() {
        Srtdbobject obj = dod.getRandomSrtdbobject();
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to provide an identifier", id);
        obj = Srtdbobject.findSrtdbobject(id);
        Assert.assertNotNull("Find method for 'Srtdbobject' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Srtdbobject' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SrtdbobjectIntegrationTest.testFindAllSrtdbobjects() {
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", dod.getRandomSrtdbobject());
        long count = Srtdbobject.countSrtdbobjects();
        Assert.assertTrue("Too expensive to perform a find all test for 'Srtdbobject', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Srtdbobject> result = Srtdbobject.findAllSrtdbobjects();
        Assert.assertNotNull("Find all method for 'Srtdbobject' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Srtdbobject' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SrtdbobjectIntegrationTest.testFindSrtdbobjectEntries() {
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", dod.getRandomSrtdbobject());
        long count = Srtdbobject.countSrtdbobjects();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Srtdbobject> result = Srtdbobject.findSrtdbobjectEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Srtdbobject' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Srtdbobject' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SrtdbobjectIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", dod.getRandomSrtdbobject());
        Srtdbobject obj = dod.getNewTransientSrtdbobject(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Srtdbobject' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Srtdbobject' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SrtdbobjectIntegrationTest.testRemove() {
        Srtdbobject obj = dod.getRandomSrtdbobject();
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtdbobject' failed to provide an identifier", id);
        obj = Srtdbobject.findSrtdbobject(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Srtdbobject' with identifier '" + id + "'", Srtdbobject.findSrtdbobject(id));
    }
    
}
