// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.kern.Verdrag;
import nl.bzk.brp.model.data.kern.VerdragDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect VerdragDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VerdragDataOnDemand: @Component;
    
    private Random VerdragDataOnDemand.rnd = new SecureRandom();
    
    private List<Verdrag> VerdragDataOnDemand.data;
    
    public Verdrag VerdragDataOnDemand.getNewTransientVerdrag(int index) {
        Verdrag obj = new Verdrag();
        setDataanvgel(obj, index);
        setDateindegel(obj, index);
        setOms(obj, index);
        return obj;
    }
    
    public void VerdragDataOnDemand.setDataanvgel(Verdrag obj, int index) {
        BigDecimal dataanvgel = BigDecimal.valueOf(index);
        obj.setDataanvgel(dataanvgel);
    }
    
    public void VerdragDataOnDemand.setDateindegel(Verdrag obj, int index) {
        BigDecimal dateindegel = BigDecimal.valueOf(index);
        obj.setDateindegel(dateindegel);
    }
    
    public void VerdragDataOnDemand.setOms(Verdrag obj, int index) {
        String oms = "oms_" + index;
        if (oms.length() > 250) {
            oms = new Random().nextInt(10) + oms.substring(1, 250);
        }
        obj.setOms(oms);
    }
    
    public Verdrag VerdragDataOnDemand.getSpecificVerdrag(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Verdrag obj = data.get(index);
        Integer id = obj.getId();
        return Verdrag.findVerdrag(id);
    }
    
    public Verdrag VerdragDataOnDemand.getRandomVerdrag() {
        init();
        Verdrag obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Verdrag.findVerdrag(id);
    }
    
    public boolean VerdragDataOnDemand.modifyVerdrag(Verdrag obj) {
        return false;
    }
    
    public void VerdragDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Verdrag.findVerdragEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Verdrag' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Verdrag>();
        for (int i = 0; i < 10; i++) {
            Verdrag obj = getNewTransientVerdrag(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
