--------------------------------------------------------------------------------
-- PostgreSQL SQL-DDL bestand voor Basisregistratie Personen (BRP)            --
-- PostgreSQL - Kern Rechten                                                  --
--------------------------------------------------------------------------------
-- 
-- Gegenereerd door BRP Meta Register Release 58.
-- Gegenereerd op: vrijdag 19 mei 2017 10:00:47
-- 
--------------------------------------------------------------------------------

-- Rechten toekennen
GRANT USAGE ON SCHEMA AutAut TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA Beh TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA Conv TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA IST TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA Kern TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA MigBlok TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT USAGE ON SCHEMA VerConv TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;

GRANT SELECT ON AutAut.Bijhautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Bijhautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Bijhautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.BijhautorisatieSrtAdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.BijhautorisatieSrtAdmHnd TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_BijhautorisatieSrtAdmHnd TO BRP_Beheer;
GRANT SELECT ON AutAut.BijhouderFiatuitz TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.BijhouderFiatuitz TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_BijhouderFiatuitz TO BRP_Beheer;
GRANT SELECT ON AutAut.Dienst TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Dienst TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Dienst TO BRP_Beheer;
GRANT SELECT ON AutAut.Dienstbundel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Dienstbundel TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Dienstbundel TO BRP_Beheer;
GRANT SELECT ON AutAut.DienstbundelGroep TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.DienstbundelGroep TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_DienstbundelGroep TO BRP_Beheer;
GRANT SELECT ON AutAut.DienstbundelGroepAttr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.DienstbundelGroepAttr TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_DienstbundelGroepAttr TO BRP_Beheer;
GRANT SELECT ON AutAut.DienstbundelLO3Rubriek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.DienstbundelLO3Rubriek TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_DienstbundelLO3Rubriek TO BRP_Beheer;
GRANT SELECT ON AutAut.EenheidSelinterval TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.EffectAfnemerindicaties TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.His_Bijhautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_Bijhautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_Bijhautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.His_BijhautorisatieSrtAdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_BijhautorisatieSrtAdmHnd TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_BijhautorisatieSrtAdmHnd TO BRP_Beheer;
GRANT SELECT ON AutAut.His_BijhouderFiatuitz TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_BijhouderFiatuitz TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_BijhouderFiatuitz TO BRP_Beheer;
GRANT SELECT ON AutAut.His_Dienst TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_Dienst TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_Dienst TO BRP_Beheer;
GRANT SELECT ON AutAut.His_DienstAttendering TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_DienstAttendering TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_DienstAttendering TO BRP_Beheer;
GRANT SELECT ON AutAut.His_DienstSel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_DienstSel TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_DienstSel TO BRP_Beheer;
GRANT SELECT ON AutAut.His_DienstZoeken TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_DienstZoeken TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_DienstZoeken TO BRP_Beheer;
GRANT SELECT ON AutAut.His_Dienstbundel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_Dienstbundel TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_Dienstbundel TO BRP_Beheer;
GRANT SELECT ON AutAut.His_Levsautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_Levsautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_Levsautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.His_PersAfnemerindicatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_His_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.His_Seltaak TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_Seltaak TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_Seltaak TO BRP_Beheer;
GRANT SELECT ON AutAut.His_SeltaakStatus TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_SeltaakStatus TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_SeltaakStatus TO BRP_Beheer;
GRANT SELECT ON AutAut.His_ToegangBijhautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_ToegangBijhautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_ToegangBijhautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.His_ToegangLevsautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.His_ToegangLevsautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_His_ToegangLevsautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.LeverwijzeSel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.Levsautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Levsautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Levsautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.PersAfnemerindicatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.PersAfnemerindicatie TO BRP_Bijhouding;
GRANT USAGE ON AutAut.seq_PersAfnemerindicatie TO BRP_Bijhouding;
GRANT SELECT ON AutAut.Protocolleringsniveau TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.Selrun TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Selrun TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Selrun TO BRP_Beheer;
GRANT SELECT ON AutAut.Seltaak TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.Seltaak TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_Seltaak TO BRP_Beheer;
GRANT SELECT ON AutAut.SeltaakStatus TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.SrtDienst TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.SrtSel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON AutAut.ToegangBijhautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.ToegangBijhautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_ToegangBijhautorisatie TO BRP_Beheer;
GRANT SELECT ON AutAut.ToegangLevsautorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON AutAut.ToegangLevsautorisatie TO BRP_Beheer;
GRANT USAGE ON AutAut.seq_ToegangLevsautorisatie TO BRP_Beheer;
GRANT SELECT ON Beh.SrtBerVrijBer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Beh.SrtBerVrijBer TO BRP_Beheer;
GRANT USAGE ON Beh.seq_SrtBerVrijBer TO BRP_Beheer;
GRANT SELECT ON Beh.VrijBer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Beh.VrijBer TO BRP_Bijhouding;
GRANT USAGE ON Beh.seq_VrijBer TO BRP_Bijhouding;
GRANT INSERT, UPDATE, DELETE ON Beh.VrijBer TO BRP_Beheer;
GRANT USAGE ON Beh.seq_VrijBer TO BRP_Beheer;
GRANT SELECT ON Beh.VrijBerPartij TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Beh.VrijBerPartij TO BRP_Bijhouding;
GRANT USAGE ON Beh.seq_VrijBerPartij TO BRP_Bijhouding;
GRANT INSERT, UPDATE, DELETE ON Beh.VrijBerPartij TO BRP_Beheer;
GRANT USAGE ON Beh.seq_VrijBerPartij TO BRP_Beheer;
GRANT SELECT ON Conv.ConvAandInhingVermissingReis TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvAandInhingVermissingReis TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvAandInhingVermissingReis TO BRP_Beheer;
GRANT SELECT ON Conv.ConvAangifteAdresh TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvAangifteAdresh TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvAangifteAdresh TO BRP_Beheer;
GRANT SELECT ON Conv.ConvAdellijkeTitelPredikaat TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvAdellijkeTitelPredikaat TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvAdellijkeTitelPredikaat TO BRP_Beheer;
GRANT SELECT ON Conv.ConvLO3Rubriek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvLO3Rubriek TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvLO3Rubriek TO BRP_Beheer;
GRANT SELECT ON Conv.ConvRNIDeelnemer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvRNIDeelnemer TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvRNIDeelnemer TO BRP_Beheer;
GRANT SELECT ON Conv.ConvRdnBeeindigenNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvRdnBeeindigenNation TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvRdnBeeindigenNation TO BRP_Beheer;
GRANT SELECT ON Conv.ConvRdnOntbindingHuwelijkGer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvRdnOntbindingHuwelijkGer TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvRdnOntbindingHuwelijkGer TO BRP_Beheer;
GRANT SELECT ON Conv.ConvRdnOpnameNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvRdnOpnameNation TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvRdnOpnameNation TO BRP_Beheer;
GRANT SELECT ON Conv.ConvRdnOpschorting TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvRdnOpschorting TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvRdnOpschorting TO BRP_Beheer;
GRANT SELECT ON Conv.ConvSrtNLReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvSrtNLReisdoc TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvSrtNLReisdoc TO BRP_Beheer;
GRANT SELECT ON Conv.ConvVoorvoegsel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Conv.ConvVoorvoegsel TO BRP_Beheer;
GRANT USAGE ON Conv.seq_ConvVoorvoegsel TO BRP_Beheer;
GRANT SELECT ON IST.Autorisatietabel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON IST.Autorisatietabel TO BRP_Beheer;
GRANT USAGE ON IST.seq_Autorisatietabel TO BRP_Beheer;
GRANT SELECT ON IST.Stapel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON IST.Stapel TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_Stapel TO BRP_Bijhouding;
GRANT SELECT ON IST.StapelRelatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON IST.StapelRelatie TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_StapelRelatie TO BRP_Bijhouding;
GRANT SELECT ON IST.StapelVoorkomen TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON IST.StapelVoorkomen TO BRP_Bijhouding;
GRANT USAGE ON IST.seq_StapelVoorkomen TO BRP_Bijhouding;
GRANT SELECT ON Kern.AandInhingVermissingReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AandInhingVermissingReisdoc TO BRP_Beheer;
GRANT USAGE ON Kern.seq_AandInhingVermissingReisdoc TO BRP_Beheer;
GRANT SELECT ON Kern.AandVerblijfsr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AandVerblijfsr TO BRP_Beheer;
GRANT USAGE ON Kern.seq_AandVerblijfsr TO BRP_Beheer;
GRANT SELECT ON Kern.Aang TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Aang TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Aang TO BRP_Beheer;
GRANT SELECT ON Kern.Actie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Actie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Actie TO BRP_Bijhouding;
GRANT SELECT ON Kern.ActieBron TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.ActieBron TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_ActieBron TO BRP_Bijhouding;
GRANT SELECT ON Kern.AdellijkeTitel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.AdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AdmHnd TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AdmHnd TO BRP_Bijhouding;
GRANT SELECT ON Kern.AdmHndGedeblokkeerdeRegel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AdmHndGedeblokkeerdeRegel TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_AdmHndGedeblokkeerdeRegel TO BRP_Bijhouding;
GRANT SELECT ON Kern.AutVanAfgifteBLPersnr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AutVanAfgifteBLPersnr TO BRP_Beheer;
GRANT USAGE ON Kern.seq_AutVanAfgifteBLPersnr TO BRP_Beheer;
GRANT SELECT ON Kern.AuttypeVanAfgifteReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.AuttypeVanAfgifteReisdoc TO BRP_Beheer;
GRANT USAGE ON Kern.seq_AuttypeVanAfgifteReisdoc TO BRP_Beheer;
GRANT SELECT ON Kern.Betr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Betr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Betr TO BRP_Bijhouding;
GRANT SELECT ON Kern.Bijhaard TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Bijhresultaat TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Bijhsituatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.BurgerzakenModule TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.CategorieAdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Doc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Doc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Doc TO BRP_Bijhouding;
GRANT SELECT ON Kern.Element TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.GegevenInOnderzoek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.GegevenInOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_GegevenInOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.Gem TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Gem TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Gem TO BRP_Beheer;
GRANT SELECT ON Kern.Geslachtsaand TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.His_Betr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_Betr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Betr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_GegevenInOnderzoek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_GegevenInOnderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_GegevenInOnderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Onderzoek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_Onderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Onderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_OuderOuderlijkGezag TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_OuderOuderlijkGezag TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_OuderOuderlijkGezag TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_OuderOuderschap TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_OuderOuderschap TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_OuderOuderschap TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Partij TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_Partij TO BRP_Beheer;
GRANT USAGE ON Kern.seq_His_Partij TO BRP_Beheer;
GRANT SELECT ON Kern.His_PartijBijhouding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PartijBijhouding TO BRP_Beheer;
GRANT USAGE ON Kern.seq_His_PartijBijhouding TO BRP_Beheer;
GRANT SELECT ON Kern.His_PartijRol TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PartijRol TO BRP_Beheer;
GRANT USAGE ON Kern.seq_His_PartijRol TO BRP_Beheer;
GRANT SELECT ON Kern.His_PartijVrijBer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PartijVrijBer TO BRP_Beheer;
GRANT USAGE ON Kern.seq_His_PartijVrijBer TO BRP_Beheer;
GRANT SELECT ON Kern.His_PersAdres TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersAdres TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersAdres TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersAfgeleidAdministrati TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersAfgeleidAdministrati TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersAfgeleidAdministrati TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersBLPersnr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersBLPersnr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersBLPersnr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersBijhouding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersBijhouding TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersBijhouding TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersDeelnEUVerkiezingen TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersDeelnEUVerkiezingen TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersDeelnEUVerkiezingen TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeboorte TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersGeboorte TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeboorte TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeslachtsaand TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersGeslachtsaand TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeslachtsaand TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersGeslnaamcomp TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersIDs TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersIDs TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersIDs TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersIndicatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersIndicatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersIndicatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersInschr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersInschr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersInschr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersMigratie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersMigratie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersMigratie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNaamgebruik TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersNaamgebruik TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNaamgebruik TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersNrverwijzing TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersNrverwijzing TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersNrverwijzing TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersOverlijden TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersOverlijden TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersOverlijden TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersPK TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersPK TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersPK TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersSamengesteldeNaam TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersSamengesteldeNaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersSamengesteldeNaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersUitslKiesr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersUitslKiesr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersUitslKiesr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerblijfsr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersVerblijfsr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerblijfsr TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerificatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersVerificatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerificatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVerstrbeperking TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersVerstrbeperking TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVerstrbeperking TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_PersVoornaam TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_PersVoornaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_PersVoornaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.His_Relatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.His_Relatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_His_Relatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.Historievorm TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Koppelvlak TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.LandGebied TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.LandGebied TO BRP_Beheer;
GRANT USAGE ON Kern.seq_LandGebied TO BRP_Beheer;
GRANT SELECT ON Kern.Naamgebruik TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.NadereBijhaard TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Nation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Nation TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Nation TO BRP_Beheer;
GRANT SELECT ON Kern.Onderzoek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Onderzoek TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Onderzoek TO BRP_Bijhouding;
GRANT SELECT ON Kern.Partij TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Partij TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Partij TO BRP_Beheer;
GRANT SELECT ON Kern.PartijRol TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PartijRol TO BRP_Beheer;
GRANT USAGE ON Kern.seq_PartijRol TO BRP_Beheer;
GRANT SELECT ON Kern.Pers TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Pers TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Pers TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersAdres TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersAdres TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersAdres TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersBLPersnr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersBLPersnr TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersBLPersnr TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersCache TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersCache TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersCache TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersGeslnaamcomp TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersGeslnaamcomp TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersGeslnaamcomp TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersIndicatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersIndicatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersIndicatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersNation TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersNation TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersReisdoc TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersReisdoc TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVerificatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersVerificatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVerificatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVerstrbeperking TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersVerstrbeperking TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVerstrbeperking TO BRP_Bijhouding;
GRANT SELECT ON Kern.PersVoornaam TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.PersVoornaam TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_PersVoornaam TO BRP_Bijhouding;
GRANT SELECT ON Kern.Plaats TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Plaats TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Plaats TO BRP_Beheer;
GRANT SELECT ON Kern.Predicaat TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.RdnEindeRelatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.RdnEindeRelatie TO BRP_Beheer;
GRANT USAGE ON Kern.seq_RdnEindeRelatie TO BRP_Beheer;
GRANT SELECT ON Kern.RdnVerkNLNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.RdnVerkNLNation TO BRP_Beheer;
GRANT USAGE ON Kern.seq_RdnVerkNLNation TO BRP_Beheer;
GRANT SELECT ON Kern.RdnVerliesNLNation TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.RdnVerliesNLNation TO BRP_Beheer;
GRANT USAGE ON Kern.seq_RdnVerliesNLNation TO BRP_Beheer;
GRANT SELECT ON Kern.RdnWijzVerblijf TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.RdnWijzVerblijf TO BRP_Beheer;
GRANT USAGE ON Kern.seq_RdnWijzVerblijf TO BRP_Beheer;
GRANT SELECT ON Kern.Rechtsgrond TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Rechtsgrond TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Rechtsgrond TO BRP_Beheer;
GRANT SELECT ON Kern.Regel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Relatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Relatie TO BRP_Bijhouding;
GRANT USAGE ON Kern.seq_Relatie TO BRP_Bijhouding;
GRANT SELECT ON Kern.Richting TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Rol TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtActie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtActieBrongebruik TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtActieBrongebruik TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtActieBrongebruik TO BRP_Beheer;
GRANT SELECT ON Kern.SrtAdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtAdres TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtBer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtBerElement TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtBerElement TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtBerElement TO BRP_Beheer;
GRANT SELECT ON Kern.SrtBetr TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtDoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtDoc TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtDoc TO BRP_Beheer;
GRANT SELECT ON Kern.SrtElement TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtElementAutorisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtIndicatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtMelding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtMigratie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtNLReisdoc TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtNLReisdoc TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtNLReisdoc TO BRP_Beheer;
GRANT SELECT ON Kern.SrtPartij TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtPartij TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtPartij TO BRP_Beheer;
GRANT SELECT ON Kern.SrtPers TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtRelatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtSynchronisatie TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.SrtVrijBer TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.SrtVrijBer TO BRP_Beheer;
GRANT USAGE ON Kern.seq_SrtVrijBer TO BRP_Beheer;
GRANT SELECT ON Kern.StatusLevAdmHnd TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.StatusOnderzoek TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Stelsel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Verantwoording TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.VersieStufBG TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.VersieStufBG TO BRP_Beheer;
GRANT USAGE ON Kern.seq_VersieStufBG TO BRP_Beheer;
GRANT SELECT ON Kern.VertalingBersrtBRP TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.VertalingBersrtBRP TO BRP_Beheer;
GRANT USAGE ON Kern.seq_VertalingBersrtBRP TO BRP_Beheer;
GRANT SELECT ON Kern.Verwerkingsresultaat TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Verwerkingswijze TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON Kern.Voorvoegsel TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON Kern.Voorvoegsel TO BRP_Beheer;
GRANT USAGE ON Kern.seq_Voorvoegsel TO BRP_Beheer;
GRANT SELECT ON MigBlok.Blokkering TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON MigBlok.Blokkering TO BRP_Bijhouding;
GRANT USAGE ON MigBlok.seq_Blokkering TO BRP_Bijhouding;
GRANT SELECT ON MigBlok.RdnBlokkering TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3AandOuder TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON VerConv.LO3AandOuder TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3AandOuder TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Ber TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON VerConv.LO3Ber TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Ber TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3BerBron TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3CategorieMelding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3Melding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON VerConv.LO3Melding TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Melding TO BRP_Bijhouding;
GRANT SELECT ON VerConv.LO3Severity TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3SrtAandOuder TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3SrtMelding TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT SELECT ON VerConv.LO3Voorkomen TO BRP_Lezen, BRP_Bijhouding, BRP_Beheer;
GRANT INSERT, UPDATE, DELETE ON VerConv.LO3Voorkomen TO BRP_Bijhouding;
GRANT USAGE ON VerConv.seq_LO3Voorkomen TO BRP_Bijhouding;
