// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.lev;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.bzk.brp.model.data.kern.Pers;
import nl.bzk.brp.model.data.kern.PersDataOnDemand;
import nl.bzk.brp.model.data.lev.Lev;
import nl.bzk.brp.model.data.lev.LevDataOnDemand;
import nl.bzk.brp.model.data.lev.Levpers;
import nl.bzk.brp.model.data.lev.LevpersDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LevpersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LevpersDataOnDemand: @Component;
    
    private Random LevpersDataOnDemand.rnd = new SecureRandom();
    
    private List<Levpers> LevpersDataOnDemand.data;
    
    @Autowired
    private LevDataOnDemand LevpersDataOnDemand.levDataOnDemand;
    
    @Autowired
    private PersDataOnDemand LevpersDataOnDemand.persDataOnDemand;
    
    public Levpers LevpersDataOnDemand.getNewTransientLevpers(int index) {
        Levpers obj = new Levpers();
        setLev(obj, index);
        setPers(obj, index);
        return obj;
    }
    
    public void LevpersDataOnDemand.setLev(Levpers obj, int index) {
        Lev lev = levDataOnDemand.getRandomLev();
        obj.setLev(lev);
    }
    
    public void LevpersDataOnDemand.setPers(Levpers obj, int index) {
        Pers pers = persDataOnDemand.getRandomPers();
        obj.setPers(pers);
    }
    
    public Levpers LevpersDataOnDemand.getSpecificLevpers(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Levpers obj = data.get(index);
        Long id = obj.getId();
        return Levpers.findLevpers(id);
    }
    
    public Levpers LevpersDataOnDemand.getRandomLevpers() {
        init();
        Levpers obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Levpers.findLevpers(id);
    }
    
    public boolean LevpersDataOnDemand.modifyLevpers(Levpers obj) {
        return false;
    }
    
    public void LevpersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Levpers.findLevpersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Levpers' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Levpers>();
        for (int i = 0; i < 10; i++) {
            Levpers obj = getNewTransientLevpers(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
