// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.HisPerseuverkiezingen;
import nl.bzk.brp.model.data.kern.HisPerseuverkiezingenDataOnDemand;
import nl.bzk.brp.model.data.kern.HisPerseuverkiezingenIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HisPerseuverkiezingenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HisPerseuverkiezingenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HisPerseuverkiezingenIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HisPerseuverkiezingenIntegrationTest: @Transactional;
    
    @Autowired
    private HisPerseuverkiezingenDataOnDemand HisPerseuverkiezingenIntegrationTest.dod;
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testCountHisPerseuverkiezingens() {
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", dod.getRandomHisPerseuverkiezingen());
        long count = HisPerseuverkiezingen.countHisPerseuverkiezingens();
        Assert.assertTrue("Counter for 'HisPerseuverkiezingen' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testFindHisPerseuverkiezingen() {
        HisPerseuverkiezingen obj = dod.getRandomHisPerseuverkiezingen();
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to provide an identifier", id);
        obj = HisPerseuverkiezingen.findHisPerseuverkiezingen(id);
        Assert.assertNotNull("Find method for 'HisPerseuverkiezingen' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HisPerseuverkiezingen' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testFindAllHisPerseuverkiezingens() {
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", dod.getRandomHisPerseuverkiezingen());
        long count = HisPerseuverkiezingen.countHisPerseuverkiezingens();
        Assert.assertTrue("Too expensive to perform a find all test for 'HisPerseuverkiezingen', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HisPerseuverkiezingen> result = HisPerseuverkiezingen.findAllHisPerseuverkiezingens();
        Assert.assertNotNull("Find all method for 'HisPerseuverkiezingen' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HisPerseuverkiezingen' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testFindHisPerseuverkiezingenEntries() {
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", dod.getRandomHisPerseuverkiezingen());
        long count = HisPerseuverkiezingen.countHisPerseuverkiezingens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HisPerseuverkiezingen> result = HisPerseuverkiezingen.findHisPerseuverkiezingenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HisPerseuverkiezingen' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HisPerseuverkiezingen' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", dod.getRandomHisPerseuverkiezingen());
        HisPerseuverkiezingen obj = dod.getNewTransientHisPerseuverkiezingen(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HisPerseuverkiezingen' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HisPerseuverkiezingen' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HisPerseuverkiezingenIntegrationTest.testRemove() {
        HisPerseuverkiezingen obj = dod.getRandomHisPerseuverkiezingen();
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HisPerseuverkiezingen' failed to provide an identifier", id);
        obj = HisPerseuverkiezingen.findHisPerseuverkiezingen(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HisPerseuverkiezingen' with identifier '" + id + "'", HisPerseuverkiezingen.findHisPerseuverkiezingen(id));
    }
    
}
