// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.Persnation;
import nl.bzk.brp.model.data.kern.PersnationDataOnDemand;
import nl.bzk.brp.model.data.kern.PersnationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersnationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PersnationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PersnationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PersnationIntegrationTest: @Transactional;
    
    @Autowired
    private PersnationDataOnDemand PersnationIntegrationTest.dod;
    
    @Test
    public void PersnationIntegrationTest.testCountPersnations() {
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", dod.getRandomPersnation());
        long count = Persnation.countPersnations();
        Assert.assertTrue("Counter for 'Persnation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PersnationIntegrationTest.testFindPersnation() {
        Persnation obj = dod.getRandomPersnation();
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Persnation' failed to provide an identifier", id);
        obj = Persnation.findPersnation(id);
        Assert.assertNotNull("Find method for 'Persnation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Persnation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PersnationIntegrationTest.testFindAllPersnations() {
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", dod.getRandomPersnation());
        long count = Persnation.countPersnations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Persnation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Persnation> result = Persnation.findAllPersnations();
        Assert.assertNotNull("Find all method for 'Persnation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Persnation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PersnationIntegrationTest.testFindPersnationEntries() {
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", dod.getRandomPersnation());
        long count = Persnation.countPersnations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Persnation> result = Persnation.findPersnationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Persnation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Persnation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PersnationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", dod.getRandomPersnation());
        Persnation obj = dod.getNewTransientPersnation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Persnation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Persnation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Persnation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PersnationIntegrationTest.testRemove() {
        Persnation obj = dod.getRandomPersnation();
        Assert.assertNotNull("Data on demand for 'Persnation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Persnation' failed to provide an identifier", id);
        obj = Persnation.findPersnation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Persnation' with identifier '" + id + "'", Persnation.findPersnation(id));
    }
    
}
