// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.bzk.brp.model.data.kern;

import java.util.List;
import nl.bzk.brp.model.data.kern.Srtbetr;
import nl.bzk.brp.model.data.kern.SrtbetrDataOnDemand;
import nl.bzk.brp.model.data.kern.SrtbetrIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SrtbetrIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SrtbetrIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SrtbetrIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SrtbetrIntegrationTest: @Transactional;
    
    @Autowired
    private SrtbetrDataOnDemand SrtbetrIntegrationTest.dod;
    
    @Test
    public void SrtbetrIntegrationTest.testCountSrtbetrs() {
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", dod.getRandomSrtbetr());
        long count = Srtbetr.countSrtbetrs();
        Assert.assertTrue("Counter for 'Srtbetr' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SrtbetrIntegrationTest.testFindSrtbetr() {
        Srtbetr obj = dod.getRandomSrtbetr();
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to provide an identifier", id);
        obj = Srtbetr.findSrtbetr(id);
        Assert.assertNotNull("Find method for 'Srtbetr' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Srtbetr' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SrtbetrIntegrationTest.testFindAllSrtbetrs() {
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", dod.getRandomSrtbetr());
        long count = Srtbetr.countSrtbetrs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Srtbetr', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Srtbetr> result = Srtbetr.findAllSrtbetrs();
        Assert.assertNotNull("Find all method for 'Srtbetr' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Srtbetr' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SrtbetrIntegrationTest.testFindSrtbetrEntries() {
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", dod.getRandomSrtbetr());
        long count = Srtbetr.countSrtbetrs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Srtbetr> result = Srtbetr.findSrtbetrEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Srtbetr' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Srtbetr' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SrtbetrIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", dod.getRandomSrtbetr());
        Srtbetr obj = dod.getNewTransientSrtbetr(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Srtbetr' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Srtbetr' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SrtbetrIntegrationTest.testRemove() {
        Srtbetr obj = dod.getRandomSrtbetr();
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to initialize correctly", obj);
        Short id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Srtbetr' failed to provide an identifier", id);
        obj = Srtbetr.findSrtbetr(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Srtbetr' with identifier '" + id + "'", Srtbetr.findSrtbetr(id));
    }
    
}
