/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;

// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA

/**
 * Multirealiteitregel generated by hbm2java
 */
public class Multirealiteitregel implements java.io.Serializable {

    private int                    id;
    private Srtmultirealiteitregel srtmultirealiteitregel;
    private Long                   persByPers;
    private Long                   betr;
    private Long                   persByMultirealiteitpers;
    private Long                   relatie;
    private Long                   persByGeldigvoor;
    private String              multirealiteitregelstatushis = StatusHis.A.name();

    public Multirealiteitregel() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public Srtmultirealiteitregel getSrtmultirealiteitregel() {
        return this.srtmultirealiteitregel;
    }

    public void setSrtmultirealiteitregel(final Srtmultirealiteitregel srtmultirealiteitregel) {
        this.srtmultirealiteitregel = srtmultirealiteitregel;
    }

    public Long getPersByPers() {
        return this.persByPers;
    }

    public void setPersByPers(final Long persByPers) {
        this.persByPers = persByPers;
    }

    public Long getBetr() {
        return this.betr;
    }

    public void setBetr(final Long betr) {
        this.betr = betr;
    }

    public Long getPersByMultirealiteitpers() {
        return this.persByMultirealiteitpers;
    }

    public void setPersByMultirealiteitpers(final Long persByMultirealiteitpers) {
        this.persByMultirealiteitpers = persByMultirealiteitpers;
    }

    public Long getRelatie() {
        return this.relatie;
    }

    public void setRelatie(final Long relatie) {
        this.relatie = relatie;
    }

    public Long getPersByGeldigvoor() {
        return this.persByGeldigvoor;
    }

    public void setPersByGeldigvoor(final Long persByGeldigvoor) {
        this.persByGeldigvoor = persByGeldigvoor;
    }

    public String getMultirealiteitregelstatushis() {
        return this.multirealiteitregelstatushis;
    }

    public void setMultirealiteitregelstatushis(final String multirealiteitregelstatushis) {
        this.multirealiteitregelstatushis = multirealiteitregelstatushis;
    }

}
