/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;

// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;


/**
 * Pers generated by hbm2java
 */
public class Pers implements java.io.Serializable {

    private String            aanschrstatushis             = StatusHis.A.name();
    private Adellijketitel       adellijketitel;
    private Adellijketitel       adellijketitelaanschr;
    private Long                 anr;
    private String            bijhgemstatushis             = StatusHis.A.name();
    private String            bijhverantwoordelijkheidstat = StatusHis.A.name();
    private String               blgeboorteplaats;
    private String               blplaatsoverlijden;
    private String               blregiogeboorte;
    private String               blregiooverlijden;
    private Integer              bsn;
    private Integer              dataanlaanpdeelneuverkiezing;
    private Integer              dataanvaaneenslverblijfsr;
    private Integer              dataanvverblijfsr;
    private Integer              dateindeuitsleukiesr;
    private Integer              dateindeuitslnlkiesr;
    private Integer              datgeboorte;
    private Integer              datinschr;
    private Integer              datinschringem;
    private Integer              datoverlijden;
    private Integer              datvestiginginnederland;
    private Integer              datvoorzeindeverblijfsr;
    private String            euverkiezingenstatushis      = StatusHis.A.name();
    private String            geboortestatushis            = StatusHis.A.name();
    private Geslachtsaand        geslachtsaand;
    private String            geslachtsaandstatushis       = StatusHis.A.name();
    private String               geslnaam;
    private String               geslnaamaanschr;
    private int                  id;
    private String            idsstatushis                 = StatusHis.A.name();
    private String            immigratiestatushis          = StatusHis.A.name();
    private Boolean              indaanschralgoritmischafgele;
    private Boolean              indaanschrmetadellijketitels;
    private Boolean              indalgoritmischafgeleid;
    private Boolean              inddeelneuverkiezingen;
    private Boolean              indgegevensinonderzoek;
    private Boolean              indnreeksalsgeslnaam;
    private Boolean              indonverwdocaanw;
    private Boolean              indpkvollediggeconv;
    private Boolean              induitslnlkiesr;
    private String            inschrstatushis              = StatusHis.A.name();
    private Land                 landByLandgeboorte;
    private Land                 landByLandoverlijden;
    private Land                 landByLandvanwaargevestigd;
    private String               omsgeboorteloc;
    private String               omslocoverlijden;
    private String            opschortingstatushis         = StatusHis.A.name();
    private String            overlijdenstatushis          = StatusHis.A.name();
    private Partij               partijByBijhgem;
    private Partij               partijByGemgeboorte;
    private Partij               partijByGemoverlijden;
    private Partij               partijByGempk;
    private Pers                 persByVolgendepers;
    private Pers                 persByVorigepers;
    private String            pkstatushis                  = StatusHis.A.name();
    private Plaats               plaatsByWplgeboorte;
    private Plaats               plaatsByWploverlijden;
    private Predikaat            predikaatByPredikaat;
    private Predikaat            predikaatByPredikaataanschr;
    private Rdnopschorting       rdnopschorting;
    private String            samengesteldenaamstatushis   = StatusHis.A.name();
    private String               scheidingsteken;
    private String               scheidingstekenaanschr;
    private Srtpers              srtpers;
    private Date                 tijdstiplaatstewijz;
    private String            uitslnlkiesrstatushis        = StatusHis.A.name();
    private Verantwoordelijke    verantwoordelijke;
    private Verblijfsr           verblijfsr;
    private String            verblijfsrstatushis          = StatusHis.A.name();
    private Long                 versienr;
    private String               voornamen;
    private String               voornamenaanschr;
    private String               voorvoegsel;
    private String               voorvoegselaanschr;
    private Wijzegebruikgeslnaam wijzegebruikgeslnaam;

    public Pers() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public Predikaat getPredikaatByPredikaataanschr() {
        return this.predikaatByPredikaataanschr;
    }

    public void setPredikaatByPredikaataanschr(final Predikaat predikaatByPredikaataanschr) {
        this.predikaatByPredikaataanschr = predikaatByPredikaataanschr;
    }

    public Partij getPartijByGempk() {
        return this.partijByGempk;
    }

    public void setPartijByGempk(final Partij partijByGempk) {
        this.partijByGempk = partijByGempk;
    }

    public Plaats getPlaatsByWplgeboorte() {
        return this.plaatsByWplgeboorte;
    }

    public void setPlaatsByWplgeboorte(final Plaats plaatsByWplgeboorte) {
        this.plaatsByWplgeboorte = plaatsByWplgeboorte;
    }

    public Pers getPersByVolgendepers() {
        return this.persByVolgendepers;
    }

    public void setPersByVolgendepers(final Pers persByVolgendepers) {
        this.persByVolgendepers = persByVolgendepers;
    }

    public Verblijfsr getVerblijfsr() {
        return this.verblijfsr;
    }

    public void setVerblijfsr(final Verblijfsr verblijfsr) {
        this.verblijfsr = verblijfsr;
    }

    public Predikaat getPredikaatByPredikaat() {
        return this.predikaatByPredikaat;
    }

    public void setPredikaatByPredikaat(final Predikaat predikaatByPredikaat) {
        this.predikaatByPredikaat = predikaatByPredikaat;
    }

    public Plaats getPlaatsByWploverlijden() {
        return this.plaatsByWploverlijden;
    }

    public void setPlaatsByWploverlijden(final Plaats plaatsByWploverlijden) {
        this.plaatsByWploverlijden = plaatsByWploverlijden;
    }

    public Pers getPersByVorigepers() {
        return this.persByVorigepers;
    }

    public void setPersByVorigepers(final Pers persByVorigepers) {
        this.persByVorigepers = persByVorigepers;
    }

    public Partij getPartijByGemgeboorte() {
        return this.partijByGemgeboorte;
    }

    public void setPartijByGemgeboorte(final Partij partijByGemgeboorte) {
        this.partijByGemgeboorte = partijByGemgeboorte;
    }

    public Adellijketitel getAdellijketitelaanschr() {
        return this.adellijketitelaanschr;
    }

    public void setAdellijketitelaanschr(final Adellijketitel adellijketitelaanschr) {
        this.adellijketitelaanschr = adellijketitelaanschr;
    }

    public Verantwoordelijke getVerantwoordelijke() {
        return this.verantwoordelijke;
    }

    public void setVerantwoordelijke(final Verantwoordelijke verantwoordelijke) {
        this.verantwoordelijke = verantwoordelijke;
    }

    public Partij getPartijByBijhgem() {
        return this.partijByBijhgem;
    }

    public void setPartijByBijhgem(final Partij partijByBijhgem) {
        this.partijByBijhgem = partijByBijhgem;
    }

    public Geslachtsaand getGeslachtsaand() {
        return this.geslachtsaand;
    }

    public void setGeslachtsaand(final Geslachtsaand geslachtsaand) {
        this.geslachtsaand = geslachtsaand;
    }

    public Srtpers getSrtpers() {
        return this.srtpers;
    }

    public void setSrtpers(final Srtpers srtpers) {
        this.srtpers = srtpers;
    }

    public Land getLandByLandoverlijden() {
        return this.landByLandoverlijden;
    }

    public void setLandByLandoverlijden(final Land landByLandoverlijden) {
        this.landByLandoverlijden = landByLandoverlijden;
    }

    public Wijzegebruikgeslnaam getWijzegebruikgeslnaam() {
        return this.wijzegebruikgeslnaam;
    }

    public void setWijzegebruikgeslnaam(final Wijzegebruikgeslnaam wijzegebruikgeslnaam) {
        this.wijzegebruikgeslnaam = wijzegebruikgeslnaam;
    }

    public Land getLandByLandgeboorte() {
        return this.landByLandgeboorte;
    }

    public void setLandByLandgeboorte(final Land landByLandgeboorte) {
        this.landByLandgeboorte = landByLandgeboorte;
    }

    public Land getLandByLandvanwaargevestigd() {
        return this.landByLandvanwaargevestigd;
    }

    public void setLandByLandvanwaargevestigd(final Land landByLandvanwaargevestigd) {
        this.landByLandvanwaargevestigd = landByLandvanwaargevestigd;
    }

    public Partij getPartijByGemoverlijden() {
        return this.partijByGemoverlijden;
    }

    public void setPartijByGemoverlijden(final Partij partijByGemoverlijden) {
        this.partijByGemoverlijden = partijByGemoverlijden;
    }

    public Rdnopschorting getRdnopschorting() {
        return this.rdnopschorting;
    }

    public void setRdnopschorting(final Rdnopschorting rdnopschorting) {
        this.rdnopschorting = rdnopschorting;
    }

    public Adellijketitel getAdellijketitel() {
        return this.adellijketitel;
    }

    public void setAdellijketitel(final Adellijketitel adellijketitel) {
        this.adellijketitel = adellijketitel;
    }

    public Integer getDatgeboorte() {
        return this.datgeboorte;
    }

    public void setDatgeboorte(final Integer datgeboorte) {
        this.datgeboorte = datgeboorte;
    }

    public String getBlgeboorteplaats() {
        return this.blgeboorteplaats;
    }

    public void setBlgeboorteplaats(final String blgeboorteplaats) {
        this.blgeboorteplaats = blgeboorteplaats;
    }

    public String getBlregiogeboorte() {
        return this.blregiogeboorte;
    }

    public void setBlregiogeboorte(final String blregiogeboorte) {
        this.blregiogeboorte = blregiogeboorte;
    }

    public String getOmsgeboorteloc() {
        return this.omsgeboorteloc;
    }

    public void setOmsgeboorteloc(final String omsgeboorteloc) {
        this.omsgeboorteloc = omsgeboorteloc;
    }

    public String getGeboortestatushis() {
        return this.geboortestatushis;
    }

    public void setGeboortestatushis(final String geboortestatushis) {
        this.geboortestatushis = geboortestatushis;
    }

    public Integer getDatvestiginginnederland() {
        return this.datvestiginginnederland;
    }

    public void setDatvestiginginnederland(final Integer datvestiginginnederland) {
        this.datvestiginginnederland = datvestiginginnederland;
    }

    public String getImmigratiestatushis() {
        return this.immigratiestatushis;
    }

    public void setImmigratiestatushis(final String immigratiestatushis) {
        this.immigratiestatushis = immigratiestatushis;
    }

    public Integer getDatoverlijden() {
        return this.datoverlijden;
    }

    public void setDatoverlijden(final Integer datoverlijden) {
        this.datoverlijden = datoverlijden;
    }

    public String getBlplaatsoverlijden() {
        return this.blplaatsoverlijden;
    }

    public void setBlplaatsoverlijden(final String blplaatsoverlijden) {
        this.blplaatsoverlijden = blplaatsoverlijden;
    }

    public String getBlregiooverlijden() {
        return this.blregiooverlijden;
    }

    public void setBlregiooverlijden(final String blregiooverlijden) {
        this.blregiooverlijden = blregiooverlijden;
    }

    public String getOmslocoverlijden() {
        return this.omslocoverlijden;
    }

    public void setOmslocoverlijden(final String omslocoverlijden) {
        this.omslocoverlijden = omslocoverlijden;
    }

    public String getOverlijdenstatushis() {
        return this.overlijdenstatushis;
    }

    public void setOverlijdenstatushis(final String overlijdenstatushis) {
        this.overlijdenstatushis = overlijdenstatushis;
    }

    public String getOpschortingstatushis() {
        return this.opschortingstatushis;
    }

    public void setOpschortingstatushis(final String opschortingstatushis) {
        this.opschortingstatushis = opschortingstatushis;
    }

    public Integer getDatinschr() {
        return this.datinschr;
    }

    public void setDatinschr(final Integer datinschr) {
        this.datinschr = datinschr;
    }

    public Long getVersienr() {
        return this.versienr;
    }

    public void setVersienr(final Long versienr) {
        this.versienr = versienr;
    }

    public String getInschrstatushis() {
        return this.inschrstatushis;
    }

    public void setInschrstatushis(final String inschrstatushis) {
        this.inschrstatushis = inschrstatushis;
    }

    public Boolean getIndaanschrmetadellijketitels() {
        return this.indaanschrmetadellijketitels;
    }

    public void setIndaanschrmetadellijketitels(final Boolean indaanschrmetadellijketitels) {
        this.indaanschrmetadellijketitels = indaanschrmetadellijketitels;
    }

    public Boolean getIndaanschralgoritmischafgele() {
        return this.indaanschralgoritmischafgele;
    }

    public void setIndaanschralgoritmischafgele(final Boolean indaanschralgoritmischafgele) {
        this.indaanschralgoritmischafgele = indaanschralgoritmischafgele;
    }

    public String getVoornamenaanschr() {
        return this.voornamenaanschr;
    }

    public void setVoornamenaanschr(final String voornamenaanschr) {
        this.voornamenaanschr = voornamenaanschr;
    }

    public String getVoorvoegselaanschr() {
        return this.voorvoegselaanschr;
    }

    public void setVoorvoegselaanschr(final String voorvoegselaanschr) {
        this.voorvoegselaanschr = voorvoegselaanschr;
    }

    public String getScheidingstekenaanschr() {
        return this.scheidingstekenaanschr;
    }

    public void setScheidingstekenaanschr(final String scheidingstekenaanschr) {
        this.scheidingstekenaanschr = scheidingstekenaanschr;
    }

    public String getGeslnaamaanschr() {
        return this.geslnaamaanschr;
    }

    public void setGeslnaamaanschr(final String geslnaamaanschr) {
        this.geslnaamaanschr = geslnaamaanschr;
    }

    public String getAanschrstatushis() {
        return this.aanschrstatushis;
    }

    public void setAanschrstatushis(final String aanschrstatushis) {
        this.aanschrstatushis = aanschrstatushis;
    }

    public Boolean getIndpkvollediggeconv() {
        return this.indpkvollediggeconv;
    }

    public void setIndpkvollediggeconv(final Boolean indpkvollediggeconv) {
        this.indpkvollediggeconv = indpkvollediggeconv;
    }

    public String getPkstatushis() {
        return this.pkstatushis;
    }

    public void setPkstatushis(final String pkstatushis) {
        this.pkstatushis = pkstatushis;
    }

    public Integer getDataanvverblijfsr() {
        return this.dataanvverblijfsr;
    }

    public void setDataanvverblijfsr(final Integer dataanvverblijfsr) {
        this.dataanvverblijfsr = dataanvverblijfsr;
    }

    public Integer getDatvoorzeindeverblijfsr() {
        return this.datvoorzeindeverblijfsr;
    }

    public void setDatvoorzeindeverblijfsr(final Integer datvoorzeindeverblijfsr) {
        this.datvoorzeindeverblijfsr = datvoorzeindeverblijfsr;
    }

    public Integer getDataanvaaneenslverblijfsr() {
        return this.dataanvaaneenslverblijfsr;
    }

    public void setDataanvaaneenslverblijfsr(final Integer dataanvaaneenslverblijfsr) {
        this.dataanvaaneenslverblijfsr = dataanvaaneenslverblijfsr;
    }

    public String getVerblijfsrstatushis() {
        return this.verblijfsrstatushis;
    }

    public void setVerblijfsrstatushis(final String verblijfsrstatushis) {
        this.verblijfsrstatushis = verblijfsrstatushis;
    }

    public Boolean getInddeelneuverkiezingen() {
        return this.inddeelneuverkiezingen;
    }

    public void setInddeelneuverkiezingen(final Boolean inddeelneuverkiezingen) {
        this.inddeelneuverkiezingen = inddeelneuverkiezingen;
    }

    public Integer getDataanlaanpdeelneuverkiezing() {
        return this.dataanlaanpdeelneuverkiezing;
    }

    public void setDataanlaanpdeelneuverkiezing(final Integer dataanlaanpdeelneuverkiezing) {
        this.dataanlaanpdeelneuverkiezing = dataanlaanpdeelneuverkiezing;
    }

    public Integer getDateindeuitsleukiesr() {
        return this.dateindeuitsleukiesr;
    }

    public void setDateindeuitsleukiesr(final Integer dateindeuitsleukiesr) {
        this.dateindeuitsleukiesr = dateindeuitsleukiesr;
    }

    public String getEuverkiezingenstatushis() {
        return this.euverkiezingenstatushis;
    }

    public void setEuverkiezingenstatushis(final String euverkiezingenstatushis) {
        this.euverkiezingenstatushis = euverkiezingenstatushis;
    }

    public String getVoornamen() {
        return this.voornamen;
    }

    public void setVoornamen(final String voornamen) {
        this.voornamen = voornamen;
    }

    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }

    public void setVoorvoegsel(final String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }

    public String getScheidingsteken() {
        return this.scheidingsteken;
    }

    public void setScheidingsteken(final String scheidingsteken) {
        this.scheidingsteken = scheidingsteken;
    }

    public String getGeslnaam() {
        return this.geslnaam;
    }

    public void setGeslnaam(final String geslnaam) {
        this.geslnaam = geslnaam;
    }

    public Boolean getIndnreeksalsgeslnaam() {
        return this.indnreeksalsgeslnaam;
    }

    public void setIndnreeksalsgeslnaam(final Boolean indnreeksalsgeslnaam) {
        this.indnreeksalsgeslnaam = indnreeksalsgeslnaam;
    }

    public Boolean getIndalgoritmischafgeleid() {
        return this.indalgoritmischafgeleid;
    }

    public void setIndalgoritmischafgeleid(final Boolean indalgoritmischafgeleid) {
        this.indalgoritmischafgeleid = indalgoritmischafgeleid;
    }

    public String getSamengesteldenaamstatushis() {
        return this.samengesteldenaamstatushis;
    }

    public void setSamengesteldenaamstatushis(final String samengesteldenaamstatushis) {
        this.samengesteldenaamstatushis = samengesteldenaamstatushis;
    }

    public Integer getDatinschringem() {
        return this.datinschringem;
    }

    public void setDatinschringem(final Integer datinschringem) {
        this.datinschringem = datinschringem;
    }

    public Boolean getIndonverwdocaanw() {
        return this.indonverwdocaanw;
    }

    public void setIndonverwdocaanw(final Boolean indonverwdocaanw) {
        this.indonverwdocaanw = indonverwdocaanw;
    }

    public String getBijhgemstatushis() {
        return this.bijhgemstatushis;
    }

    public void setBijhgemstatushis(final String bijhgemstatushis) {
        this.bijhgemstatushis = bijhgemstatushis;
    }

    public String getGeslachtsaandstatushis() {
        return this.geslachtsaandstatushis;
    }

    public void setGeslachtsaandstatushis(final String geslachtsaandstatushis) {
        this.geslachtsaandstatushis = geslachtsaandstatushis;
    }

    public Integer getBsn() {
        return this.bsn;
    }

    public void setBsn(final Integer bsn) {
        this.bsn = bsn;
    }

    public Long getAnr() {
        return this.anr;
    }

    public void setAnr(final Long anr) {
        this.anr = anr;
    }

    public String getIdsstatushis() {
        return this.idsstatushis;
    }

    public void setIdsstatushis(final String idsstatushis) {
        this.idsstatushis = idsstatushis;
    }

    public Date getTijdstiplaatstewijz() {
        return this.tijdstiplaatstewijz;
    }

    public void setTijdstiplaatstewijz(final Date tijdstiplaatstewijz) {
        this.tijdstiplaatstewijz = tijdstiplaatstewijz;
    }

    public Boolean getIndgegevensinonderzoek() {
        return this.indgegevensinonderzoek;
    }

    public void setIndgegevensinonderzoek(final Boolean indgegevensinonderzoek) {
        this.indgegevensinonderzoek = indgegevensinonderzoek;
    }

    public Boolean getInduitslnlkiesr() {
        return this.induitslnlkiesr;
    }

    public void setInduitslnlkiesr(final Boolean induitslnlkiesr) {
        this.induitslnlkiesr = induitslnlkiesr;
    }

    public Integer getDateindeuitslnlkiesr() {
        return this.dateindeuitslnlkiesr;
    }

    public void setDateindeuitslnlkiesr(final Integer dateindeuitslnlkiesr) {
        this.dateindeuitslnlkiesr = dateindeuitslnlkiesr;
    }

    public String getUitslnlkiesrstatushis() {
        return this.uitslnlkiesrstatushis;
    }

    public void setUitslnlkiesrstatushis(final String uitslnlkiesrstatushis) {
        this.uitslnlkiesrstatushis = uitslnlkiesrstatushis;
    }

    public String getBijhverantwoordelijkheidstat() {
        return this.bijhverantwoordelijkheidstat;
    }

    public void setBijhverantwoordelijkheidstat(final String bijhverantwoordelijkheidstat) {
        this.bijhverantwoordelijkheidstat = bijhverantwoordelijkheidstat;
    }

}
