/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * Persreisdoc generated by hbm2java
 */
public class Persreisdoc  implements java.io.Serializable {


     private int id;
     private Srtnlreisdoc srtnlreisdoc;
     private Pers pers;
     private Rdnvervallenreisdoc rdnvervallenreisdoc;
     private Autvanafgiftereisdoc autvanafgiftereisdoc;
     private String nr;
     private Integer datingangdoc;
     private Integer datuitgifte;
     private Integer datvoorzeeindegel;
     private Integer datinhingvermissing;
     private Short lengtehouder;
     private String persreisdocstatushis = StatusHis.A.name();

    public Persreisdoc() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }
    public Srtnlreisdoc getSrtnlreisdoc() {
        return this.srtnlreisdoc;
    }

    public void setSrtnlreisdoc(final Srtnlreisdoc srtnlreisdoc) {
        this.srtnlreisdoc = srtnlreisdoc;
    }
    public Pers getPers() {
        return this.pers;
    }

    public void setPers(final Pers pers) {
        this.pers = pers;
    }
    public Rdnvervallenreisdoc getRdnvervallenreisdoc() {
        return this.rdnvervallenreisdoc;
    }

    public void setRdnvervallenreisdoc(final Rdnvervallenreisdoc rdnvervallenreisdoc) {
        this.rdnvervallenreisdoc = rdnvervallenreisdoc;
    }
    public Autvanafgiftereisdoc getAutvanafgiftereisdoc() {
        return this.autvanafgiftereisdoc;
    }

    public void setAutvanafgiftereisdoc(final Autvanafgiftereisdoc autvanafgiftereisdoc) {
        this.autvanafgiftereisdoc = autvanafgiftereisdoc;
    }
    public String getNr() {
        return this.nr;
    }

    public void setNr(final String nr) {
        this.nr = nr;
    }
    public Integer getDatingangdoc() {
        return this.datingangdoc;
    }

    public void setDatingangdoc(final Integer datingangdoc) {
        this.datingangdoc = datingangdoc;
    }
    public Integer getDatuitgifte() {
        return this.datuitgifte;
    }

    public void setDatuitgifte(final Integer datuitgifte) {
        this.datuitgifte = datuitgifte;
    }
    public Integer getDatvoorzeeindegel() {
        return this.datvoorzeeindegel;
    }

    public void setDatvoorzeeindegel(final Integer datvoorzeeindegel) {
        this.datvoorzeeindegel = datvoorzeeindegel;
    }
    public Integer getDatinhingvermissing() {
        return this.datinhingvermissing;
    }

    public void setDatinhingvermissing(final Integer datinhingvermissing) {
        this.datinhingvermissing = datinhingvermissing;
    }
    public Short getLengtehouder() {
        return this.lengtehouder;
    }

    public void setLengtehouder(final Short lengtehouder) {
        this.lengtehouder = lengtehouder;
    }
    public String getPersreisdocstatushis() {
        return this.persreisdocstatushis;
    }

    public void setPersreisdocstatushis(final String persreisdocstatushis) {
        this.persreisdocstatushis = persreisdocstatushis;
    }




}


