/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;

// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA

/**
 * Relatie generated by hbm2java
 */
public class Relatie implements java.io.Serializable {

    private int              id;
    private Srtrelatie       srtrelatie;
    private Plaats           plaatsByWplaanv;
    private Partij           partijByGemeinde;
    private Plaats           plaatsByWpleinde;
    private Rdnbeeindrelatie rdnbeeindrelatie;
    private Partij           partijByGemaanv;
    private Land             landByLandaanv;
    private Land             landByLandeinde;
    private Integer          dataanv;
    private String           blplaatsaanv;
    private String           blregioaanv;
    private String           omslocaanv;
    private Integer          dateinde;
    private String           blplaatseinde;
    private String           blregioeinde;
    private String           omsloceinde;
    private String        relatiestatushis = StatusHis.A.name();

    public Relatie() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public Srtrelatie getSrtrelatie() {
        return this.srtrelatie;
    }

    public void setSrtrelatie(final Srtrelatie srtrelatie) {
        this.srtrelatie = srtrelatie;
    }

    public Plaats getPlaatsByWplaanv() {
        return this.plaatsByWplaanv;
    }

    public void setPlaatsByWplaanv(final Plaats plaatsByWplaanv) {
        this.plaatsByWplaanv = plaatsByWplaanv;
    }

    public Partij getPartijByGemeinde() {
        return this.partijByGemeinde;
    }

    public void setPartijByGemeinde(final Partij partijByGemeinde) {
        this.partijByGemeinde = partijByGemeinde;
    }

    public Plaats getPlaatsByWpleinde() {
        return this.plaatsByWpleinde;
    }

    public void setPlaatsByWpleinde(final Plaats plaatsByWpleinde) {
        this.plaatsByWpleinde = plaatsByWpleinde;
    }

    public Rdnbeeindrelatie getRdnbeeindrelatie() {
        return this.rdnbeeindrelatie;
    }

    public void setRdnbeeindrelatie(final Rdnbeeindrelatie rdnbeeindrelatie) {
        this.rdnbeeindrelatie = rdnbeeindrelatie;
    }

    public Partij getPartijByGemaanv() {
        return this.partijByGemaanv;
    }

    public void setPartijByGemaanv(final Partij partijByGemaanv) {
        this.partijByGemaanv = partijByGemaanv;
    }

    public Land getLandByLandaanv() {
        return this.landByLandaanv;
    }

    public void setLandByLandaanv(final Land landByLandaanv) {
        this.landByLandaanv = landByLandaanv;
    }

    public Land getLandByLandeinde() {
        return this.landByLandeinde;
    }

    public void setLandByLandeinde(final Land landByLandeinde) {
        this.landByLandeinde = landByLandeinde;
    }

    public Integer getDataanv() {
        return this.dataanv;
    }

    public void setDataanv(final Integer dataanv) {
        this.dataanv = dataanv;
    }

    public String getBlplaatsaanv() {
        return this.blplaatsaanv;
    }

    public void setBlplaatsaanv(final String blplaatsaanv) {
        this.blplaatsaanv = blplaatsaanv;
    }

    public String getBlregioaanv() {
        return this.blregioaanv;
    }

    public void setBlregioaanv(final String blregioaanv) {
        this.blregioaanv = blregioaanv;
    }

    public String getOmslocaanv() {
        return this.omslocaanv;
    }

    public void setOmslocaanv(final String omslocaanv) {
        this.omslocaanv = omslocaanv;
    }

    public Integer getDateinde() {
        return this.dateinde;
    }

    public void setDateinde(final Integer dateinde) {
        this.dateinde = dateinde;
    }

    public String getBlplaatseinde() {
        return this.blplaatseinde;
    }

    public void setBlplaatseinde(final String blplaatseinde) {
        this.blplaatseinde = blplaatseinde;
    }

    public String getBlregioeinde() {
        return this.blregioeinde;
    }

    public void setBlregioeinde(final String blregioeinde) {
        this.blregioeinde = blregioeinde;
    }

    public String getOmsloceinde() {
        return this.omsloceinde;
    }

    public void setOmsloceinde(final String omsloceinde) {
        this.omsloceinde = omsloceinde;
    }

    public String getRelatiestatushis() {
        return this.relatiestatushis;
    }

    public void setRelatiestatushis(final String relatiestatushis) {
        this.relatiestatushis = relatiestatushis;
    }

}
