
DROP INDEX IF EXISTS "autaut"."ix_bijhouderfiatuitz_bijhouder" ;        -- CREATE INDEX ix_bijhouderfiatuitz_bijhouder ON autaut.bijhouderfiatuitz USING btree (bijhouder);
DROP INDEX IF EXISTS "autaut"."ix_bijhouderfiatuitz_bijhouderbijhvoorstel" ;        -- CREATE INDEX ix_bijhouderfiatuitz_bijhouderbijhvoorstel ON autaut.bijhouderfiatuitz USING btree (bijhouderbijhvoorstel);
DROP INDEX IF EXISTS "autaut"."ix_dienst_dienstbundel" ;        -- CREATE INDEX ix_dienst_dienstbundel ON autaut.dienst USING btree (dienstbundel);
DROP INDEX IF EXISTS "autaut"."ix_dienstbundel_levsautorisatie" ;        -- CREATE INDEX ix_dienstbundel_levsautorisatie ON autaut.dienstbundel USING btree (levsautorisatie);
DROP INDEX IF EXISTS "autaut"."ix_his_bijhouderfiatuitz_bijhouderbijhvoorstel" ;        -- CREATE INDEX ix_his_bijhouderfiatuitz_bijhouderbijhvoorstel ON autaut.his_bijhouderfiatuitz USING btree (bijhouderbijhvoorstel);
DROP INDEX IF EXISTS "autaut"."ix_his_persafnemerindicatie_tsreg_tsverval" ;        -- CREATE INDEX ix_his_persafnemerindicatie_tsreg_tsverval ON autaut.his_persafnemerindicatie USING btree (tsreg, tsverval);
DROP INDEX IF EXISTS "autaut"."ix_persafnemerindicatie_afnemer" ;        -- CREATE INDEX ix_persafnemerindicatie_afnemer ON autaut.persafnemerindicatie USING btree (afnemer);
DROP INDEX IF EXISTS "autaut"."ix_persafnemerindicatie_levsautorisatie" ;        -- CREATE INDEX ix_persafnemerindicatie_levsautorisatie ON autaut.persafnemerindicatie USING btree (levsautorisatie);
DROP INDEX IF EXISTS "autaut"."ix_toegangbijhautorisatie_ondertekenaar" ;        -- CREATE INDEX ix_toegangbijhautorisatie_ondertekenaar ON autaut.toegangbijhautorisatie USING btree (ondertekenaar);
DROP INDEX IF EXISTS "autaut"."ix_toegangbijhautorisatie_transporteur" ;        -- CREATE INDEX ix_toegangbijhautorisatie_transporteur ON autaut.toegangbijhautorisatie USING btree (transporteur);
DROP INDEX IF EXISTS "autaut"."ix_toeganglevsautorisatie_levsautorisatie" ;        -- CREATE INDEX ix_toeganglevsautorisatie_levsautorisatie ON autaut.toeganglevsautorisatie USING btree (levsautorisatie);
DROP INDEX IF EXISTS "autaut"."ix_toeganglevsautorisatie_ondertekenaar" ;        -- CREATE INDEX ix_toeganglevsautorisatie_ondertekenaar ON autaut.toeganglevsautorisatie USING btree (ondertekenaar);
DROP INDEX IF EXISTS "autaut"."ix_toeganglevsautorisatie_transporteur" ;        -- CREATE INDEX ix_toeganglevsautorisatie_transporteur ON autaut.toeganglevsautorisatie USING btree (transporteur);
DROP INDEX IF EXISTS "ber"."ix_ber_admhnd" ;        -- CREATE INDEX ix_ber_admhnd ON ber.ber USING btree (admhnd);
DROP INDEX IF EXISTS "ber"."ix_ber_antwoordop" ;        -- CREATE INDEX ix_ber_antwoordop ON ber.ber USING btree (antwoordop);
DROP INDEX IF EXISTS "ber"."ix_ber_dienst" ;        -- CREATE INDEX ix_ber_dienst ON ber.ber USING btree (dienst);
DROP INDEX IF EXISTS "ber"."ix_ber_levsautorisatie" ;        -- CREATE INDEX ix_ber_levsautorisatie ON ber.ber USING btree (levsautorisatie);
DROP INDEX IF EXISTS "ber"."ix_ber_ontvangendepartij" ;        -- CREATE INDEX ix_ber_ontvangendepartij ON ber.ber USING btree (ontvangendepartij);
DROP INDEX IF EXISTS "ber"."ix_ber_referentienr" ;        -- CREATE INDEX ix_ber_referentienr ON ber.ber USING btree (referentienr);
DROP INDEX IF EXISTS "ber"."ix_ber_referentienru" ;        -- CREATE INDEX ix_ber_referentienru ON ber.ber USING btree (upper((referentienr)::text));
DROP INDEX IF EXISTS "ber"."ix_ber_tsontv" ;        -- CREATE INDEX ix_ber_tsontv ON ber.ber USING btree (tsontv);
DROP INDEX IF EXISTS "ber"."ix_ber_tsverzending" ;        -- CREATE INDEX ix_ber_tsverzending ON ber.ber USING btree (tsverzending);
DROP INDEX IF EXISTS "ber"."ix_ber_zendendepartij" ;        -- CREATE INDEX ix_ber_zendendepartij ON ber.ber USING btree (zendendepartij);
DROP INDEX IF EXISTS "ber"."ix_berpers_ber" ;        -- CREATE INDEX ix_berpers_ber ON ber.berpers USING btree (ber);
DROP INDEX IF EXISTS "ber"."ix_berpers_pers" ;        -- CREATE INDEX ix_berpers_pers ON ber.berpers USING btree (pers);
DROP INDEX IF EXISTS "ist"."ix_stapelrelatie_relatie" ;        -- CREATE INDEX ix_stapelrelatie_relatie ON ist.stapelrelatie USING btree (relatie);
DROP INDEX IF EXISTS "ist"."ix_stapelvoorkomen_admhnd" ;        -- CREATE INDEX ix_stapelvoorkomen_admhnd ON ist.stapelvoorkomen USING btree (admhnd);
DROP INDEX IF EXISTS "ist"."ix_stapelvoorkomen_partij" ;        -- CREATE INDEX ix_stapelvoorkomen_partij ON ist.stapelvoorkomen USING btree (partij);
DROP INDEX IF EXISTS "kern"."ix_actie_admhnd" ;        -- CREATE INDEX ix_actie_admhnd ON kern.actie USING btree (admhnd);
DROP INDEX IF EXISTS "kern"."ix_actiebron_doc" ;        -- CREATE INDEX ix_actiebron_doc ON kern.actiebron USING btree (doc);
DROP INDEX IF EXISTS "kern"."ix_admhnd_tslev" ;        -- CREATE INDEX ix_admhnd_tslev ON kern.admhnd USING btree (tslev);
DROP INDEX IF EXISTS "kern"."ix_admhnd_tsreg" ;        -- CREATE INDEX ix_admhnd_tsreg ON kern.admhnd USING btree (tsreg);
DROP INDEX IF EXISTS "kern"."ix_admhndgedeblokkeerderegel_admhnd" ;        -- CREATE INDEX ix_admhndgedeblokkeerderegel_admhnd ON kern.admhndgedeblokkeerderegel USING btree (admhnd);
DROP INDEX IF EXISTS "kern"."ix_betr_pers" ;        -- CREATE INDEX ix_betr_pers ON kern.betr USING btree (pers);
DROP INDEX IF EXISTS "kern"."ix_betr_relatie" ;        -- CREATE INDEX ix_betr_relatie ON kern.betr USING btree (relatie);
DROP INDEX IF EXISTS "kern"."ix_gegeveninonderzoek_onderzoek" ;        -- CREATE INDEX ix_gegeveninonderzoek_onderzoek ON kern.gegeveninonderzoek USING btree (onderzoek);
DROP INDEX IF EXISTS "kern"."uc_his_onderzoek_onderzoek_tsreg" ;        -- CREATE INDEX uc_his_onderzoek_onderzoek_tsreg ON kern.his_onderzoek USING btree (onderzoek, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_ouderouderlijkgezag_betr_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_ouderouderlijkgezag_betr_tsreg_dataanvgel ON kern.his_ouderouderlijkgezag USING btree (betr, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_ouderouderschap_betr_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_ouderouderschap_betr_tsreg_dataanvgel ON kern.his_ouderouderschap USING btree (betr, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persadres_persadres_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persadres_persadres_tsreg_dataanvgel ON kern.his_persadres USING btree (persadres, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."ix_his_persafgeleidadministrati_admhnd" ;        -- CREATE INDEX ix_his_persafgeleidadministrati_admhnd ON kern.his_persafgeleidadministrati USING btree (admhnd);
DROP INDEX IF EXISTS "kern"."uc_his_persafgeleidadministrati_pers_tsreg" ;        -- CREATE INDEX uc_his_persafgeleidadministrati_pers_tsreg ON kern.his_persafgeleidadministrati USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persbijhouding_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persbijhouding_pers_tsreg_dataanvgel ON kern.his_persbijhouding USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persdeelneuverkiezingen_pers_tsreg" ;        -- CREATE INDEX uc_his_persdeelneuverkiezingen_pers_tsreg ON kern.his_persdeelneuverkiezingen USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persgeboorte_pers_tsreg" ;        -- CREATE INDEX uc_his_persgeboorte_pers_tsreg ON kern.his_persgeboorte USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persgeslachtsaand_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persgeslachtsaand_pers_tsreg_dataanvgel ON kern.his_persgeslachtsaand USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persgeslnaamcomp_persgeslnaamcomp_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persgeslnaamcomp_persgeslnaamcomp_tsreg_dataanvgel ON kern.his_persgeslnaamcomp USING btree (persgeslnaamcomp, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."ix_his_persids_anr" ;        -- CREATE INDEX ix_his_persids_anr ON kern.his_persids USING btree (anr);
DROP INDEX IF EXISTS "kern"."ix_his_persids_bsn" ;        -- CREATE INDEX ix_his_persids_bsn ON kern.his_persids USING btree (bsn);
DROP INDEX IF EXISTS "kern"."uc_his_persids_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persids_pers_tsreg_dataanvgel ON kern.his_persids USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persindicatie_persindicatie_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persindicatie_persindicatie_tsreg_dataanvgel ON kern.his_persindicatie USING btree (persindicatie, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persinschr_pers_tsreg" ;        -- CREATE INDEX uc_his_persinschr_pers_tsreg ON kern.his_persinschr USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persmigratie_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persmigratie_pers_tsreg_dataanvgel ON kern.his_persmigratie USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persnaamgebruik_pers_tsreg" ;        -- CREATE INDEX uc_his_persnaamgebruik_pers_tsreg ON kern.his_persnaamgebruik USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persnation_persnation_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persnation_persnation_tsreg_dataanvgel ON kern.his_persnation USING btree (persnation, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persnrverwijzing_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persnrverwijzing_pers_tsreg_dataanvgel ON kern.his_persnrverwijzing USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persoverlijden_pers_tsreg" ;        -- CREATE INDEX uc_his_persoverlijden_pers_tsreg ON kern.his_persoverlijden USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_perspk_pers_tsreg" ;        -- CREATE INDEX uc_his_perspk_pers_tsreg ON kern.his_perspk USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persreisdoc_persreisdoc_tsreg" ;        -- CREATE INDEX uc_his_persreisdoc_persreisdoc_tsreg ON kern.his_persreisdoc USING btree (persreisdoc, tsreg);
DROP INDEX IF EXISTS "kern"."ix_his_perssamengesteldenaam_geslnaamstamu" ;        -- CREATE INDEX ix_his_perssamengesteldenaam_geslnaamstamu ON kern.his_perssamengesteldenaam USING btree (upper((geslnaamstam)::text));
DROP INDEX IF EXISTS "kern"."uc_his_perssamengesteldenaam_pers_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_perssamengesteldenaam_pers_tsreg_dataanvgel ON kern.his_perssamengesteldenaam USING btree (pers, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_persuitslkiesr_pers_tsreg" ;        -- CREATE INDEX uc_his_persuitslkiesr_pers_tsreg ON kern.his_persuitslkiesr USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persverblijfsr_pers_tsreg" ;        -- CREATE INDEX uc_his_persverblijfsr_pers_tsreg ON kern.his_persverblijfsr USING btree (pers, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persverificatie_persverificatie_tsreg" ;        -- CREATE INDEX uc_his_persverificatie_persverificatie_tsreg ON kern.his_persverificatie USING btree (persverificatie, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persverstrbeperking_persverstrbeperking_tsreg" ;        -- CREATE INDEX uc_his_persverstrbeperking_persverstrbeperking_tsreg ON kern.his_persverstrbeperking USING btree (persverstrbeperking, tsreg);
DROP INDEX IF EXISTS "kern"."uc_his_persvoornaam_persvoornaam_tsreg_dataanvgel" ;        -- CREATE INDEX uc_his_persvoornaam_persvoornaam_tsreg_dataanvgel ON kern.his_persvoornaam USING btree (persvoornaam, tsreg, dataanvgel);
DROP INDEX IF EXISTS "kern"."uc_his_relatie_relatie_tsreg" ;        -- CREATE INDEX uc_his_relatie_relatie_tsreg ON kern.his_relatie USING btree (relatie, tsreg);
DROP INDEX IF EXISTS "kern"."ix_partij_oin" ;        -- CREATE INDEX ix_partij_oin ON kern.partij USING btree (oin);
DROP INDEX IF EXISTS "kern"."ix_pers_admhnd" ;        -- CREATE INDEX ix_pers_admhnd ON kern.pers USING btree (admhnd);
DROP INDEX IF EXISTS "kern"."ix_pers_anr" ;        -- CREATE INDEX ix_pers_anr ON kern.pers USING btree (anr);
DROP INDEX IF EXISTS "kern"."ix_pers_bsn" ;        -- CREATE INDEX ix_pers_bsn ON kern.pers USING btree (bsn);
DROP INDEX IF EXISTS "kern"."ix_pers_geslnaamstamu" ;        -- CREATE INDEX ix_pers_geslnaamstamu ON kern.pers USING btree (upper((geslnaamstam)::text));
DROP INDEX IF EXISTS "kern"."uc_pers_anr" ;        -- CREATE UNIQUE INDEX uc_pers_anr ON kern.pers USING btree (anr) WHERE ((srt = 1) AND (naderebijhaard <> ALL (ARRAY[7, 8])));
DROP INDEX IF EXISTS "kern"."ix_persadres_gem_nor_huisnr_huisletter_huisnrtoevoeging_srtu" ;        -- CREATE INDEX ix_persadres_gem_nor_huisnr_huisletter_huisnrtoevoeging_srtu ON kern.persadres USING btree (gem, upper((nor)::text), huisnr, upper((huisletter)::text), upper((huisnrtoevoeging)::text), srt);
DROP INDEX IF EXISTS "kern"."ix_persadres_identcodenraand" ;        -- CREATE INDEX ix_persadres_identcodenraand ON kern.persadres USING btree (identcodenraand);
DROP INDEX IF EXISTS "kern"."ix_persadres_pers" ;        -- CREATE INDEX ix_persadres_pers ON kern.persadres USING btree (pers);
DROP INDEX IF EXISTS "kern"."ix_persadres_postcode_huisnr_huisletter_huisnrtoevoeging_srtu" ;        -- CREATE INDEX ix_persadres_postcode_huisnr_huisletter_huisnrtoevoeging_srtu ON kern.persadres USING btree (upper((postcode)::text), huisnr, upper((huisletter)::text), upper((huisnrtoevoeging)::text), srt);
DROP INDEX IF EXISTS "kern"."ix_perscache_pers" ;        -- CREATE INDEX ix_perscache_pers ON kern.perscache USING btree (pers);
DROP INDEX IF EXISTS "kern"."ix_persreisdoc_pers" ;        -- CREATE INDEX ix_persreisdoc_pers ON kern.persreisdoc USING btree (pers);
DROP INDEX IF EXISTS "kern"."ix_persverificatie_geverifieerde" ;        -- CREATE INDEX ix_persverificatie_geverifieerde ON kern.persverificatie USING btree (geverifieerde);
DROP INDEX IF EXISTS "prot"."ix_levsaantek_admhnd" ;        -- CREATE INDEX ix_levsaantek_admhnd ON prot.levsaantek USING btree (admhnd);
DROP INDEX IF EXISTS "prot"."ix_levsaantek_dienst" ;        -- CREATE INDEX ix_levsaantek_dienst ON prot.levsaantek USING btree (dienst);
DROP INDEX IF EXISTS "prot"."ix_levsaantek_toeganglevsautorisatie" ;        -- CREATE INDEX ix_levsaantek_toeganglevsautorisatie ON prot.levsaantek USING btree (toeganglevsautorisatie);
DROP INDEX IF EXISTS "prot"."ix_levsaantekpers_pers" ;        -- CREATE INDEX ix_levsaantekpers_pers ON prot.levsaantekpers USING btree (pers);
DROP INDEX IF EXISTS "verconv"."ix_lo3ber_anr" ;        -- CREATE INDEX ix_lo3ber_anr ON verconv.lo3ber USING btree (anr);
DROP INDEX IF EXISTS "verconv"."ix_lo3ber_pers" ;        -- CREATE INDEX ix_lo3ber_pers ON verconv.lo3ber USING btree (pers);


