/**
 * This file is copyright 2017 State of the Netherlands (Ministry of Interior Affairs and Kingdom Relations).
 * It is made available under the terms of the GNU Affero General Public License, version 3 as published by the Free Software Foundation.
 * The project of which this file is part, may be found at https://github.com/MinBZK/operatieBRP.
 */

package nl.bzk.brp.testdatageneratie.domain.kern;
// Generated 12-sep-2012 11:17:43 by Hibernate Tools 3.2.4.GA



/**
 * HisPersgeslnaamcomp generated by hbm2java
 */
public class HisPersgeslnaamcomp extends His {


     private Predikaat predikaat;
     private Actie actieByActieaanpgel;
     private Persgeslnaamcomp persgeslnaamcomp;
     private Adellijketitel adellijketitel;
     private String voorvoegsel;
     private String scheidingsteken;
     private String naam;

    public HisPersgeslnaamcomp() {
    }

    public HisPersgeslnaamcomp(final Persgeslnaamcomp familienaam) {
        persgeslnaamcomp = familienaam;
        predikaat = familienaam.getPredikaat();
        adellijketitel = familienaam.getAdellijketitel();
        setDataanvgel(familienaam.getPers().getDatinschr());
        voorvoegsel = familienaam.getVoorvoegsel();
        scheidingsteken = familienaam.getScheidingsteken();
        naam = familienaam.getNaam();
    }

    public Predikaat getPredikaat() {
        return this.predikaat;
    }

    public void setPredikaat(final Predikaat predikaat) {
        this.predikaat = predikaat;
    }
    public Actie getActieByActieaanpgel() {
        return this.actieByActieaanpgel;
    }

    public void setActieByActieaanpgel(final Actie actieByActieaanpgel) {
        this.actieByActieaanpgel = actieByActieaanpgel;
    }
    public Persgeslnaamcomp getPersgeslnaamcomp() {
        return this.persgeslnaamcomp;
    }

    public void setPersgeslnaamcomp(final Persgeslnaamcomp persgeslnaamcomp) {
        this.persgeslnaamcomp = persgeslnaamcomp;
    }
    public Adellijketitel getAdellijketitel() {
        return this.adellijketitel;
    }

    public void setAdellijketitel(final Adellijketitel adellijketitel) {
        this.adellijketitel = adellijketitel;
    }
    public String getVoorvoegsel() {
        return this.voorvoegsel;
    }

    public void setVoorvoegsel(final String voorvoegsel) {
        this.voorvoegsel = voorvoegsel;
    }
    public String getScheidingsteken() {
        return this.scheidingsteken;
    }

    public void setScheidingsteken(final String scheidingsteken) {
        this.scheidingsteken = scheidingsteken;
    }
    public String getNaam() {
        return this.naam;
    }

    public void setNaam(final String naam) {
        this.naam = naam;
    }




}


