#!/bin/bash
echo Content-type: text/plain

. ./env
. ./functions

echo ""

export PGPASSWORD="${GBAV_DB_PASSWORD}"
psql -h ${GBAV_DB_HOST} ${GBAV_DB_NAME} --user ${GBAV_DB_USER} -c 'TRUNCATE TABLE lo3_bericht CASCADE'
psql -h ${GBAV_DB_HOST} ${GBAV_DB_NAME} --user ${GBAV_DB_USER} -c 'TRUNCATE TABLE lo3_pl_persoon CASCADE'
psql -h ${GBAV_DB_HOST} ${GBAV_DB_NAME} --user ${GBAV_DB_USER} -c 'TRUNCATE TABLE lo3_pl CASCADE'
psql -h ${GBAV_DB_HOST} ${GBAV_DB_NAME} --user ${GBAV_DB_USER} -c 'TRUNCATE TABLE lo3_pl_afnemer_ind CASCADE'
