#!/bin/bash
echo Content-type: application/json
echo ""

dat=`date`;

. ./env
. ./functions

i=0;
echo "{";

. ./files
log=`rm -v ${EXPECTED_FILE} 2>&1`;

echo "\"status\" : \"ok\", ";
echo "\"log\" : \"${dat} ${log}\"";

echo "}";
compare ${anr} > ${RESULTS_LOCATION}/${anr}.json
