#!/bin/bash
echo "Content-type: text/plain; charset=UTF-8"
echo ""

if [ "${1}" != "" ];
then
	stage=${1};
fi

. ./env
. ./functions

ums=$( find ${PL_LOCATION} -type d -name U\* );

next_upload;

echo "Maak locatie aan ${PL_LOCATION}/${stage}";
loc="${PL_LOCATION}/${stage}";

mkdir -p ${loc}/GBA;
mkdir -p ${loc}/BRP;

for i in ${UPLOAD_LOCATION}/*xml;
do
	if [ -e ${i} ];
	then
		mv -v ${UPLOAD_LOCATION}/*xml ${loc}/BRP;
	fi
done

for i in ${UPLOAD_LOCATION}/*xls;
do
	if [ -e ${i} ];
	then
		mv -v ${UPLOAD_LOCATION}/*xls ${loc}/GBA;
		cp "${TESTCASE_PROPERTIES_LOCATION}" ${loc}/GBA;
	fi
done

for i in ${UPLOAD_LOCATION}/*csv;
do
	if [ -e ${i} ];
	then
		${CSV_TO_XLS} ${i} ${loc}/GBA
		cp "${TESTCASE_PROPERTIES_LOCATION}" ${loc}/GBA;
		rm -v ${i};
	fi
done

# bepaal max id voor bepalen welke berichten bij deze stage hoort
export PGPASSWORD=${MIGR_DB_PASSWORD};
max=$( psql -A -h ${VOISC_DB_HOST} -U ${MIGR_DB_USER} -d ${VOISC_DB_NAME} -p ${VOISC_DB_PORT} -t -S -c 'select max(id) from voisc.bericht' );

bash ./run_gba "${stage}" "${loc}/GBA" "${UPLOAD_BSN_LIST_FILE}" &
bash ./run_brp "${stage}" "${loc}/BRP" "${UPLOAD_BSN_LIST_FILE}" &

wait;

TIMEOUT=-1;
num=0;
while [ ${TIMEOUT} -ne 0 ];
do
	. ./check_stage_finished ${stage} ${num};
	num=$(( num + 1 ));
done

bash ./run_all "${stage}" "SQL" "${UPLOAD_BSN_LIST_FILE}" &
bash ./fill_actual_brp "${stage}" "${UPLOAD_BSN_LIST_FILE}" &
bash ./fill_actual_voisc "${stage}" "${UPLOAD_BSN_LIST_FILE}" "${max}" &

wait;

for i in GBA BRP;
do
	bash ./run_all "${stage}" "${i}" "${UPLOAD_BSN_LIST_FILE}" &
done

wait;

bash ./merge_results "upload";
