#!/bin/bash

if [ "${stage}" == "TC" ];
then
	ACTUAL_FILE="${ACTUAL_LOCATION}/TC_${script}_${anr}.GBA";
	EXPECTED_FILE="${EXPECTED_LOCATION}/TC_${script}_${anr}.GBA";
elif [ "${flavour}" == "GBA" ];
then
	ACTUAL_FILE="${ACTUAL_LOCATION}/LO3_${script}_${bn}_${anr}_${afn}.GBA";
	EXPECTED_FILE="${EXPECTED_LOCATION}/LO3_${script}_${bn}_${anr}_${afn}.GBA";
elif [ "${flavour}" == "BRP" ];
then
	ACTUAL_FILE="${ACTUAL_LOCATION}/BRP_${volgnr}_${berichttype}_${anr}_${afn}_${script}.xml";
	EXPECTED_FILE="${EXPECTED_LOCATION}/BRP_${volgnr}_${berichttype}_${anr}_${afn}_${script}.xml";
elif [ "${flavour}" == "RESBIJ" ];
then
	ACTUAL_FILE="${ACTUAL_LOCATION}/RESBIJ_${volgnr}_${berichttype}_${anr}_${script}.xml";
	EXPECTED_FILE="${EXPECTED_LOCATION}/RESBIJ_${volgnr}_${berichttype}_${anr}_${script}.xml";
elif [ "${flavour}" == "RESBEV" ];
then
	ACTUAL_FILE="${ACTUAL_LOCATION}/RESBEV_${volgnr}_${berichttype}_${anr}_${script}.xml";
	EXPECTED_FILE="${EXPECTED_LOCATION}/RESBEV_${volgnr}_${berichttype}_${anr}_${script}.xml";
else
	ACTUAL_FILE="${ACTUAL_LOCATION}/${script}_${anr}.csv";
	EXPECTED_FILE="${EXPECTED_LOCATION}/${script}_${anr}.csv";
fi
