#!/bin/bash
echo Content-type: application/json;
echo "";

. ./env

echo "[";

if [ "${type}" == "GBA" ];
then
	list=${GBA_CONTROLE_LOCATION}/*.txt;	
elif [ "${type}" == "BRP" ];
then
	list=${BRP_CONTROLE_LOCATION}/*.xsl;	

elif [ "${type}" == "SQL" ];
then
	list=${SQL_CONTROLE_LOCATION}/*.sql;	
fi

count=0;	
for i in ${list};
do
	basename=$( basename "${i}" );

        if [ $count -gt 0 ];
        then
                echo ",";
        fi

        echo "\"${basename}\"";
        count=$(( count + 1 ));
done
echo "]";
