#!/bin/bash

. ./env

>${BSN_LIST_FILE}
>${OTHER_BSN_LIST_FILE}
>${PLACEHOLDER_LIST_FILE}
rm ${RESULTS_LOCATION}/* 2> /dev/null;
rm ${BACKUP_LOCATION}/* 2> /dev/null
rm -r ${STAGES_LOCATION}/*/*/actual;
rm -r ${STAGES_LOCATION}/*/*/raw;
rm -r ${STAGES_LOCATION}/*/*/old;
rm -r ${STAGES_LOCATION}/*/*/tmp;
rm -r ${PL_LOCATION}/U*;
rm -r ${PL_LOCATION}/AI_U*;
rm -r ${STAGES_LOCATION}/U* ;

. ./config
