#!/bin/bash
echo Content-type: text/plain
echo

. ./env
. ./functions

POST_DATA=$(</dev/stdin)
echo "${POST_DATA}" > ${LEVSAUT_CONVERT_FILES}/autorisaties.txt

group="";
subgroup="";
group_set=0;
sub_group_set=0;
check_srt=0;

>${LEVSAUT_CONVERT_FILES}/output.txt
for i in `cat ${LEVSAUT_CONVERT_FILES}/autorisaties.txt | tr ' ' '_' | tr '	' '#'` ;
do
	e=`echo $i | awk -F '_' '{print $1; for (i=2; i<=NF; i++) print toupper(substr($i,1,1)) substr($i,2);}'`;
	e=$( echo $e | tr -d ' ' );

	ext=$( echo $i | awk -F '#' '{print $6}' );
	allowed=$( echo $i | awk -F '#' '{print $7}' );

	case "${ext}" in 
		"G")
			ext="/V"
			;;
		"B")
			ext="/M"
			;;
		"F")
			ext="/F"
			;;
		*)
			ext="";
			;;
	esac

	if [ $( echo $e | head -c 1 ) != "#" ];
	then
		if [ "${allowed}" == "" ];
		then
			allowed="J";
		fi
	fi

	if [ "${allowed}" == "J" ];
	then
		if [ $( echo $e | head -c 1 ) == "#" ];
		then
			element=`echo $e | awk -F '#' '{print $2}'`;
			if [ "${element}" != "" ];
			then
				out=$( grep -e "${group}.${subgroup}.${element};" ${LEVSAUT_CONVERT_FILES}/elementen.txt );
				out_arr=(${out//;/ });
				if [ "${out}" == "" ];
				then
					pre="**";
				else
					if [ "${out_arr[1]}" == "3" ];
					then
						pre="";
					else
						pre="***";
					fi
				fi

				echo ${pre}${group}.${subgroup}.${element}${ext} >> ${LEVSAUT_CONVERT_FILES}/output.txt
			fi

			sub_group_set=0;
		else
			arr=(${e//#/ });
			if [ $group_set -eq 0 ];
			then
				group=${arr[0]};
				group_set=1;
			else
				if [ $sub_group_set -eq 1 ];
				then
					group=$subgroup;
				fi

				subgroup=${arr[0]};
				sub_group_set=1;

				out=$( grep -e "${group}.${subgroup};" ${LEVSAUT_CONVERT_FILES}/elementen.txt );
				out_arr=(${out//;/ });
				if [ "${out}" == "" ];
				then
					pre="**";
				else
					if [ "${out_arr[1]}" == "2" ];
					then
						pre="";
					else
						pre="***";
					fi
				fi

				echo ${pre}${group}.${subgroup}${ext} >> ${LEVSAUT_CONVERT_FILES}/output.txt
			fi
		fi
	fi
done

grep -e "/" ${LEVSAUT_CONVERT_FILES}/output.txt | head -n -1 | sed 's/$/,/'
grep -e "/" ${LEVSAUT_CONVERT_FILES}/output.txt | tail -1 
echo "";
echo "";
grep -v -e "/" ${LEVSAUT_CONVERT_FILES}/output.txt | head -n -1 | sed 's/$/,/'
grep -v -e "/" ${LEVSAUT_CONVERT_FILES}/output.txt | tail -1
