#!/bin/bash
echo Content-type: text/plain
echo

. ./env
. ./functions

if [ ! -d "${OMSCHRIJVING_LOCATION}" ];
then
	rm "${OMSCHRIJVING_LOCATION}";
	mkdir "${OMSCHRIJVING_LOCATION}";
fi

POST_DATA=$(</dev/stdin)
echo "${POST_DATA}" > ${OMSCHRIJVING_LOCATION}/${anr}.txt

echo "";
