#!/bin/bash
echo Content-type: text/plain
echo

. ./env
. ./functions

if [ ! -d "${COMMENTS_LOCATION}" ];
then
	rm "${COMMENTS_LOCATION}";
	mkdir "${COMMENTS_LOCATION}";
fi

POST_DATA=$(</dev/stdin)
echo "${POST_DATA}" > ${COMMENTS_LOCATION}/${anr}.txt

echo "";
