#!/bin/bash
echo Content-type: text/plain
echo

. ./env
. ./functions

mkdir -p ${AFTERBURNER_DB_SCRIPTS};

POST_DATA=$(</dev/stdin)
echo "${POST_DATA}" > ${AFTERBURNER_DB_SCRIPTS}/afterburner.sql

echo "";
