#!/bin/bash

function readParams {
        qparm=(${QUERY_STRING//\&/ });
        secret=(${qparm[0]//=/ });
}

readParams;

export SECRET="9ec6c0642d6e2090b356361c4f1a962a"
export SECRET2=${secret[1]};

if [[ "${SECRET}" != "${SECRET2}" ]];
then
	echo "Status: 401 Fout"
	echo "";
	echo "Fout: verkeerde secret";
	exit 1;
fi

