#!/bin/bash
echo Content-type: application/json

. ./env

echo ""
echo "[";
c=0;
for i in `ls ${SOAP_LOCATION} | grep -v properties`;
do
        if [ $c -gt 0 ];
        then
                echo ", ";
        fi

	echo \"$(basename $i)\";
	c=$(( c + 1 ));
done
echo "]";
