delete from Kern.Nation;
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (1, 0, $$Onbekend$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (2, 1, $$Nederlandse$$ , null , null);
--deze rij wordt genegeerd
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (4, 27, $$Slowaakse$$ , 19930101 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (5, 28, $$Tsjechische$$ , 19930101 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (6, 29, $$Burger van Bosnië-Herzegovina$$ , 19920406 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (7, 30, $$Burger van Georgië$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (8, 31, $$Burger van Toerkmenistan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (9, 32, $$Burger van Tadzjikistan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (10, 33, $$Burger van Oezbekistan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (11, 34, $$Burger van Oekraine$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (12, 35, $$Burger van Kyrgyzstan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (13, 36, $$Burger van Moldavië$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (14, 37, $$Burger van Kazachstan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (15, 38, $$Burger van Belarus (Wit-Rusland)$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (16, 39, $$Burger van Azerbajdsjan$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (17, 40, $$Burger van Armenië$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (18, 41, $$Burger van Rusland$$ , 19911231 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (19, 42, $$Burger van Slovenië$$ , 19920115 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (20, 43, $$Burger van Kroatië$$ , 19920115 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (21, 44, $$Letse$$ , 19910828 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (22, 45, $$Estnische$$ , 19910828 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (23, 46, $$Litouwse$$ , 19910828 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (24, 47, $$Burger van de Marshalleilanden$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (25, 48, $$Myanmarese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (26, 49, $$Namibische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (27, 50, $$Albanese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (28, 51, $$Andorrese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (29, 52, $$Belgische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (30, 53, $$Bulgaarse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (31, 54, $$Deense$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (32, 55, $$Burger van de Bondsrepubliek Duitsland$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (33, 56, $$Finse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (34, 57, $$Franse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (35, 58, $$Jemenitische$$ , 19900522 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (36, 59, $$Griekse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (37, 60, $$Brits burger$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (38, 61, $$Hongaarse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (39, 62, $$Ierse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (40, 63, $$IJslandse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (41, 64, $$Italiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (42, 65, $$Joegoslavische$$ , null , 20040201);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (43, 66, $$Liechtensteinse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (44, 67, $$Luxemburgse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (45, 68, $$Maltese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (46, 69, $$Monegaskische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (47, 70, $$Noorse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (48, 71, $$Oostenrijkse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (49, 72, $$Poolse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (50, 73, $$Portugese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (51, 74, $$Roemeense$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (52, 75, $$Burger Sovjetunie$$ , null , 19911231);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (53, 76, $$Sanmarinese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (54, 77, $$Spaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (55, 78, $$Tsjechoslowaakse$$ , null , 19930101);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (56, 79, $$Vaticaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (57, 80, $$Zweedse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (58, 81, $$Zwitserse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (59, 82, $$Oostduitse$$ , null , 19901003);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (60, 83, $$Brits onderdaan$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (61, 84, $$Eritrese$$ , 19930528 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (62, 85, $$Brits overzees burger$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (63, 86, $$Macedonische$$ , 19930419 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (64, 87, $$Burger van Kosovo$$ , 20080615 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (65, 100, $$Algerijnse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (66, 101, $$Angolese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (67, 104, $$Burundische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (68, 105, $$Botswaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (69, 106, $$Burger van Burkina Faso$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (70, 108, $$Centrafrikaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (71, 109, $$Comorese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (72, 110, $$Kongolese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (73, 111, $$Beninse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (74, 112, $$Egyptische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (75, 113, $$Equatoriaalguinese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (76, 114, $$Etiopische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (77, 115, $$Djiboutiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (78, 116, $$Gabonese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (79, 117, $$Gambiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (80, 118, $$Ghanese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (81, 119, $$Guinese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (82, 120, $$Ivoriaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (83, 121, $$Kaapverdische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (84, 122, $$Kameroense$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (85, 123, $$Kenyaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (86, 124, $$Zaïrese$$ , null , 19970715);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (87, 125, $$Lesothaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (88, 126, $$Liberiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (89, 127, $$Libische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (90, 128, $$Malagassische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (91, 129, $$Malawische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (92, 130, $$Malinese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (93, 131, $$Marokkaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (94, 132, $$Burger van Mauritanië$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (95, 133, $$Burger van Mauritius$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (96, 134, $$Mozambiquaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (97, 135, $$Swazische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (98, 136, $$Burger van Niger$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (99, 137, $$Burger van Nigeria$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (100, 138, $$Ugandese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (101, 139, $$Guineebissause$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (102, 140, $$Zuidafrikaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (103, 142, $$Zimbabwaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (104, 143, $$Rwandese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (105, 144, $$Burger van São Tomé en Principe$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (106, 145, $$Senegalese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (107, 147, $$Sierraleoonse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (108, 148, $$Soedanese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (109, 149, $$Somalische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (110, 151, $$Tanzaniaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (111, 152, $$Togolese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (112, 154, $$Tsjadische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (113, 155, $$Tunesische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (114, 156, $$Zambiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (115, 200, $$Bahamaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (116, 202, $$Belizaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (117, 204, $$Canadese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (118, 205, $$Costaricaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (119, 206, $$Cubaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (120, 207, $$Burger van Dominicaanse Republiek$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (121, 208, $$Salvadoraanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (122, 211, $$Guatemalteekse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (123, 212, $$Haïtiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (124, 213, $$Hondurese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (125, 214, $$Jamaicaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (126, 216, $$Mexicaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (127, 218, $$Nicaraguaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (128, 219, $$Panamese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (129, 222, $$Burger van Trinidad en Tobago$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (130, 223, $$Amerikaans burger$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (131, 250, $$Argentijnse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (132, 251, $$Barbadaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (133, 252, $$Boliviaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (134, 253, $$Braziliaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (135, 254, $$Chileense$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (136, 255, $$Colombiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (137, 256, $$Ecuadoraanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (138, 259, $$Guyaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (139, 261, $$Paraguayaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (140, 262, $$Peruaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (141, 263, $$Surinaamse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (142, 264, $$Uruguayaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (143, 265, $$Venezolaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (144, 267, $$Grenadaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (145, 268, $$Burger van Saint Kitts-Nevis$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (146, 300, $$Afgaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (147, 301, $$Bahreinse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (148, 302, $$Bhutaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (149, 303, $$Burmaanse$$ , null , 19890618);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (150, 304, $$Bruneise$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (151, 305, $$Kambodjaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (152, 306, $$Srilankaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (153, 307, $$Chinese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (154, 308, $$Cyprische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (155, 309, $$Filipijnse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (156, 310, $$Taiwanese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (157, 312, $$Burger van India$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (158, 313, $$Indonesische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (159, 314, $$Iraakse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (160, 315, $$Iraanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (161, 316, $$Israëlische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (162, 317, $$Japanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (163, 318, $$Noordjemenitische$$ , null , 19900522);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (164, 319, $$Jordaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (165, 320, $$Koeweitse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (166, 321, $$Laotiaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (167, 322, $$Libanese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (168, 324, $$Maldivische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (169, 325, $$Maleisische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (170, 326, $$Mongolische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (171, 327, $$Omanitische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (172, 328, $$Nepalese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (173, 329, $$Noordkoreaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (174, 331, $$Pakistaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (175, 333, $$Katarese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (176, 334, $$Saoediarabische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (177, 335, $$Singaporaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (178, 336, $$Syrische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (179, 337, $$Thaise$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (180, 338, $$Burger van de Ver.  Arabische Emiraten$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (181, 339, $$Turkse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (182, 340, $$Zuidjemenitische$$ , null , 19900522);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (183, 341, $$Zuidkoreaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (184, 342, $$Viëtnamese$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (185, 345, $$Burger van Bangladesh$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (186, 400, $$Australische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (187, 401, $$Burger van Papua-Nieuwguinea$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (188, 402, $$Nieuwzeelandse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (189, 404, $$Westsamoaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (190, 421, $$Burger van Antigua en Barbuda$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (191, 424, $$Vanuatuse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (192, 425, $$Fijische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (193, 429, $$Burger van Britse afhankelijke gebieden$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (194, 430, $$Tongaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (195, 431, $$Nauruaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (196, 437, $$Amerikaans onderdaan$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (197, 442, $$Solomoneilandse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (198, 444, $$Seychelse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (199, 445, $$Kiribatische$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (200, 446, $$Tuvaluaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (201, 447, $$Sintluciaanse$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (202, 448, $$Burger van Dominica$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (203, 449, $$Burger van Sint Vincent en de Grenadinen$$ , null , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (204, 450, $$British National (overseas)$$ , 19870701 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (205, 451, $$Zaïrese (Congolese)$$ , 19970517 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (206, 452, $$Burger van Timor Leste$$ , 20020520 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (207, 453, $$Burger van Servië en Montenegro$$ , 20030204 , 20060603);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (208, 454, $$Burger van Servië$$ , 20060603 , null);
insert into Kern.Nation (ID, code, Naam, dataanvgel, dateindegel) values (209, 455, $$Burger van Montenegro$$ , 20060603 , null);
-- deze rij wordt genegeerd
-- deze rij wordt genegeerd
