delete from kern.voorvoegsel;
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(1,$$A$$,$$A$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(2,$$a$$,$$a$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(3,$$Aan$$,$$Aan$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(4,$$aan$$,$$aan$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(5,$$Aan de$$,$$Aan de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(6,$$aan de$$,$$aan de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(7,$$Aan den$$,$$Aan den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(8,$$aan den$$,$$aan den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(9,$$Aan der$$,$$Aan der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(10,$$aan der$$,$$aan der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(11,$$Aan het$$,$$Aan het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(12,$$aan het$$,$$aan het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(13,$$Aan t$$,$$Aan t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(14,$$aan t$$,$$aan t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(15,$$Aan 't$$,$$Aan 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(16,$$aan 't$$,$$aan 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(17,$$Af$$,$$Af$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(18,$$af$$,$$af$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(19,$$Al$$,$$Al$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(20,$$al$$,$$al$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(21,$$Am$$,$$Am$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(22,$$am$$,$$am$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(23,$$Am de$$,$$Am de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(24,$$am de$$,$$am de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(25,$$Auf$$,$$Auf$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(26,$$auf$$,$$auf$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(27,$$Auf dem$$,$$Auf dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(28,$$auf dem$$,$$auf dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(29,$$Auf den$$,$$Auf den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(30,$$auf den$$,$$auf den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(31,$$Auf der$$,$$Auf der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(32,$$auf der$$,$$auf der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(33,$$Auf ter$$,$$Auf ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(34,$$auf ter$$,$$auf ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(35,$$Aus$$,$$Aus$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(36,$$aus$$,$$aus$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(37,$$Aus dem$$,$$Aus dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(38,$$aus dem$$,$$aus dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(39,$$Aus den$$,$$Aus den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(40,$$aus den$$,$$aus den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(41,$$Aus der$$,$$Aus der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(42,$$aus der$$,$$aus der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(43,$$Aus m$$,$$Aus m$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(44,$$aus m$$,$$aus m$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(45,$$Aus 'm$$,$$Aus 'm$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(46,$$aus 'm$$,$$aus 'm$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(47,$$Ben$$,$$Ben$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(48,$$ben$$,$$ben$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(49,$$Bij$$,$$Bij$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(50,$$bij$$,$$bij$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(51,$$Bij de$$,$$Bij de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(52,$$bij de$$,$$bij de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(53,$$Bij den$$,$$Bij den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(54,$$bij den$$,$$bij den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(55,$$Bij het$$,$$Bij het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(56,$$bij het$$,$$bij het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(57,$$Bij t$$,$$Bij t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(58,$$bij t$$,$$bij t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(59,$$Bij 't$$,$$Bij 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(60,$$bij 't$$,$$bij 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(61,$$Bin$$,$$Bin$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(62,$$bin$$,$$bin$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(63,$$Boven d$$,$$Boven d$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(64,$$boven d$$,$$boven d$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(65,$$Boven d'$$,$$Boven d$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(66,$$boven d'$$,$$boven d$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(67,$$D$$,$$D$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(68,$$d$$,$$d$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(69,$$D'$$,$$D$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(70,$$d'$$,$$d$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(71,$$Da$$,$$Da$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(72,$$da$$,$$da$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(73,$$Dal$$,$$Dal$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(74,$$dal$$,$$dal$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(75,$$Dal'$$,$$Dal$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(76,$$dal'$$,$$dal$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(77,$$Dalla$$,$$Dalla$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(78,$$dalla$$,$$dalla$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(79,$$Das$$,$$Das$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(80,$$das$$,$$das$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(81,$$De$$,$$De$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(82,$$de$$,$$de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(83,$$De die$$,$$De die$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(84,$$de die$$,$$de die$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(85,$$De die le$$,$$De die le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(86,$$de die le$$,$$de die le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(87,$$De l$$,$$De l$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(88,$$de l$$,$$de l$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(89,$$De l'$$,$$De l$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(90,$$de l'$$,$$de l$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(91,$$De la$$,$$De la$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(92,$$de la$$,$$de la$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(93,$$De las$$,$$De las$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(94,$$de las$$,$$de las$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(95,$$De le$$,$$De le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(96,$$de le$$,$$de le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(97,$$De van der$$,$$De van der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(98,$$de van der$$,$$de van der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(99,$$Deca$$,$$Deca$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(100,$$deca$$,$$deca$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(101,$$Degli$$,$$Degli$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(102,$$degli$$,$$degli$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(103,$$Dei$$,$$Dei$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(104,$$dei$$,$$dei$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(105,$$Del$$,$$Del$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(106,$$del$$,$$del$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(107,$$Della$$,$$Della$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(108,$$della$$,$$della$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(109,$$Den$$,$$Den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(110,$$den$$,$$den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(111,$$Der$$,$$Der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(112,$$der$$,$$der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(113,$$Des$$,$$Des$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(114,$$des$$,$$des$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(115,$$Di$$,$$Di$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(116,$$di$$,$$di$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(117,$$Die le$$,$$Die le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(118,$$die le$$,$$die le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(119,$$Do$$,$$Do$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(120,$$do$$,$$do$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(121,$$Don$$,$$Don$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(122,$$don$$,$$don$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(123,$$Dos$$,$$Dos$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(124,$$dos$$,$$dos$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(125,$$Du$$,$$Du$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(126,$$du$$,$$du$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(127,$$El$$,$$El$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(128,$$el$$,$$el$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(129,$$Het$$,$$Het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(130,$$het$$,$$het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(131,$$I$$,$$I$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(132,$$i$$,$$i$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(133,$$Im$$,$$Im$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(134,$$im$$,$$im$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(135,$$In$$,$$In$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(136,$$in$$,$$in$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(137,$$In de$$,$$In de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(138,$$in de$$,$$in de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(139,$$In den$$,$$In den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(140,$$in den$$,$$in den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(141,$$In der$$,$$In der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(142,$$in der$$,$$in der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(143,$$In het$$,$$In het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(144,$$in het$$,$$in het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(145,$$In t$$,$$In t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(146,$$in t$$,$$in t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(147,$$In 't$$,$$In 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(148,$$in 't$$,$$in 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(149,$$L$$,$$L$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(150,$$l$$,$$l$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(151,$$L'$$,$$L$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(152,$$l'$$,$$l$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(153,$$La$$,$$La$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(154,$$la$$,$$la$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(155,$$Las$$,$$Las$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(156,$$las$$,$$las$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(157,$$Le$$,$$Le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(158,$$le$$,$$le$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(159,$$Les$$,$$Les$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(160,$$les$$,$$les$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(161,$$Lo$$,$$Lo$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(162,$$lo$$,$$lo$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(163,$$Los$$,$$Los$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(164,$$los$$,$$los$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(165,$$Of$$,$$Of$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(166,$$of$$,$$of$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(167,$$Onder$$,$$Onder$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(168,$$onder$$,$$onder$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(169,$$Onder de$$,$$Onder de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(170,$$onder de$$,$$onder de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(171,$$Onder den$$,$$Onder den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(172,$$onder den$$,$$onder den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(173,$$Onder het$$,$$Onder het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(174,$$onder het$$,$$onder het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(175,$$Onder t$$,$$Onder t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(176,$$onder t$$,$$onder t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(177,$$Onder 't$$,$$Onder 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(178,$$onder 't$$,$$onder 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(179,$$Op$$,$$Op$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(180,$$op$$,$$op$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(181,$$Op de$$,$$Op de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(182,$$op de$$,$$op de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(183,$$Op den$$,$$Op den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(184,$$op den$$,$$op den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(185,$$Op der$$,$$Op der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(186,$$op der$$,$$op der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(187,$$Op gen$$,$$Op gen$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(188,$$op gen$$,$$op gen$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(189,$$Op het$$,$$Op het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(190,$$op het$$,$$op het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(191,$$Op t$$,$$Op t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(192,$$op t$$,$$op t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(193,$$Op 't$$,$$Op 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(194,$$op 't$$,$$op 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(195,$$Op ten$$,$$Op ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(196,$$op ten$$,$$op ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(197,$$Over$$,$$Over$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(198,$$over$$,$$over$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(199,$$Over de$$,$$Over de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(200,$$over de$$,$$over de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(201,$$Over den$$,$$Over den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(202,$$over den$$,$$over den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(203,$$Over het$$,$$Over het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(204,$$over het$$,$$over het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(205,$$Over t$$,$$Over t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(206,$$over t$$,$$over t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(207,$$Over 't$$,$$Over 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(208,$$over 't$$,$$over 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(209,$$S$$,$$S$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(210,$$s$$,$$s$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(211,$$'S$$,$$'S$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(212,$$'s$$,$$'s$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(213,$$S'$$,$$S$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(214,$$s'$$,$$s$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(215,$$T$$,$$T$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(216,$$t$$,$$t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(217,$$'T$$,$$'T$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(218,$$'t$$,$$'t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(219,$$Te$$,$$Te$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(220,$$te$$,$$te$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(221,$$Ten$$,$$Ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(222,$$ten$$,$$ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(223,$$Ter$$,$$Ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(224,$$ter$$,$$ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(225,$$Tho$$,$$Tho$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(226,$$tho$$,$$tho$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(227,$$Thoe$$,$$Thoe$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(228,$$thoe$$,$$thoe$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(229,$$Thor$$,$$Thor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(230,$$thor$$,$$thor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(231,$$To$$,$$To$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(232,$$to$$,$$to$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(233,$$Toe$$,$$Toe$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(234,$$toe$$,$$toe$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(235,$$Tot$$,$$Tot$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(236,$$tot$$,$$tot$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(237,$$Uijt$$,$$Uijt$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(238,$$uijt$$,$$uijt$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(239,$$Uijt de$$,$$Uijt de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(240,$$uijt de$$,$$uijt de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(241,$$Uijt den$$,$$Uijt den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(242,$$uijt den$$,$$uijt den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(243,$$Uijt 't$$,$$Uijt 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(244,$$uijt 't$$,$$uijt 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(245,$$Uijt te de$$,$$Uijt te de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(246,$$uijt te de$$,$$uijt te de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(247,$$Uijt ten$$,$$Uijt ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(248,$$uijt ten$$,$$uijt ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(249,$$Uit$$,$$Uit$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(250,$$uit$$,$$uit$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(251,$$Uit de$$,$$Uit de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(252,$$uit de$$,$$uit de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(253,$$Uit den$$,$$Uit den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(254,$$uit den$$,$$uit den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(255,$$Uit het$$,$$Uit het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(256,$$uit het$$,$$uit het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(257,$$Uit t$$,$$Uit t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(258,$$uit t$$,$$uit t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(259,$$Uit 't$$,$$Uit 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(260,$$uit 't$$,$$uit 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(261,$$Uit te de$$,$$Uit te de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(262,$$uit te de$$,$$uit te de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(263,$$Uit ten$$,$$Uit ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(264,$$uit ten$$,$$uit ten$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(265,$$Unter$$,$$Unter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(266,$$unter$$,$$unter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(267,$$Van$$,$$Van$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(268,$$van$$,$$van$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(269,$$Van de$$,$$Van de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(270,$$van De$$,$$van De$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(271,$$van de$$,$$van de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(272,$$Van de l$$,$$Van de l$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(273,$$van de l$$,$$van de l$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(274,$$Van de l'$$,$$Van de l$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(275,$$van de l'$$,$$van de l$$,$$'$$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(276,$$Van Den$$,$$Van Den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(277,$$Van den$$,$$Van den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(278,$$van den$$,$$van den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(279,$$Van Der$$,$$Van Der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(280,$$Van der$$,$$Van der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(281,$$van der$$,$$van der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(282,$$Van gen$$,$$Van gen$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(283,$$van gen$$,$$van gen$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(284,$$Van het$$,$$Van het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(285,$$van het$$,$$van het$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(286,$$Van la$$,$$Van la$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(287,$$van la$$,$$van la$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(288,$$Van t$$,$$Van t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(289,$$van t$$,$$van t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(290,$$Van 't$$,$$Van 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(291,$$van 't$$,$$van 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(292,$$Van ter$$,$$Van ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(293,$$van ter$$,$$van ter$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(294,$$Van van de$$,$$Van van de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(295,$$van van de$$,$$van van de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(296,$$Ver$$,$$Ver$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(297,$$ver$$,$$ver$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(298,$$Vom$$,$$Vom$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(299,$$vom$$,$$vom$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(300,$$Von$$,$$Von$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(301,$$von$$,$$von$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(302,$$Von dem$$,$$Von dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(303,$$von dem$$,$$von dem$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(304,$$Von den$$,$$Von den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(305,$$von den$$,$$von den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(306,$$Von der$$,$$Von der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(307,$$von der$$,$$von der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(308,$$Von t$$,$$Von t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(309,$$von t$$,$$von t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(310,$$Von 't$$,$$Von 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(311,$$von 't$$,$$von 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(312,$$Voor$$,$$Voor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(313,$$voor$$,$$voor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(314,$$Voor de$$,$$Voor de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(315,$$voor de$$,$$voor de$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(316,$$Voor den$$,$$Voor den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(317,$$voor den$$,$$voor den$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(318,$$Voor in t$$,$$Voor in t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(319,$$voor in t$$,$$voor in t$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(320,$$Voor in 't$$,$$Voor in 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(321,$$voor in 't$$,$$voor in 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(322,$$Voor 't$$,$$Voor 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(323,$$voor 't$$,$$voor 't$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(324,$$Vor$$,$$Vor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(325,$$vor$$,$$vor$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(326,$$Vor der$$,$$Vor der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(327,$$vor der$$,$$vor der$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(328,$$Zu$$,$$Zu$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(329,$$zu$$,$$zu$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(330,$$Zum$$,$$Zum$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(331,$$zum$$,$$zum$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(332,$$Zur$$,$$Zur$$,$$ $$);
insert into kern.voorvoegsel(id, LO3Voorvoegsel, voorvoegsel, scheidingsteken) values(333,$$zur$$,$$zur$$,$$ $$);
