#!/bin/bash

function readParams {
        qparm=(${QUERY_STRING//\&/ });
        for i in "${qparm[@]}"
        do
                bparm=(${i//=/ });
                export ${bparm[0]}="${bparm[1]}";
        done
}
