#!/bin/bash
echo Content-type: application/json
echo ""

. ./env
. ./functions
readParams;

. ./do-run.sh ${gemeentebestand} ${factor}

echo "{";
echo "\"gemeentebestand\" : \"${gemeentebestand}\",";
echo "\"factor\" : \"${factor}\",";
echo "\"result\" : \"ok\"";
echo "}";
