#!/bin/bash
echo Content-type: application/json
echo ""

. ./env

echo "["
count=0;

for i in ${MULTIPLIER_OUTPUT_DIR}/*; 
do
        if [ ! -e ${i} ];
        then
                break;
        fi

	if [ $count -gt 0 ];
	then
		echo ", ";
	fi

	echo "{"
	echo "\"naam\" : \"`basename ${i}`\",";
	echo "\"datum\" : \"`stat -c %Y ${i}`000\",";
	echo "\"grootte\" : \"`stat -c %s ${i}`\"";

	echo "}";
	count=$((count + 1));
done

echo "]";
